### ISSUE TITLE
Big Sur installation issue

### ISSUE THREAD

**Issue by asuma4** [inkstitch/inkstitch#1008]
when i try to open params on my inkstitch this comes up and it wont let me open it how can i fix this
Traceback (most recent call last):
  File "/Users/runner/work/inkstitch/inkstitch/inkstitch.py", line 8, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/Users/runner/work/inkstitch/inkstitch/lib/debug.py", line 13, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/Users/runner/work/inkstitch/inkstitch/lib/svg/__init__.py", line 1, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/Users/runner/work/inkstitch/inkstitch/lib/svg/guides.py", line 3, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/Users/runner/work/inkstitch/inkstitch/lib/utils/__init__.py", line 3, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/Users/runner/work/inkstitch/inkstitch/lib/utils/geometry.py", line 3, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/shapely/geometry/__init__.py", line 4, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/shapely/geometry/base.py", line 18, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/shapely/coords.py", line 8, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/shapely/geos.py", line 138, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/shapely/geos.py", line 62, in load_dll
OSError: Could not find lib c or load any of its variants [].
[970] Failed to execute script inkstitch

**Comment by kaalleen** [comment]
For the current release there are additional installation steps necessary for big sur.
We have a description on our homepage: https://inkstitch.org/docs/install-macos/#addtitional-steps-for-catalina--big-sur
