### ISSUE TITLE
Problem saving a file in .jef format

### ISSUE THREAD

**Issue by Mariloure** [inkstitch/inkstitch#1013]
Hi, I can't save my .svg file in .jef format, here is the error that is shown:

Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\inkstitch.py", line 44, in <module>
  File "D:\a\inkstitch\inkstitch\inkscape\share\extensions\inkex.py", line 283, in affect
  File "D:\a\inkstitch\inkstitch\lib\extensions\output.py", line 48, in effect
  File "D:\a\inkstitch\inkstitch\lib\extensions\base.py", line 194, in elements_to_patches
  File "D:\a\inkstitch\inkstitch\lib\elements\element.py", line 329, in embroider
  File "D:\a\inkstitch\inkstitch\lib\elements\stroke.py", line 197, in to_patches
  File "D:\a\inkstitch\inkstitch\lib\elements\stroke.py", line 139, in is_running_stitch
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 1: ordinal not in range(128)

Could you please help me understand what it means and how to fix this?

**Comment by Mariloure** [comment]
I fixed it by cleaning the file
