### ISSUE TITLE
path51: error: Error during autofill!  

### ISSUE THREAD

**Issue by ninjawarrior7** [inkstitch/inkstitch#1027]
Hi, 

I received this popup error when trying to save into PES/PEC. Thank you.

Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\lib\elements\auto_fill.py", line 212, in to_patches
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 55, in auto_fill
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 149, in build_fill_stitch_graph
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 173, in insert_node
ValueError: min() arg is an empty sequence

**Comment by kaalleen** [comment]
Hey there. Thank you for reporting your issue. It is caused by very small fill shapes. For now there is no better way than tracing them down and remove them. If you do not want to do it manually use this function here: Extensions > Ink/Stitch > Troubleshoot > Cleanup document...

**Comment by ninjawarrior7** [comment]
I see. Still, thank you so much kaalleen!
