### ISSUE TITLE
Inkscape stuck after run stimulator in Mac

### ISSUE THREAD

**Issue by Sudu76** [inkstitch/inkstitch#1038]
HI everyone,
is anybody experiencing running stimulator in Mac . Everytime I run the stimulator I would have to force quit Inkscape and restart again as it won't work agin. I use Mac Catalina 10.15.5. I Reinstall again everything deleting (Inkscape and inkstich) but situation is the same. 

Any help would appreciate.  

Thanks

**Comment by kaalleen** [comment]
Wow, no. We haven't heard of it. But I just did some research and heard it has been an issue. Thank you for reporting it.

**Comment by camronblackburn** [comment]
I'm having the same issue with macOS on Big Sur 11.1. here's the error stack trace I'm getting after quitting the `inkstitch-gui` window:

```
[2021-02-15 20:44:31,003] ERROR in app: Exception on /stitch_plan [GET]
Traceback (most recent call last):
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
  File "/Users/runner/work/inkstitch/inkstitch/lib/api/stitch_plan.py", line 14, in get_stitch_plan
  File "/Users/runner/work/inkstitch/inkstitch/lib/extensions/base.py", line 194, in elements_to_patches
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/element.py", line 327, in embroider
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/element.py", line 384, in validate
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/fill.py", line 150, in validation_errors
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/backports/functools_lru_cache.py", line 124, in wrapper
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/fill.py", line 138, in shape
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/fill.py", line 138, in <lambda>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/shapely/geometry/base.py", line 438, in area
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/shapely/topology.py", line 55, in __call__
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/shapely/topology.py", line 18, in _validate
ValueError: Null geometry supports no operations
```

**Comment by Sudu76** [comment]
Actually I sort it out, if I press 'Command Q, it would return safely, if close the window, it would crash.

**Comment by kaalleen** [comment]
Good you found a solution. I will reopen tthe issue, because we actually wouldn't want everyone to must find a workaround. We hopefully will make it possible for macOS users to close the simulator any way they want.
