### ISSUE TITLE
(UnicodeDecodeError) Can anyone help me at Inkstitch?? 

### ISSUE THREAD

**Issue by kubischk** [inkstitch/inkstitch#1054]
Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\inkstitch.py", line 44, in <module>
  File "D:\a\inkstitch\inkstitch\lib\extensions\input.py", line 50, in affect
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\encodings\utf_8.py", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xfc in position 10: invalid start byte

this is an unexpected error and I don't know what to do.. can anyone help me?

**Comment by tyrosinase** [comment]
The current version of Ink/Stitch has trouble with special characters in the filename or path. For now, save it somewhere with no accented etc. characters, until that bug gets squashed.

**Comment by kaalleen** [comment]
This should be fixed with the new Ink/Stitch version. Therefore I am going to close the issue. When you still are seeing an issue like that, we would be interested to hear about it.
