### ISSUE TITLE
Auto Route Satin: NetworkXUnfeasible

### ISSUE THREAD

**Issue by me1232313** [inkstitch/inkstitch#1056]
Hi, 

First of all, thank you for creating this extension, I just downloaded it so I might be doing something wrong but it said to post it here so here we go:

I'm trying to embrowdery a signature, so I did the bitmap and broke it apart. I tried to do params which works fine, but when trying Satin, it doesn't work and I get this error asking me to post it here:

Ink/Stitch experienced an unexpected error.
If you'd like to help, please file an issue at https://github.com/inkstitch/inkstitch/issues and include the entire error description below: 

Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\inkstitch.py", line 44, in <module>
  File "D:\a\inkstitch\inkstitch\inkscape\share\extensions\inkex.py", line 283, in affect
  File "D:\a\inkstitch\inkstitch\lib\extensions\auto_satin.py", line 54, in effect
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_satin.py", line 316, in auto_satin
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_satin.py", line 456, in add_jumps
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\networkx\algorithms\connectivity\edge_augmentation.py", line 264, in k_edge_augmentation
NetworkXUnfeasible: impossible to 1 connect in graph with less than 2 nodes

**Comment by tyrosinase** [comment]
Auto-route satin doesn't convert things to satin stitch, but rather optimizes existing satin stitches (https://inkstitch.org/docs/satin-tools/)

Getting to that satin stitch in the first place takes a little more work: https://silverseams.com/2020/03/monogramming-without-a-font/

**Comment by kaalleen** [comment]
Thank you for reporting your error.
Would it be possible for you to send the file which is causing the error or describe the exact steps you've done to see it?

**Comment by kaalleen** [comment]
I don't think we'll receive any file for that issue anymore and I don't think this is still an issue, since we reworked satin and satin autoroute. Therefore I'll close the issue. If this ever shows up again, please open a new issue.
