### ISSUE TITLE
svg_objects: TypeError: float() argument must be a string or a number

### ISSUE THREAD

**Issue by FoxxyVixxen** [inkstitch/inkstitch#1057]
It certainly isn't happy with me. I've only just installed it, but I'm relatively sure I didn't break anything. Probably. Maybe. 

Ink/Stitch experienced an unexpected error.
If you'd like to help, please file an issue at https://github.com/inkstitch/inkstitch/issues and include the entire error description below: 

Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\inkstitch.py", line 44, in <module>
  File "D:\a\inkstitch\inkstitch\inkscape\share\extensions\inkex.py", line 283, in affect
  File "D:\a\inkstitch\inkstitch\lib\extensions\troubleshoot.py", line 26, in effect
  File "D:\a\inkstitch\inkstitch\lib\elements\fill.py", line 150, in validation_errors
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\backports\functools_lru_cache.py", line 124, in wrapper
  File "D:\a\inkstitch\inkstitch\lib\elements\fill.py", line 137, in shape
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\backports\functools_lru_cache.py", line 124, in wrapper
  File "D:\a\inkstitch\inkstitch\lib\elements\fill.py", line 124, in paths
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\backports\functools_lru_cache.py", line 124, in wrapper
  File "D:\a\inkstitch\inkstitch\lib\elements\element.py", line 267, in parse_path
  File "D:\a\inkstitch\inkstitch\lib\elements\element.py", line 256, in path
  File "D:\a\inkstitch\inkstitch\lib\elements\svg_objects.py", line 62, in circle_to_path
TypeError: float() argument must be a string or a number

**Comment by kaalleen** [comment]
Uh, sorry. This is certainly a bug (which might have been already solved).

Try to convert your objects into paths to avoid this error message for now.

**Comment by kaalleen** [comment]
I will be closing this issue. The affected file does not exist any longer. Since object paths are generated by inkex directly, we don't need to do this anymore.
