### ISSUE TITLE
fill: ValueError: need more than 0 values to unpack (intersect_region_with_grating)

### ISSUE THREAD

**Issue by Papillon-Bleu** [inkstitch/inkstitch#1071]
path28: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\lib\elements\auto_fill.py", line 212, in to_patches
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 55, in auto_fill
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 133, in build_fill_stitch_graph
  File "D:\a\inkstitch\inkstitch\lib\stitches\fill.py", line 91, in intersect_region_with_grating
ValueError: need more than 0 values to unpack

path28: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\lib\elements\auto_fill.py", line 212, in to_patches
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 55, in auto_fill
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 133, in build_fill_stitch_graph
  File "D:\a\inkstitch\inkstitch\lib\stitches\fill.py", line 91, in intersect_region_with_grating
ValueError: need more than 0 values to unpack

path28: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\lib\elements\auto_fill.py", line 212, in to_patches
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 55, in auto_fill
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 133, in build_fill_stitch_graph
  File "D:\a\inkstitch\inkstitch\lib\stitches\fill.py", line 91, in intersect_region_with_grating
ValueError: need more than 0 values to unpack

**Comment by kaalleen** [comment]
Thank you for reporting your error and sorry for your trouble.
Would it be possible to attach a zipped svg file as well?
It would be very helpful to be able to inspect the error in a file which is causing it.

**Comment by kaalleen** [comment]
See #1110
