### ISSUE TITLE
macOS: OSError: Could not find lib c or load any of its variants []

### ISSUE THREAD

**Issue by muzzamilksunge** [inkstitch/inkstitch#1081]
hello i am using Imac and i am trying to use inkscape with inkstich but it gives me error please help
whenever i try to make prams it shows me long error list
Traceback (most recent call last):
File "/Users/runner/work/inkstitch/inkstitch/inkstitch.py", line 8, in <module>
File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
File "/Users/runner/work/inkstitch/inkstitch/lib/debug.py", line 13, in <module>
File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
File "/Users/runner/work/inkstitch/inkstitch/lib/svg/__init__.py", line 1, in <module>
File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
File "/Users/runner/work/inkstitch/inkstitch/lib/svg/guides.py", line 3, in <module>
File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
File "/Users/runner/work/inkstitch/inkstitch/lib/utils/__init__.py", line 3, in <module>
File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
File "/Users/runner/work/inkstitch/inkstitch/lib/utils/geometry.py", line 3, in <module>
File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/shapely/geometry/__init__.py", line 4, in <module>
File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/shapely/geometry/base.py", line 18, in <module>
File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/shapely/coords.py", line 8, in <module>
File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/shapely/geos.py", line 138, in <module>
File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/shapely/geos.py", line 62, in load_dll
OSError: Could not find lib c or load any of its variants [].
[2816] Failed to execute script inkstitch

**Comment by MK-12-20MM** [comment]
Hi - Just another user giving a hand.

Not sure if you have seen the updated instructions. https://inkstitch.org/docs/install-macos/#addtitional-steps-for-catalina--big-sur 
This might help your situation.

**Comment by kaalleen** [comment]
I'll close this issue now. It'll be fixed in the next release. Please reopen if it is still needed.
