### ISSUE TITLE
input: UnicodeDecodeError

### ISSUE THREAD

**Issue by Ediblack** [inkstitch/inkstitch#1085]
Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\inkstitch.py", line 44, in <module>
  File "D:\a\inkstitch\inkstitch\lib\extensions\input.py", line 50, in affect
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\encodings\utf_8.py", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xd5 in position 52: invalid continuation byte

It happened after a windows update KB4589212 and KB5000802.

**Comment by MK-12-20MM** [comment]
Just a helping hand here from another user. 

You may have a Õ symbol in the path or filename. Ink/stitch has issues encoding those symbols.  There is an issue or bug opened here - https://github.com/inkstitch/inkstitch/issues/725. This issue seems related yours.

**Comment by kaalleen** [comment]
This error is hopefully fixed in the upcoming version.
Please reopen if this is not the case.
