### ISSUE TITLE
auto_fill: NetworkXNoPath

### ISSUE THREAD

**Issue by suzanneokun** [inkstitch/inkstitch#1093]
ath12338: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "lib/elements/auto_fill.py", line 218, in to_patches
  File "lib/debug.py", line 125, in decorated
  File "lib/stitches/auto_fill.py", line 64, in auto_fill
  File "lib/debug.py", line 125, in decorated
  File "lib/stitches/auto_fill.py", line 568, in path_to_stitches
  File "lib/stitches/auto_fill.py", line 533, in travel
  File "site-packages/networkx/algorithms/shortest_paths/generic.py", line 172, in shortest_path
  File "site-packages/networkx/algorithms/shortest_paths/weighted.py", line 163, in dijkstra_path
  File "site-packages/networkx/algorithms/shortest_paths/weighted.py", line 472, in single_source_dijkstra
  File "site-packages/networkx/algorithms/shortest_paths/weighted.py", line 738, in multi_source_dijkstra
NetworkXNoPath: No path to (426.8129523698138, 332.18544456995096).

**Comment by kaalleen** [comment]
Thank you for reporting your issue. We really appreaciate that you are contacting us about your problem.
You just discovered a bug in Ink/Stitch. Would it be possible for you to upload a zipped svg file which is causing the trouble, so we can investigate it further?

**Comment by suzanneokun** [comment]
Hi. Just to confirm are you asking me to send you my art file or are you going to send me a file to run?

Suzi Okun

**Comment by kaalleen** [comment]
I'd be interested in your file - if you think it's possible (maybe not, due to copyright restrictions).

**Comment by kaalleen** [comment]
See https://github.com/inkstitch/inkstitch/issues/1019#issuecomment-775942332

This issue should be fixed in the current version of Ink/Stitch. Therefore I'll close this issue now. Please reopen, if the problem still pops up.
