### ISSUE TITLE
path860: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

### ISSUE THREAD

**Issue by stlbr** [inkstitch/inkstitch#1111]
path860: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/auto_fill.py", line 212, in to_patches
  File "/Users/runner/work/inkstitch/inkstitch/lib/debug.py", line 125, in decorated
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 55, in auto_fill
  File "/Users/runner/work/inkstitch/inkstitch/lib/debug.py", line 125, in decorated
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 149, in build_fill_stitch_graph
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 173, in insert_node
ValueError: min() arg is an empty sequence

**Comment by kaalleen** [comment]
Try to remove tiny fill areas with this function: Ink/Stitch > Extensions > Troubleshoot > Cleanup document ...

This bug will be removed through the upcoming version. Thanks for reporting it!

**Comment by stlbr** [comment]
@kaalleen 
Thank you! Just a quick question as I am new... Do the upcoming versions have to be redownloaded? How does that work/ what is the easiest way to obtain the new versions.

**Comment by kaalleen** [comment]
We have no automatic update function. So yes, you will have to download and install an update by yourself. We will announce updates on our website. If you don't want to regularly check our website for updates, you can also use the rss feed (Ink/Stitch news).

https://inkstitch.org/docs/install-macos/#upgrade

**Comment by kaalleen** [comment]
Since the poblem has been fixed, I am going to close this issue.
