### ISSUE TITLE
svg_objects error

### ISSUE THREAD

**Issue by Ka1zoku-0** [inkstitch/inkstitch#1119]
Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\inkstitch.py", line 44, in <module>
  File "D:\a\inkstitch\inkstitch\inkscape\share\extensions\inkex.py", line 283, in affect
  File "D:\a\inkstitch\inkstitch\lib\extensions\embroider.py", line 84, in effect
  File "D:\a\inkstitch\inkstitch\lib\extensions\base.py", line 194, in elements_to_patches
  File "D:\a\inkstitch\inkstitch\lib\elements\element.py", line 327, in embroider
  File "D:\a\inkstitch\inkstitch\lib\elements\element.py", line 384, in validate
  File "D:\a\inkstitch\inkstitch\lib\elements\fill.py", line 150, in validation_errors
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\backports\functools_lru_cache.py", line 124, in wrapper
  File "D:\a\inkstitch\inkstitch\lib\elements\fill.py", line 137, in shape
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\backports\functools_lru_cache.py", line 124, in wrapper
  File "D:\a\inkstitch\inkstitch\lib\elements\fill.py", line 124, in paths
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\backports\functools_lru_cache.py", line 124, in wrapper
  File "D:\a\inkstitch\inkstitch\lib\elements\element.py", line 267, in parse_path
  File "D:\a\inkstitch\inkstitch\lib\elements\element.py", line 256, in path
  File "D:\a\inkstitch\inkstitch\lib\elements\svg_objects.py", line 62, in circle_to_path
TypeError: float() argument must be a string or a number

**Comment by kaalleen** [comment]
Thanks for reporting your error. For now it would be best to convert your object into a path. We will handle objects differently in the very next release. This should solve your issue too.

**Comment by kaalleen** [comment]
Since this is fixed in the main branch already. I'll close this issue now.
