### ISSUE TITLE
svg_objects error

### ISSUE THREAD

**Issue by wileycoyote02** [inkstitch/inkstitch#1148]
Ink/Stitch experienced an unexpected error.
If you'd like to help, please file an issue at https://github.com/inkstitch/inkstitch/issues and include the entire error description below: 

Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\inkstitch.py", line 44, in <module>
  File "D:\a\inkstitch\inkstitch\inkscape\share\extensions\inkex.py", line 283, in affect
  File "D:\a\inkstitch\inkstitch\lib\extensions\cleanup.py", line 39, in effect
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\backports\functools_lru_cache.py", line 124, in wrapper
  File "D:\a\inkstitch\inkstitch\lib\elements\fill.py", line 137, in shape
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\backports\functools_lru_cache.py", line 124, in wrapper
  File "D:\a\inkstitch\inkstitch\lib\elements\fill.py", line 124, in paths
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\backports\functools_lru_cache.py", line 124, in wrapper
  File "D:\a\inkstitch\inkstitch\lib\elements\element.py", line 267, in parse_path
  File "D:\a\inkstitch\inkstitch\lib\elements\element.py", line 256, in path
  File "D:\a\inkstitch\inkstitch\lib\elements\svg_objects.py", line 62, in circle_to_path
TypeError: float() argument must be a string or a number

**Comment by kaalleen** [comment]
Oh, interesting. Thanks for reporting this issue.

In the next release we will parse object elements differently. So I think this error will very soon be outdated (with the next release). Until then, select your objects and turn them into paths (Path > Convert Object to path)

**Comment by kaalleen** [comment]
See #1163
