### ISSUE TITLE
WindowsError: [Error 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by neverstitches** [inkstitch/inkstitch#1149]
Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\inkstitch.py", line 44, in <module>
  File "D:\a\inkstitch\inkstitch\inkscape\share\extensions\inkex.py", line 283, in affect
  File "D:\a\inkstitch\inkstitch\lib\extensions\simulator.py", line 16, in effect
  File "D:\a\inkstitch\inkstitch\lib\gui\electron.py", line 31, in open_url
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\subprocess.py", line 394, in __init__
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\subprocess.py", line 644, in _execute_child
WindowsError: [Error 193] %1 is not a valid Win32 application

**Comment by kaalleen** [comment]
Can somebody help us out here? I am not really sure about this one...

**Comment by tyrosinase** [comment]
If it's a brand-new install, I assume that's the wrong version (installed Linux Ink/Stitch on Windows or something).

**Comment by kaalleen** [comment]
No further feedback. I'll close this issue now. Please reopen if you are still having issues with your Ink/Stitch installation.
