### ISSUE TITLE
auto_fill: ValueError: min() arg is an empty sequence

### ISSUE THREAD

**Issue by bharper1408** [inkstitch/inkstitch#1157]
Hi I've came across this issue, is anyone able to help?

path5219: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/auto_fill.py", line 212, in to_patches
  File "/Users/runner/work/inkstitch/inkstitch/lib/debug.py", line 125, in decorated
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 55, in auto_fill
  File "/Users/runner/work/inkstitch/inkstitch/lib/debug.py", line 125, in decorated
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 149, in build_fill_stitch_graph
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 173, in insert_node
ValueError: min() arg is an empty sequence

**Comment by kaalleen** [comment]
Thanks for reporting your issue. This error message we know so well by now and have seen it many times. It will be fixed in the next release. Until then it is important to clean your document from small fill objects (you still should do so woth the next release, it will just be more forgiving). Ink/Stitch has a tool to help you with this: Extensions > Ink/Stitch > Troubleshoot > Cleanup document...

**Comment by kaalleen** [comment]
I'll close this issue. The new release (v2.0.0) should have fixed it. Please reopen, if the error still occurs.
