### ISSUE TITLE
Error during autofill

### ISSUE THREAD

**Issue by deshcollide** [inkstitch/inkstitch#1161]
Traceback (most recent call last):
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/auto_fill.py", line 225, in to_patches
  File "/Users/runner/work/inkstitch/inkstitch/lib/debug.py", line 125, in decorated
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 55, in auto_fill
  File "/Users/runner/work/inkstitch/inkstitch/lib/debug.py", line 125, in decorated
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 149, in build_fill_stitch_graph
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 173, in insert_node
ValueError: min() arg is an empty sequence

**Comment by kaalleen** [comment]
Thanks for your error report. This error here is reported to us on a weekly basis and I will be very happy, when the fix is being released in our next Ink/Stitch version. Until then you will have to remove very small fill shapes from your document by using the cleanup document function delivered with Ink/Stitch (in the troubleshoot section).

**Comment by kaalleen** [comment]
I'll close this issue. The new release (v2.0.0) should have fixed it. Please reopen, if the error still occurs.
