### ISSUE TITLE
Error in svg_objects.py

### ISSUE THREAD

**Issue by hoesgarth** [inkstitch/inkstitch#1163]
Traceback (most recent call last):
  File "/Users/runner/work/inkstitch/inkstitch/inkstitch.py", line 44, in <module>
  File "/Users/runner/work/inkstitch/inkstitch/inkscape/share/extensions/inkex.py", line 283, in affect
  File "/Users/runner/work/inkstitch/inkstitch/lib/extensions/embroider.py", line 84, in effect
  File "/Users/runner/work/inkstitch/inkstitch/lib/extensions/base.py", line 194, in elements_to_patches
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/element.py", line 327, in embroider
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/element.py", line 384, in validate
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/fill.py", line 150, in validation_errors
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/backports/functools_lru_cache.py", line 124, in wrapper
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/fill.py", line 137, in shape
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/backports/functools_lru_cache.py", line 124, in wrapper
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/fill.py", line 124, in paths
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/backports/functools_lru_cache.py", line 124, in wrapper
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/element.py", line 267, in parse_path
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/element.py", line 256, in path
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/svg_objects.py", line 62, in circle_to_path
TypeError: float() argument must be a string or a number

**Comment by kaalleen** [comment]
Thank you for reporting your error. Try to convert your circle into a path object. There is currently an error in how we handle circle objects. This will be fixed in the next release.
