### ISSUE TITLE
Conversion error

### ISSUE THREAD

**Issue by bengal987** [inkstitch/inkstitch#1167]
For some reason it wont convert or show a stitch demo thru params, but if I individually select each object then run params it works, but still no luck with the conversion.

path1615: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\lib\elements\auto_fill.py", line 212, in to_patches
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 55, in auto_fill
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 149, in build_fill_stitch_graph
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 173, in insert_node
ValueError: min() arg is an empty sequence

**Comment by tyrosinase** [comment]
On Mon, Apr 26, 2021, at 1:42 AM, bengal987 wrote:
> 

> For some reason it wont convert or show a stitch demo thru params, but if I individually select each object then run params it works, but still no luck with the conversion.


For me that usually means there's a tiny broken object somewhere. (My Inkscape likes to create zero-object groups, single-point lines, and other paradoxical shapes. No idea why, probably time for a clean reinstall.) Sometimes I open the XML view and just highlight each object in turn until I find the one that's not supposed to be there.

**Comment by kaalleen** [comment]
This issue should not happen anymore with the newest release. Therefore I will close this issue. Please reopen, if you still are having problems.
