### ISSUE TITLE
Fatal error detected - Failed to execute script pyi_rth_multiprocessing  

### ISSUE THREAD

**Issue by Tina-Chris** [inkstitch/inkstitch#1195]
I've got a comment on our Youtube Channel, including the following error message:
@Ink/Stitch    Windows 7 Service Pack 1 -   Egal welche Funktion ich Ausführe

Traceback (most recent call last):
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_multiprocessing.py", line 17, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "multiprocessing\__init__.py", line 16, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "multiprocessing\context.py", line 6, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "multiprocessing\reduction.py", line 16, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "socket.py", line 49, in <module>
ImportError: DLL load failed while importing _socket: Falscher Parameter

**Comment by B-ellanna** [comment]
Got the same error report from another Windows 7 user over Facebook. 
Maybe the windows 7 does not provide the DLL which the modules call on? 
![Screenshot_20210508-175107_Kiwi Browser](https://user-images.githubusercontent.com/64272979/117545427-068bc080-b026-11eb-8662-3d36e8b0712d.jpg)

**Comment by kaalleen** [comment]
https://github.com/pyinstaller/pyinstaller/issues/4855 suggests intalling security updates for Windows 7 would solve the issue.
