### ISSUE TITLE
svg_objects bug

### ISSUE THREAD

**Issue by hoesgarth** [inkstitch/inkstitch#1201]
Traceback (most recent call last):
  File "/Users/runner/work/inkstitch/inkstitch/inkstitch.py", line 44, in <module>
  File "/Users/runner/work/inkstitch/inkstitch/inkscape/share/extensions/inkex.py", line 283, in affect
  File "/Users/runner/work/inkstitch/inkstitch/lib/extensions/troubleshoot.py", line 26, in effect
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/fill.py", line 150, in validation_errors
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/backports/functools_lru_cache.py", line 124, in wrapper
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/fill.py", line 137, in shape
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/backports/functools_lru_cache.py", line 124, in wrapper
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/fill.py", line 124, in paths
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/backports/functools_lru_cache.py", line 124, in wrapper
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/element.py", line 267, in parse_path
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/element.py", line 256, in path
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/svg_objects.py", line 62, in circle_to_path
TypeError: float() argument must be a string or a number

**Comment by kaalleen** [comment]
Thanks for reporting your error. I am wondering if you updated Ink/Stitch to the newest version. This error is known for a former version of Ink/Stitch, but cannot appear in Ink/Stitch 2.0.0

If you need instructions how to update/install Ink/Stitch, follow this link: https://inkstitch.org/docs/install/
