### ISSUE TITLE
auto_fill: ValueError: min() arg is an empty sequence

### ISSUE THREAD

**Issue by KathyD4** [inkstitch/inkstitch#1202]
(This is my first attempt at making a design in Inkstitch-definite possibility of operator error)

path112: error: Error during autofill!  This means that there is a problem with Ink/Stitch.
If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\lib\elements\auto_fill.py", line 212, in to_patches
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 55, in auto_fill
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 149, in build_fill_stitch_graph
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 173, in insert_node
ValueError: min() arg is an empty sequence

**Comment by lexelby** [comment]
Definitely not user error!  We always consider it a bug if you see a traceback like that.

What version of Ink/Stitch are you using?

**Comment by kaalleen** [comment]
This issue should have been fixed with Ink/Stitch 2.0
Please reopen, if the error still occurs
