### ISSUE TITLE
Save to PES error Path2849 Error during Autofill!

### ISSUE THREAD

**Issue by manaughl** [inkstitch/inkstitch#1211]
When I try to save a personally created design in Inkscape/inkstitch, create the SVG then run Params it all checks out. Then I try to save it as extention PES and i get the error below. It has a statin stitch outline in one layer and then a fill layer. 

path2849: error: Error during autofill!

Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\lib\elements\auto_fill.py", line 212, in to_patches
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 55, in auto_fill
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 149, in build_fill_stitch_graph
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 173, in insert_node
ValueError: min() arg is an empty sequence

**Comment by kaalleen** [comment]
Looks like you are not using the latest Ink/Stitch release. We are expecting that this issue has been solved.

Download and install our latest release as described here: https://inkstitch.org/docs/install-windows/
