### ISSUE TITLE
stitch_plan: IndexError: list index out of range

### ISSUE THREAD

**Issue by gabsmertes** [inkstitch/inkstitch#1214]
Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex\base.py", line 141, in run
  File "lib\extensions\output.py", line 56, in effect
  File "lib\stitch_plan\stitch_plan.py", line 26, in patches_to_stitch_plan
IndexError: list index out of range

**Comment by kaalleen** [comment]
Hey there. Thanks for your error report. We have seen this issue popping up several times in the last few days. But I haven't been able to see a file which is causing the error. Would it be possible for you to send us your svg file?

**Comment by kaalleen** [comment]
Closing in favor of #1226 with more detailed information.
