### ISSUE TITLE
Import SVG doesn't solve Adobe Illustrator namespace error

### ISSUE THREAD

**Issue by buzzmandt** [inkstitch/inkstitch#1225]
I keep getting this error....

"Ink/Stitch cannot read your SVG file. This is often the case when you use a file which has been created with Adobe Illustrator.

Try to import the file into Inkscape through 'File > Import...' (Ctrl+I)"

But the thing is I made it with Inkscape, and have already been creating inkstitch files with it. Just suddenly it can't read it. Any suggestions or tips I can try?

I have already tried the suggested importing it, doesn't work.

This is happening on many of my inkscape svg files. It's rendering many of my projects useless.
Using Manjaro linux, Inkscape 1.1, Inkstitch 2.0

![image](https://user-images.githubusercontent.com/76489837/120085245-6a912a00-c0a4-11eb-92e4-6efcbb50bdf5.png)

**Comment by buzzmandt** [comment]
Sometimes lately I'm also getting this. Is it related?

"lib/extensions/base.py:58: DeprecationWarning: inkex.etree was removed, use "from lxml import etree"

**Comment by kaalleen** [comment]
Thank you for reporting your issue!

> `lib/extensions/base.py:58: DeprecationWarning: inkex.etree was removed, use "from lxml import etree`

The last error is just a warning, it shouldn't prevent anything from working. It will be fixed in the next Ink/Stitch release.

The other error must be very annoying. Sorry that you have to go through this. I heard Inkscape 1.1 is causing trouble for Ink/Stitch, but haven't heard any details yet. Maybe this is one of it. If possible, it would be nice to have a look at one of the affected files, Would it be possible for you to upload it here? It must be in a zip cotainer, GitHub doesn't allow a direct upload of svg files.

For a fast solution I would suggest to downgrade Inkscape to 1.0.2 for now. Report if this issues also shows up when you use an older Inkscape version.

**Comment by buzzmandt** [comment]
I attempted some troubleshooting and went back to inkscape 1.0.2 (Manjaro repo) with inkstitch 2.0. Did the same thing, running Inkstitch>Troubleshoot>Troubleshoot Objects.

So I tried inkscape 1.0.2 with inkstitch 1.29.1 and that same SVG file gave me this error instead, running Inkstitch>Troubleshoot>Troubleshoot Objects

`Ink/Stitch experienced an unexpected error.
If you'd like to help, please file an issue at https://github.com/inkstitch/inkstitch/issues and include the entire error description below: 

Traceback (most recent call last):
  File "/home/runner/work/inkstitch/inkstitch/inkstitch.py", line 44, in <module>
  File "/home/runner/work/inkstitch/inkstitch/inkscape/share/extensions/inkex.py", line 279, in affect
  File "/home/runner/work/inkstitch/inkstitch/lib/extensions/base.py", line 219, in parse
  File "/home/runner/work/inkstitch/inkstitch/inkscape/share/extensions/inkex.py", line 202, in parse
  File "src/lxml/etree.pyx", line 3521, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1880, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1900, in lxml.etree._parseFilelikeDocument
  File "src/lxml/parser.pxi", line 1795, in lxml.etree._parseDocFromFilelike
  File "src/lxml/parser.pxi", line 1201, in lxml.etree._BaseParser._parseDocFromFilelike
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
XMLSyntaxError: xmlns:i: '&#38;#38;ns_ai;' is not a valid URI, line 3, column 33 (line 3)`

So then I tried inkscape 1.1 (Flatpack) with inkstitch 1.29.1 and the same SVG file gives me this almost identical read out, running Inkstitch>Troubleshoot>Troubleshoot Objects.

`Ink/Stitch experienced an unexpected error.
If you'd like to help, please file an issue at https://github.com/inkstitch/inkstitch/issues and include the entire error description below: 

Traceback (most recent call last):
  File "/home/runner/work/inkstitch/inkstitch/inkstitch.py", line 44, in <module>
  File "/home/runner/work/inkstitch/inkstitch/inkscape/share/extensions/inkex.py", line 279, in affect
  File "/home/runner/work/inkstitch/inkstitch/lib/extensions/base.py", line 219, in parse
  File "/home/runner/work/inkstitch/inkstitch/inkscape/share/extensions/inkex.py", line 202, in parse
  File "src/lxml/etree.pyx", line 3521, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1880, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1900, in lxml.etree._parseFilelikeDocument
  File "src/lxml/parser.pxi", line 1795, in lxml.etree._parseDocFromFilelike
  File "src/lxml/parser.pxi", line 1201, in lxml.etree._BaseParser._parseDocFromFilelike
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
XMLSyntaxError: xmlns:i: '&#38;#38;ns_ai;' is not a valid URI, line 21, column 33 (line 21)`

Here is the file in question (there are others but this is the one i did all the above testing on), nicely zipped up in formal zip garb as requested :)
[SAM_LOGO_SHIRT_Pink copy.zip](https://github.com/inkstitch/inkstitch/files/6566235/SAM_LOGO_SHIRT_Pink.copy.zip)

**Comment by kaalleen** [comment]
Wow thanks for the file and test report. Looking at your file I am very puzzled by what you have said about not using adobe illustrator. There is a lot of adobe illustrator "code" in your file which makes it impossible for Ink/Stitch and even a lot of Inkscape functions to parse the file correctly (same issue when trying to save as optimized svg). Usually the import solution worked and cleaned up the file, looks like this is not the case anymore. Bad news.

I haven't tried to use the "file > import" function with inkscape 1.0.2. Maybe it still works, could you try? Otherwise I am afraid I have no better solution to offer than cleaning up the files manually in a text editor.  I am really curious how adobe illustrator has conquered the file if it has not been touched with it.

Anyway... here is your manually cleaned up file as a starting point 
[SAM_LOGO_SHIRT_Pink copy_cleaned.zip](https://github.com/inkstitch/inkstitch/files/6566792/SAM_LOGO_SHIRT_Pink.copy_cleaned.zip)

**Comment by buzzmandt** [comment]
Holy crap, now I feel dumb LOL
In all honesty the svg file was originally made by someone else and sent to me. It's absolutely probable that he used illustrator....

What blew my mind was the fact I had edited it and saved it in inkscape. I totally thought that would have overridden any adobe stuff. My bad. We'll close this one and call it user error LOL. 

So, now I gotta figure out how to do that cleanup thing you did. But that's on me, not you....

Thank you for the interaction and the help.

**Comment by kaalleen** [comment]
I would like to keep this open since our offered solution obviously doesn't work anymore. We will need to update the error message text in some way.

The easiest way I can think of right now, is to copy paste the elements into a new document. Be careful not to also copy the switch group (this would copy the error as well). Before copying you would need to reapply colors since they are set as a css attribute and will not be recognized in the new document otherwise. Selecting the colored groups and turn off and on the color in the fill and stroke panel would be sufficient.

**Comment by kaalleen** [comment]
Closing.

Inkscape fixed the issue. They will output a warning about bad namespaces instead of exiting with a parsing error.
