### ISSUE TITLE
auto_fill: ValueError: min() arg is an empty sequence (fixed in 2.0)

### ISSUE THREAD

**Issue by emmalinecoulter** [inkstitch/inkstitch#1227]
Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\lib\elements\auto_fill.py", line 212, in to_patches
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 55, in auto_fill
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 149, in build_fill_stitch_graph
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 173, in insert_node
ValueError: min() arg is an empty sequence

**Comment by kaalleen** [comment]
This error was caused by very small fill elements in your document. The previous Ink/Stitch version wasn't able to handle them. This error message should disappear once you updated your Ink/Stitch version to Ink/Stitch 2.0

You still should try to trace those elements down and delete them. You do not really want them to be stitched out. Ink/Stitch has an extension for this reason: Extensions > Ink/Stitch > Troubleshoot > Cleanup document...
