### ISSUE TITLE
InkStitch jump stitch trim add

### ISSUE THREAD

**Issue by newbutold47** [inkstitch/inkstitch#1252]
Ink/Stitch Version: v2.0.0 (linux)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex/base.py", line 141, in run
  File "lib/extensions/object_commands.py", line 38, in effect
  File "lib/commands.py", line 392, in add_commands
  File "lib/commands.py", line 345, in get_command_pos
  File "lib/elements/element.py", line 309, in shape
NotImplementedError: ('INTERNAL ERROR: %s must implement shape()', <class 'lib.elements.text.TextObject'>)

**Comment by newbutold47** [comment]
Thank you will give it a go...

**Comment by newbutold47** [comment]
Kaalleen, I looked at the links re:#1230. I'm not sure how that will help me. Are you suggesting inserting code or is this a fix that was made and can solve my issue. I am fairly new to the embroidery world so I am not sure about the info.

**Comment by newbutold47** [comment]
Kaalleen, I tried the object to path command and it worked!!! Thank you!

**Comment by kaalleen** [comment]
Great. The second answer was just to myself. I didn't mean you will have to insert code anywhere. But looks like you figured that out already ;)
