### ISSUE TITLE
auto_fill: IndexError: tuple index out of range

### ISSUE THREAD

**Issue by hj579** [inkstitch/inkstitch#1269]
path14: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.0.0 (osx)

Traceback (most recent call last):
  File "lib/stitches/auto_fill.py", line 63, in auto_fill
  File "lib/debug.py", line 133, in decorated
  File "lib/stitches/auto_fill.py", line 144, in build_fill_stitch_graph
  File "lib/stitches/fill.py", line 97, in intersect_region_with_grating
ValueError: not enough values to unpack (expected 4, got 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib/elements/auto_fill.py", line 223, in to_patches
  File "lib/debug.py", line 133, in decorated
  File "lib/stitches/auto_fill.py", line 66, in auto_fill
  File "lib/stitches/auto_fill.py", line 263, in fallback
  File "shapely/geometry/base.py", line 895, in __getitem__
IndexError: tuple index out of range

**Comment by kaalleen** [comment]
Thank you for your error report. You discovered an interesting bug.
Would it be possible for you to send us the file which is causing the error? We would like to have a look at it in order to fix our code.
You can either post it here when it is zipped or send an e-mail to send-us-files@inkstitch.org
