### ISSUE TITLE
could not convert string to float

### ISSUE THREAD

**Issue by HirokaJP** [inkstitch/inkstitch#1271]
When I tried to do "Save a copy" with .jef format, I got this error.
I'm struggling to create .jef file yet, thus I may make not good drawing for .jef file....

```
Ink/Stitch Version: v2.0.0 (osx)


Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex/base.py", line 141, in run
  File "lib/extensions/output.py", line 55, in effect
  File "lib/extensions/base.py", line 207, in elements_to_patches
  File "lib/elements/element.py", line 362, in embroider
  File "lib/elements/element.py", line 418, in validate
  File "lib/elements/fill.py", line 182, in validation_errors
  File "lib/elements/fill.py", line 142, in shape
  File "lib/elements/fill.py", line 129, in paths
  File "lib/elements/element.py", line 305, in parse_path
  File "lib/elements/element.py", line 301, in path
  File "inkex/paths.py", line 1123, in __init__
  File "inkex/paths.py", line 1139, in parse_string
  File "inkex/utils.py", line 203, in strargs
  File "inkex/utils.py", line 203, in <listcomp>
ValueError: could not convert string to float: '178.066+228.606'
```

**Comment by kaalleen** [comment]
Uh, that is an interesting bug report. In order to solve the issue it would be best for us if we could have a look at your file. Would it be possible to post it here or send it to us through send-us-files@inkstitch.org ? We would greatfully appreciate your help.

**Comment by kaalleen** [comment]
Turns out this happens, when Ink/Stitch tries to render comments in the svg file (mostly created by other programs than Inkscape). This bug should be resolved with the next release. Therefore I'll close this issue now. Please reopen, if you receive this error message again with the upcoming release.
