### ISSUE TITLE
Error message when i try break apart objects 

### ISSUE THREAD

**Issue by HppPrinters** [inkstitch/inkstitch#1282]
PLease assist me with this im getting these error messages when it try run it on designs  

Ink/Stitch Version: v2.0.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex\base.py", line 141, in run
  File "lib\extensions\break_apart.py", line 59, in effect
  File "lib\extensions\break_apart.py", line 144, in polygons_to_nodes
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by tyrosinase** [comment]
That's a known bug that I think @kaalleen *just* rolled a fix for into main: https://github.com/inkstitch/inkstitch/issues/1246

**Comment by HppPrinters** [comment]
Thanks alot

**Comment by kaalleen** [comment]
As a workaround for now you could try to select the object and reapply the fill color.
