### ISSUE TITLE
Windows: setlocale()

### ISSUE THREAD

**Issue by Jsulung** [inkstitch/inkstitch#1294]
Hello, i am new in inkstich
kindly need help
after installation, there is error as below ( i used msi inkscape installation and directly extract to extension folder as youtube tutorial)

Ink/Stitch Version: v2.0.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex\base.py", line 141, in run
  File "lib\extensions\params.py", line 626, in effect
  File "lib\extensions\params.py", line 340, in __init__
  File "lib\extensions\params.py", line 606, in create_tabs
  File "lib\extensions\params.py", line 69, in __init__
wx._core.wxAssertionError: C++ assertion "strcmp(setlocale(0, 0), "C") == 0" failed at ..\..\src\common\intl.cpp(1694) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.
Things are going to break, please only change locale by creating wxLocale objects to avoid this!

**Comment by kaalleen** [comment]
@Jsulung thank you for your error report. We have seen this one before, have a look over here: #1232

**Comment by Jsulung** [comment]
thanks, it is solved now, i did installation using exe instead of msi, so i can choose the default local to be not re-create, it works
