### ISSUE TITLE
svg_objects issue

### ISSUE THREAD

**Issue by mattyhatter09** [inkstitch/inkstitch#1297]
when i try to export a pattern for embordery i get this error

Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\inkstitch.py", line 44, in <module>
  File "D:\a\inkstitch\inkstitch\inkscape\share\extensions\inkex.py", line 283, in affect
  File "D:\a\inkstitch\inkstitch\lib\extensions\embroider.py", line 84, in effect
  File "D:\a\inkstitch\inkstitch\lib\extensions\base.py", line 194, in elements_to_patches
  File "D:\a\inkstitch\inkstitch\lib\elements\element.py", line 329, in embroider
  File "D:\a\inkstitch\inkstitch\lib\elements\stroke.py", line 193, in to_patches
  File "D:\a\inkstitch\inkstitch\lib\elements\stroke.py", line 78, in paths
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\backports\functools_lru_cache.py", line 124, in wrapper
  File "D:\a\inkstitch\inkstitch\lib\elements\element.py", line 267, in parse_path
  File "D:\a\inkstitch\inkstitch\lib\elements\element.py", line 256, in path
  File "D:\a\inkstitch\inkstitch\lib\elements\svg_objects.py", line 62, in circle_to_path
TypeError: float() argument must be a string or a number

**Comment by kaalleen** [comment]
Thank you for reporting your issue. This error is one of the errors we have seen with an older Ink/Stitch version. I think an update will solve this problem. Download and install Ink/Stitch as described here: https://inkstitch.org/docs/install-windows/

**Comment by kaalleen** [comment]
I will close this issue. The error has been fixed with the release of Ink/Stitch 2.0
