### ISSUE TITLE
Auto-Satin: AttributeError: 'NoneType' object has no attribute 'intersects'

### ISSUE THREAD

**Issue by Wenceslass** [inkstitch/inkstitch#1299]
Hello,

Every time when i want to use Auto-Route Satin Columns comes this Error message:

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex\base.py", line 141, in run
  File "lib\extensions\auto_satin.py", line 69, in effect
  File "lib\stitches\auto_satin.py", line 325, in auto_satin
  File "lib\stitches\auto_satin.py", line 619, in operations_to_elements_and_trims
  File "lib\stitches\auto_satin.py", line 73, in to_satin
  File "lib\elements\satin_column.py", line 451, in split
  File "lib\elements\satin_column.py", line 517, in _assign_rungs_to_split_rails
  File "lib\elements\satin_column.py", line 517, in <genexpr>
AttributeError: 'NoneType' object has no attribute 'intersects'

**Comment by kaalleen** [comment]
Thank you for your error report. This is an interesting error. Could you post your svg file here or send it to send-us-files@inkstitch.org
We would like to have a look at it in order to fix it.

**Comment by Wenceslass** [comment]
Hello,

Sorry I have no save the same state where the error comes.
This is the most similar which I found. 
[PAPATO3.zip](https://github.com/inkstitch/inkstitch/files/6925625/PAPATO3.zip)

**Comment by kaalleen** [comment]
Thank you so much. It is always very helpful to receive files with errors. Do you still remember which changes you have made to this file before the error came up?
