### ISSUE TITLE
Unable to save ink/stitch

### ISSUE THREAD

**Issue by PacePrintDesign** [inkstitch/inkstitch#1307]
lib/extensions/base.py:58: DeprecationWarning: inkex.etree was removed, use "from lxml import etree"
Ink/Stitch experienced an unexpected error.

If you'd like to help, please file an issue at https://github.com/inkstitch/inkstitch/issues and include the entire error description below:

Ink/Stitch Version: v2.0.0 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex/base.py", line 141, in run
  File "lib/extensions/output.py", line 56, in effect
  File "lib/stitch_plan/stitch_plan.py", line 26, in patches_to_stitch_plan
IndexError: list index out of range

**Comment by kaalleen** [comment]
Thank you for your error reports. This error has been reported several times after the last release. It usually comes up, when you try to render only text or images. Ink/Stitch can only work with them, when they have been converted to vector graphics.

For text consider to use the Ink/Stitch lettering tool.
For images you can either manually trace your image with the bezier tool or try the Inkscape Bitmap tracing function found in the path menu. If you use the tracing method, you may want to use the Ink/Stitch > Fill Tools > Break apart fill objects function afterwards.

**Comment by tyrosinase** [comment]
Okay I've been threatening to do this for quite awhile and I finally did. Here's the first draft of a "so you have a bitmap and want it to become an embroidery file" tutorial: https://silverseams.com/free-patterns/embroidery-patterns/digitizing-with-ink-stitch/

I should probably put it in a repo (someone more experienced with Github is welcome to slurp it into this one; it's CC-BY-SA) so people can fix it, given that (1) I have no professional embroidery experience, and (2) conventional embroidery still isn't my top use of the thing.

I mean, we recently established that I had never noticed the difference between solid-line zigzag satin and rails-and-rungs true satin, so we know I have blind spots. Also I'm still getting over a bad cold and this was all written under the influence of pseudoephedrine (ugh).

**Comment by kaalleen** [comment]
This bug should not appear in the upcoming version anymore. Therefore I'll close the issue. Please reopen, if you ever see this again.
