### ISSUE TITLE
"could not convert string to float" when troubleshooting objects

### ISSUE THREAD

**Issue by kaelandm** [inkstitch/inkstitch#1308]
I clicked "Troubleshoot Objects" and received this error: 

Ink/Stitch Version: v2.0.0 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex/base.py", line 141, in run
  File "lib/extensions/troubleshoot.py", line 35, in effect
  File "lib/elements/polyline.py", line 101, in validation_warnings
  File "lib/elements/polyline.py", line 54, in points
  File "lib/elements/polyline.py", line 54, in <listcomp>
  File "lib/elements/polyline.py", line 54, in <listcomp>
ValueError: could not convert string to float: ''

**Comment by kaalleen** [comment]
Thank you for your error report, we really appreciate it. In order to solve the issue it would be very helpful for us, if we could have a look at the file. It would be great if you could post it here or send it to us via mail: send-us-files@inkstitch.org

**Comment by kaelandm** [comment]
I emailed it! I have a feeling the error might have something to do with bringing the svg from Illustrator to Inkscape. I've been creating svgs in Adobe Illustrator and opening them in Inkscape only to use Inkstitch, but Inkstitch seems to have trouble recognizing the paths created in Illustrator as paths (it insisted on treating them as fill objects, even when they were formatted correctly as running stitches, until I duplicated all of the paths and deleted the originals). Not sure if that helps.
