### ISSUE TITLE
MultiPolygon error on Break Apart FIll Objects

### ISSUE THREAD

**Issue by kaelandm** [inkstitch/inkstitch#1309]
I'm working with a large file with a lot of objects. I ran "Break Apart Fill Objects" and received this error: 

Ink/Stitch Version: v2.0.0 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex/base.py", line 141, in run
  File "lib/extensions/break_apart.py", line 59, in effect
  File "lib/extensions/break_apart.py", line 159, in polygons_to_nodes
AttributeError: 'MultiPolygon' object has no attribute 'exterior'

**Comment by kaalleen** [comment]
Thank you for your error report, we really appreciate it. In order to solve the issue it would be very helpful for us, if we could have a look at the file. It would be great if you could post it here or send it to us via mail: send-us-files@inkstitch.org

**Comment by kaelandm** [comment]
I emailed it! I have a feeling the error (same as the other one I reported) might have something to do with bringing the svg from Illustrator to Inkscape. I've been creating svgs in Adobe Illustrator and opening them in Inkscape only to use Inkstitch, but Inkstitch seems to have trouble recognizing the paths created in Illustrator as paths (it insisted on treating them as fill objects, even when they were formatted correctly as running stitches, until I duplicated all of the paths and deleted the originals). Not sure if that helps.

**Comment by kaalleen** [comment]
Thank you so much for the file. It is really valuable in order to fix the issues. While for the other issue it will reproduce the error, I am not able to trigger the break apart error again. I can only see running stitches which will be ignored by the break apart function. It would be nice to get more info how you ran the function, when the error showed up.

Adobe Illustrator can be really troublesome for Ink/Stitch. In your file I cannot seem to find issues that could be caused by it. But you have a style setting which will be difficult for Ink/Stitch 2.0 to read (the next version will be able to do so), but it's not used on any of the objects in the file and therefore shouldn't cause any issues.

**Comment by kaalleen** [comment]
Ok, giving a fill to the objects will reproduce the error just fine. Thank you again for your help!!
