### ISSUE TITLE
Stitch_plan: IndexError

### ISSUE THREAD

**Issue by CruiseGirl** [inkstitch/inkstitch#1314]
Below is the error in InkScape. The image was InkScape created text, nothing more.

Ink/Stitch Version: v2.0.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex\base.py", line 141, in run
  File "lib\extensions\output.py", line 56, in effect
  File "lib\stitch_plan\stitch_plan.py", line 26, in patches_to_stitch_plan
IndexError: list index out of range

**Comment by kaalleen** [comment]
Thank you for your error report. This specific error has been discussed here: #1307

**Comment by kaalleen** [comment]
This bug should not appear in the upcoming version anymore. Therefore I'll close the issue. Please reopen, if you ever see this again.
