### ISSUE TITLE
Problem exporting save file. 

### ISSUE THREAD

**Issue by DanWasHere** [inkstitch/inkstitch#1318]
Got an error when trying to export a save file. I'm going to try and run it through regardless as the file did save but it asked to send this code to you guys

path1022: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\lib\elements\auto_fill.py", line 212, in to_patches
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 55, in auto_fill
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 149, in build_fill_stitch_graph
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 173, in insert_node
ValueError: min() arg is an empty sequence

**Comment by kaalleen** [comment]
Thank you for your error report. This error is well known for a former version of Ink/Stitch.

Ink/Stitch v2.0.0 should be able to handle it better. I would still recommend you run Extensions > Ink/Stitch > Troubleshoot > Cleanup document... to remove tiny fill shapes that where possibly produced by image tracing.

If you want to update Ink/Stitch, follow the instructions on https://inkstitch.org/docs/install-windows/
