### ISSUE TITLE
Not able to save my svg file to pes file

### ISSUE THREAD

**Issue by pennster** [inkstitch/inkstitch#1323]
Not able to save my svg file to pes file.  Here is the error:

Ink/Stitch Version: v2.0.0 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex/base.py", line 141, in run
  File "lib/extensions/output.py", line 56, in effect
  File "lib/stitch_plan/stitch_plan.py", line 26, in patches_to_stitch_plan
IndexError: list index out of range

**Comment by tyrosinase** [comment]
This looks like the same issue as #1307 - if your design is only Inkscape text (versus Ink/Stitch lettering), you'll have to convert it to something embroiderable first. There are details in that issue.

**Comment by kaalleen** [comment]
This bug should not appear in the upcoming version anymore. Therefore I'll close the issue. Please reopen, if you ever see this again.
