### ISSUE TITLE
Params has no color for stitch 

### ISSUE THREAD

**Issue by DyeCozy** [inkstitch/inkstitch#1324]
Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex/base.py", line 141, in run
  File "lib/extensions/break_apart.py", line 59, in effect
  File "lib/extensions/break_apart.py", line 144, in polygons_to_nodes
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by tyrosinase** [comment]
This looks like the same issue as #1316, which is fixed for the next release and has a couple workarounds in the meantime.

**Comment by kaalleen** [comment]
I'll close this issue because there will be a fix in the upcoming release. Please reopen, if this is showing up again.
