### ISSUE TITLE
Cannot convert .svg file to .pes file for embroidery machine using inkstitch

### ISSUE THREAD

**Issue by KTWolf** [inkstitch/inkstitch#1325]
My param comes out looking correct the realistic preview shows everything coming out looking correctly but when I try to export it this shows up:

Ink/Stitch Version: v2.0.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex\base.py", line 141, in run
  File "lib\extensions\output.py", line 55, in effect
  File "lib\extensions\base.py", line 207, in elements_to_patches
  File "lib\elements\element.py", line 362, in embroider
  File "lib\elements\element.py", line 418, in validate
  File "lib\elements\fill.py", line 182, in validation_errors
  File "lib\elements\fill.py", line 164, in shape
  File "shapely\geometry\multipolygon.py", line 62, in __init__
  File "shapely\geometry\multipolygon.py", line 177, in geos_multipolygon_from_polygons
ValueError: Sequences of multi-polygons are not valid arguments

**Comment by tyrosinase** [comment]
This miiiiight be the same as #1215, in which case `Extensions > Ink/Stitch > Fill Tool > Break apart fill objects` should fix it. (There's no mention of things working in realistic preview there though, so maybe not. But that's the usual issue with multi-polygons.)

**Comment by kaalleen** [comment]
I'll close this issue because there will be a fix in the upcoming release. Please reopen, if this is showing up again.
