### ISSUE TITLE
element.py: NoneType attribute error

### ISSUE THREAD

**Issue by cantloupe** [inkstitch/inkstitch#1330]
My typical workflow is to draw linework of my design in the Concepts app on Android, then export that as a DXF. I pull the DXF into Inkscape on Windows 10 and follow the linework to make the actual embroidered design using fills within Inkscape, then run the params tool on these fills. This has been working without issue. 

This time, I exported as an SVG from Concepts rather than a DXF and brought that into Inkscape. I followed the same process as I have in the past after that, but now get the following error when I try to run anything from Ink/Stitch (params, fill tools, etc.) on the image: 

```
Ink/Stitch Version: v2.0.0 (windows)


Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex\base.py", line 141, in run
  File "lib\extensions\params.py", line 626, in effect
  File "lib\extensions\params.py", line 340, in __init__
  File "lib\extensions\params.py", line 590, in create_tabs
  File "lib\extensions\params.py", line 521, in get_nodes_by_class
  File "lib\extensions\base.py", line 181, in get_nodes
  File "lib\extensions\base.py", line 168, in descendants
  File "lib\extensions\base.py", line 141, in descendants
  File "lib\elements\element.py", line 92, in __init__
  File "lib\elements\element.py", line 124, in get_param
AttributeError: 'NoneType' object has no attribute 'strip'
```

The DXF from Concepts and the SVG I'm trying to embroider from are both attached:

[Concepts SVG Error.zip](https://github.com/inkstitch/inkstitch/files/7033334/Concepts.SVG.Error.zip)

**Comment by kaalleen** [comment]
Thank you so much for the file. This really makes it easy to figure out what is going wrong.
In your case Ink/Stitch somehow grabbed a comment in the svg file and tried to render it as an embroidery element. Ink/Stitch should be more clever about it, sorry for your trouble.

Here your two files without the comments. They should be working
[Concepts.SVG.Error.zip](https://github.com/inkstitch/inkstitch/files/7040692/Concepts.SVG.Error.zip)
