### ISSUE TITLE
Auto_fill: NetworkXNoPath

### ISSUE THREAD

**Issue by whimsicaljester** [inkstitch/inkstitch#1331]
path317_4: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.0.0 (windows)

Traceback (most recent call last):
  File "networkx\algorithms\shortest_paths\weighted.py", line 728, in multi_source_dijkstra
KeyError: (237.87498959380633, 155.9055118110241)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "lib\elements\auto_fill.py", line 235, in to_patches
  File "lib\debug.py", line 133, in decorated
  File "lib\stitches\auto_fill.py", line 73, in auto_fill
  File "lib\debug.py", line 133, in decorated
  File "lib\stitches\auto_fill.py", line 629, in path_to_stitches
  File "lib\stitches\auto_fill.py", line 594, in travel
  File "networkx\algorithms\shortest_paths\generic.py", line 162, in shortest_path
  File "networkx\algorithms\shortest_paths\weighted.py", line 157, in dijkstra_path
  File "networkx\algorithms\shortest_paths\weighted.py", line 464, in single_source_dijkstra
  File "networkx\algorithms\shortest_paths\weighted.py", line 730, in multi_source_dijkstra
networkx.exception.NetworkXNoPath: No path to (237.87498959380633, 155.9055118110241).

:) just posting bc the error message said it would be helpful to post

**Comment by kaalleen** [comment]
This is a very interresting bug which you have discovered there.
In order to solve the issue it would be very helpful to receive the file which is causing the error.
Would it be possible to send it to us? You can either post it here or send it via mail to send-us-files@inkstitch.org

**Comment by kaalleen** [comment]
Closing in favor of #2056
