### ISSUE TITLE
use4904: error: Error during autofill!

### ISSUE THREAD

**Issue by TriploidTree** [inkstitch/inkstitch#1338]
I have an old SVG from vinyl printing I'm trying to convert to inkstitch. 
I've got to a point where troubleshoot objects says everything is great, and when I run the simulator, it lays out lovely. 
[finalMokaEmb.svg.tar.gz](https://github.com/inkstitch/inkstitch/files/7147846/finalMokaEmb.svg.tar.gz)
However, when I try to save to .pes, get an error message (use4904: error: Error during autofill!) and it won't save. 

Traceback (most recent call last):
  File "lib/elements/auto_fill.py", line 223, in to_patches
  File "lib/elements/auto_fill.py", line 191, in underlay_shape
  File "lib/elements/auto_fill.py", line 187, in shrink_or_grow_shape
  File "lib/elements/fill.py", line 142, in shape
  File "lib/elements/fill.py", line 129, in paths
  File "lib/elements/element.py", line 305, in parse_path
  File "lib/elements/element.py", line 294, in path
  File "inkex/elements/_use.py", line 45, in get_path
  File "inkex/elements/_base.py", line 419, in path
  File "inkex/paths.py", line 1123, in __init__
  File "inkex/paths.py", line 1139, in parse_string
  File "inkex/utils.py", line 203, in strargs
  File "inkex/utils.py", line 203, in <listcomp>
ValueError: could not convert string to float: '.633.003'

**Comment by kaalleen** [comment]
@TriploidTree Thank you for your error report. This is really appreciated. Especially sending a file along with it is of great help.

I tested your file with a recent version. I cannot remember, when the error has been fixed, but the error didn't show up. Maybe you want to try to export your design with development version? Take for example https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-letters-to-font
I suggest this one because it fixes an error in the main branch which makes it impossible to open embroidery files (such as .pes). But it may have other issues. If you discover any of them, we are very curious to hear about it.

**Comment by TriploidTree** [comment]
Cool, I'll try that. I think I'm running v2.0.0 on Inkscape 1.1 (1:1.1+202105261517+ce6663b3b7)

**Comment by TriploidTree** [comment]
Ok, same inkscape with the letters-to-font build, it saves with no major upset. (I did get the following error: lib/elements/clone.py:103: DeprecationWarning: inkex.deprecated.composed_style -> Calculate the final styles applied to this element
    This function has been deprecated in favor of BaseElement.specified_style())
When I opened it on the machine I found a weird blob, so I embroidered up till that point (the inkstitch computer is *all the way* upstairs, and I was making dinner).
After dinner, I opened it on the computer and the blob is part of the .pes and I can't find a corresponding object on the original .svg, so now I am utterly baffled, but I have a moka pot. When I resave the svg to pes, I still get the unexpected blob.
![mokaPatch](https://user-images.githubusercontent.com/4170521/133153428-55450bac-cadb-48d1-818f-0b0861bb30c2.png)
![IMG_20210913_203803](https://user-images.githubusercontent.com/4170521/133153683-7f51ff18-6ccd-495b-8136-4808be07038c.jpg)
[MokaPotEmbroidery.tar.gz](https://github.com/inkstitch/inkstitch/files/7157270/MokaPotEmbroidery.tar.gz)

**Comment by kaalleen** [comment]
Interesting. Thank you for the feedback, warning message and file.
We will have to work on the code to fix these issues.
I cleaned your file, so you can go on working on your file. Rename it to .svg
[finalMokaEmb.log](https://github.com/inkstitch/inkstitch/files/7191046/finalMokaEmb.log)

Just a little note on the design itself. You may not want to cut your satin border in the edges, because you will see that later on. To do so, you can add a node into one side and break the square open at that point. When you run convert to satin on the prepared element, the satin will split at exactly that place.
