### ISSUE TITLE
fill: NotImplementedError: Multi-part geometries do not provide a coordinate sequence

### ISSUE THREAD

**Issue by HappyDuckHobbies** [inkstitch/inkstitch#1342]
Ink/Stitch Version: v2.0.0 (windows)

Traceback (most recent call last):
  File "lib\elements\auto_fill.py", line 235, in to_patches
  File "lib\debug.py", line 133, in decorated
  File "lib\stitches\auto_fill.py", line 63, in auto_fill
  File "lib\debug.py", line 133, in decorated
  File "lib\stitches\auto_fill.py", line 144, in build_fill_stitch_graph
  File "lib\stitches\fill.py", line 151, in intersect_region_with_grating
  File "shapely\geometry\base.py", line 867, in coords
NotImplementedError: Multi-part geometries do not provide a coordinate sequence

**Comment by kaalleen** [comment]
Thank you for your error report. Would it be possible for you to attach the troublesome svg file? It would help us a lot to investigate the error.

**Comment by kaalleen** [comment]
Same issue as #1427 (fixed)
