### ISSUE TITLE
save as dst file

### ISSUE THREAD

**Issue by maz8601** [inkstitch/inkstitch#1350]
please help, i have no idea how toconvert my png logo file to dst file for my semco embroidery machine.

Ink/Stitch Version: v2.0.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex\base.py", line 141, in run
  File "lib\extensions\output.py", line 56, in effect
  File "lib\stitch_plan\stitch_plan.py", line 26, in patches_to_stitch_plan
IndexError: list index out of range

**Comment by tyrosinase** [comment]
There's an explanation of that in this blog entry: https://silverseams.com/tutorials/digitizing-with-ink-stitch/

There are also video tutorials if you poke around YouTube (links to which probably should go in that blog entry at some point).

**Comment by kaalleen** [comment]
This bug should not appear in the upcoming version anymore. Therefore I'll close the issue. Please reopen, if you ever see this again.
