### ISSUE TITLE
I am unable to save a font I recently downloaded to be used with my Ink/Stitch Version: v2.0.0. Can I have some assistance, please.

### ISSUE THREAD

**Issue by koookie3** [inkstitch/inkstitch#1361]
Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex\base.py", line 141, in run
  File "lib\extensions\output.py", line 56, in effect
  File "lib\stitch_plan\stitch_plan.py", line 26, in patches_to_stitch_plan
IndexError: list index out of range

**Comment by tyrosinase** [comment]
If by "font" you mean a TrueType or the like, it first needs to be converted to something embroiderable.

https://silverseams.com/2020/03/monogramming-without-a-font/ and https://silverseams.com/tutorials/digitizing-with-ink-stitch/ talk about getting there.

**Comment by kaalleen** [comment]
This bug should not appear in the upcoming version anymore. Therefore I'll close the issue. Please reopen, if you ever see this again.
