### ISSUE TITLE
Got this error after making text and trying stimulator

### ISSUE THREAD

**Issue by agagnon830** [inkstitch/inkstitch#1362]
Ink/Stitch Version: v2.0.0 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex/base.py", line 141, in run
  File "lib/extensions/stitch_plan_preview.py", line 27, in effect
  File "lib/stitch_plan/stitch_plan.py", line 26, in patches_to_stitch_plan
IndexError: list index out of range

**Comment by tyrosinase** [comment]
Look at #1307 (or #1361, or... let's just say you're not alone) for some answers. Ink/Stitch shouldn't be throwing an incomprehensible message, but also it can't handle raw fonts.

**Comment by kaalleen** [comment]
This bug should not appear in the upcoming version anymore. Therefore I'll close the issue. Please reopen, if you ever see this again.
