### ISSUE TITLE
Unexpected error on Params

### ISSUE THREAD

**Issue by notmassproduced** [inkstitch/inkstitch#1368]
Hello!

I just started using Inkstitch and got this error message on the first try.
![2021-10-01](https://user-images.githubusercontent.com/91718424/135575518-672db5b3-0546-4934-ac4a-9e5d70b5f1a1.png)
 
Ink/Stitch Version: v2.0.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex\base.py", line 141, in run
  File "lib\extensions\params.py", line 626, in effect
  File "lib\extensions\params.py", line 340, in __init__
  File "lib\extensions\params.py", line 606, in create_tabs
  File "lib\extensions\params.py", line 69, in __init__
wx._core.wxAssertionError: C++ assertion "strcmp(setlocale(0, 0), "C") == 0" failed at ..\..\src\common\intl.cpp(1694) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.
Things are going to break, please only change locale by creating wxLocale objects to avoid this!

Help please! thanks.

**Comment by kaalleen** [comment]
Have a look at this issue here: #1232 This should help.

**Comment by kaalleen** [comment]
This issue will be solved in the upcoming release. Therefore I'm going to close this issue. Please reopen, if you have more questions.
