### ISSUE TITLE
speedups: ValueError: A LinearRing must have at least 3 coordinate tuples

### ISSUE THREAD

**Issue by Fellnasendesign** [inkstitch/inkstitch#1372]
DRINGEND, was ist zu tun??

Ich wollte eben eine Datei als pes speichern und bekam folgende Meldung:

Traceback (most recent call last):
  File "d:\a\inkstitch\inkstitch\inkstitch.py", line 44, in <module>
  File "d:\a\inkstitch\inkstitch\inkscape\share\extensions\inkex.py", line 283, in affect
  File "d:\a\inkstitch\inkstitch\lib\extensions\output.py", line 48, in effect
  File "d:\a\inkstitch\inkstitch\lib\extensions\base.py", line 185, in elements_to_patches
  File "d:\a\inkstitch\inkstitch\lib\elements\element.py", line 307, in embroider
  File "d:\a\inkstitch\inkstitch\lib\elements\element.py", line 364, in validate
  File "d:\a\inkstitch\inkstitch\lib\elements\fill.py", line 147, in validation_errors
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\backports\functools_lru_cache.py", line 124, in wrapper
  File "d:\a\inkstitch\inkstitch\lib\elements\fill.py", line 135, in shape
  File "d:\a\inkstitch\inkstitch\lib\elements\fill.py", line 135, in <lambda>
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\shapely\geometry\polygon.py", line 240, in __init__
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\shapely\geometry\polygon.py", line 494, in geos_polygon_from_py
  File "speedups\_speedups.pyx", line 321, in shapely.speedups._speedups.geos_linearring_from_py
ValueError: A LinearRing must have at least 3 coordinate tuples

**Comment by Fellnasendesign** [comment]
Done...inkscape with inkstitch new installed, no more error
