### ISSUE TITLE
Error converting string to float

### ISSUE THREAD

**Issue by kamikadzew** [inkstitch/inkstitch#1375]
I'm trying to get a hang on the software but i keep getting errors trying to:

- Simulate
- Stitch plan preview
- Troubleshoot object

All of them are similar and look like this:

```
Ink/Stitch experienced an unexpected error.

If you'd like to help, please file an issue at https://github.com/inkstitch/inkstitch/issues and include the entire error description below:

Ink/Stitch Version: v2.0.0 (windows)


Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex\base.py", line 141, in run
  File "lib\extensions\troubleshoot.py", line 32, in effect
  File "lib\elements\fill.py", line 182, in validation_errors
  File "lib\elements\fill.py", line 142, in shape
  File "lib\elements\fill.py", line 129, in paths
  File "lib\elements\element.py", line 305, in parse_path
  File "lib\elements\element.py", line 301, in path
  File "inkex\paths.py", line 1123, in __init__
  File "inkex\paths.py", line 1139, in parse_string
  File "inkex\utils.py", line 203, in strargs
  File "inkex\utils.py", line 203, in <listcomp>
ValueError: could not convert string to float: '-1.42.55'
```

**Comment by tyrosinase** [comment]
Looks like maybe the same as #1271 and #1338. Was it a file created entirely in Inkscape or imported?

**Comment by kaalleen** [comment]
No answer so far. The error message does look like the linked issues. That means it should have been fixed by now and will be corrected in the next release. I'm going to close this issue. If this shows up in the next release, please reopen.
