### ISSUE TITLE
"IndexError: list index out of range"

### ISSUE THREAD

**Issue by joule5** [inkstitch/inkstitch#1377]
(Hi. 1st time on github, so hopefully I'm doing this right. It said if I'd like to help to please file an issue here. Thank you.)

Ink/Stitch Version: v2.0.0 (linux)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex/base.py", line 141, in run
  File "lib/extensions/output.py", line 56, in effect
  File "lib/stitch_plan/stitch_plan.py", line 26, in patches_to_stitch_plan
IndexError: list index out of range

**Comment by kaalleen** [comment]
This bug should not appear in the upcoming version anymore. Therefore I'll close the issue. Please reopen, if you ever see this again.
