### ISSUE TITLE
Calculate clipPath into the shape

### ISSUE THREAD

**Issue by felsgaertner** [inkstitch/inkstitch#1413]
Hi,

when I select all objects and select "parameters", I get a preview of the stitching project.  
But with both "save as" output file and stitch plan preview I get this error:

~~~code
Ink/Stitch experienced an unexpected error.

If you'd like to help, please file an issue at https://github.com/inkstitch/inkstitch/issues and include the entire error description below:

Ink/Stitch Version: v2.0.0 (linux)


Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex/base.py", line 141, in run
  File "lib/extensions/output.py", line 55, in effect
  File "lib/extensions/base.py", line 207, in elements_to_patches
  File "lib/elements/element.py", line 362, in embroider
  File "lib/elements/element.py", line 418, in validate
  File "lib/elements/fill.py", line 182, in validation_errors
  File "lib/elements/fill.py", line 142, in shape
  File "lib/elements/fill.py", line 129, in paths
  File "lib/elements/element.py", line 305, in parse_path
  File "lib/elements/element.py", line 301, in path
  File "inkex/paths.py", line 1123, in __init__
  File "inkex/paths.py", line 1139, in parse_string
  File "inkex/utils.py", line 203, in strargs
  File "inkex/utils.py", line 203, in <listcomp>
ValueError: could not convert string to float: '.305.143.585.317.851.506'
~~~

This text is found once in the SVG file as
~~~xml
  <clipPath
     id="c">
    <path
       d="m608.847 324.356c.305.143.585.317.851.506-.264-.189-.546-.363-.851-.506m1.57 1.132c-.144-.148-.298-.285-.46-.418.162.132.316.271.46.418>
       id="path1012" />
  </clipPath>
~~~

Some version info here:
- Inkscape 1.1.1 (1:1.1+202109281949+c3084ef5ed)
- Ink/Stitch Version: v2.0.0 (linux)
- Linux Mint 20.1
- Python 3.8.10

**Comment by kaalleen** [comment]
I'll make this a feature request. We should aim to alter the path with the clipPath value instead of ignoring it.
