### ISSUE TITLE
element.py: IndexError: list index out of range

### ISSUE THREAD

**Issue by vanjape** [inkstitch/inkstitch#1414]
when i want to open params or simulator preview window these shows to me.

Ink/Stitch Version: v2.0.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex\base.py", line 141, in run
  File "lib\extensions\simulator.py", line 17, in effect
  File "lib\extensions\base.py", line 184, in get_elements
  File "lib\extensions\base.py", line 181, in get_nodes
  File "lib\extensions\base.py", line 168, in descendants
  File "lib\extensions\base.py", line 168, in descendants
  File "lib\extensions\base.py", line 150, in descendants
  File "lib\elements\element.py", line 204, in has_style
  File "lib\elements\element.py", line 185, in _get_style_raw
  File "lib\elements\element.py", line 175, in parse_style
  File "lib\elements\element.py", line 175, in <dictcomp>
IndexError: list index out of range

**Comment by kaalleen** [comment]
Thank you for your error report. This error mostly shows up, when you try to render only objects which Ink/Stitch doesn't understand (such as images or text). To fix the error you can use one of the options described below.

* For text consider to use the Ink/Stitch lettering tool.
* For images you can either manually trace your image with the bezier tool or try the Inkscape Bitmap tracing function found in the path menu. If you use the tracing method, you may want to use the Ink/Stitch > Fill Tools > Break apart fill objects function afterwards.

**Comment by vanjape** [comment]
Thanks for the replay.
I have it all drawn with the bezier tool. Last week everything was working normally. I don't know what could be wrong.

**Comment by kaalleen** [comment]
Interesting. In this case it's hard to say what is going wrong without having a look at the file. Could you send it to us? Maybe there is an other bug that needs a fix. You can send it either here as a zip file or send your svg file to send-us-files@inkstitch.org

**Comment by vanjape** [comment]
[sloncekspodatkimoder.zip](https://github.com/inkstitch/inkstitch/files/7463264/sloncekspodatkimoder.zip)

**Comment by kaalleen** [comment]
Closing. The style detection has been reworked a lot since this issue was created.
Please open a new issue if there are similar issue again.
