### ISSUE TITLE
fill: Multi-part geometries

### ISSUE THREAD

**Issue by Liligrenouille** [inkstitch/inkstitch#1415]
remplissage corps entier (path1219): erreur : Erreur pendant l'auto-remplissage. Cela veut dire que Ink/Stitch a un problème.

Si vous désirez nous aider à améliorer Ink/Stitch, veuillez SVP copier/coller ce message dans un nouveau rapport d'erreur (issue) ici: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.0.0 (osx)

Traceback (most recent call last):
  File "lib/elements/auto_fill.py", line 223, in to_patches
  File "lib/debug.py", line 133, in decorated
  File "lib/stitches/auto_fill.py", line 63, in auto_fill
  File "lib/debug.py", line 133, in decorated
  File "lib/stitches/auto_fill.py", line 144, in build_fill_stitch_graph
  File "lib/stitches/fill.py", line 151, in intersect_region_with_grating
  File "shapely/geometry/base.py", line 867, in coords
NotImplementedError: Multi-part geometries do not provide a coordinate sequence

**Comment by kaalleen** [comment]
Thank you for your error report. I believe this has been fixed for the next Ink/Stitch version, but I am not sure.
Would it be possible for you to send us the file either here in as a zip file or via mail to send-us-files@inkstitch.org
If you send the file, we can analyse what is going wrong and also help you to correct the error at this point.

**Comment by kaalleen** [comment]
Same as #1427
