### ISSUE TITLE
Inkstich error

### ISSUE THREAD

**Issue by hpreza** [inkstitch/inkstitch#1421]
Ink/Stitch Version: v2.0.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex\base.py", line 141, in run
  File "lib\extensions\params.py", line 626, in effect
  File "lib\extensions\params.py", line 340, in __init__
  File "lib\extensions\params.py", line 606, in create_tabs
  File "lib\extensions\params.py", line 69, in __init__
wx._core.wxAssertionError: C++ assertion "strcmp(setlocale(0, 0), "C") == 0" failed at ..\..\src\common\intl.cpp(1694) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.
Things are going to break, please only change locale by creating wxLocale objects to avoid this!

My name. Helder Preza
my email: h_preza@yahoo.com

**Comment by tyrosinase** [comment]
There is a fix out for that: #1232

**Comment by kaalleen** [comment]
Since this has been fixed for the upcoming release, I'll close the issue now. Please reopen, if you have more questions or if you are seeing this again within the next release.
