### ISSUE TITLE
Ink/Stitch experienced an unexpected error.

### ISSUE THREAD

**Issue by Jenny-JK** [inkstitch/inkstitch#1424]
Ink/Stitch Version: v2.0.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex\base.py", line 141, in run
  File "lib\extensions\break_apart.py", line 59, in effect
  File "lib\extensions\break_apart.py", line 144, in polygons_to_nodes
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by kaalleen** [comment]
Try to reapply the colors of your design. Just open the fill and stroke panel and turn on and off the color settings. This will be fixed within the next release. Sorry for your trouble.

**Comment by kaalleen** [comment]
Please reopen, if this problem still exists in the upcoming release.
