### ISSUE TITLE
auto_fill: NotImplementedError: Multi-part geometries do not provide a coordinate sequence

### ISSUE THREAD

**Issue by swaphulk** [inkstitch/inkstitch#1427]
**Steps to replicate:**
1) Open inkscape
2) Open svg
3) Save as
4) Select .PES
5) Save

**Error:**

Ink/Stitch Version: v2.0.0 (osx)

Traceback (most recent call last):
  File "lib/elements/auto_fill.py", line 223, in to_patches
  File "lib/debug.py", line 133, in decorated
  File "lib/stitches/auto_fill.py", line 71, in auto_fill
  File "lib/debug.py", line 133, in decorated
  File "lib/stitches/auto_fill.py", line 297, in build_travel_graph
  File "lib/stitches/auto_fill.py", line 435, in build_travel_edges
  File "lib/stitches/auto_fill.py", line 386, in travel_grating
  File "lib/stitches/fill.py", line 151, in intersect_region_with_grating
  File "shapely/geometry/base.py", line 867, in coords
NotImplementedError: Multi-part geometries do not provide a coordinate sequence

**The SVG**
Here's the most boiled-down svg that still encounters this error:
```
<svg
   width="350mm"
   height="340mm"
   xmlns:svg="http://www.w3.org/2000/svg">
   <g id="layer1">
       <path d="M 160 160 L 160 170 L 210 170 L 210 180 L 200 180 L 200 190 L 150 190 L 150 180 L 140 180 L 140 170 L 120 170 L 120 160 z" style="fill:#e8e33c;"/>
  </g>
</svg>
```

Love this extension. Thanks so much for your help!

**Comment by kaalleen** [comment]
Thank you for your bug report. This bug is still present in recent development versions. Therefore your svg file is very valuable for us.

**Comment by doj** [comment]
I have the same issue, I'm attaching a minimal SVG file
[asd.svg.gz](https://github.com/inkstitch/inkstitch/files/7601138/asd.svg.gz)
.

**Comment by kaalleen** [comment]
The provided file renders just fine in the current Ink/Stitch version.
