### ISSUE TITLE
HELP!!

### ISSUE THREAD

**Issue by Laarzz** [inkstitch/inkstitch#1430]
Ink/Stitch Version: v2.0.0 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex/base.py", line 141, in run
  File "lib/extensions/object_commands.py", line 38, in effect
  File "lib/commands.py", line 392, in add_commands
  File "lib/commands.py", line 345, in get_command_pos
  File "lib/elements/element.py", line 309, in shape
NotImplementedError: ('INTERNAL ERROR: %s must implement shape()', <class 'lib.elements.text.TextObject'>)

IS THERE A FIX FOR THIS????

**Comment by tyrosinase** [comment]
Not an Ink/Stitch dev but I'll jump in: what does `Troubleshoot > Troubleshoot Objects` say?

**Comment by kaalleen** [comment]
Thanks for reporting the error. We really appreciate your input. Each traceback we consider a bug in Ink/Stitch, which shouldn't be shown to the user.

To fix your issue convert your text into a path. In most cases fonts look better though, if they are satin stitches, not fill stitches. You can also checkout the lettering tool in the Ink/Stitch extension section.

**Comment by kaalleen** [comment]
Ink/Stitch will give a proper error message in the next version. Therefore I will close this issue now. Please reopen, if you have more questions about this topic.
