### ISSUE TITLE
Error creating json

### ISSUE THREAD

**Issue by majodesign** [inkstitch/inkstitch#1435]
Ink/Stitch Version: v2.0.0 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex/base.py", line 141, in run
  File "lib/extensions/lettering_generate_json.py", line 48, in effect
  File "lib/lettering/kerning.py", line 25, in horiz_adv_x
  File "lib/lettering/kerning.py", line 25, in <listcomp>
ValueError: invalid literal for int() with base 10: 'c'

After spending hours to convert an font to an ink stitch font and saving the file to →.svg i go to create the json file and get the above error.

**Comment by majodesign** [comment]
Isseur is resolved after kerning the font file the error disapeared. So tt closed.
