### ISSUE TITLE
wxpython: wxLocale

### ISSUE THREAD

**Issue by Sagarpurii** [inkstitch/inkstitch#1436]
Ink/Stitch Version: v2.0.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex\base.py", line 141, in run
  File "lib\extensions\params.py", line 626, in effect
  File "lib\extensions\params.py", line 340, in __init__
  File "lib\extensions\params.py", line 606, in create_tabs
  File "lib\extensions\params.py", line 69, in __init__
wx._core.wxAssertionError: C++ assertion "strcmp(setlocale(0, 0), "C") == 0" failed at ..\..\src\common\intl.cpp(1694) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.
Things are going to break, please only change locale by creating wxLocale objects to avoid this!

**Comment by kaalleen** [comment]
This bug shows up with various language settings. To fix it have a look at #1232

**Comment by kaalleen** [comment]
I'll close this issue. It'll should be fixed in the next release.
