### ISSUE TITLE
commands: 'MultiPolygon' object has no attribute 'exterior'

### ISSUE THREAD

**Issue by Laarzz** [inkstitch/inkstitch#1437]
Ink/Stitch Version: v2.0.0 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex/base.py", line 141, in run
  File "lib/extensions/object_commands.py", line 38, in effect
  File "lib/commands.py", line 392, in add_commands
  File "lib/commands.py", line 345, in get_command_pos
AttributeError: 'MultiPolygon' object has no attribute 'exterior'

I traced the pictures bitmap like the video told me to do but this error still happened!! someone help

**Comment by kaalleen** [comment]
Interesting. Thanks for reporting this back to us. Do you still have the file which is causing the issue? It would be nice if we could have a look at it.

Did you run the fill tools > break apart fill objects... function on your design before you tried to apply a command? It may help, not sure.

**Comment by PumpkinWolf** [comment]
I feel like I'm having a similar issue? I used the fill tools and params will work when the part of my image that is only black is showing but the second I add some colored fill lines I get this:

Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "lib\gui\simulator.py", line 779, in run
  File "lib\gui\simulator.py", line 792, in update_patches
  File "lib\stitch_plan\stitch_plan.py", line 26, in patches_to_stitch_plan
  File "lib\stitch_plan\stitch_plan.py", line 78, in new_color_block
  File "lib\stitch_plan\stitch_plan.py", line 177, in __init__
  File "lib\stitch_plan\stitch_plan.py", line 212, in color
  File "lib\threads\color.py", line 29, in __init__
TypeError: 'NoneType' object is not iterable


I'm on windows.

**Comment by PumpkinWolf** [comment]
Update I got it to work with all of the coloring except the colored stoke lines I spoke of?? I'm so confused why these particular stokes are causing an error. Let me know if you'd like screenshots.

**Comment by Tina-Chris** [comment]
@PumpkinWolf you could send the culprit files for us to review the problem send-us-files@inkstitch.org
