### ISSUE TITLE
break apart and fill

### ISSUE THREAD

**Issue by jawsfree** [inkstitch/inkstitch#1450]
nk/Stitch experienced an unexpected error.

If you'd like to help, please file an issue at https://github.com/inkstitch/inkstitch/issues and include the entire error description below:

Ink/Stitch Version: v2.0.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex\base.py", line 141, in run
  File "lib\extensions\break_apart.py", line 59, in effect
  File "lib\extensions\break_apart.py", line 144, in polygons_to_nodes
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by jawsfree** [comment]
this is error from complex attempt

Ink/Stitch experienced an unexpected error.

If you'd like to help, please file an issue at https://github.com/inkstitch/inkstitch/issues and include the entire error description below:

Ink/Stitch Version: v2.0.0 (windows)


Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex\base.py", line 141, in run
  File "lib\extensions\break_apart.py", line 59, in effect
  File "lib\extensions\break_apart.py", line 144, in polygons_to_nodes
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by tyrosinase** [comment]
That's a known problem that will be fixed in the next release (see #1316 etc.) - reapply colors on the objects (turn them off and back on) and it should be fine.

**Comment by kaalleen** [comment]
I'll close this issue, since it has been fixed for the next release. Please reopen, if the error still shows up in the next version of Ink/Stitch.
