### ISSUE TITLE
Issue when trying to save file

### ISSUE THREAD

**Issue by jenniecahoon35** [inkstitch/inkstitch#1456]
Ink/Stitch Version: v2.0.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex\base.py", line 141, in run
  File "lib\extensions\output.py", line 56, in effect
  File "lib\stitch_plan\stitch_plan.py", line 26, in patches_to_stitch_plan
IndexError: list index out of range

**Comment by tyrosinase** [comment]
That's a known bug; in the future I think Ink/Stitch will properly you a non-error explanation. At the moment that's what it does when it doesn't have any valid stitch-able objects. You'll find a more thorough explanation in the comments of #1307.

**Comment by kaalleen** [comment]
This bug should not appear in the upcoming version anymore. Therefore I'll close the issue. Please reopen, if you ever see this again.
