### ISSUE TITLE
auto_fill: NetworkXNoPath: No path to ...

### ISSUE THREAD

**Issue by janawilhite** [inkstitch/inkstitch#1459]
path3315-4: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.0.0 (osx)

Traceback (most recent call last):
  File "networkx/algorithms/shortest_paths/weighted.py", line 728, in multi_source_dijkstra
KeyError: (148.78710239999998, 101.10937200000001)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "lib/elements/auto_fill.py", line 235, in to_patches
  File "lib/debug.py", line 133, in decorated
  File "lib/stitches/auto_fill.py", line 73, in auto_fill
  File "lib/debug.py", line 133, in decorated
  File "lib/stitches/auto_fill.py", line 629, in path_to_stitches
  File "lib/stitches/auto_fill.py", line 594, in travel
  File "networkx/algorithms/shortest_paths/generic.py", line 162, in shortest_path
  File "networkx/algorithms/shortest_paths/weighted.py", line 157, in dijkstra_path
  File "networkx/algorithms/shortest_paths/weighted.py", line 464, in single_source_dijkstra
  File "networkx/algorithms/shortest_paths/weighted.py", line 730, in multi_source_dijkstra
networkx.exception.NetworkXNoPath: No path to (148.78710239999998, 101.10937200000001).

**Comment by tyrosinase** [comment]
This looks like the same issue as #1331 and/or #1417, which unfortunately don't have fixes yet (that I know of). If it's possible, send the file to the devs at send-us-files@inkstitch.org.

In the meantime, changing the stitching order so the autofill tries a different start/end point for that object might get around it.

**Comment by Tina-Chris** [comment]
@tyrosinase how do you differentiate between this here and the other "error during autofill" in this issue? https://github.com/inkstitch/inkstitch/issues/1428
I ask to be able to point users to the correct solution.
Thanks
Tina

**Comment by tyrosinase** [comment]
The tracebacks are very different. the one with "NetworkXNoPath: No path to [coordinates]" is the auto-filler painting itself into a corner, and (AFAIK) no other situation. The "min() arg is an empty sequence" means it has something un-fillable - either a too-small thing that needs the cleanup done on it, or else someone has loaded a bitmap or Inkscape text and said "embroider this" with no further human intervention.

It's pretty easy to find previous issues/solutions just by grabbing something toward the end that looks distinctive and putting that in GitHub's search line. But I'm not sure if that's something that would be intuitive enough for a non-developer to do though (I'm not a Python dev but Perl5 tracebacks are the same) so I am not sure changing the "paste this into a new issue" instructions would improve things.

**Comment by kaalleen** [comment]
Closing in favor of #2056
