### ISSUE TITLE
output: AttributeError:  'NoneType' object has no attribute 'pyembroidery_thread'

### ISSUE THREAD

**Issue by malobae** [inkstitch/inkstitch#1477]
Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex\base.py", line 141, in run
  File "lib\extensions\output.py", line 63, in effect
  File "lib\output.py", line 61, in write_embroidery_file
AttributeError: 'NoneType' object has no attribute 'pyembroidery_thread'

**Comment by kaalleen** [comment]
Thank you for reporting your issue. For us it would make it easy to fix the bug, if we had the svg file which is causing it. Would you mind to upload it here or send it to send-us-files@inkstitch.org

**Comment by kaalleen** [comment]
Closing in favor of https://github.com/inkstitch/inkstitch/issues/2825
