### ISSUE TITLE
Convert to PES?

### ISSUE THREAD

**Issue by kru752** [inkstitch/inkstitch#1481]
Ink/Stitch Version: v2.0.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex\base.py", line 141, in run
  File "lib\extensions\output.py", line 56, in effect
  File "lib\stitch_plan\stitch_plan.py", line 26, in patches_to_stitch_plan
IndexError: list index out of range

**Comment by tyrosinase** [comment]
That's a known bug; in the future I think Ink/Stitch will properly give you a non-error explanation. At the moment that's what it does when it doesn't have any valid stitch-able objects. You'll find a more thorough explanation in the comments of #1307.
