### ISSUE TITLE
NetworkXNoPath (autofill)

### ISSUE THREAD

**Issue by TheBlackWolfHouston** [inkstitch/inkstitch#1491]
Embroidery Tech in Houston encountering problem with your product. Please advise or resolve. Thank you.

----------------------------------------

path17961: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.0.0 (windows)

Traceback (most recent call last):
  File "networkx\algorithms\shortest_paths\weighted.py", line 728, in multi_source_dijkstra
KeyError: (216.64363756048314, 528.2640121991135)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "lib\elements\auto_fill.py", line 223, in to_patches
  File "lib\debug.py", line 133, in decorated
  File "lib\stitches\auto_fill.py", line 73, in auto_fill
  File "lib\debug.py", line 133, in decorated
  File "lib\stitches\auto_fill.py", line 629, in path_to_stitches
  File "lib\stitches\auto_fill.py", line 594, in travel
  File "networkx\algorithms\shortest_paths\generic.py", line 162, in shortest_path
  File "networkx\algorithms\shortest_paths\weighted.py", line 157, in dijkstra_path
  File "networkx\algorithms\shortest_paths\weighted.py", line 464, in single_source_dijkstra
  File "networkx\algorithms\shortest_paths\weighted.py", line 730, in multi_source_dijkstra
networkx.exception.NetworkXNoPath: No path to (216.64363756048314, 528.2640121991135).

**Comment by tyrosinase** [comment]
This looks like the same issue as #1331 and/or #1417, which unfortunately don't have fixes yet (that I know of). If it's possible, send the file to the devs at send-us-files@inkstitch.org.

In the meantime, changing the stitching order so the autofill tries a different start/end point for that object might get around it.

**Comment by TheBlackWolfHouston** [comment]
As a new user, I don't quite know what you mean by "stitching order". Are you referring to which segment gets embroidered first? Also, which file should I send?

Thanks

**Comment by tyrosinase** [comment]
Yes, the fill will start at different points depending on what comes before or after it, and you can sometimes talk it into choosing a start point where it doesn't paint itself into a corner.

What's happening is that it fills most of the shape in and then realizes it can't get to an un-filled spot elsewhere in the shape now. If re-ordering the stitching isn't possible or doesn't help, you can help it out by manually breaking up the shape into multiple, simpler ones if you can find a place to do that that won't show a seam.

The devs have discussed using different algorithms to choose the paths, so if you can send them the problem SVG that helps. (If copyright or customer agreements mean you can't, that's fine.)

**Comment by kaalleen** [comment]
Closing in favor of #2056
