### ISSUE TITLE
Windows speedups issue

### ISSUE THREAD

**Issue by annesolulu** [inkstitch/inkstitch#1496]
Ink/Stitch Version: v2.0.0 (windows)

Traceback (most recent call last):
  File "shapely\speedups\_speedups.pyx", line 88, in shapely.speedups._speedups.geos_linestring_from_py
AttributeError: 'list' object has no attribute '__array_interface__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex\base.py", line 141, in run
  File "lib\extensions\object_commands.py", line 38, in effect
  File "lib\commands.py", line 392, in add_commands
  File "lib\commands.py", line 345, in get_command_pos
  File "lib\elements\stroke.py", line 98, in shape
  File "lib\elements\stroke.py", line 98, in <listcomp>
  File "shapely\geometry\linestring.py", line 48, in __init__
  File "shapely\geometry\linestring.py", line 97, in _set_coords
  File "shapely\speedups\_speedups.pyx", line 154, in shapely.speedups._speedups.geos_linestring_from_py
ValueError: LineStrings must have at least 2 coordinate tuples

**Comment by kaalleen** [comment]
Interesting, that this appears on a windows machine. We are used to this kind of error only for macOS. The solution usually would be to delete the speedups library for shapely. But I am not sure at the moment how this can be done with the windows version. I'll have to think about it and come back to you.

**Comment by kaalleen** [comment]
Could you try the just released Ink/Stitch version and report if this issue is still there?

**Comment by annesolulu** [comment]
I have re-tried to reproduce the problem first on 2.0 release. But since my report in december, I changed a little my path and I am not able to reproduce, even if I add a trim command.
I just installed V2.1 release, and everything is still ok.
Thank you anyway !
