### ISSUE TITLE
Error on Extensions > Inkstitch > Fix errors > Fix errors in objects

### ISSUE THREAD

**Issue by tobik** [inkstitch/inkstitch#1500]
Ink/Stitch Version: v2.0.0 (linux)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex/base.py", line 141, in run
  File "lib/extensions/troubleshoot.py", line 32, in effect
  File "lib/elements/fill.py", line 182, in validation_errors
  File "lib/elements/fill.py", line 164, in shape
  File "shapely/geometry/multipolygon.py", line 62, in __init__
  File "shapely/geometry/multipolygon.py", line 177, in geos_multipolygon_from_polygons
ValueError: Sequences of multi-polygons are not valid arguments

**Comment by tyrosinase** [comment]
There's a workaround for this in #1215 and it is fixed in a future release.

**Comment by tobik** [comment]
Thank you very much.
