### ISSUE TITLE
Hi this is my second day using this and I'm running into an error I cannot surpass as it says it's on your end

### ISSUE THREAD

**Issue by Pear-e** [inkstitch/inkstitch#1505]
path519_17: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.0.0 (osx)

Traceback (most recent call last):
  File "networkx/algorithms/shortest_paths/weighted.py", line 728, in multi_source_dijkstra
KeyError: (163.754792148634, 337.50632572351265)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "lib/elements/auto_fill.py", line 223, in to_patches
  File "lib/debug.py", line 133, in decorated
  File "lib/stitches/auto_fill.py", line 73, in auto_fill
  File "lib/debug.py", line 133, in decorated
  File "lib/stitches/auto_fill.py", line 629, in path_to_stitches
  File "lib/stitches/auto_fill.py", line 594, in travel
  File "networkx/algorithms/shortest_paths/generic.py", line 162, in shortest_path
  File "networkx/algorithms/shortest_paths/weighted.py", line 157, in dijkstra_path
  File "networkx/algorithms/shortest_paths/weighted.py", line 464, in single_source_dijkstra
  File "networkx/algorithms/shortest_paths/weighted.py", line 730, in multi_source_dijkstra
networkx.exception.NetworkXNoPath: No path to (163.754792148634, 337.50632572351265).

**Comment by tyrosinase** [comment]
Unfortunately that's a known bug, #1459 has a little more discussion of it, and potential workarounds.

**Comment by kaalleen** [comment]
Closing in favor of #2056
