### ISSUE TITLE
Valid image but getting these codes

### ISSUE THREAD

**Issue by Zaidei** [inkstitch/inkstitch#1514]
Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex\base.py", line 141, in run
  File "lib\extensions\stitch_plan_preview.py", line 27, in effect
  File "lib\stitch_plan\stitch_plan.py", line 32, in patches_to_stitch_plan
  File "lib\threads\color.py", line 65, in __ne__
  File "lib\threads\color.py", line 59, in __eq__
  File "lib\threads\color.py", line 29, in __init__
TypeError: 'NoneType' object is not iterable

**Comment by tyrosinase** [comment]
Oh, that's one the devs have been looking for examples of: see #1334 for workarounds, but if you can share a copy of the unfixed file(s) first that would probably help them with a permanent fix.

**Comment by kaalleen** [comment]
I believe this has been fixed lately. If not, please reopen!!
