### ISSUE TITLE
Ink/Stitch experienced an unexpected error.

### ISSUE THREAD

**Issue by georgschilling** [inkstitch/inkstitch#1535]
Ink/Stitch Version: v2.0.0 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex/base.py", line 141, in run
  File "lib/extensions/stitch_plan_preview.py", line 27, in effect
  File "lib/stitch_plan/stitch_plan.py", line 26, in patches_to_stitch_plan
IndexError: list index out of range

**Comment by tyrosinase** [comment]
That's a known bug in the previous version; the newest release of Ink/Stitch will properly give you a non-error explanation. But that's what it does when it doesn't have any valid stitch-able objects, so you don't necessarily have to upgrade - just see the comments on #1307.
