### ISSUE TITLE
Multi-part geometries do not provide a coordinate sequence (2.1.0)

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#1544]
Got an interesting error while trying to do a Stitch Plan Preview of some of the fonts (okay, all of the fonts). Not sure if it's a variation of #1427 or a truly new bug.

This is on Raspbian, Inkscape 1.0.2 (the Raspbian repo one), and a manually-built Inkstitch 2.1.0. Troubleshooting has no complaints, and it's all Lettering objects.

```
path1136: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: Manual Install (Linux)


Traceback (most recent call last):
  File "/home/pi/inkstitch/lib/elements/auto_fill.py", line 228, in to_stitch_groups
    stitches=auto_fill(
  File "/home/pi/inkstitch/lib/debug.py", line 133, in decorated
    result = func(*args, **kwargs)
  File "/home/pi/inkstitch/lib/stitches/auto_fill.py", line 72, in auto_fill
    travel_graph = build_travel_graph(fill_stitch_graph, shape, angle, underpath)
  File "/home/pi/inkstitch/lib/debug.py", line 133, in decorated
    result = func(*args, **kwargs)
  File "/home/pi/inkstitch/lib/stitches/auto_fill.py", line 298, in build_travel_graph
    boundary_points, travel_edges = build_travel_edges(shape, fill_stitch_angle)
  File "/home/pi/inkstitch/lib/stitches/auto_fill.py", line 437, in build_travel_edges
    grating2 = travel_grating(shape, fill_angle - math.pi / 4, scale * 2 * PIXELS_PER_MM)
  File "/home/pi/inkstitch/lib/stitches/auto_fill.py", line 387, in travel_grating
    rows_of_segments = intersect_region_with_grating(shape, angle, row_spacing)
  File "/home/pi/inkstitch/lib/stitches/fill.py", line 149, in intersect_region_with_grating
    if res.is_empty or len(res.coords) == 1:
  File "/home/pi/.local/lib/python3.9/site-packages/shapely/geometry/base.py", line 840, in coords
    raise NotImplementedError(
NotImplementedError: Multi-part geometries do not provide a coordinate sequence


```

**Comment by kaalleen** [comment]
I suppose this is the same issue. There is a pull request for this one, but it's not a very nice solution I guess.

**Comment by kaalleen** [comment]
Seems to be fixed. Open a new issue if this shows up again.
