### ISSUE TITLE
inkscape config path error

### ISSUE THREAD

**Issue by SpyrzGaming** [inkstitch/inkstitch#1549]
If you'd like to help, please file an issue at https://github.com/inkstitch/inkstitch/issues and include the entire error description below:

Ink/Stitch Version: v2.1.2 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 67, in <module>
  File "inkex\base.py", line 147, in run
  File "lib\extensions\print_pdf.py", line 313, in effect
  File "lib\threads\catalog.py", line 118, in ThreadCatalog
  File "lib\threads\catalog.py", line 21, in __init__
  File "lib\threads\catalog.py", line 28, in get_palettes_paths
  File "lib\utils\inkscape.py", line 14, in guess_inkscape_config_path
  File "ntpath.py", line 185, in split
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by kaalleen** [comment]
Oh sorry, my bad. Try to go back for now to Ink/Stitch 2.1.0
https://github.com/inkstitch/inkstitch/releases/tag/v2.1.0
Pick the windows.exe file.

**Comment by SpyrzGaming** [comment]
Okey. Thank you

**Comment by kaalleen** [comment]
Would you mind to run the linked version below? I hope it fixes your issue?

https://github.com/inkstitch/inkstitch/releases/download/dev-build-kaalleen-ink-conf-path1/inkstitch-kaalleen-ink-conf-path1-windows.exe
