### ISSUE TITLE
NotImplementedError: Multi-part geometries (fill)

### ISSUE THREAD

**Issue by stupidstinky** [inkstitch/inkstitch#1564]
path176: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.1.2 (windows)

Traceback (most recent call last):
  File "lib\elements\auto_fill.py", line 228, in to_stitch_groups
  File "lib\debug.py", line 133, in decorated
  File "lib\stitches\auto_fill.py", line 72, in auto_fill
  File "lib\debug.py", line 133, in decorated
  File "lib\stitches\auto_fill.py", line 298, in build_travel_graph
  File "lib\stitches\auto_fill.py", line 438, in build_travel_edges
  File "lib\stitches\auto_fill.py", line 387, in travel_grating
  File "lib\stitches\fill.py", line 149, in intersect_region_with_grating
  File "shapely\geometry\base.py", line 840, in coords
NotImplementedError: Multi-part geometries do not provide a coordinate sequence

**Comment by kaalleen** [comment]
Possibly yes. This is a bug in Ink/Stitch. We hope, that this has been fixed lately.

If you want to test it with a development version download it here: https://github.com/inkstitch/inkstitch/releases/download/dev-build-kall-test/inkstitch-kall-test-windows.exe

We are curious, if that helped :)
