### ISSUE TITLE
Stitch Plan Preview Error

### ISSUE THREAD

**Issue by suedarby** [inkstitch/inkstitch#1567]
Ink/Stitch experienced an unexpected error.
If you'd like to help, please file an issue at https://github.com/inkstitch/inkstitch/issues and include the entire error description below: 

Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\inkstitch.py", line 44, in <module>
  File "D:\a\inkstitch\inkstitch\inkscape\share\extensions\inkex.py", line 283, in affect
  File "D:\a\inkstitch\inkstitch\lib\extensions\stitch_plan_preview.py", line 18, in effect
  File "D:\a\inkstitch\inkstitch\lib\extensions\base.py", line 194, in elements_to_patches
  File "D:\a\inkstitch\inkstitch\lib\elements\element.py", line 329, in embroider
  File "D:\a\inkstitch\inkstitch\lib\elements\auto_fill.py", line 197, in to_patches
  File "D:\a\inkstitch\inkstitch\lib\elements\auto_fill.py", line 181, in get_starting_point
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\backports\functools_lru_cache.py", line 124, in wrapper
  File "D:\a\inkstitch\inkstitch\lib\elements\element.py", line 294, in get_command
  File "src\lxml\etree.pyx", line 1294, in lxml.etree._Element.get
  File "src\lxml\apihelpers.pxi", line 577, in lxml.etree._getAttributeValue
  File "src\lxml\apihelpers.pxi", line 564, in lxml.etree._getNodeAttributeValue
  File "src\lxml\apihelpers.pxi", line 1657, in lxml.etree._getNsTag
  File "src\lxml\apihelpers.pxi", line 1675, in lxml.etree.__getNsTag
  File "src\lxml\apihelpers.pxi", line 1538, in lxml.etree._utf8
TypeError: Argument must be bytes or unicode, got 'builtin_function_or_method'

**Comment by kaalleen** [comment]
Thank you for your error reports. I am wondering, if you are using a current version of Ink/Stitch?

**Comment by kaalleen** [comment]
Closing, because this seems to belong to an outdated Ink/Stitch version. Please comment down below here or into a new issue, if this is still showing up in recent releases.
