### ISSUE TITLE
Fill silently fails on underlay

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#1569]
Fill is apparently struggling with the holes in this small shape, but instead of throwing an error it just leaves out the underlay.

svg-as-text, please don't choke, Github:
[BadExample.txt](https://github.com/inkstitch/inkstitch/files/7972688/BadExample.txt)

Rotating the shape slightly fixes it, but interestingly changing the fill angle doesn't necessarily do so. Even dragging it to a different place on the document can fix it (which is why it's in such an odd place in this document; that's where the copy-paste landed).

**Comment by kaalleen** [comment]
Traceback (most recent call last):
  File "/inkstitch/lib/elements/fill_stitch.py", line 482, in to_stitch_groups
    underlay_stitch_groups, start = self.do_underlay(start)
  File "/inkstitch/lib/elements/fill_stitch.py", line 515, in do_underlay
    stitches=auto_fill(
  File "/inkstitch/lib/debug.py", line 133, in decorated
    result = func(*args, **kwargs)
  File "/inkstitch/lib/stitches/auto_fill.py", line 74, in auto_fill
    result = path_to_stitches(path, travel_graph, fill_stitch_graph, angle, row_spacing,
  File "/inkstitch/lib/debug.py", line 133, in decorated
    result = func(*args, **kwargs)
  File "/inkstitch/lib/stitches/auto_fill.py", line 631, in path_to_stitches
    travel_graph.remove_edges_from(fill_stitch_graph[edge[0]][edge[1]]['segment'].get('underpath_edges', []))
  File "[..]/python3.9/site-packages/networkx/classes/coreviews.py", line 82, in __getitem__
    return AtlasView(self._atlas[name])
KeyError: (108.22270637916098, 929.4031677194731)
