### ISSUE TITLE
ValueError: Sequences of multi-polygons are not valid arguments

### ISSUE THREAD

**Issue by Kahwoods** [inkstitch/inkstitch#1574]
Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex\base.py", line 141, in run
  File "lib\extensions\troubleshoot.py", line 32, in effect
  File "lib\elements\fill.py", line 182, in validation_errors
  File "lib\elements\fill.py", line 164, in shape
  File "shapely\geometry\multipolygon.py", line 62, in __init__
  File "shapely\geometry\multipolygon.py", line 177, in geos_multipolygon_from_polygons
ValueError: Sequences of multi-polygons are not valid arguments

**Comment by kaalleen** [comment]
Thank you for your error report. This is very helpful. Can you post your current version of Ink/Stitch?

**Comment by kaalleen** [comment]
Not enough information. Probably fixed. Please open a new issue if this is still showing up. In that case a svg file would be most helpful.
