### ISSUE TITLE
commands:  AttributeError: 'MultiPolygon' object has no attribute 'exterior'

### ISSUE THREAD

**Issue by britbrad96** [inkstitch/inkstitch#1578]
Traceback (most recent call last):
  File "inkstitch.py", line 67, in <module>
  File "inkex\base.py", line 147, in run
  File "lib\extensions\object_commands.py", line 38, in effect
  File "lib\commands.py", line 384, in add_commands
  File "lib\commands.py", line 337, in get_command_pos
AttributeError: 'MultiPolygon' object has no attribute 'exterior'

**Comment by kaalleen** [comment]
Thanks for your error report! Can you add your current Ink/Stitch version?

**Comment by kaalleen** [comment]
Duplicate of #1768
