### ISSUE TITLE
error during autofill

### ISSUE THREAD

**Issue by terridixon** [inkstitch/inkstitch#1585]
use1420: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.1.2 (windows)

Traceback (most recent call last):
  File "lib\elements\auto_fill.py", line 228, in to_stitch_groups
  File "lib\debug.py", line 133, in decorated
  File "lib\stitches\auto_fill.py", line 64, in auto_fill
  File "lib\debug.py", line 133, in decorated
  File "lib\stitches\auto_fill.py", line 145, in build_fill_stitch_graph
  File "lib\stitches\fill.py", line 144, in intersect_region_with_grating
  File "shapely\geometry\base.py", line 649, in intersection
  File "shapely\topology.py", line 70, in __call__
  File "shapely\topology.py", line 35, in _check_topology
shapely.errors.TopologicalError: The operation 'GEOSIntersection_r' could not be performed. Likely cause is invalidity of the geometry <shapely.geometry.multipolygon.MultiPolygon object at 0x0DE70EE0>

shapely.geos - ERROR - TopologyException: Input geom 1 is invalid: Self-intersection at or near point 363.70667016929309 954.07138775139538 at 363.70667016929309 954.07138775139538
shapely.geos - INFO - Self-intersection at or near point 363.70667016929309 954.07138775139538

**Comment by kaalleen** [comment]
Thank you for your error report. It'd be interesting to see the svg file in order to fix the error. Could you upload it here or send us a mail to send-us-files@inkstitch.org ?

**Comment by terridixon** [comment]
I redid everything and it went through. I have over wrote the file so I no
longer have it. I think it was something to do with my computer. It needs a
new hard drive I think.

**Comment by kaalleen** [comment]
Ok, thanks anyway for your feedback. The autofill file has been reworked for the next release. That's why I will close this issue now. Just open a new error report, if this is showing up again after the next release.
