### ISSUE TITLE
 Ink/Stitch experienced an unexpected error.

### ISSUE THREAD

**Issue by kelleyburns** [inkstitch/inkstitch#1587]
shapely.geos - ERROR - TopologyException: found non-noded intersection between LINESTRING (209.807 715.386, 209.696 711.885) and LINESTRING (209.049 711.779, 209.923 712.328) at 209.70562665356869 712.19137692523543

Ink/Stitch experienced an unexpected error.

If you'd like to help, please file an issue at https://github.com/inkstitch/inkstitch/issues and include the entire error description below:

Ink/Stitch Version: v2.1.2 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 67, in <module>
  File "inkex\base.py", line 147, in run
  File "lib\extensions\break_apart.py", line 54, in effect
  File "lib\extensions\break_apart.py", line 68, in break_apart_paths
  File "shapely\ops.py", line 152, in unary_union
  File "shapely\geometry\base.py", line 76, in geom_factory
ValueError: No Shapely geometry can be created from null value

**Comment by kaalleen** [comment]
Thank you for your error report. I believe this happened due to the shapely version we have been using.
Could you try if this error still occurs when you are running this version here: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kall-test ?

**Comment by kaalleen** [comment]
Closing - no further response and the issue should be solved.
