### ISSUE TITLE
Inkstitch break apart fill objects error

### ISSUE THREAD

**Issue by Tvbearart** [inkstitch/inkstitch#1598]
I am not able to use the break apart feature due to this non error. 

Ink/Stitch Version: v2.1.2 (windows)

Ink/Stitch Version: v2.1.2 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 67, in <module>
  File "inkex\base.py", line 147, in run
  File "lib\extensions\break_apart.py", line 54, in effect
  File "lib\extensions\break_apart.py", line 68, in break_apart_paths
  File "shapely\ops.py", line 152, in unary_union
  File "shapely\geometry\base.py", line 76, in geom_factory
ValueError: No Shapely geometry can be created from null value

**Comment by kaalleen** [comment]
Huh, not sure what happened. Could you mind trying this development version here https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kall-test and report back, if the error still pops up? If so, it would be great if we could have a look at your svg file. If you don't want to upload it here, you can also send it to send-us-files@inkstitch.org

**Comment by kaalleen** [comment]
This error was showing up due to the shapely version we were using in the release. It should be fixed in the next Ink/Stitch version.
