### ISSUE TITLE
Thread color NoneType object

### ISSUE THREAD

**Issue by hlutar** [inkstitch/inkstitch#1599]
Ink/Stitch Version: v2.1.2 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 67, in <module>
  File "inkex/base.py", line 147, in run
  File "lib/extensions/output.py", line 56, in effect
  File "lib/stitch_plan/stitch_plan.py", line 24, in stitch_groups_to_stitch_plan
  File "lib/stitch_plan/stitch_plan.py", line 79, in new_color_block
  File "lib/stitch_plan/color_block.py", line 16, in __init__
  File "lib/stitch_plan/color_block.py", line 51, in color
  File "lib/threads/color.py", line 33, in __init__
TypeError: 'NoneType' object is not iterable

**Comment by kaalleen** [comment]
Huh,  I thought this has been fixed a while ago, seems it is not...

Ink/Stitch has troubles to recognize the color of one or more of your objects. If you reapply the colors through the color palettes at the bottom or the fill and stroke dialog box, you should be fine.

**Comment by hlutar** [comment]
Okay! I’m going to try that! Thank you, I’ll let you know how it goes!! Thank you, thank you.

**Comment by kaalleen** [comment]
No response. It is probably fixed. Closing. Please open a new issue if you encounter this error again.
