### ISSUE TITLE
Having Trouble Opening a .SEW File

### ISSUE THREAD

**Issue by ghost** [inkstitch/inkstitch#1610]
I get this message,

Ink/Stitch Version: v2.1.2 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 67, in <module>
  File "lib\extensions\input.py", line 14, in run
  File "lib\stitch_plan\generate_stitch_plan.py", line 22, in generate_stitch_plan
  File "pyembroidery\PyEmbroidery.py", line 520, in read
  File "pyembroidery\PyEmbroidery.py", line 473, in read_embroidery
  File "pyembroidery\SewReader.py", line 10, in read
TypeError: unsupported operand type(s) for %=: 'NoneType' and 'int'

**Comment by kaalleen** [comment]
Hello and welcome! Ink/Stitch at the moment isn't capable to open .sew files. Here is a list of files Ink/Stitch can work with. Maybe you find an other suitable format: https://inkstitch.org/docs/file-formats/

**Comment by kaalleen** [comment]
Sorry, I just see... we should be able to read, just not write.
Would you mind to send us the file for inspection? We have a mail address in case you don't want to upload it here: send-us-files@inkstitch.org

**Comment by kaalleen** [comment]
Would you mind to test this version here and report back if it solves your issue?
https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-pyembroidery-update1435

**Comment by kaalleen** [comment]
No further response. Closing.

Plesse open a new issue with an attached file if this is also happening with newer Ink/Stitch versions.
