### ISSUE TITLE
Error in 'Break Apart Fill Objects ...'

### ISSUE THREAD

**Issue by tscherfel** [inkstitch/inkstitch#1617]
I get an Error while I want to break apart fill objects.
I want to say, the path for the fill objects is definitely not closed.
I'm working an a complex Object, delete some knots, break path, delete segments, put some together and so on and in this situation not all knots where connected correctly.
So I think that's why I get this error.
Maybe You can find something in the code.
(And sorry for my poor English)

Ink/Stitch Version: v2.1.2 (linux)

Traceback (most recent call last):
  File "inkstitch.py", line 67, in <module>
  File "inkex/base.py", line 147, in run
  File "lib/extensions/break_apart.py", line 54, in effect
  File "lib/extensions/break_apart.py", line 68, in break_apart_paths
  File "shapely/ops.py", line 152, in unary_union
  File "shapely/geometry/base.py", line 76, in geom_factory
ValueError: No Shapely geometry can be created from null value

**Comment by kaalleen** [comment]
I believe you are receiving this error due to the shapely version included in the latest official release for linux.
You can try this version here instead: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kall-test
Hope it works with that version?!?

**Comment by bitshifter52** [comment]
I'm having the same issue:

shapely.geos - ERROR - TopologyException: found non-noded intersection between LINESTRING (43.2954 167.713, 43.0631 167.845) and LINESTRING (58.8398 191.284, 43.1701 167.525) at 43.294196806314524 167.71338633790626

Ink/Stitch experienced an unexpected error.

If you'd like to help, please file an issue at https://github.com/inkstitch/inkstitch/issues and include the entire error description below:

Ink/Stitch Version: v2.1.2 (linux)


Traceback (most recent call last):
  File "inkstitch.py", line 67, in <module>
  File "inkex/base.py", line 147, in run
  File "lib/extensions/break_apart.py", line 54, in effect
  File "lib/extensions/break_apart.py", line 68, in break_apart_paths
  File "shapely/ops.py", line 152, in unary_union
  File "shapely/geometry/base.py", line 76, in geom_factory
ValueError: No Shapely geometry can be created from null value

**Comment by kaalleen** [comment]
Would you mind to test this version here if the error is still showing up?

https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kall-test

**Comment by kaalleen** [comment]
Most probably fixed. Closing. Please open a new issue if this error is still showing up.
