### ISSUE TITLE
Ink/Stitch experienced an unexpected error.

### ISSUE THREAD

**Issue by Anna-Just** [inkstitch/inkstitch#1627]
I tried to open an ordinary dst-file and got this error message and the file wasn't opened. That happened with different dst files, but for some it is working.

Ink/Stitch Version: v2.0.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "lib\extensions\input.py", line 21, in run
  File "pyembroidery\PyEmbroidery.py", line 520, in read
  File "pyembroidery\PyEmbroidery.py", line 473, in read_embroidery
  File "pyembroidery\DstReader.py", line 86, in read
  File "pyembroidery\DstReader.py", line 55, in dst_read_header
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 8: invalid continuation byte

**Comment by tyrosinase** [comment]
If there's an "ä" in the file or directory name, the workaround is to rename it. But upgrading to the current Ink/Stitch should fix the problem.

**Comment by Anna-Just** [comment]
Thank you! That's it!
After renaming the file I was able to open it. 
Actually I thought I already had the new version.

**Comment by tyrosinase** [comment]
I'm running 2.1.2 and even that might be a little behind. But there are a lot of bug-fixes between there and 2.0.0, you should definitely upgrade.

**Comment by Anna-Just** [comment]
Thanks again (especially for your quick replies). I have now made the update. The last available version is still 2.1.2. 
Also in this version I can't open files with umlauts, but as long as it works after renaming, everything is fine. :)

**Comment by kaalleen** [comment]
Tested recently by a windows users. This doesn't seem to be a problem anymore.
