### ISSUE TITLE
Fresh InkScape and InkStich error

### ISSUE THREAD

**Issue by agiberson** [inkstitch/inkstitch#1629]
Hi, I've just done a fresh install of InkScape (Inkscape 1.1.2 (b8e25be833, 2022-02-05)) and InkStitch (v2.1.2) using the Windows installer exe.  

When I try to do anything (ex params) I get a Error pop up that says:

Unhandled exception in script

Failed to execute script 'pyi_rth_multiprocessing" due to the unhandled exception: DLL load failed while importing _socket: The parameter is incorrect.

Traceback (most recent call last):
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_multiprocessing.py", line 12, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "multiprocessing\__init__.py", line 16, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "multiprocessing\context.py", line 6, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "multiprocessing\reduction.py", line 16, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "socket.py", line 49, in <module>
ImportError: DLL load failed while importing _socket: The parameter is incorrect.

**Comment by kaalleen** [comment]
Have a look over here:  #1195
