### ISSUE TITLE
Stitch plan: IndexError

### ISSUE THREAD

**Issue by Hannahrob29** [inkstitch/inkstitch#1632]
Ink/Stitch Version: v2.1.2 (osx)
Traceback (most recent call last):
  File "inkstitch.py", line 67, in <module>
  File "inkex/base.py", line 147, in run
  File "lib/extensions/output.py", line 56, in effect
  File "lib/stitch_plan/stitch_plan.py", line 24, in stitch_groups_to_stitch_plan
IndexError: list index out of range

**Comment by kaalleen** [comment]
Did you try to output a text or an image?

**Comment by kaalleen** [comment]
No response, closing. If this shows up again, please open a new issue.
