### ISSUE TITLE
Windows: ImportError: DLL load failed while importing _socket

### ISSUE THREAD

**Issue by Pascal35** [inkstitch/inkstitch#1633]
Hello, 
I just install on windows and I have the following error... impossible to use InkScape

Traceback (most recent call last):
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_multiprocessing.py", line 12, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "multiprocessing\__init__.py", line 16, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "multiprocessing\context.py", line 6, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "multiprocessing\reduction.py", line 16, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "socket.py", line 49, in <module>
ImportError: DLL load failed while importing _socket: Paramètre incorrect.

**Comment by kaalleen** [comment]
Thanks for the error report. Have a look over here #1195 this may have a solution.

**Comment by Pascal35** [comment]
Thanks, I will check windows update..
