### ISSUE TITLE
Ink Stitch Error

### ISSUE THREAD

**Issue by dkalbach** [inkstitch/inkstitch#1635]
AutoSatin Running Stitch 1 (autosatinrun1-3): error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.0.0 (osx)

Traceback (most recent call last):
  File "lib/stitches/auto_fill.py", line 63, in auto_fill
  File "lib/debug.py", line 133, in decorated
  File "lib/stitches/auto_fill.py", line 144, in build_fill_stitch_graph
  File "lib/stitches/fill.py", line 97, in intersect_region_with_grating
ValueError: not enough values to unpack (expected 4, got 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib/elements/auto_fill.py", line 223, in to_patches
  File "lib/debug.py", line 133, in decorated
  File "lib/stitches/auto_fill.py", line 66, in auto_fill
  File "lib/stitches/auto_fill.py", line 263, in fallback
  File "shapely/geometry/base.py", line 895, in __getitem__
IndexError: tuple index out of range

**Comment by tyrosinase** [comment]
I think that looks like #1269 again... at least in one case that's been caused by a satin object that also had a fill. If that's your situation, Ink/Stitch should be warning you instead of failing, but at least removing the extraneous fill will make it stop.

**Comment by dkalbach** [comment]
Thank you - absolutely fixed it.  I added the fill to prompt a thread color change.  I know where the change occurs so I can do it manually, was just trying to add the prompt.

**Comment by tyrosinase** [comment]
To change the satin (or running) color, you want to change the line color rather than the fill - right clicking the swatch will bring up a little menu, or holding shift as you left-click will apply the color to the line.

You can also try `Ink/Stitch > Commands > Attach Command To Object` and put on a Stop command, but your format/machine have to support that (for example Brother PES format does, I thiiiiink, but common Brother machines don't).
