### ISSUE TITLE
Letters to font error

### ISSUE THREAD

**Issue by tyannrae** [inkstitch/inkstitch#1636]
Ink/Stitch Version: v2.1.2 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 67, in <module>
  File "inkex\base.py", line 147, in run
  File "lib\extensions\letters_to_font.py", line 43, in effect
  File "lib\extensions\letters_to_font.py", line 73, in get_glyph_element
  File "lib\stitch_plan\generate_stitch_plan.py", line 26, in generate_stitch_plan
AttributeError: 'NoneType' object has no attribute 'get_as_colorblocks'

**Comment by tyrosinase** [comment]
That looks like maybe a variation on the bug where Ink/Stitch can't detect the thread color. The current workaround is to change the color and re-save, though that's kind of a nuisance on a whole alphabet.

**Comment by tyannrae** [comment]
Thanks!  I will give that a try.

**Comment by kaalleen** [comment]
Hm, I'm not sure if this is the same issue. Do you also get an error message, when you open the embroidery letter files with Inkscape directly? Which file format do they have?

**Comment by tyannrae** [comment]
I will have to try to recreate.  I have been struggling with a few issues.  I do have another I am currently having trouble with...

Traceback (most recent call last):
  File "lib\extensions\lettering.py", line 324, in apply
  File "lib\extensions\lettering.py", line 272, in update_lettering
  File "lib\lettering\font.py", line 183, in render_text
  File "lib\lettering\font.py", line 105, in _load_variants
  File "lib\lettering\font_variant.py", line 60, in __init__
  File "lib\lettering\font_variant.py", line 69, in _load_glyphs
  File "lib\lettering\font_variant.py", line 77, in _clean_group
  File "src\lxml\etree.pyx", line 2448, in lxml.etree._Attrib.__delitem__
  File "src\lxml\apihelpers.pxi", line 606, in lxml.etree._delAttribute
KeyError: '{http://www.inkscape.org/namespaces/inkscape}groupmode'

**Comment by kaalleen** [comment]
Huh, I am not really sure what is going on... ?!?
Would you mind to send one or more of your font files for inspection? 

send-us-files@inkstitch.org

**Comment by isherifwilson** [comment]
I think I've run into this problem as well!

> Include the error description and also (if possible) the svg file.
> 
> Ink/Stitch Version: v3.0.1 (osx)
> 
> 
> Traceback (most recent call last):
>   File "inkstitch.py", line 84, in <module>
>   File "inkex/base.py", line 250, in run
>   File "lib/extensions/letters_to_font.py", line 43, in effect
>   File "lib/extensions/letters_to_font.py", line 73, in get_glyph_element
>   File "lib/stitch_plan/generate_stitch_plan.py", line 26, in generate_stitch_plan
>  AttributeError: 'NoneType' object has no attribute 'get_as_colorblocks'

![A (closed)](https://github.com/inkstitch/inkstitch/assets/2531845/d1ab1d32-7cfb-43f7-94c0-ee89b06543f0)
![B (closed)](https://github.com/inkstitch/inkstitch/assets/2531845/7b9df7c4-0867-4d7f-b117-5685e0f44e80)

![A (open)](https://github.com/inkstitch/inkstitch/assets/2531845/355f4d4b-6bc3-4f70-82d7-ad1fb9603989)
![B (open)](https://github.com/inkstitch/inkstitch/assets/2531845/23830a92-8e4b-464a-8a5c-f59b589a9eab)
![C (open)](https://github.com/inkstitch/inkstitch/assets/2531845/cd04aa87-3281-4f00-b8c0-7f2ba92e9f16)
![D (open)](https://github.com/inkstitch/inkstitch/assets/2531845/ab776e63-5893-42c7-8b86-15198ae12526)
![E (open)](https://github.com/inkstitch/inkstitch/assets/2531845/26760e38-7776-41b2-8ba6-d1bb5f89e3cb)

**Comment by kaalleen** [comment]
Sorry, I somehow missed your post. Interesting, it never occurred to me that someone would want to use it on actual svg files. Which file format did you chose for the import?

**Comment by isherifwilson** [comment]
Hi! I don't remember exactly my import process, but here is a snippet — the letters A, B, and C — of a very simple hand-written style font that we created by writing onto a tablet and then turned into running stitches to be used in designs.

When I get a chance, I’ll try to recreate the process but thanks in advance for any insight!

￼
