### ISSUE TITLE
Polyline - Could not convert string to float

### ISSUE THREAD

**Issue by mlehman9** [inkstitch/inkstitch#1646]
Ink/Stitch Version: v2.1.2 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 67, in <module>
  File "inkex/base.py", line 147, in run
  File "lib/extensions/troubleshoot.py", line 32, in effect
  File "lib/elements/polyline.py", line 102, in validation_warnings
  File "lib/elements/polyline.py", line 55, in points
  File "lib/elements/polyline.py", line 55, in <listcomp>
  File "lib/elements/polyline.py", line 55, in <listcomp>
ValueError: could not convert string to float: ''

**Comment by kaalleen** [comment]
Huh, this wasn't supposed to happen. Thank you for reporting it. Definitely a bug we need to fix.
I could be wrong, but I think for now you could convert your Polyline into a path which then should be working correctly.
