### ISSUE TITLE
get_node_transform: AttributeError: 'NoneType' object has no attribute 'getparent'

### ISSUE THREAD

**Issue by laputaite** [inkstitch/inkstitch#1647]
Tried to Trim Stich through Auto Route Satin Columns and got this error:
Ink/Stitch Version: v2.1.2 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 67, in <module>
  File "inkex/base.py", line 147, in run
  File "lib/extensions/auto_satin.py", line 69, in effect
  File "lib/stitches/auto_satin.py", line 335, in auto_satin
  File "lib/stitches/auto_satin.py", line 740, in add_trims
  File "lib/commands.py", line 383, in add_commands
  File "lib/commands.py", line 285, in add_group
  File "lib/svg/path.py", line 67, in get_correction_transform
  File "lib/svg/path.py", line 44, in get_node_transform
AttributeError: 'NoneType' object has no attribute 'getparent'

**Comment by kaalleen** [comment]
That's definitely a bug in Ink/Stitch. Would you mind to send us the SVG file which is causing it?

**Comment by laputaite** [comment]
Not 100% sure it's the right one. I think I've deleted most of them already.

![LOGO_2x2cm ai 2022_05_04_16_45_50 0](https://user-images.githubusercontent.com/104904978/166812403-b9fd2d59-d523-409c-85c9-16c645ce3829.svg)

**Comment by kaalleen** [comment]
Thank you for the file, really, it is just not common, that we actually get a file to work with :)

I cannot reproduce the error with your file though. It could be due to the version of Ink/Stitch I am using (or it is not the correct file).

**Comment by kaalleen** [comment]
#2328 has a file
