### ISSUE TITLE
Issue With Satin Stitches (Duplicate of #1647?)

### ISSUE THREAD

**Issue by CALL-198** [inkstitch/inkstitch#1648]
Using Ink/Stitch 2.1.2 with Inkscape 1.1.2 (b8e25be833, 2022-02-05) and tried Auto-Route Satin Columns with Trim jump stitches:

Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\inkstitch.py", line 44, in <module>
  File "D:\a\inkstitch\inkstitch\inkscape\share\extensions\inkex.py", line 283, in affect
  File "D:\a\inkstitch\inkstitch\lib\extensions\auto_satin.py", line 54, in effect
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_satin.py", line 335, in auto_satin
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_satin.py", line 735, in add_trims
  File "D:\a\inkstitch\inkstitch\lib\commands.py", line 388, in add_commands
  File "D:\a\inkstitch\inkstitch\lib\commands.py", line 293, in add_group
  File "D:\a\inkstitch\inkstitch\lib\svg\path.py", line 62, in get_correction_transform
  File "D:\a\inkstitch\inkstitch\lib\svg\path.py", line 36, in get_node_transform
AttributeError: 'NoneType' object has no attribute 'getparent'

**Comment by kaalleen** [comment]
Yes, it is the same error. Do you by any chance still have the file which is causing the error?

**Comment by kaalleen** [comment]
Closing this (duplicate)
