### ISSUE TITLE
write_embroidery_file:  AttributeError: 'NoneType' object has no attribute 'pyembroidery_thread'

### ISSUE THREAD

**Issue by Spliter66** [inkstitch/inkstitch#1651]
Ink/Stitch Version: v2.1.2 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 67, in <module>
  File "inkex\base.py", line 147, in run
  File "lib\extensions\zip.py", line 67, in effect
  File "lib\output.py", line 61, in write_embroidery_file
AttributeError: 'NoneType' object has no attribute 'pyembroidery_thread'

**Comment by Spliter66** [comment]
Thansk for your Great work on this Software

**Comment by kaalleen** [comment]
Thanks :)
Could you send the file which was causing the error?

**Comment by kaalleen** [comment]
Closing in favor of #2825
