### ISSUE TITLE
Ink/Stitch Version: v2.1.2 (windows)

### ISSUE THREAD

**Issue by stevenchong83** [inkstitch/inkstitch#1654]
Traceback (most recent call last):
  File "inkstitch.py", line 67, in <module>
  File "inkex\base.py", line 147, in run
  File "lib\extensions\break_apart.py", line 54, in effect
  File "lib\extensions\break_apart.py", line 68, in break_apart_paths
  File "shapely\ops.py", line 152, in unary_union
  File "shapely\geometry\base.py", line 76, in geom_factory
ValueError: No Shapely geometry can be created from null value

**Comment by tyrosinase** [comment]
This looks like the same problem as #1598, which doesn't have a solution yet but has some things to try.

**Comment by kaalleen** [comment]
I think this one is actually a shapely issue, due to the version we were using in the release.

If you don't mind to test development version, try this one out: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kall-test

I suppose the error shouldn't pop up anymore.
