### ISSUE TITLE
Inkstitch Problem

### ISSUE THREAD

**Issue by K-Normal** [inkstitch/inkstitch#1663]
path1639_25: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.1.2 (windows)

Traceback (most recent call last):
  File "lib\elements\auto_fill.py", line 246, in to_stitch_groups
  File "lib\debug.py", line 133, in decorated
  File "lib\stitches\auto_fill.py", line 64, in auto_fill
  File "lib\debug.py", line 133, in decorated
  File "lib\stitches\auto_fill.py", line 145, in build_fill_stitch_graph
  File "lib\stitches\fill.py", line 149, in intersect_region_with_grating
  File "shapely\geometry\base.py", line 840, in coords
NotImplementedError: Multi-part geometries do not provide a coordinate sequence

**Comment by tyrosinase** [comment]
This looks like the same as #1564 - have a look at that one.

**Comment by kaalleen** [comment]
In version 2.2.0 the code for fill elements has been updated. Please try with that version and report in a new issue if this error is still showing up.
