### ISSUE TITLE
Error during autofill (contour/single spiral)

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#1688]
I've successfully broken the lastest(ish) test release! Made a random test shape and played around with the new fills, and got it to error out.

[drawing.svg.txt](https://github.com/inkstitch/inkstitch/files/8883874/drawing.svg.txt)

```path2004: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: test (linux)


Traceback (most recent call last):
  File "lib/elements/fill_stitch.py", line 489, in to_stitch_groups
  File "lib/elements/fill_stitch.py", line 567, in do_contour_fill
  File "lib/stitches/contour_fill.py", line 495, in single_spiral
  File "lib/stitches/contour_fill.py", line 507, in _spiral_fill
  File "lib/stitches/contour_fill.py", line 548, in _make_spiral
  File "lib/stitches/contour_fill.py", line 437, in _interpolate_linear_rings
  File "trimesh/exceptions.py", line 28, in __getattribute__
  File "trimesh/__init__.py", line 44, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "trimesh/path/__init__.py", line 9, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "trimesh/path/path.py", line 32, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "trimesh/path/repair.py", line 11, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "scipy/spatial/__init__.py", line 107, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "scipy/spatial/_procrustes.py", line 9, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "scipy/linalg/__init__.py", line 198, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "scipy/linalg/_misc.py", line 4, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "scipy/linalg/lapack.py", line 818, in <module>
ImportError: /home/silver/.config/inkscape/extensions/inkstitch/bin/scipy/linalg/_flapack.cpython-38-x86_64-linux-gnu.so: ELF load command address/offset not properly aligned```

**Comment by lexelby** [comment]
Well done, thank you!  Fortunately this one is easy to fix.

**Comment by tyrosinase** [comment]
Oh good.

Also this release is doing the stitch-length thing, though I expect that's because the fix is in a different castle right now. Mentioning it just in case though. Got some teeeeeeeeny-tiny stitches going around the toes on this critter (who fits in a 5x7/130x180 hoop, for scale).

![IMG_1910](https://user-images.githubusercontent.com/9473609/173250539-0b34cac5-a807-487a-8381-249ee881ca52.JPEG)

**Comment by tyrosinase** [comment]
Oh, okay, I can revert to the current version for now then.
