### ISSUE TITLE
AttributeError: 'LineString' object has no attribute 'geoms'

### ISSUE THREAD

**Issue by duckymomo360** [inkstitch/inkstitch#1724]
This keeps happening when exporting to pes file and when using simulator.

Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\output.py", line 56, in effect
  File "lib\extensions\base.py", line 200, in elements_to_stitch_groups
  File "lib\elements\element.py", line 329, in embroider
  File "lib\elements\element.py", line 387, in validate
  File "lib\elements\fill_stitch.py", line 321, in validation_errors
  File "lib\elements\fill_stitch.py", line 274, in shape
AttributeError: 'LineString' object has no attribute 'geoms'

![ai](https://user-images.githubusercontent.com/24615614/178154456-c299dbd9-575a-48b8-bdfc-aecff73ce116.svg)

**Comment by kaalleen** [comment]
Thank you for reporting this issue and sending a file for inspection. Definitely a bug that we will need to fix.
Remove path128 from your file to get your design working.

**Comment by kaalleen** [comment]
Closing in favor of #1742
