### ISSUE TITLE
Memory Error in auto-run

### ISSUE THREAD

**Issue by fantascey** [inkstitch/inkstitch#1753]
Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\auto_run.py", line 35, in effect
  File "lib\stitches\auto_run.py", line 119, in autorun
  File "lib\stitches\auto_run.py", line 156, in build_graph
  File "lib\stitches\auto_run.py", line 44, in __init__
  File "lib\stitches\auto_run.py", line 75, in _get_intersection_points
  File "shapely\geometry\base.py", line 689, in intersection
  File "shapely\geometry\base.py", line 84, in geom_factory
  File "shapely\geometry\base.py", line 241, in _set_geom
  File "shapely\geometry\base.py", line 199, in _empty
  File "shapely\geometry\base.py", line 250, in __setattr__
MemoryError

![key](https://user-images.githubusercontent.com/38048308/181528487-25d24bfb-92b3-4b7d-9df4-1cf2dc03c89c.svg)

**Comment by kaalleen** [comment]
Thank you for reporting this error message and showing your svg file. This is very helpful for us.

In order to help you with your specific issue... Could you describe what you were trying to achieve?
Do you want to convert this key back into an svg fill area?

**Comment by kaalleen** [comment]
No respond. Closing.
