### ISSUE TITLE
IndexError in stitch plan preview

### ISSUE THREAD

**Issue by ChiffonsElo** [inkstitch/inkstitch#1755]
Hi the team!

Here is the stacktrace I got when I try to open the stitch plan preview:

Ink/Stitch Version: v2.2.0 (windows)

```
Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\stitch_plan_preview.py", line 39, in effect
  File "lib\extensions\base.py", line 200, in elements_to_stitch_groups
  File "lib\elements\element.py", line 331, in embroider
  File "lib\elements\stroke.py", line 445, in to_stitch_groups
  File "lib\elements\stroke.py", line 435, in ripple_stitch
  File "lib\stitches\ripple_stitch.py", line 25, in ripple_stitch
  File "lib\stitches\ripple_stitch.py", line 41, in _do_ripple
IndexError: list index out of range
```
Of course there is a problem with the path1156 that contains some broken nodes and the "parameters" doesn't work either.

Regards
Elodie
![test plume](https://user-images.githubusercontent.com/110193298/181608408-d9b9a173-ee82-4de1-b099-dce08b79a659.svg)

**Comment by kaalleen** [comment]
Wow, thanks for that error report!
