### ISSUE TITLE
 Erreur pendant l'auto-remplissage

### ISSUE THREAD

**Issue by Lady-Pink** [inkstitch/inkstitch#1758]
CHAPEAU (path1095): erreur : Erreur pendant l'auto-remplissage. Cela veut dire que Ink/Stitch a un problème.

Si vous désirez nous aider à améliorer Ink/Stitch, veuillez SVP copier/coller ce message dans un nouveau rapport d'erreur (issue) ici: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.2.0 (osx)

Traceback (most recent call last):
  File "lib/elements/fill_stitch.py", line 566, in to_stitch_groups
  File "lib/elements/fill_stitch.py", line 677, in do_guided_fill
  File "lib/stitches/guided_fill.py", line 34, in guided_fill
  File "lib/stitches/guided_fill.py", line 240, in intersect_region_with_grating_guideline
  File "lib/stitches/guided_fill.py", line 196, in clean_offset_line
  File "lib/stitches/guided_fill.py", line 118, in repair_multiple_parallel_offset_curves
ValueError: max() arg is an empty sequence

CHAPEAU (path1095): erreur : Erreur pendant l'auto-remplissage. Cela veut dire que Ink/Stitch a un problème.

Si vous désirez nous aider à améliorer Ink/Stitch, veuillez SVP copier/coller ce message dans un nouveau rapport d'erreur (issue) ici: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.2.0 (osx)

Traceback (most recent call last):
  File "lib/elements/fill_stitch.py", line 566, in to_stitch_groups
  File "lib/elements/fill_stitch.py", line 677, in do_guided_fill
  File "lib/stitches/guided_fill.py", line 34, in guided_fill
  File "lib/stitches/guided_fill.py", line 240, in intersect_region_with_grating_guideline
  File "lib/stitches/guided_fill.py", line 196, in clean_offset_line
  File "lib/stitches/guided_fill.py", line 118, in repair_multiple_parallel_offset_curves
ValueError: max() arg is an empty sequence

**Comment by kaalleen** [comment]
Thank you for the info. Do you still have the svg which was causing the issue? It'd be nice for us to have a look at it in order to resolve the problem. You can either post it here or send it to send-us-files@inkstitch.org

**Comment by Lady-Pink** [comment]
Bonjour
Voici le .svg qui a cause le probléme
J’ai glissé ce fichier directement depuis le Finder sur l’icône Inkscape pour lancé le programme
Ensuite j’ai utilisé l’extension LaserCut Jigsaw pour faire un puzzle que je voudrais broder ou faire un jeu en broderie

Merci à tous et toutes pour votre travail
Cordialement
Francine LARIVIERE

**Comment by kaalleen** [comment]
Thanks, somehow the file is still missing.
I think it will not upload via mail?

**Comment by JoTiTu** [comment]
Are there any news on this bug? I have just encountered exactly the same one while exploring the new guided fill feature.

**Comment by kaalleen** [comment]
File has been send in issue #1758

**Comment by kaalleen** [comment]
Sorry it was issue #1811
