### ISSUE TITLE
AutoFill: AttributeError: 'LineString' 

### ISSUE THREAD

**Issue by stitchwitch786** [inkstitch/inkstitch#1763]
Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\stitch_plan_preview.py", line 39, in effect
  File "lib\extensions\base.py", line 200, in elements_to_stitch_groups
  File "lib\elements\element.py", line 329, in embroider
  File "lib\elements\element.py", line 387, in validate
  File "lib\elements\fill_stitch.py", line 321, in validation_errors
  File "lib\elements\fill_stitch.py", line 274, in shape
AttributeError: 'LineString' object has no attribute 'geoms'

**Comment by tyrosinase** [comment]
This bug should be fixed in a development version: #1742 has the details.

**Comment by kaalleen** [comment]
Closing in favor of #1742
