### ISSUE TITLE
Fill: ZeroDivisionError

### ISSUE THREAD

**Issue by mhogans** [inkstitch/inkstitch#1764]
path1358: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 556, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 590, in do_underlay
  File "lib\debug.py", line 133, in decorated
  File "lib\stitches\auto_fill.py", line 62, in auto_fill
  File "lib\stitches\fill.py", line 163, in intersect_region_with_grating
ZeroDivisionError: float division by zero

**Comment by tyrosinase** [comment]
This looks like the same as #1733, which is a known bug.

**Comment by kaalleen** [comment]
But we didn't receive a file which is causing the error. If you still have the svg file, it could help us in order to fix the issue.
You can either post it here or send it to send-us-files@inkstitch.org

**Comment by kaalleen** [comment]
Closing in favor of #1829
