### ISSUE TITLE
Fill: AttributeError: 'LineString'

### ISSUE THREAD

**Issue by elfelton** [inkstitch/inkstitch#1767]
Windows 10 x64
Inkscape 1.2.1

Ink/Stitch Version: v2.2.0 (windows)  

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\troubleshoot.py", line 29, in effect
  File "lib\elements\fill_stitch.py", line 321, in validation_errors
  File "lib\elements\fill_stitch.py", line 274, in shape
AttributeError: 'LineString' object has no attribute 'geoms'

**Comment by elfelton** [comment]
Here is the offending SVG file.

![FMS_Logo_text_few_paint_bristles](https://user-images.githubusercontent.com/8985461/182681374-432ea574-d854-49b8-a3d8-e49514b9dc4b.svg)

**Comment by tyrosinase** [comment]
There's a dev version, mentioned in #1742 - see if that fixes it for you.

**Comment by elfelton** [comment]
Hello @tyrosinase, I can verify that the [build kall-test ](https://github.com/inkstitch/inkstitch/commit/4f7cd2885f4d0e725b33c919ef655af0240948cb)resolves my issue.

Thank you
