### ISSUE TITLE
object commands: 'MultiPolygon' object has no attribute 'exterior'

### ISSUE THREAD

**Issue by PynkLadi** [inkstitch/inkstitch#1768]
Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v2.2.0 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 231, in run
  File "lib/extensions/object_commands.py", line 38, in effect
  File "lib/commands.py", line 397, in add_commands
  File "lib/commands.py", line 350, in get_command_pos
AttributeError: 'MultiPolygon' object has no attribute 'exterior'

**Comment by kaalleen** [comment]
Thank you for the error report!! Would you mind to send us an svg file which is causing the error?

**Comment by kaalleen** [comment]
Closing in favor of #2173

**Comment by iusliberratio** [comment]
Hello, I have same problem: 

"Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v3.0.1 (windows)


Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "lib\extensions\input.py", line 22, in run
  File "lib\stitch_plan\generate_stitch_plan.py", line 22, in generate_stitch_plan
  File "pyembroidery\EmbPattern.py", line 1560, in static_read
  File "pyembroidery\EmbPattern.py", line 1493, in read_embroidery
  File "pyembroidery\PesReader.py", line 67, in read
  File "pyembroidery\PecReader.py", line 26, in read_pec
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

It could be great to use this probram. Kind Regards

**Comment by iusliberratio** [comment]
Maybe its better to use it with linux than with Windows?
