### ISSUE TITLE
break apart: TopologyException

### ISSUE THREAD

**Issue by type8008** [inkstitch/inkstitch#1771]
Ink/Stitch Version: v2.1.2 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 67, in <module>
  File "inkex\base.py", line 147, in run
  File "lib\extensions\break_apart.py", line 54, in effect
  File "lib\extensions\break_apart.py", line 68, in break_apart_paths
  File "shapely\ops.py", line 152, in unary_union
  File "shapely\geometry\base.py", line 76, in geom_factory
ValueError: No Shapely geometry can be created from null value

**Comment by tyrosinase** [comment]
Looks like (per #1678) this is fixed in 2.2.0. Try installing the latest release and it should be much happier.
