### ISSUE TITLE
error when saving pes file for inkstitch extension in inskape

### ISSUE THREAD

**Issue by Jim-johjohn** [inkstitch/inkstitch#1772]
hello,
I received this error:
Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 562, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 611, in do_auto_fill
  File "lib\debug.py", line 133, in decorated
  File "lib\stitches\auto_fill.py", line 75, in auto_fill
  File "lib\debug.py", line 133, in decorated
  File "lib\stitches\auto_fill.py", line 630, in path_to_stitches
  File "lib\stitches\auto_fill.py", line 591, in travel
  File "networkx\algorithms\shortest_paths\generic.py", line 167, in shortest_path
  File "networkx\algorithms\shortest_paths\weighted.py", line 2377, in bidirectional_dijkstra
networkx.exception.NetworkXNoPath: No path between (247.9241033148674, 286.29921259842524) and (248.04737836600216, 285.4871353983622).

**Comment by tyrosinase** [comment]
That's a bug the devs have been chasing for awhile: #1562 and some other reports. Check that report for info on sending them a file, if you can.

**Comment by kaalleen** [comment]
Closing in favor #2056
