### ISSUE TITLE
Fill: ZeroDivisionError

### ISSUE THREAD

**Issue by KINGMONTU** [inkstitch/inkstitch#1779]
Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 556, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 590, in do_underlay
  File "lib\debug.py", line 133, in decorated
  File "lib\stitches\auto_fill.py", line 62, in auto_fill
  File "lib\stitches\fill.py", line 163, in intersect_region_with_grating
ZeroDivisionError: float division by zero

**Comment by tyrosinase** [comment]
This looks like the same bug as #1764, which as of that report hadn't been duplicated by the devs... there are instructions there on how to send them a file with the problem.

**Comment by kaalleen** [comment]
Closing in favor of #1829
