### ISSUE TITLE
Elements - ValueError: ZoneClose segments [...]

### ISSUE THREAD

**Issue by jupejuperocket** [inkstitch/inkstitch#1780]
[](url)nk/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\troubleshoot.py", line 29, in effect
  File "lib\elements\fill_stitch.py", line 321, in validation_errors
  File "lib\elements\fill_stitch.py", line 256, in shape
  File "lib\elements\fill_stitch.py", line 283, in _get_clipped_path
  File "lib\elements\fill_stitch.py", line 243, in original_shape
  File "lib\elements\fill_stitch.py", line 230, in paths
  File "lib\elements\element.py", line 267, in parse_path
  File "lib\elements\element.py", line 263, in path
  File "inkex\paths.py", line 1654, in to_superpath
  File "inkex\paths.py", line 1685, in __init__
  File "inkex\paths.py", line 1736, in append
  File "inkex\paths.py", line 485, in to_curve
ValueError: ZoneClose segments can not be changed into curves.

[SVG here](http://jupe.ca/koko.svg)

**Comment by imagerymartin** [comment]
Also had this issue:

Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 556, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 590, in do_underlay
  File "lib\debug.py", line 133, in decorated
  File "lib\stitches\auto_fill.py", line 62, in auto_fill
  File "lib\stitches\fill.py", line 163, in intersect_region_with_grating
ZeroDivisionError: float division by zero

**Comment by googlegaby** [comment]
Same

**Comment by tyrosinase** [comment]
The latter of the errors is in the process of being fixed, but it's actually triggered by a problem with your file (just, it should handle it better than that). Here's a note on it: https://github.com/inkstitch/inkstitch/issues/1787#issuecomment-1217346922

**Comment by kaalleen** [comment]
@jupejuperocket in order to get things running without that error message, delete the two polygon elements (polygon177-8 and polygon189-6). They have no points and are empty. Also read how to prepare a file so that it is better usable for embroidery. You won't have a nice stitch out with that one as is.
