### ISSUE TITLE
Having an issue converting my logo from SVG to DST

### ISSUE THREAD

**Issue by FavorMagnet** [inkstitch/inkstitch#1781]
Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 231, in run
  File "lib/extensions/output.py", line 56, in effect
  File "lib/extensions/base.py", line 200, in elements_to_stitch_groups
  File "lib/elements/element.py", line 329, in embroider
  File "lib/elements/element.py", line 387, in validate
  File "lib/elements/fill_stitch.py", line 321, in validation_errors
  File "lib/elements/fill_stitch.py", line 274, in shape
AttributeError: 'LineString' object has no attribute 'geoms'

**Comment by tyrosinase** [comment]
The dreaded stealth-geoms! There's a dev version mentioned in #1742 - see if that fixes it for you.

**Comment by kaalleen** [comment]
Closing in favor of #1742
