### ISSUE TITLE
Fill stitch: AttributeError: 'LineString'

### ISSUE THREAD

**Issue by nbsaporter** [inkstitch/inkstitch#1784]
Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 231, in run
  File "lib/extensions/output.py", line 56, in effect
  File "lib/extensions/base.py", line 200, in elements_to_stitch_groups
  File "lib/elements/element.py", line 329, in embroider
  File "lib/elements/element.py", line 387, in validate
  File "lib/elements/fill_stitch.py", line 321, in validation_errors
  File "lib/elements/fill_stitch.py", line 274, in shape
AttributeError: 'LineString' object has no attribute 'geoms'
![StayWild-removebg-preview](https://user-images.githubusercontent.com/82936528/184392615-ac6d0e8c-e6f3-414a-bd55-5668e02b4ad3.svg)

**Comment by tyrosinase** [comment]
Stealth-geoms strike again! There's a dev version mentioned in https://github.com/inkstitch/inkstitch/issues/1742 - see if that fixes it for you.

(However: you will probably instead want to centerline-trace that image and turn it into a satin-stitched object.)

**Comment by kaalleen** [comment]
Closing in favor of #1742
