### ISSUE TITLE
brand new to inkstitch, logo svg conversion to pes

### ISSUE THREAD

**Issue by gregographicdesign** [inkstitch/inkstitch#1785]
path149: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 556, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 590, in do_underlay
  File "lib\debug.py", line 133, in decorated
  File "lib\stitches\auto_fill.py", line 62, in auto_fill
  File "lib\stitches\fill.py", line 163, in intersect_region_with_grating
ZeroDivisionError: float division by zero

path149: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 556, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 590, in do_underlay
  File "lib\debug.py", line 133, in decorated
  File "lib\stitches\auto_fill.py", line 62, in auto_fill
  File "lib\stitches\fill.py", line 163, in intersect_region_with_grating
ZeroDivisionError: float division by zero

path111: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 564, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 632, in do_contour_fill
  File "lib\stitches\contour_fill.py", line 137, in offset_polygon
  File "lib\stitches\contour_fill.py", line 186, in _match_polygons_and_holes
  File "shapely\geometry\base.py", line 685, in difference
  File "shapely\topology.py", line 72, in __call__
  File "shapely\topology.py", line 37, in _check_topology
shapely.errors.TopologicalError: The operation 'GEOSDifference_r' could not be performed. Likely cause is invalidity of the geometry <shapely.geometry.multipolygon.MultiPolygon object at 0x15EB4100>

shapely.geos - ERROR - TopologyException: Input geom 1 is invalid: Self-intersection at 222.59572672782562 40.389590242834828
shapely.geos - INFO - Self-intersection at or near point 222.59572672782562 40.389590242834828

**Comment by kaalleen** [comment]
Thank you for your error report. It'd be interesting to have a look at the file which produced this error. If you still have it, you can either post it here - if not possible due to copyright issues, you can also upload it here:

https://lexneva.name/owncloud/index.php/s/NCcJbJqnKmL7nES

**Comment by kaalleen** [comment]
Closing in favor of #1829
