### ISSUE TITLE
Contour Fill: TopologicalError

### ISSUE THREAD

**Issue by VaughanWilsonCumbria** [inkstitch/inkstitch#1789]
path324: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 564, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 632, in do_contour_fill
  File "lib\stitches\contour_fill.py", line 137, in offset_polygon
  File "lib\stitches\contour_fill.py", line 186, in _match_polygons_and_holes
  File "shapely\geometry\base.py", line 685, in difference
  File "shapely\topology.py", line 72, in __call__
  File "shapely\topology.py", line 37, in _check_topology
shapely.errors.TopologicalError: The operation 'GEOSDifference_r' could not be performed. Likely cause is invalidity of the geometry <shapely.geometry.multipolygon.MultiPolygon object at 0x3854B7C0>

shapely.geos - ERROR - TopologyException: Input geom 1 is invalid: Self-intersection at 249.79480812040097 540.98074073449754
shapely.geos - INFO - Self-intersection at or near point 249.79480812040097 540.98074073449754

**Comment by kaalleen** [comment]
Closing in favor of #1916
