### ISSUE TITLE
Contour Fill: TopologicalError

### ISSUE THREAD

**Issue by kratochviljakub** [inkstitch/inkstitch#1795]
Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 564, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 632, in do_contour_fill
  File "lib\stitches\contour_fill.py", line 137, in offset_polygon
  File "lib\stitches\contour_fill.py", line 186, in _match_polygons_and_holes
  File "shapely\geometry\base.py", line 685, in difference
  File "shapely\topology.py", line 72, in __call__
  File "shapely\topology.py", line 37, in _check_topology
shapely.errors.TopologicalError: The operation 'GEOSDifference_r' could not be performed. Likely cause is invalidity of the geometry <shapely.geometry.multipolygon.MultiPolygon object at 0x141845E0>

shapely.geos - ERROR - TopologyException: Input geom 1 is invalid: Self-intersection at 51.166319153215028 16.225102542026189
shapely.geos - INFO - Self-intersection at or near point 51.166319153215028 16.225102542026189

**Comment by kaalleen** [comment]
Closing in favor of #1916
