### ISSUE TITLE
Fill: AttributeError: 'LineString'

### ISSUE THREAD

**Issue by jbish13** [inkstitch/inkstitch#1804]
I opened a SVG file and attempted to save as PES file and received the following error:

Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\output.py", line 56, in effect
  File "lib\extensions\base.py", line 200, in elements_to_stitch_groups
  File "lib\elements\element.py", line 329, in embroider
  File "lib\elements\element.py", line 387, in validate
  File "lib\elements\fill_stitch.py", line 321, in validation_errors
  File "lib\elements\fill_stitch.py", line 274, in shape
AttributeError: 'LineString' object has no attribute 'geoms'

File did not save
![Jb_REVISED_SVG_BW_0RIG_NO_MOTTO](https://user-images.githubusercontent.com/112222124/187008463-89685f37-c3fb-4b66-88bb-bd494aab1b9f.png)
.
File used is attached

**Comment by tyrosinase** [comment]
Simple? Oh no, that is a very, very complex file.

It could *be* simplified (the cross-hatched area could be done with a sparse fill/underlay, for example), and a lot of lines could be coverted to running stitches, but that kind of insight is not something the computers are generally up to just yet (at least, not in open-source algorithms).

**Comment by jbish13** [comment]
Thank you very much for your insight. This is new for me and was hoping to DIY it.

**Comment by tyrosinase** [comment]
Yep, unfortunately we all went through that disappointing phase of "I can't just send this to the machine?" They're like any other 3D printer in that regard. 😔

**Comment by kaalleen** [comment]
Closing in favor of #1742
