### ISSUE TITLE
contour_fill: TopologyException

### ISSUE THREAD

**Issue by type8008** [inkstitch/inkstitch#1807]
path3804: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 564, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 632, in do_contour_fill
  File "lib\stitches\contour_fill.py", line 137, in offset_polygon
  File "lib\stitches\contour_fill.py", line 186, in _match_polygons_and_holes
  File "shapely\geometry\base.py", line 685, in difference
  File "shapely\topology.py", line 72, in __call__
  File "shapely\topology.py", line 37, in _check_topology
shapely.errors.TopologicalError: The operation 'GEOSDifference_r' could not be performed. Likely cause is invalidity of the geometry <shapely.geometry.multipolygon.MultiPolygon object at 0x1C624B68>

shapely.geos - ERROR - TopologyException: Input geom 1 is invalid: Self-intersection at 282.84650407690964 283.35490685123227
shapely.geos - INFO - Self-intersection at or near point 282.84650407690964 283.35490685123227

**Comment by type8008** [comment]
![Honey Bees Plees](https://user-images.githubusercontent.com/107273159/187056143-f7d3a197-6ca4-4af5-8d77-78261131597f.svg)

**Comment by kaalleen** [comment]
Sorry, that you never got an answer on your issue report. Your shape isn't very suitable for contour fill. Still we should avoid to show a better message or avoid this error showing up. Other people posted similar issues.
So we are going to decide on one and close the other ones. Have a look at #1916 for more information.
