### ISSUE TITLE
auto_fill: NetworkXNoPath

### ISSUE THREAD

**Issue by murpphym** [inkstitch/inkstitch#1808]
I can't save a .pes file because of these errors. Can anyone help? 

Here is the message in entirety: 

"path6039: error: Error during autofill!  This means that there is a problem with Ink/Stitch. If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new 

Ink/Stitch Version: v2.2.0 (osx) 
Traceback (most recent call last): 
File "lib/elements/fill_stitch.py", line 562, in to_stitch_groups 
File "lib/elements/fill_stitch.py", line 611, in do_auto_fill 
File "lib/debug.py", line 133, in decorated 
File "lib/stitches/auto_fill.py", line 75, in auto_fill F
ile "lib/debug.py", line 133, in decorated 
File "lib/stitches/auto_fill.py", line 630, in path_to_stitches 
File "lib/stitches/auto_fill.py", line 591, in travel 
File "networkx/algorithms/shortest_paths/generic.py", line 167, in shortest_path 
File "networkx/algorithms/shortest_paths/weighted.py", line 2377, in bidirectional_dijkstra networkx.exception.NetworkXNoPath: No path between (474.3210984163284, 172.91338582677164) and (474.54216243299203, 172.03387505787202)."

**Comment by tyrosinase** [comment]
That's a bug the devs have been chasing for awhile: #1562 and some other reports. Check that report for info on sending them a file, if you can.

**Comment by kaalleen** [comment]
Closing in favor of #2056
