### ISSUE TITLE
Layer commands: AttributeError (no layer in the document)

### ISSUE THREAD

**Issue by JMak22** [inkstitch/inkstitch#1810]
Hi guys, Inkstitch wanted me to call you and let you know the following:

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\layer_commands.py", line 23, in effect
  File "lib\commands.py", line 404, in add_layer_commands
  File "lib\svg\path.py", line 67, in get_correction_transform
  File "lib\svg\path.py", line 44, in get_node_transform
AttributeError: 'NoneType' object has no attribute 'getparent

![eschersketch Rosette 3](https://user-images.githubusercontent.com/112358835/187242402-fed2dacb-594e-4df9-acfb-82746c470b83.svg)

I hope this helps,
Jmak

**Comment by kaalleen** [comment]
Thank you for taking the extra steps to inform us about this error message which we don't want anyone to see.

The problem with your file (when adding a layer command) is, that there is no layer in the document. You can open the objects and layers dialog and right click on the group. Then select "group to layer". Then you'll be able to add a layer command.

**Comment by kaalleen** [comment]
Fixed in the latest release
