### ISSUE TITLE
Fill: ZeroDivisionError

### ISSUE THREAD

**Issue by Kidabah** [inkstitch/inkstitch#1812]
Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 556, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 590, in do_underlay
  File "lib\debug.py", line 133, in decorated
  File "lib\stitches\auto_fill.py", line 62, in auto_fill
  File "lib\stitches\fill.py", line 163, in intersect_region_with_grating
ZeroDivisionError: float division by zero

Inkscape crashed and told me i had to close it and see the error. This is the error i recieved.

**Comment by kaalleen** [comment]
We have a development branch with this error fixed. If you want to try it out here is the link: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-thisandthat01

**Comment by kaalleen** [comment]
Closing in favor of #1829
