### ISSUE TITLE
contour_fill: TopologicalError

### ISSUE THREAD

**Issue by ajaxofall** [inkstitch/inkstitch#1820]
path407: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 564, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 632, in do_contour_fill
  File "lib\stitches\contour_fill.py", line 137, in offset_polygon
  File "lib\stitches\contour_fill.py", line 186, in _match_polygons_and_holes
  File "shapely\geometry\base.py", line 685, in difference
  File "shapely\topology.py", line 72, in __call__
  File "shapely\topology.py", line 37, in _check_topology
shapely.errors.TopologicalError: The operation 'GEOSDifference_r' could not be performed. Likely cause is invalidity of the geometry <shapely.geometry.multipolygon.MultiPolygon object at 0x13507E50>

path407: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 564, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 632, in do_contour_fill
  File "lib\stitches\contour_fill.py", line 137, in offset_polygon
  File "lib\stitches\contour_fill.py", line 186, in _match_polygons_and_holes
  File "shapely\geometry\base.py", line 685, in difference
  File "shapely\topology.py", line 72, in __call__
  File "shapely\topology.py", line 37, in _check_topology
shapely.errors.TopologicalError: The operation 'GEOSDifference_r' could not be performed. Likely cause is invalidity of the geometry <shapely.geometry.multipolygon.MultiPolygon object at 0x133EFAC0>

shapely.geos - ERROR - TopologyException: Input geom 1 is invalid: Self-intersection at 84.069130247962022 532.19510920098719
shapely.geos - INFO - Self-intersection at or near point 84.069130247962022 532.19510920098719
shapely.geos - ERROR - TopologyException: Input geom 1 is invalid: Self-intersection at 84.069130247962022 532.19510920098719
shapely.geos - INFO - Self-intersection at or near point 84.069130247962022 532.19510920098719

**Comment by tyrosinase** [comment]
This looks like the same as #1807 / #1795 / #1789 / #1785, but I'm not seeing any answers in those issues. Could be one of the devs will have a better answer, but also it looks like some of the issues are still looking for example files. You can upload the SVG here, or email it to send-us-files@inkstitch.org.

**Comment by kaalleen** [comment]
Closing this in favor of #1916
