### ISSUE TITLE
fill: AttributeError: 'LineString'

### ISSUE THREAD

**Issue by Uzuky77** [inkstitch/inkstitch#1824]
Hello, 
I need some help, i got this message from the software and i can't solve the problem..

Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\output.py", line 56, in effect
  File "lib\extensions\base.py", line 200, in elements_to_stitch_groups
  File "lib\elements\element.py", line 329, in embroider
  File "lib\elements\element.py", line 387, in validate
  File "lib\elements\fill_stitch.py", line 321, in validation_errors
  File "lib\elements\fill_stitch.py", line 274, in shape
AttributeError: 'LineString' object has no attribute 'geoms'

**Comment by tyrosinase** [comment]
That looks like the same as #1794, and the same situation as I explain in this comment: https://github.com/inkstitch/inkstitch/issues/1794#issuecomment-1221362680

**Comment by Uzuky77** [comment]
i'm trying to understand, but even if i go to check the dev version nothing seems to fix the problem ?

**Comment by tyrosinase** [comment]
If you followed all the steps in that comment (including confirming you're actually running the dev version), then the devs will probably want to look at your file. You can upload the SVG here, or email it to send-us-files@inkstitch.org.

**Comment by Uzuky77** [comment]
ok thank you i will send an email, and can i remove the dev version ?

**Comment by tyrosinase** [comment]
Entirely up to you... there's no real reason to (that I know of), it's just an early version of what will eventually be the next release.

**Comment by Uzuky77** [comment]
oh ok thank you mate

**Comment by kaalleen** [comment]
Closing in favor of #1742
