### ISSUE TITLE
Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

### ISSUE THREAD

**Issue by foreverrlanaellc** [inkstitch/inkstitch#1825]
Traceback (most recent call last):
  File "shapely\speedups\_speedups.pyx", line 252, in shapely.speedups._speedups.geos_linearring_from_py
AttributeError: 'list' object has no attribute '__array_interface__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\troubleshoot.py", line 29, in effect
  File "lib\elements\fill_stitch.py", line 321, in validation_errors
  File "lib\elements\fill_stitch.py", line 256, in shape
  File "lib\elements\fill_stitch.py", line 287, in _get_clipped_path
  File "lib\elements\fill_stitch.py", line 287, in <lambda>
  File "shapely\geometry\polygon.py", line 261, in __init__
  File "shapely\geometry\polygon.py", line 539, in geos_polygon_from_py
  File "shapely\speedups\_speedups.pyx", line 346, in shapely.speedups._speedups.geos_linearring_from_py
ValueError: A LinearRing must have at least 3 coordinate tuples

![Good Moms multicolor test](https://user-images.githubusercontent.com/113642308/190512454-e4b3b702-7660-4c45-b6ab-3d03b52a032c.svg)

**Comment by tyrosinase** [comment]
What version of Ink/Stitch are you using? That should be fixed since v1.29.1 at least, which is pretty old.
