### ISSUE TITLE
fill: AttributeError: 'LineString' object has no attribute 'geoms'

### ISSUE THREAD

**Issue by swervieverv** [inkstitch/inkstitch#1836]
Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\zip.py", line 47, in effect
  File "lib\extensions\base.py", line 200, in elements_to_stitch_groups
  File "lib\elements\element.py", line 329, in embroider
  File "lib\elements\element.py", line 387, in validate
  File "lib\elements\fill_stitch.py", line 321, in validation_errors
  File "lib\elements\fill_stitch.py", line 274, in shape
AttributeError: 'LineString' object has no attribute 'geoms'

![Eagles Football Design (7 inch)](https://user-images.githubusercontent.com/114618678/192879187-2f7ed0c7-058a-4a21-b44f-db3ef2b496d3.svg)

**Comment by tyrosinase** [comment]
That looks like the same as https://github.com/inkstitch/inkstitch/issues/1794, and the same situation as I explain in this comment: https://github.com/inkstitch/inkstitch/issues/1794#issuecomment-1221362680
