### ISSUE TITLE
Autofill error

### ISSUE THREAD

**Issue by Codi007** [inkstitch/inkstitch#1847]
Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 556, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 590, in do_underlay
  File "lib\debug.py", line 133, in decorated
  File "lib\stitches\auto_fill.py", line 62, in auto_fill
  File "lib\stitches\fill.py", line 163, in intersect_region_with_grating
ZeroDivisionError: float division by zero

**Comment by tyrosinase** [comment]
There is a dev release that will fix this error (https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-thisandthat01, pr #1727) but it's being triggered by a too-small or too-thin piece in your SVG - often a traced bitmap in need of cleanup. You can use `Extensions > Ink/Stitch > Troubleshoot > Cleanup Document` and that will generally find them for you.
