### ISSUE TITLE
ZoneClose segments can not be changed into curves.

### ISSUE THREAD

**Issue by amandachristian** [inkstitch/inkstitch#1877]
Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\troubleshoot.py", line 29, in effect
  File "lib\elements\fill_stitch.py", line 321, in validation_errors
  File "lib\elements\fill_stitch.py", line 256, in shape
  File "lib\elements\fill_stitch.py", line 283, in _get_clipped_path
  File "lib\elements\fill_stitch.py", line 243, in original_shape
  File "lib\elements\fill_stitch.py", line 230, in paths
  File "lib\elements\element.py", line 267, in parse_path
  File "lib\elements\element.py", line 263, in path
  File "inkex\paths.py", line 1654, in to_superpath
  File "inkex\paths.py", line 1685, in __init__
  File "inkex\paths.py", line 1736, in append
  File "inkex\paths.py", line 485, in to_curve
ValueError: ZoneClose segments can not be changed into curves.

![Feeders Artwork](https://user-images.githubusercontent.com/116663580/197819651-b8269f5e-cf0e-4c3c-993d-92cf71726ea2.svg)

**Comment by tyrosinase** [comment]
If I'm reading the notes on #1780 (the same error) correctly, there is a dev release that should fix this error (https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-thisandthat01, pr https://github.com/inkstitch/inkstitch/pull/1727)... though that might just refer to the intersect-with-grating bug also mentioned there.

If you don't want to install the dev release, or it doesn't fix it, you can try finding the ZoneClose object and convert it to something more generic (I usually do a `Path > Union` with just the single object selected) as a workaround.
