### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by tjbk23** [inkstitch/inkstitch#1881]
Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\troubleshoot.py", line 29, in effect
  File "lib\elements\fill_stitch.py", line 321, in validation_errors
  File "lib\elements\fill_stitch.py", line 274, in shape
AttributeError: 'LineString' object has no attribute 'geoms'
![Boon Quilt Label](https://user-images.githubusercontent.com/116860352/198497857-4c6327da-4efe-48d1-9784-a08d8d2fd19f.svg)

**Comment by tyrosinase** [comment]
There's a development version that fixes this: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kall-test

Closing in favor of #1742 (which also has more info on workarounds etc.)
