### ISSUE TITLE
'LineString' object has no attribute 'geoms'

### ISSUE THREAD

**Issue by jamestebby** [inkstitch/inkstitch#1884]
Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\troubleshoot.py", line 29, in effect
  File "lib\elements\fill_stitch.py", line 321, in validation_errors
  File "lib\elements\fill_stitch.py", line 274, in shape
AttributeError: 'LineString' object has no attribute 'geoms'

**Comment by tyrosinase** [comment]
There's a development version that fixes this: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kall-test

Closing in favor of https://github.com/inkstitch/inkstitch/issues/1742 (which also has more info on workarounds etc.)
