### ISSUE TITLE
Issue with troubleshooting

### ISSUE THREAD

**Issue by lord-aaron** [inkstitch/inkstitch#1885]
I get this error why trying to troubleshoot a few of the satin stitches
![D20 Swords 02 Embroidery-03](https://user-images.githubusercontent.com/51931921/198898982-22a4212e-84fa-4cfd-9669-f33afefd5cb9.svg)

Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\troubleshoot.py", line 29, in effect
  File "lib\elements\satin_column.py", line 455, in validation_errors
  File "lib\elements\satin_column.py", line 949, in to_stitch_groups
  File "lib\elements\satin_column.py", line 803, in do_zigzag_underlay
  File "lib\elements\satin_column.py", line 689, in plot_points_on_rails
  File "lib\elements\satin_column.py", line 424, in flattened_sections
  File "lib\elements\satin_column.py", line 424, in <listcomp>
IndexError: tuple index out of range

**Comment by tyrosinase** [comment]
That's the error you get when there's a satin stitch that has an extraneous fill. There's a dev release, #1727 , that will fix the error (it will stitch the fill, then the satin, as far as I know) but generally a satin isn't a good fill shape so you'll just want to clear the unwanted fill.

**Comment by lord-aaron** [comment]
Thanks for the advice and the information! That's something I can work with.
