### ISSUE TITLE
Mac updated again is this the problem?

### ISSUE THREAD

**Issue by arkansasotr** [inkstitch/inkstitch#1899]
Ink/Stitch Version: v2.2.0 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 231, in run
  File "lib/extensions/output.py", line 56, in effect
  File "lib/extensions/base.py", line 200, in elements_to_stitch_groups
  File "lib/elements/element.py", line 329, in embroider
  File "lib/elements/element.py", line 387, in validate
  File "lib/elements/fill_stitch.py", line 321, in validation_errors
![Uploading 2domnokirtten2

.svg…]()

  File "lib/elements/fill_stitch.py", line 274, in shape
AttributeError: 'LineString' object has no attribute 'geoms'

**Comment by arkansasotr** [comment]
Never mind.  It was operator error.  Once I found that the errors and corrected them; 
no other problem occurred.
