### ISSUE TITLE
Issue when creating custom lettering 

### ISSUE THREAD

**Issue by justandywu** [inkstitch/inkstitch#1909]
[https://github.com/inkstitch/inkstitch/issues/1880](url)

Sorry I tried to fix some more things, but I ended up breaking more things. :(

I'm trying to generate JSON and for some reason I'm getting this error:

Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please

copy the entire error message below
save your SVG file and
create a new issue at https://github.com/inkstitch/inkstitch/issues
Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
File "inkstitch.py", line 84, in
File "inkex\base.py", line 231, in run
File "lib\extensions\lettering_generate_json.py", line 84, in effect
PermissionError: [Errno 13] Permission denied: 'C:\Program Files\Inkscape\etc\custom fonts\obviouscompanyembroidery\font.json'

I also tried to remake the glyph file, but now it's having a different issue... but now I can't generate the JSON

I don't know if this is something that you do, but is there a way to get on a call to troubleshoot? Otherwise we can just interact vs this

**Comment by kaalleen** [comment]
That may be caused by the location you are trying to save to. Try to save your font and json file in your user directory - not in Program Files.

**Comment by justandywu** [comment]
Now I'm getting this issue :(

Traceback (most recent call last):
  File "lib\extensions\lettering.py", line 328, in apply
  File "lib\extensions\lettering.py", line 273, in update_lettering
  File "lib\lettering\font.py", line 208, in render_text
  File "lib\lettering\font.py", line 363, in _apply_auto_satin
  File "lib\stitches\auto_satin.py", line 333, in auto_satin
  File "lib\stitches\utils\autoroute.py", line 145, in get_starting_and_ending_nodes
  File "lib\stitches\utils\autoroute.py", line 160, in find_node
ValueError: min() arg is an empty sequence
Traceback (most recent call last):
  File "lib\extensions\lettering.py", line 328, in apply
  File "lib\extensions\lettering.py", line 273, in update_lettering
  File "lib\lettering\font.py", line 208, in render_text
  File "lib\lettering\font.py", line 363, in _apply_auto_satin
  File "lib\stitches\auto_satin.py", line 333, in auto_satin
  File "lib\stitches\utils\autoroute.py", line 145, in get_starting_and_ending_nodes
  File "lib\stitches\utils\autoroute.py", line 160, in find_node
ValueError: min() arg is an empty sequence
Traceback (most recent call last):
  File "lib\extensions\lettering.py", line 328, in apply
  File "lib\extensions\lettering.py", line 273, in update_lettering
  File "lib\lettering\font.py", line 208, in render_text
  File "lib\lettering\font.py", line 363, in _apply_auto_satin
  File "lib\stitches\auto_satin.py", line 333, in auto_satin
  File "lib\stitches\utils\autoroute.py", line 145, in get_starting_and_ending_nodes
  File "lib\stitches\utils\autoroute.py", line 160, in find_node
ValueError: min() arg is an empty sequence

**Comment by kaalleen** [comment]
Uncheck auto-routing when you create the json file.

**Comment by justandywu** [comment]
I think this works. Thanks so much for your help!

**Comment by kaalleen** [comment]
Thank you for your feedback. Glad it worked for you!!
