### ISSUE TITLE
Problem with auto filling (contour method)

### ISSUE THREAD

**Issue by juliastickt** [inkstitch/inkstitch#1916]
path3055: Fehler: Es ist ein Fehler bei der AutoFüllung aufgetreten! Das bedeutet, es gibt ein Problem mit Ink/Stitch.

Wenn du uns helfen willst Ink/Stitch zu verbessern, kopiere die gesamte Nachricht und erstelle einen neuen Fehlerbericht (Issue) auf: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.2.0 (linux)

Traceback (most recent call last):
  File "lib/elements/fill_stitch.py", line 564, in to_stitch_groups
  File "lib/elements/fill_stitch.py", line 632, in do_contour_fill
  File "lib/stitches/contour_fill.py", line 137, in offset_polygon
  File "lib/stitches/contour_fill.py", line 186, in _match_polygons_and_holes
  File "shapely/geometry/base.py", line 685, in difference
  File "shapely/topology.py", line 72, in __call__
  File "shapely/topology.py", line 37, in _check_topology
shapely.errors.TopologicalError: The operation 'GEOSDifference_r' could not be performed. Likely cause is invalidity of the geometry <shapely.geometry.multipolygon.MultiPolygon object at 0x7f644f190850>

path3055: Fehler: Es ist ein Fehler bei der AutoFüllung aufgetreten! Das bedeutet, es gibt ein Problem mit Ink/Stitch.

Wenn du uns helfen willst Ink/Stitch zu verbessern, kopiere die gesamte Nachricht und erstelle einen neuen Fehlerbericht (Issue) auf: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.2.0 (linux)

Traceback (most recent call last):
  File "lib/elements/fill_stitch.py", line 564, in to_stitch_groups
  File "lib/elements/fill_stitch.py", line 632, in do_contour_fill
  File "lib/stitches/contour_fill.py", line 137, in offset_polygon
  File "lib/stitches/contour_fill.py", line 186, in _match_polygons_and_holes
  File "shapely/geometry/base.py", line 685, in difference
  File "shapely/topology.py", line 72, in __call__
  File "shapely/topology.py", line 37, in _check_topology
shapely.errors.TopologicalError: The operation 'GEOSDifference_r' could not be performed. Likely cause is invalidity of the geometry <shapely.geometry.multipolygon.MultiPolygon object at 0x7f644e61a160>

path3055: Fehler: Es ist ein Fehler bei der AutoFüllung aufgetreten! Das bedeutet, es gibt ein Problem mit Ink/Stitch.

Wenn du uns helfen willst Ink/Stitch zu verbessern, kopiere die gesamte Nachricht und erstelle einen neuen Fehlerbericht (Issue) auf: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.2.0 (linux)

Traceback (most recent call last):
  File "lib/elements/fill_stitch.py", line 564, in to_stitch_groups
  File "lib/elements/fill_stitch.py", line 632, in do_contour_fill
  File "lib/stitches/contour_fill.py", line 137, in offset_polygon
  File "lib/stitches/contour_fill.py", line 186, in _match_polygons_and_holes
  File "shapely/geometry/base.py", line 685, in difference
  File "shapely/topology.py", line 72, in __call__
  File "shapely/topology.py", line 37, in _check_topology
shapely.errors.TopologicalError: The operation 'GEOSDifference_r' could not be performed. Likely cause is invalidity of the geometry <shapely.geometry.multipolygon.MultiPolygon object at 0x7f644e6a5100>

shapely.geos - ERROR - TopologyException: Input geom 1 is invalid: Self-intersection at 122.96820646645202 28.695520765012798
shapely.geos - INFO - Self-intersection at or near point 122.96820646645202 28.695520765012798
shapely.geos - ERROR - TopologyException: Input geom 1 is invalid: Self-intersection at 122.96820646645202 28.695520765012798
shapely.geos - INFO - Self-intersection at or near point 122.96820646645202 28.695520765012798
shapely.geos - ERROR - TopologyException: Input geom 1 is invalid: Self-intersection at 122.96820646645202 28.695520765012798
shapely.geos - INFO - Self-intersection at or near point 122.96820646645202 28.695520765012798

**Comment by kaalleen** [comment]
Thank you for the error report. Would you mind to also send the svg file which is causing the error?

If that's not possible due to license issues we have an other option to upload your svg here: https://lexneva.name/owncloud/index.php/s/NCcJbJqnKmL7nES

**Comment by juliastickt** [comment]
![Glocke](https://user-images.githubusercontent.com/118892708/203525155-b4a4ef8d-0724-4dc7-8331-6ce2552e3c25.svg)

**Comment by juliastickt** [comment]
Thank you so much for your advises!
I now made it with a satin stitch - a really great stitch and you are right it looks better than what it could be with contour fill.
Thank you so much!!!

**Comment by kaalleen** [comment]
You are welcome. Glad I could help.
