### ISSUE TITLE
Path 2197 error

### ISSUE THREAD

**Issue by camceg** [inkstitch/inkstitch#1943]
Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\lib\elements\auto_fill.py", line 225, in to_patches
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 55, in auto_fill
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 149, in build_fill_stitch_graph
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 173, in insert_node
ValueError: min() arg is an empty sequence

**Comment by tyrosinase** [comment]
There are a few things that can cause that bug to surface, usually when you're trying to convert a bitmap.

Not having actually traced the bitmap will do it. https://silverseams.com/tutorials/digitizing-with-ink-stitch/ will walk you through the steps you need to go through before you're ready to build a stitch file.

Having traced it and ended up with one or more tiny unstitchable scraps: run `Extensions > Ink/Stitch > Troubleshoot > Cleanup Document` and it should clear those up.

If it's neither of those, then `Extensions > Ink/Stitch > Troubleshoot > Troubleshoot Objects` is the next step. What (if anything) does that report?

**Comment by kaalleen** [comment]
@tyrosinase have you seen this error showing up in the current release?

**Comment by tyrosinase** [comment]
I've never seen it turn up at all personally, but... oh wait, that's auto_fill, not auto_satin. So moving the current release should fix the error message (though it still probably won't be ready to stitch, OP).
