### ISSUE TITLE
unexpected error when saving a pes file

### ISSUE THREAD

**Issue by lukeb88** [inkstitch/inkstitch#1951]
On Mac OSX Ventura 13.0 (Apple M1 Pro)
Inkscape 1.2.2 (b0a84865, 2022-12-01)
Ink/Stitch Version: v2.2.0 (osx)

Just installed both Inkscape and Ink/Stitch.

I've imported an .ai file (attached here in .svg), and the I tried to:
- open Ink/Stitch parameters: Ink/Stick does not answer, i had to force the exit 
- save the file in .pes format and received the following error: 

```
Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 231, in run
  File "lib/extensions/output.py", line 56, in effect
  File "lib/extensions/base.py", line 200, in elements_to_stitch_groups
  File "lib/elements/element.py", line 329, in embroider
  File "lib/elements/element.py", line 387, in validate
  File "lib/elements/fill_stitch.py", line 321, in validation_errors
  File "lib/elements/fill_stitch.py", line 274, in shape

AttributeError: 'LineString' object has no attribute 'geoms'
```

![indy](https://user-images.githubusercontent.com/9743132/206923897-70421dad-864b-4abd-8b14-36387e2d7dbb.svg)

**Comment by tyrosinase** [comment]
This looks like the same as https://github.com/inkstitch/inkstitch/issues/1794, and the comments on it and https://github.com/inkstitch/inkstitch/issues/1931 should point you in the right direction.
