### ISSUE TITLE
contour_fill: TopologicalError

### ISSUE THREAD

**Issue by RoxaneBrode** [inkstitch/inkstitch#1959]
Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 564, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 632, in do_contour_fill
  File "lib\stitches\contour_fill.py", line 137, in offset_polygon
  File "lib\stitches\contour_fill.py", line 186, in _match_polygons_and_holes
  File "shapely\geometry\base.py", line 685, in difference
  File "shapely\topology.py", line 72, in __call__
  File "shapely\topology.py", line 37, in _check_topology
shapely.errors.TopologicalError: The operation 'GEOSDifference_r' could not be performed. Likely cause is invalidity of the geometry <shapely.geometry.multipolygon.MultiPolygon object at 0x16946370>

shapely.geos - ERROR - TopologyException: Input geom 1 is invalid: Self-intersection at 242.91495139519239 391.07252201714346
shapely.geos - INFO - Self-intersection at or near point 242.91495139519239 391.07252201714346

**Comment by tyrosinase** [comment]
This is a known bug, from #1916 and other issues.

It may be that your shape isn't suited to contour fill. You may need to break it into simpler shapes, or choose a different fill. If you can share the SVG (or at least that shape), we may be able to give you some advice on it.

**Comment by RoxaneBrode** [comment]
Thanks a lot.
Here is the shape in svg. sorry for the poverty of my text, I don't speak English, it's a google translation.
![tete mort](https://user-images.githubusercontent.com/120611596/207881962-4274b2eb-ef8f-498d-bc9c-5b092653e90f.svg)

**Comment by tyrosinase** [comment]
You can post in French and I can Google-translate the other way. And some devs and contributors are native speakers of French if the machine fails.

Interestingly, it worked for me... maybe just differences in pathing choices between different library versions. It did fail to create the underlay though. But here it is in .pes form - you can load it back in as a manual stitch path as a workaround.

[207881962-4274b2eb-ef8f-498d-bc9c-5b092653e90f.pes.zip](https://github.com/inkstitch/inkstitch/files/10237749/207881962-4274b2eb-ef8f-498d-bc9c-5b092653e90f.pes.zip)

**Comment by RoxaneBrode** [comment]
Merci beaucoup. cela seras plus facile pour moi en français. Je vais tenter votre solution. merci beaucoup encore.

**Comment by kaalleen** [comment]
Closing in favor of #1916
