### ISSUE TITLE
Cutwork: UnboundLocalError

### ISSUE THREAD

**Issue by ArtisticEMB** [inkstitch/inkstitch#1960]
Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 231, in run
  File "lib/extensions/cutwork_segmentation.py", line 76, in effect
UnboundLocalError: local variable 'parent' referenced before assignment

**Comment by kaalleen** [comment]
Thank you for your error report. This has been fixed and will not show up in the next version anymore.
The problem is most probably that you are running the extension on a filled object, while it is expecting a stroke. Add a stroke color and you'll be fine.

Previous issue: #1936
