### ISSUE TITLE
Contour Fill: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#1962]
```
Ink/Stitch Version: v2.2.0 (linux)

Traceback (most recent call last):
  File "lib/elements/fill_stitch.py", line 564, in to_stitch_groups
  File "lib/elements/fill_stitch.py", line 636, in do_contour_fill
  File "lib/stitches/contour_fill.py", line 397, in inner_to_outer
  File "lib/stitches/contour_fill.py", line 364, in _find_path_inner_to_outer
  File "lib/stitches/contour_fill.py", line 364, in _find_path_inner_to_outer
  File "lib/stitches/contour_fill.py", line 364, in _find_path_inner_to_outer
  [Previous line repeated 4 more times]
  File "lib/stitches/contour_fill.py", line 331, in _find_path_inner_to_outer
  File "lib/stitches/contour_fill.py", line 282, in _create_nearest_points_list
TypeError: 'NoneType' object is not subscriptable
```

![BadContour](https://user-images.githubusercontent.com/9473609/208185530-f22fb079-ba87-47af-b2e2-631c07620889.svg)

I found a magic circle that Contour Fill hates. This error has appeared in another issue but the user closed it (maybe after finding a workaround - changing the size or proportions just slightly will do it).

**Comment by kaalleen** [comment]
Thank you for the file :)
#1966 Should solve the issue.
