### ISSUE TITLE
contour_fill: TopologicalError

### ISSUE THREAD

**Issue by GemGemCity** [inkstitch/inkstitch#1963]
path44964: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.2.0 (osx)

Traceback (most recent call last):
  File "lib/elements/fill_stitch.py", line 564, in to_stitch_groups
  File "lib/elements/fill_stitch.py", line 632, in do_contour_fill
  File "lib/stitches/contour_fill.py", line 137, in offset_polygon
  File "lib/stitches/contour_fill.py", line 186, in _match_polygons_and_holes
  File "shapely/geometry/base.py", line 685, in difference
  File "shapely/topology.py", line 72, in __call__
  File "shapely/topology.py", line 37, in _check_topology
shapely.errors.TopologicalError: The operation 'GEOSDifference_r' could not be performed. Likely cause is invalidity of the geometry <shapely.geometry.multipolygon.MultiPolygon object at 0x1496c8ac0>

path44964: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.2.0 (osx)

Traceback (most recent call last):
  File "lib/elements/fill_stitch.py", line 564, in to_stitch_groups
  File "lib/elements/fill_stitch.py", line 632, in do_contour_fill
  File "lib/stitches/contour_fill.py", line 137, in offset_polygon
  File "lib/stitches/contour_fill.py", line 186, in _match_polygons_and_holes
  File "shapely/geometry/base.py", line 685, in difference
  File "shapely/topology.py", line 72, in __call__
  File "shapely/topology.py", line 37, in _check_topology
shapely.errors.TopologicalError: The operation 'GEOSDifference_r' could not be performed. Likely cause is invalidity of the geometry <shapely.geometry.multipolygon.MultiPolygon object at 0x14958fdc0>

shapely.geos - ERROR - TopologyException: Input geom 1 is invalid: Self-intersection at 207.52192125823137 358.26194315701076
shapely.geos - INFO - Self-intersection at or near point 207.52192125823137 358.26194315701076
shapely.geos - ERROR - TopologyException: Input geom 1 is invalid: Self-intersection at 207.52192125823137 358.26194315701076
shapely.geos - INFO - Self-intersection at or near point 207.52192125823137 358.26194315701076

**Comment by tyrosinase** [comment]
This is a known bug, from https://github.com/inkstitch/inkstitch/issues/1916 and other issues.

It may be that your shape isn't suited to contour fill. You may need to break it into simpler shapes, or choose a different fill. If you can share the SVG (or at least that shape), we may be able to give you some advice on it.

**Comment by kaalleen** [comment]
Closing in favor of #1916
