### ISSUE TITLE
Inkstitch can simulate but not export PES file

### ISSUE THREAD

**Issue by MWGCMJAY** [inkstitch/inkstitch#1974]
Param and simulation renders work just fine but when I go to export as PES I get something like this every time. Attached is the current version of the SVG. Thanks in advance!

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\output.py", line 56, in effect
  File "lib\extensions\base.py", line 200, in elements_to_stitch_groups
  File "lib\elements\element.py", line 329, in embroider
  File "lib\elements\element.py", line 387, in validate
  File "lib\elements\fill_stitch.py", line 321, in validation_errors
  File "lib\elements\fill_stitch.py", line 274, in shape
AttributeError: 'Point' object has no attribute 'geoms'

![Jack Daniels FIXED](https://user-images.githubusercontent.com/121206756/209035066-05c89430-c64c-433a-8195-7c3a3c303ecd.svg)

**Comment by tyrosinase** [comment]
If it's the same as #1816, there is a circle with no radius somewhere in your SVG. You can either find and delete it, or there's a dev release that will fix it. Or I think if you can wait, that dev release is about to go live.

**Comment by MWGCMJAY** [comment]
ok! I will look into both of these options, thanks!

**Comment by MWGCMJAY** [comment]
> If it's the same as #1816, there is a circle with no radius somewhere in your SVG. You can either find and delete it, or there's a dev release that will fix it. Or I think if you can wait, that dev release is about to go live.

So I went into illustrator and simplified the svg as much as possible, removing all extra shapes. its renders just fine in the params window but now it gives me this error on the realistic preview:

[2022-12-21 21:53:49,763] ERROR in app: Exception on /stitch_plan [GET]
Traceback (most recent call last):
  File "flask\app.py", line 2077, in wsgi_app
  File "flask\app.py", line 1525, in full_dispatch_request
  File "flask\app.py", line 1523, in full_dispatch_request
  File "flask\app.py", line 1509, in dispatch_request
  File "lib\api\stitch_plan.py", line 22, in get_stitch_plan
  File "lib\extensions\base.py", line 200, in elements_to_stitch_groups
  File "lib\elements\element.py", line 329, in embroider
  File "lib\elements\element.py", line 387, in validate
  File "lib\elements\fill_stitch.py", line 321, in validation_errors
  File "lib\elements\fill_stitch.py", line 256, in shape
  File "lib\elements\fill_stitch.py", line 283, in _get_clipped_path
  File "lib\elements\fill_stitch.py", line 243, in original_shape
  File "lib\elements\fill_stitch.py", line 230, in paths
  File "lib\elements\element.py", line 267, in parse_path
  File "lib\elements\element.py", line 263, in path
  File "inkex\paths.py", line 1654, in to_superpath
  File "inkex\paths.py", line 1685, in __init__
  File "inkex\paths.py", line 1736, in append
  File "inkex\paths.py", line 485, in to_curve
ValueError: ZoneClose segments can not be changed into curves.

I feel like I somehow messed it up even worse :/

**Comment by tyrosinase** [comment]
Well you did achieve a slightly longer error trace. 🏆

If I'm reading the notes on https://github.com/inkstitch/inkstitch/issues/1780 (the same error) correctly, that dev release should fix this error (https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-thisandthat01, pr https://github.com/inkstitch/inkstitch/pull/1727)... though that might just refer to the intersect-with-grating bug also mentioned there.

If you don't want to install the dev release, or it doesn't fix it, you can try finding the ZoneClose object and convert it to something more generic (I usually do a Path > Union with just the single object selected) as a workaround.

In fact, I just downloaded the original image and yeah, there's a bunch of oddball tracing artifacts. What I'd do on a simple graphic like that is do a Select All, then shift-click to deselect all the big shapes. Then just hit delete and all the little scraps will go away. Normally `Troubleshoot > Cleanup Document` will get rid of all the scraps for you, but the current version runs into the same geom errors sometimes, so with a big blocky design it's not hard to just deselect things you want to keep.

I'd delete the light blocks inside the label too, and then dupe the label, Break Apart, delete the main piece and re-color all the remaining interior pieces.

Also, create a layer and move everything out of root - I think the current release has some oddities that come up with no-layer designs, so play it safe. (Or don't, if you wanna go for the error-trace hat trick. 😁)

**Comment by MWGCMJAY** [comment]
Looking into the dev release, wish me luck!

**Comment by MWGCMJAY** [comment]
I think it worked!!! will throw it on the brother here in a sec to make sure but params, realistic render, and saving all worked fine! Thank you so much @tyrosinase you have been extremely helpful tonight. Also shoutout to @kaalleen for the dev work!
