### ISSUE TITLE
'Point' object has no attribute 'geoms'

### ISSUE THREAD

**Issue by kunathea** [inkstitch/inkstitch#1977]
Ink/Stitch Version: v2.2.0 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 231, in run
  File "lib/extensions/cleanup.py", line 41, in effect
  File "lib/elements/fill_stitch.py", line 274, in shape
AttributeError: 'Point' object has no attribute 'geoms'

**Comment by tyrosinase** [comment]
This looks to be the same as #1816, meaning there's a zero-radius circle somewhere in your file. The notes on that issue should get you pointed in the right direction.
