### ISSUE TITLE
path4651: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

### ISSUE THREAD

**Issue by Ebyx** [inkstitch/inkstitch#1985]
Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 556, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 590, in do_underlay
  File "lib\debug.py", line 133, in decorated
  File "lib\stitches\auto_fill.py", line 62, in auto_fill
  File "lib\stitches\fill.py", line 163, in intersect_region_with_grating
ZeroDivisionError: float division by zero

**Comment by chrisyelf** [comment]
Does this version work?
https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kall-test

**Comment by Ebyx** [comment]
> Does this version work? https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kall-test

Yes, it seems to be working, this version. Thank you very much!
