### ISSUE TITLE
Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

### ISSUE THREAD

**Issue by sddpromos** [inkstitch/inkstitch#1994]
Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\auto_run.py", line 35, in effect
  File "lib\stitches\auto_run.py", line 128, in autorun
  File "lib\stitches\auto_run.py", line 202, in path_to_elements
  File "networkx\classes\coreviews.py", line 54, in __getitem__
KeyError: 'POINT (288.15862259488 178.97138465952)'

**Comment by kaalleen** [comment]
Thank you for your bug report. Do you still have the svg which is causing the error? It would be helpful for us to be able to solve the issue.

**Comment by kaalleen** [comment]
See #2335
