### ISSUE TITLE
Issue with contour fill

### ISSUE THREAD

**Issue by dljoyner2020** [inkstitch/inkstitch#2002]
Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 564, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 632, in do_contour_fill
  File "lib\stitches\contour_fill.py", line 137, in offset_polygon
  File "lib\stitches\contour_fill.py", line 186, in _match_polygons_and_holes
  File "shapely\geometry\base.py", line 685, in difference
  File "shapely\topology.py", line 72, in __call__
  File "shapely\topology.py", line 37, in _check_topology
shapely.errors.TopologicalError: The operation 'GEOSDifference_r' could not be performed. Likely cause is invalidity of the geometry <shapely.geometry.multipolygon.MultiPolygon object at 0x200AA658>

path10367: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 564, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 632, in do_contour_fill
  File "lib\stitches\contour_fill.py", line 137, in offset_polygon
  File "lib\stitches\contour_fill.py", line 186, in _match_polygons_and_holes
  File "shapely\geometry\base.py", line 685, in difference
  File "shapely\topology.py", line 72, in __call__
  File "shapely\topology.py", line 37, in _check_topology
shapely.errors.TopologicalError: The operation 'GEOSDifference_r' could not be performed. Likely cause is invalidity of the geometry <shapely.geometry.multipolygon.MultiPolygon object at 0x233B9088>

shapely.geos - ERROR - TopologyException: Input geom 1 is invalid: Self-intersection at 222.7004271809989 110.61886834177224
shapely.geos - INFO - Self-intersection at or near point 222.7004271809989 110.61886834177224
shapely.geos - ERROR - TopologyException: Input geom 1 is invalid: Self-intersection at 222.7004271809989 110.61886834177224
shapely.geos - INFO - Self-intersection at or near point 222.7004271809989 110.61886834177224

**Comment by ptibor76** [comment]
same here.
a simple SVG is attached:
![inkstitch_error_contour_fill](https://user-images.githubusercontent.com/21263746/211149018-6068e7e3-3d99-4868-a011-c9e1cd583434.svg)

**Comment by kaalleen** [comment]
Most probably this has been fixed in #1966 and will work in the next release of Ink/Stitch. Thank you for reporting the error.
