### ISSUE TITLE
osx: shapely - ValueError: A LinearRing must have at least 3 coordinate tuples

### ISSUE THREAD

**Issue by kaylairis** [inkstitch/inkstitch#2007]
Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v2.2.0 (osx)

Traceback (most recent call last):
  File "shapely/speedups/_speedups.pyx", line 252, in shapely.speedups._speedups.geos_linearring_from_py
AttributeError: 'list' object has no attribute '__array_interface__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 231, in run
  File "lib/extensions/troubleshoot.py", line 29, in effect
  File "lib/elements/fill_stitch.py", line 321, in validation_errors
  File "lib/elements/fill_stitch.py", line 256, in shape
  File "lib/elements/fill_stitch.py", line 287, in _get_clipped_path
  File "lib/elements/fill_stitch.py", line 287, in <lambda>
  File "shapely/geometry/polygon.py", line 261, in __init__
  File "shapely/geometry/polygon.py", line 539, in geos_polygon_from_py
  File "shapely/speedups/_speedups.pyx", line 346, in shapely.speedups._speedups.geos_linearring_from_py
ValueError: A LinearRing must have at least 3 coordinate tuples

**Comment by kaalleen** [comment]
Would you mind to send your svg file and tell us your macOS version?

**Comment by kaalleen** [comment]
This usually is dependent on the shapely version. This is dependent on the installed macOS version. I'll close this issue, because this may have been fixed simply through an shapely update for macOS.
