### ISSUE TITLE
Cannot save svg as pes on Ventura

### ISSUE THREAD

**Issue by angry-garden-salad** [inkstitch/inkstitch#2014]
MacOS Ventura 13.1
Inkscape 1.2.2 (b0a8486, 2022-12-01)
Ink/Stitch Version: v2.2.0 (osx)

After I have my SVG setup the way I want and I've confirmed in the InkStitch Simulator it looks they way I want, I try to save it as a PES and I get the following error:

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 231, in run
  File "lib/extensions/output.py", line 56, in effect
  File "lib/extensions/base.py", line 200, in elements_to_stitch_groups
  File "lib/elements/element.py", line 331, in embroider
  File "lib/elements/clone.py", line 72, in to_stitch_groups
  File "lib/elements/clone.py", line 137, in get_clone_source
IndexError: list index out of range
![lulu](https://user-images.githubusercontent.com/122660708/212453516-9d17df20-52df-4a1a-a923-40be96e3890e.svg)

**Comment by angry-garden-salad** [comment]
My SVG image was bad.
