### ISSUE TITLE
satin_column: IndexError: tuple index out of range

### ISSUE THREAD

**Issue by glgbarajas** [inkstitch/inkstitch#2046]
This happened while trying a semi-complicated set of interlinked satin-stitch figures

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\troubleshoot.py", line 29, in effect
  File "lib\elements\satin_column.py", line 455, in validation_errors
  File "lib\elements\satin_column.py", line 954, in to_stitch_groups
  File "lib\elements\satin_column.py", line 839, in do_satin
  File "lib\elements\satin_column.py", line 689, in plot_points_on_rails
  File "lib\elements\satin_column.py", line 424, in flattened_sections
  File "lib\elements\satin_column.py", line 424, in <listcomp>
IndexError: tuple index out of range

**Comment by kaalleen** [comment]
Thank you for your error report. Would you mind to send the svg file which is causing the error?

**Comment by kaalleen** [comment]
This usually happens in 3.0.1 when a running stitch was selected along with a satin column when params was used and applied as satin column. This will be fixed in the next release.
