### ISSUE TITLE
Manual Setup on MacOS: ValueError and module not found

### ISSUE THREAD

**Issue by bastanja** [inkstitch/inkstitch#2054]
Hello,

I followed the instructions for [manual setup of Ink/Stitch](https://inkstitch.org/developers/inkstitch/manual-setup), including the troubleshoot step to set the python version for inkscape in order to find shapely.

Operating System: MacOS
Inkscape installation folder: ~/Applications/Inkscape.app or /Applications/Inkscape.app (home folder and system applications path, I tried both)
Inkscape Version: Inkscape 1.2.1 (9c6d41e4, 2022-07-14)
Ink/Stitch Version: main from Sun Jan 29, revision a2c6d5fb
Python Version: 3.8.16

When I run Extensions -> Ink/Stitch -> Params I get the following error message:

```
Traceback (most recent call last):
  File "/Users/tanja/Developer/inkstitch/inkstitch.py", line 22, in <module>
    sys.path.remove(extensions_path)
ValueError: list.remove(x): x not in list
```

So I assume the removal and adding of the extensions_path (https://github.com/inkstitch/inkstitch/blob/a2c6d5fbcbbfaffb0604705c5530310649a8db82/inkstitch.py#L22) did not work.

When I try to get rid of the ValueError by adding a try and except, inkstitch.py continues, but I get another error:

```
Traceback (most recent call last):
  File "inkstitch.py", line 34, in <module>
    from inkex import errormsg
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/__init__.py", line 11, in <module>
    from .extensions import *
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/extensions.py", line 34, in <module>
    from .elements import (
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/elements/__init__.py", line 10, in <module>
    from ._base import ShapeElement, BaseElement
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/elements/_base.py", line 38, in <module>
    from ..styles import Style, Classes
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/styles.py", line 33, in <module>
    from .css import ConditionalRule
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/css.py", line 27, in <module>
    import cssselect
ModuleNotFoundError: No module named 'cssselect'
```

Maybe this is caused by the inkex version bundled with inkscape, which is not new enough, and the fact that removing it from sys.path did not work?

Any hints how to analyze this furher?

Is there a way to attach a debugger to the python script when it is run from inside inkscape?

**Comment by bastanja** [comment]
I managed to continue a bit further. After installing cssselect, trimesh and scipy I got to the following error message:

```
/Users/tanja/Developer/inkstitch/venv/lib/python3.8/site-packages/networkx/classes/graph.py:23: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  from collections import Mapping
/Users/tanja/Developer/inkstitch/venv/lib/python3.8/site-packages/networkx/classes/reportviews.py:95: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  from collections import Mapping, Set, Iterable
Traceback (most recent call last):
  File "inkstitch.py", line 38, in <module>
    from lib import extensions
  File "/Users/tanja/Developer/inkstitch/lib/extensions/__init__.py", line 6, in <module>
    from lib.extensions.troubleshoot import Troubleshoot
  File "/Users/tanja/Developer/inkstitch/lib/extensions/troubleshoot.py", line 10, in <module>
    from .base import InkstitchExtension
  File "/Users/tanja/Developer/inkstitch/lib/extensions/base.py", line 18, in <module>
    from ..elements import EmbroideryElement, nodes_to_elements
  File "/Users/tanja/Developer/inkstitch/lib/elements/__init__.py", line 6, in <module>
    from .clone import Clone
  File "/Users/tanja/Developer/inkstitch/lib/elements/clone.py", line 16, in <module>
    from .element import EmbroideryElement, param
  File "/Users/tanja/Developer/inkstitch/lib/elements/element.py", line 15, in <module>
    from ..patterns import apply_patterns
  File "/Users/tanja/Developer/inkstitch/lib/patterns.py", line 9, in <module>
    from .stitch_plan import Stitch
  File "/Users/tanja/Developer/inkstitch/lib/stitch_plan/__init__.py", line 6, in <module>
    from .color_block import ColorBlock
  File "/Users/tanja/Developer/inkstitch/lib/stitch_plan/color_block.py", line 7, in <module>
    from ..threads import ThreadColor
  File "/Users/tanja/Developer/inkstitch/lib/threads/__init__.py", line 6, in <module>
    from .catalog import ThreadCatalog
  File "/Users/tanja/Developer/inkstitch/lib/threads/catalog.py", line 13, in <module>
    from .palette import ThreadPalette
  File "/Users/tanja/Developer/inkstitch/lib/threads/palette.py", line 8, in <module>
    from colormath.color_conversions import convert_color
  File "/Users/tanja/Developer/inkstitch/venv/lib/python3.8/site-packages/colormath/color_conversions.py", line 13, in <module>
    import networkx
  File "/Users/tanja/Developer/inkstitch/venv/lib/python3.8/site-packages/networkx/__init__.py", line 117, in <module>
    import networkx.readwrite
  File "/Users/tanja/Developer/inkstitch/venv/lib/python3.8/site-packages/networkx/readwrite/__init__.py", line 15, in <module>
    from networkx.readwrite.graphml import *
  File "/Users/tanja/Developer/inkstitch/venv/lib/python3.8/site-packages/networkx/readwrite/graphml.py", line 314, in <module>
    class GraphML(object):
  File "/Users/tanja/Developer/inkstitch/venv/lib/python3.8/site-packages/networkx/readwrite/graphml.py", line 346, in GraphML
    (np.int, "int"), (np.int8, "int"),
  File "/Users/tanja/Developer/inkstitch/venv/lib/python3.8/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'int'
```

**Comment by bastanja** [comment]
Tried it again with a new venv, because I suspect that some python packages did not fit together. After installing the requirements with `pip install -r requirements.txt` the package cssselect was still missing. I installed it manually.

The ValueError seems to be solved when Inkscape.app is in the expected path /Applications/Inkscape.app/ not in the ~/Applications folder.

The `AttributeError: module 'numpy' has no attribute 'int'` is gone now, too. Probably installing the requirements did not work initially and I manually installed wrong versions of packages.

Now I get this when trying to run Params:

```
This program needs access to the screen. Please run with a
Framework build of python, and only when you are logged in
on the main display of your Mac.
````

This seems to be related to wxpython and maybe pyenv. Still investiating. Hints are welcome :-)

**Comment by bastanja** [comment]
Using a framework build of python solved the issue that the app needs access to the screen.

I installed python using pyenv. So I first uninstalled it:

```
pyenv uninstall 3.8.16
````

And then re-installed it as framework version:

```
env PYTHON_CONFIGURE_OPTS="--enable-framework" pyenv install 3.8.16
```

Then set up a new venv, install the requirements.

Now the Params dialog opens and I can use the manual setup of Ink/Stitch.

So, to summarize:
- The manual setup expects that inkscape is installed in /Applications, not ~/Applications. If it is in the wrong folder, it throws a ValueError
- The python version used with Ink/Stitch needs to be a framework python

**Comment by lexelby** [comment]
Oh hi!! @rlevine just pointed me to your stitch generator project, which looks _amazing_.  I'm really happy you're here!

Yes, there is a way to attach a debugger.  You can use either PyDev or PyCharm, both have compatible debuggers built in that work with Ink/Stitch.  Create a file named DEBUG in your inkstitch clone dir.  When that file exists, inkstitch.py will attempt to connect to the debugger on startup.

Thanks for your detailed feedback on the manual setup stuff.  I think @rlevine just went through the same hairpulling.  If either of you two is motivated to create a PR against our gh-pages branch, we would be happy to receive it.

And a note for both of you: we have an open source license for JetBrains products (including PyCharm) for use on this project.  I am able to request that new people are added as long as they are "regular contributors" to the project.  So that's an option if you (or anyone else) are interested.
