### ISSUE TITLE
auto_fill: NetworkXNoPath

### ISSUE THREAD

**Issue by jimevt** [inkstitch/inkstitch#2056]
I have two objects/paths that I can render individually, but when I try to render them both, the visualizer hung.  When I killed it with the "X" in the top right, I got this message:

path21319: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 556, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 590, in do_underlay
  File "lib\debug.py", line 133, in decorated
  File "lib\stitches\auto_fill.py", line 75, in auto_fill
  File "lib\debug.py", line 133, in decorated
  File "lib\stitches\auto_fill.py", line 630, in path_to_stitches
  File "lib\stitches\auto_fill.py", line 591, in travel
  File "networkx\algorithms\shortest_paths\generic.py", line 167, in shortest_path
  File "networkx\algorithms\shortest_paths\weighted.py", line 2377, in bidirectional_dijkstra
networkx.exception.NetworkXNoPath: No path between (30.043842245272, 46.255182719272) and (25.51181102362205, 46.18612308559187).
path21319: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 556, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 590, in do_underlay
  File "lib\debug.py", line 133, in decorated
  File "lib\stitches\auto_fill.py", line 75, in auto_fill
  File "lib\debug.py", line 133, in decorated
  File "lib\stitches\auto_fill.py", line 630, in path_to_stitches
  File "lib\stitches\auto_fill.py", line 591, in travel
  File "networkx\algorithms\shortest_paths\generic.py", line 167, in shortest_path
  File "networkx\algorithms\shortest_paths\weighted.py", line 2377, in bidirectional_dijkstra
networkx.exception.NetworkXNoPath: No path between (30.043842245272, 46.255182719272) and (25.51181102362205, 46.18612308559187).

**Comment by kaalleen** [comment]
Would you mind to show us the file which is causing the issue?

**Comment by jimevt** [comment]
![ProblemBird_2](https://user-images.githubusercontent.com/5093698/217650438-e23456d9-8679-49c7-b88f-1faeed3fa3a4.svg)

Each of these renders on their own, but I can't render them together.

Thanks!

**Comment by jimevt** [comment]
I was able to fix issues with the bird border that caused this issue - there were a couple of points right on top of each other in the wing. 
   I tried removing all but the last one, saving, and running the visualizer again, but that 2nd point seemed to re-appear.  Eventually I moved the extra point a little further out on the line, saved, and everything worked OK.

   This is my first design in Inkscape, so I won't be surprised/dismayed if you tell me I don't know what I'm doing :-)

**Comment by kaalleen** [comment]
Sorry for the late answer. I can actually reproduce the error. Thank you for the file. I'll have a closer look at it as soon as I find the time.

**Comment by kaalleen** [comment]
You are right, the problem is the duplicated point in the fill stitching. I wonder why it renders alone but not all together.

Any ideas @lexelby ? We are seeing this issue relatively often. Would be nice if we could fix it.

![2056_problem_area](https://user-images.githubusercontent.com/36401965/222905945-40b28cdd-cc81-4b21-aa3b-3c84e2e769dd.png)

**Comment by kaalleen** [comment]
#1562 holds an other file which can reproduce the error.
