### ISSUE TITLE
the geoms strike again

### ISSUE THREAD

**Issue by Lenise22** [inkstitch/inkstitch#2064]
[](url)
Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 231, in run
  File "lib/extensions/output.py", line 56, in effect
  File "lib/extensions/base.py", line 200, in elements_to_stitch_groups
  File "lib/elements/element.py", line 329, in embroider
  File "lib/elements/element.py", line 387, in validate
  File "lib/elements/fill_stitch.py", line 321, in validation_errors
  File "lib/elements/fill_stitch.py", line 274, in shape
AttributeError: 'LineString' object has no attribute ['geoms']

(![gon nike ink](https://user-images.githubusercontent.com/124225238/218244805-ba235c49-2b41-4d8d-aa23-f32109aa890a.svg))

**Comment by bianchifan** [comment]
You should specify your operating system and the exact version for the developers.
At me it works properly on Linux MInt 20.3 with actual Inkscape/Inkstitch..simulation, PES, DST...

![Bildschirmfoto vom 2023-02-11 10-41-11](https://user-images.githubusercontent.com/17491743/218251692-a085c436-a637-48e2-a3ad-ca1c7d26925c.jpg)

**Comment by Lenise22** [comment]
can you send a zip file of the pes?

**Comment by bianchifan** [comment]
Of course i Can, but it doesn't solve your problem...
[218244805-ba235c49-2b41-4d8d-aa23-f32109aa890ao.zip](https://github.com/inkstitch/inkstitch/files/10714134/218244805-ba235c49-2b41-4d8d-aa23-f32109aa890ao.zip)

**Comment by Lenise22** [comment]
i know :( thank you! i do have a Monterry processing macbook and my inkstitch says version 2. something I'm gonna have to check when i get a chance

**Comment by kaalleen** [comment]
Closing in favor of #2065
