### ISSUE TITLE
guided_fill: ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by PEPEGR1LL0** [inkstitch/inkstitch#2073]
Hola adjunto reporte de error:

path51546: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.2.0 (osx)

Traceback (most recent call last):
  File "lib/elements/fill_stitch.py", line 566, in to_stitch_groups
  File "lib/elements/fill_stitch.py", line 677, in do_guided_fill
  File "lib/stitches/guided_fill.py", line 34, in guided_fill
  File "lib/stitches/guided_fill.py", line 240, in intersect_region_with_grating_guideline
  File "lib/stitches/guided_fill.py", line 196, in clean_offset_line
  File "lib/stitches/guided_fill.py", line 118, in repair_multiple_parallel_offset_curves
ValueError: max() arg is an empty sequence

**Comment by kaalleen** [comment]
Would you mind to send us your svg file which is causing the error? If you can isolate the specific guided fill element that would be nice too.

**Comment by kaalleen** [comment]
Please have a look at #1811 This only seems to happen with macOS systems and a specific shapely version.
I think we updated shapely for the next release.
