### ISSUE TITLE
Inkstich Issue

### ISSUE THREAD

**Issue by EvieLovesLearning** [inkstitch/inkstitch#2075]
path17: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 556, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 590, in do_underlay
  File "lib\debug.py", line 133, in decorated
  File "lib\stitches\auto_fill.py", line 62, in auto_fill
  File "lib\stitches\fill.py", line 163, in intersect_region_with_grating
ZeroDivisionError: float division by zero

**Comment by Pheonica** [comment]
How did you solve this? I'm having the same issue.

**Comment by EvieLovesLearning** [comment]
Hey, I'm not completely certain to be honest. When I got that message, I
had dropped my file into Inkstitch. I didn't have the same problem when I
opened the file through Inkstitch itself.

Op do 16 feb. 2023 20:37 schreef Pheonica ***@***.***>:
