### ISSUE TITLE
Windows 10:  AttributeError: 'NullWriter' object has no attribute 'buffer'

### ISSUE THREAD

**Issue by LucieRous** [inkstitch/inkstitch#2092]
I have install inkscape and then inkstich but it not run 
Traceback (most recent call last):
  File "inkstitch.py", line 25, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "inkex\__init__.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "inkex\extensions.py", line 34, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "inkex\elements\__init__.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "inkex\elements\_base.py", line 36, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "inkex\base.py", line 51, in <module>
AttributeError: 'NullWriter' object has no attribute 'buffer'

can you help me?

**Comment by kaalleen** [comment]
Which operating system do you use?

**Comment by LucieRous** [comment]
windows 10

**Comment by kaalleen** [comment]
Is this Ink/Stitch v2.2.0 ?

**Comment by Maiocco** [comment]
I also have the identical issue and it is version 2.2.0.  I've tried the installer from institch's website and from github, with the same result.

**Comment by Stitches33** [comment]
I see the same issues when trying to run v2.2.0.  I've tried the installer from their site and github.  I've also tried instillation in different locations.  Thanks for the help.

**Comment by kaalleen** [comment]
Sorry, I somehow forgot about your issue. Now that a new version has been released, could you get it running?

**Comment by kaalleen** [comment]
Closing the issue. Please open a new issue if the error is showing up again with a newer version of Ink/Stitch.
