### ISSUE TITLE
Debug while saving an embrodery PES file

### ISSUE THREAD

**Issue by mplagnol** [inkstitch/inkstitch#2094]
-
Ink/Stitch Version: v2.2.0 (osx)

Traceback (most recent call last):
  File "lib/elements/fill_stitch.py", line 556, in to_stitch_groups
  File "lib/elements/fill_stitch.py", line 590, in do_underlay
  File "lib/debug.py", line 133, in decorated
  File "lib/stitches/auto_fill.py", line 62, in auto_fill
  File "lib/stitches/fill.py", line 163, in intersect_region_with_grating
ZeroDivisionError: float division by zero

**Comment by mplagnol** [comment]
i've tried to restart and do it again but I still have the same issue. I copie my SVG source image

![NateDof](https://user-images.githubusercontent.com/12998677/221371677-f271d6e7-bf4d-4b7f-90a8-030cf646d68d.svg)

**Comment by Marif91** [comment]
As-tu vérifié qu'il n'y avait pas d'erreurs dans ton tracé (inkstitch - Résolution de problèmes - Dépistage de problèmes avec les objets)?

A mon avis ton motif est un motif destiné à l'impression avec de très nombreux détails inadaptés à la broderie. L'as-tu saisi toi-même ?

**Comment by kaalleen** [comment]
Duplicate of #1829
