### ISSUE TITLE
Issue Trying to Save As PES file 

### ISSUE THREAD

**Issue by krhernandez25** [inkstitch/inkstitch#2140]
Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\output.py", line 56, in effect
  File "lib\extensions\base.py", line 200, in elements_to_stitch_groups
  File "lib\elements\element.py", line 329, in embroider
  File "lib\elements\element.py", line 387, in validate
  File "lib\elements\fill_stitch.py", line 321, in validation_errors
  File "lib\elements\fill_stitch.py", line 274, in shape
AttributeError: 'LineString' object has no attribute 'geoms'

**Comment by kaalleen** [comment]
Remove small elements from your document, this should fix your issue.

**Comment by kaalleen** [comment]
Duplicate of https://github.com/inkstitch/inkstitch/issues/1742
