### ISSUE TITLE
icing (path1495): error: Error during autofill!  

### ISSUE THREAD

**Issue by GemGemCity** [inkstitch/inkstitch#2141]
icing (path1495): error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.2.0 (osx)

Traceback (most recent call last):
  File "lib/elements/fill_stitch.py", line 556, in to_stitch_groups
  File "lib/elements/fill_stitch.py", line 590, in do_underlay
  File "lib/debug.py", line 133, in decorated
  File "lib/stitches/auto_fill.py", line 75, in auto_fill
  File "lib/debug.py", line 133, in decorated
  File "lib/stitches/auto_fill.py", line 630, in path_to_stitches
  File "lib/stitches/auto_fill.py", line 591, in travel
  File "networkx/algorithms/shortest_paths/generic.py", line 167, in shortest_path
  File "networkx/algorithms/shortest_paths/weighted.py", line 2377, in bidirectional_dijkstra
networkx.exception.NetworkXNoPath: No path between (369.0381756198029, 115.35437406878626) and (388.2121252109063, 131.64928680873223).

**Comment by kaalleen** [comment]
See also: #2056

**Comment by kaalleen** [comment]
Closing in favor of #2056
