### ISSUE TITLE
path195: error: Error during autofill

### ISSUE THREAD

**Issue by StargazingOrion** [inkstitch/inkstitch#2154]
path195: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 562, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 611, in do_auto_fill
  File "lib\debug.py", line 133, in decorated
  File "lib\stitches\auto_fill.py", line 75, in auto_fill
  File "lib\debug.py", line 133, in decorated
  File "lib\stitches\auto_fill.py", line 630, in path_to_stitches
  File "lib\stitches\auto_fill.py", line 591, in travel
  File "networkx\algorithms\shortest_paths\generic.py", line 167, in shortest_path
  File "networkx\algorithms\shortest_paths\weighted.py", line 2377, in bidirectional_dijkstra
networkx.exception.NetworkXNoPath: No path between (377.9528, 0.9448818897637636) and (121.71581105056998, 1.1116258934692).

**Comment by kaalleen** [comment]
Ohh, we have seen this one. It seems to be influenced by the starting- or ending position of this element. Try to set start and end commands for path195 and modify them slightly until it works.

It could be helpful for us in order to fix the error if you could provide the file which is causing it.

**Comment by StargazingOrion** [comment]
Got home from work today and tried one more time prior to adding commands and it finally worked? Not to mention consistently working. Here is the file just in case. 

I'm not too informed on what the program is really capable of as I'm not super tech-savvy but this program rocks so I wanted to post the error if it helped you guys at all :)

here is the file I was using just in case - 

![palindrome svg lol](https://user-images.githubusercontent.com/128337906/226456537-e18096bd-e2e7-43fd-bc61-7ebe48d36577.svg)
