### ISSUE TITLE
No handlers could be found for logger "shapely.geos"

### ISSUE THREAD

**Issue by danielkschneider** [inkstitch/inkstitch#216]
IMHO this should produce a message to the user telling him/her to simplify path, e.b. break it up into smaller polygones (if that is the problem). I attached the zip of the SVG. 

I also found a workaround. 
- In Fill and Stroke, Fill tab, tick the "Fill solid ..... " icon 
- Fill again with the paint bucket. This will create a new path
- Kill the old path

No handlers could be found for logger "shapely.geos"
Traceback (most recent call last):
  File "inkstitch.py", line 20, in <module>
    if script_name.endswith('.py'):
  File "inkscape-0.92.2/share/extensions/inkex.py", line 283, in affect
  File "lib/extensions/embroider.py", line 83, in effect
  File "lib/extensions/base.py", line 196, in elements_to_patches
  File "lib/elements/element.py", line 257, in embroider
  File "lib/elements/auto_fill.py", line 129, in to_patches
  File "lib/stitches/auto_fill.py", line 21, in auto_fill
  File "lib/stitches/fill.py", line 139, in intersect_region_with_grating
  File "site-packages/shapely/geometry/base.py", line 620, in intersection
  File "site-packages/shapely/topology.py", line 70, in __call__
  File "site-packages/shapely/topology.py", line 38, in _check_topology
TopologicalError: The operation 'GEOSIntersection_r' could not be performed. Likely cause is invalidity of the geometry <shapely.geometry.multipolygon.MultiPolygon object at 0x7f20b0cce8d0>

[moth-bug.svg.zip](https://github.com/lexelby/inkstitch/files/2141202/moth-bug.svg.zip)

[moth-bug-fixed.svg.zip](https://github.com/lexelby/inkstitch/files/2141516/moth-bug-fixed.svg.zip)

FYI: My motivation for doing this: A co-worker wanted her drawing stitched. I got it done with a commercial program and wanted to see how much work it would require to get it done with Inkstitch. https://www.instagram.com/p/BkdGy1gHg93/?hl=en&taken-by=daniel.k.schneider

**Comment by lexelby** [comment]
Thanks!  I could have sworn Ink/Stitch caught this exception , but perhaps I missed a case.  I agree that it should handle this gracefully and make recommendations to the user on how to fix the shape.

The gist of it is:

* the outline of the shape or any of its holes should not cross over itself (like a lemniscate)
* there should be one outer shape and some number of holes
  * not two or more distinct separate "islands"
* the holes should not touch each other or intersect
