### ISSUE TITLE
Group of Satin Stitches Error when AutoRouting Satin Stitches

### ISSUE THREAD

**Issue by chubean** [inkstitch/inkstitch#2166]
Hopefully this is the right way to post an issue I have.  Satin stitches converted using the new function (square).  They run through Params and Visualize just fine, but now I need to auto-route and they are giving the following error.

Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

Ink/Stitch Version: stitch-selection-methods (linux)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 231, in run
  File "lib/extensions/auto_satin.py", line 69, in effect
  File "lib/stitches/auto_satin.py", line 349, in auto_satin
  File "lib/stitches/auto_satin.py", line 486, in operations_to_elements_and_trims
  File "lib/stitches/auto_satin.py", line 248, in to_element
  File "lib/elements/element.py", line 61, in __init__
  File "lib/elements/element.py", line 99, in _update_legacy_params
  File "lib/elements/element.py", line 235, in get_style
  File "lib/elements/element.py", line 232, in _get_specified_style
  File "inkex/elements/_base.py", line 626, in specified_style
  File "inkex/styles.py", line 460, in specified_style
  File "inkex/styles.py", line 425, in cascaded_style
  File "inkex/elements/_base.py", line 352, in root
inkex.utils.FragmentError: Element fragment does not have a document root!

**Comment by chubean** [comment]
Same for my running stitches.

Ink/Stitch Version: stitch-selection-methods (linux)


Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 231, in run
  File "lib/extensions/auto_run.py", line 35, in effect
  File "lib/stitches/auto_run.py", line 133, in autorun
  File "lib/stitches/auto_run.py", line 245, in path_to_elements
  File "lib/stitches/auto_run.py", line 300, in create_element
  File "lib/elements/element.py", line 61, in __init__
  File "lib/elements/element.py", line 99, in _update_legacy_params
  File "lib/elements/element.py", line 235, in get_style
  File "lib/elements/element.py", line 232, in _get_specified_style
  File "inkex/elements/_base.py", line 626, in specified_style
  File "inkex/styles.py", line 460, in specified_style
  File "inkex/styles.py", line 425, in cascaded_style
  File "inkex/elements/_base.py", line 352, in root
inkex.utils.FragmentError: Element fragment does not have a document root!

**Comment by chubean** [comment]
Maybe I just need to timeshift.

**Comment by lexelby** [comment]
Well that's interesting!  Thanks for the bug report.  That's definitely a bug in one of our recent changes.  @kaalleen I guess we can't get styles in the constructor...

@chubean What do you mean by timeshift?

**Comment by kaalleen** [comment]
Thank you for your error report and testing development versions!!

@lexelby We just need to update inkex once again. They fixed the issue within inkex already.

**Comment by chubean** [comment]
@lexelby I thought maybe I messed up because after the error, I uninstalled inkstitch and Inkscape and I couldn’t get past the error even after a reinstall. Timeshift would do a system restore point. I haven’t done that yet because I’m under the weather.

**Comment by lexelby** [comment]
Yikes! No, you definitely don't need to restore from backup to fix this one.

**Comment by chubean** [comment]
Back in business!  Auto-route successful!  Thank you!
Do you guys sleep? :)
