### ISSUE TITLE
Jump stich Removal

### ISSUE THREAD

**Issue by Gunrep517** [inkstitch/inkstitch#2173]
Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.
![THA R B PNG No BackGround with turkey sized](https://user-images.githubusercontent.com/128974117/227773409-b56c3e84-8f6c-4f56-9b99-6a70806fff6e.png)
Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\object_commands.py", line 38, in effect
  File "lib\commands.py", line 397, in add_commands
  File "lib\commands.py", line 350, in get_command_pos
AttributeError: 'MultiPolygon' object has no attribute 'exterior'

**Comment by kaalleen** [comment]
Thank you for your error report. Would you mind to share your svg file?

**Comment by kaalleen** [comment]
#2195 had an svg file. Issue is fixed in current Ink/Stitch version (v3.0.1)
