### ISSUE TITLE
Traceback issue using "Cleanup Document" Function

### ISSUE THREAD

**Issue by Jazziec2010** [inkstitch/inkstitch#2177]
nk/Stitch Version: v2.2.0 (osx)

Traceback (most recent call last):
  File "shapely/speedups/_speedups.pyx", line 90, in shapely.speedups._speedups.geos_linestring_from_py
AttributeError: 'list' object has no attribute '__array_interface__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 231, in run
  File "lib/extensions/cleanup.py", line 45, in effect
  File "lib/elements/stroke.py", line 330, in shape
  File "lib/elements/stroke.py", line 334, in as_multi_line_string
  File "lib/elements/stroke.py", line 334, in <listcomp>
  File "shapely/geometry/linestring.py", line 46, in __init__
  File "shapely/speedups/_speedups.pyx", line 156, in shapely.speedups._speedups.geos_linestring_from_py
ValueError: LineStrings must have at least 2 coordinate tuples
![Logo](https://user-images.githubusercontent.com/129114404/228055355-dd0e8283-f8f3-4797-ae5e-996bdc83709c.svg)

**Comment by kaalleen** [comment]
Thank you for your error report.

This is a problem with the shapely version we shipped with the osx build. Cleanup document would delete 0 elements for your document though, they are all big enough.
