### ISSUE TITLE
Can't conver svg to pes

### ISSUE THREAD

**Issue by skishore902** [inkstitch/inkstitch#2207]
Is there something I'm missing. I tried going to embroider  but it gives a similar error. Never used inkscape before, I thought this was a simple conversion. If theres plenty to do, is there a tutorial to follow that will give detailed instructions on the covnersion?

experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\output.py", line 56, in effect
  File "lib\extensions\base.py", line 200, in elements_to_stitch_groups
  File "lib\elements\element.py", line 329, in embroider
  File "lib\elements\element.py", line 387, in validate
  File "lib\elements\fill_stitch.py", line 321, in validation_errors
  File "lib\elements\fill_stitch.py", line 274, in shape
AttributeError: 'LineString' object has no attribute 'geoms'

![Holistic Dragon Logo White](https://user-images.githubusercontent.com/13138522/230738625-021e5e9e-d223-4e0f-9cc6-0abb461fd82f.svg)

**Comment by Marif91** [comment]
Il faut suivre un tutoriel, ton motif n'est pas paramétré pour une broderie, par ailleurs il est immense, il mesure 1200mm*990mm... Certaines formes sont beaucoup trop petites pour pouvoir les broder.

Ton motif doit être réduit et simplifié !

**Comment by kaalleen** [comment]
Duplicate of https://github.com/inkstitch/inkstitch/issues/1742
