### ISSUE TITLE
Ran into an error, file seems to have stopped working.

### ISSUE THREAD

**Issue by fuckfastfashion** [inkstitch/inkstitch#2219]
I am currently digitizing my logo, while doing so suddenly this error has popped up.
This happened when doing a preview. After that I tried to add a command to the K which also prompted the same issue.

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "shapely\speedups\_speedups.pyx", line 90, in shapely.speedups._speedups.geos_linestring_from_py
AttributeError: 'list' object has no attribute '__array_interface__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\object_commands.py", line 37, in effect
  File "lib\elements\satin_column.py", line 242, in shape
  File "lib\elements\satin_column.py", line 259, in flattened_rails
  File "lib\elements\satin_column.py", line 253, in rails
  File "lib\elements\satin_column.py", line 253, in <listcomp>
  File "lib\elements\satin_column.py", line 329, in rail_indices
  File "lib\elements\satin_column.py", line 329, in <listcomp>
  File "shapely\geometry\linestring.py", line 46, in __init__
  File "shapely\speedups\_speedups.pyx", line 156, in shapely.speedups._speedups.geos_linestring_from_py
ValueError: LineStrings must have at least 2 coordinate tuples

The file is attached below.
![FFF LOGO BLACK updated 8-4 75%](https://user-images.githubusercontent.com/130765460/232053012-4111dc3f-0494-46e2-aa3d-48ab389b2b0d.svg)

**Comment by kaalleen** [comment]
In your "new text (fuck)" layer you have the "K (fuck) group with a path label "k". Add just one more node to one of the rungs and it will run through again. Sorry for that. This error will be fixed in the very next release.

**Comment by fuckfastfashion** [comment]
> 

Absolute legend! Thank you for the fix, glad to get it working again. Awesome to see you guys pick this stuff up so quickly and update it so soon as well. Really appreciate the work you put in this project.

**Comment by kaalleen** [comment]
Nice, thanks for your feedback!
