### ISSUE TITLE
AttributeError: 'MultiPolygon' object has no attribute 'exterior'

### ISSUE THREAD

**Issue by carre420** [inkstitch/inkstitch#2269]
Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\object_commands.py", line 38, in effect
  File "lib\commands.py", line 397, in add_commands
  File "lib\commands.py", line 350, in get_command_pos
AttributeError: 'MultiPolygon' object has no attribute 'exterior'

**Comment by kaalleen** [comment]
Do you stilll have the svg file? It'd be interesting to see.

**Comment by kaalleen** [comment]
Duplicate of #2225
Seems to be fixed...
