### ISSUE TITLE
Error antes de iniciar la aplicación

### ISSUE THREAD

**Issue by momosiqui** [inkstitch/inkstitch#2273]
Failed to execute script "inkstich" due to unhandled exception: "NullWriter" object has no attribute "buffer."

Traceback (most recent call last):
  File "inkstitch.py", line 25, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "inkex\__init__.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "inkex\extensions.py", line 34, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "inkex\elements\__init__.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "inkex\elements\_base.py", line 36, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "inkex\base.py", line 51, in <module>
AttributeError: 'NullWriter' object has no attribute 'buffer'

**Comment by kaalleen** [comment]
Which Windows Version is this? Which Ink/Stitch Version is this?
How did you install Ink/Stitch?
Does this show up when you run any Ink/Stitch extension from within Inkscape?

**Comment by momosiqui** [comment]
apologies. The content of this application in Spanish is scarce and I had to add it to the Inkscape extensions manually. I thought that it was executed through the application icon, when in reality its function is to display some extensions within Inkscape

Anyway thanks for answering. Now I just need to learn how to use it correctly. :=

**Comment by kaalleen** [comment]
Thank you for your feedback and don't hesitate to ask if you have any questions.
