### ISSUE TITLE
ContourFill: TopologyException

### ISSUE THREAD

**Issue by DonArnestro** [inkstitch/inkstitch#2279]
Hello,
please find attached the error message.
I cannot describe when it raise up, because I tried several things before under the "Params". It wasn't only one thing and I clicked then cancel.

Regards
Arne

circle49: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 564, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 632, in do_contour_fill
  File "lib\stitches\contour_fill.py", line 137, in offset_polygon
  File "lib\stitches\contour_fill.py", line 186, in _match_polygons_and_holes
  File "shapely\geometry\base.py", line 685, in difference
  File "shapely\topology.py", line 72, in __call__
  File "shapely\topology.py", line 37, in _check_topology
shapely.errors.TopologicalError: The operation 'GEOSDifference_r' could not be performed. Likely cause is invalidity of the geometry <shapely.geometry.multipolygon.MultiPolygon object at 0x1F069CA0>

circle49: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 564, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 632, in do_contour_fill
  File "lib\stitches\contour_fill.py", line 137, in offset_polygon
  File "lib\stitches\contour_fill.py", line 186, in _match_polygons_and_holes
  File "shapely\geometry\base.py", line 685, in difference
  File "shapely\topology.py", line 72, in __call__
  File "shapely\topology.py", line 37, in _check_topology
shapely.errors.TopologicalError: The operation 'GEOSDifference_r' could not be performed. Likely cause is invalidity of the geometry <shapely.geometry.multipolygon.MultiPolygon object at 0x1F60CEB0>

shapely.geos - ERROR - TopologyException: Input geom 1 is invalid: Self-intersection at 75.168911584013259 144.81647473629164
shapely.geos - INFO - Self-intersection at or near point 75.168911584013259 144.81647473629164
shapely.geos - ERROR - TopologyException: Input geom 1 is invalid: Self-intersection at 75.168911584013259 144.81647473629164
shapely.geos - INFO - Self-intersection at or near point 75.168911584013259 144.81647473629164

**Comment by kaalleen** [comment]
Do you still have the svg file on which you tried the contour fill settings?

**Comment by DonArnestro** [comment]
I believe it was this file.
But I cannot remember to the workingstep.

![Wappen_Deinste_Stitches60](https://github.com/inkstitch/inkstitch/assets/132883448/92d0052a-541a-47e0-9305-e4abc4366699)

**Comment by kaalleen** [comment]
This renders fine with the newest release, therefore I'll close the issue.
If you see this ever again, please open a new issue and send the svg file along.
