### ISSUE TITLE
Inkstitch error code

### ISSUE THREAD

**Issue by polonag** [inkstitch/inkstitch#2286]
Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\troubleshoot.py", line 29, in effect
  File "lib\elements\fill_stitch.py", line 321, in validation_errors
  File "lib\elements\fill_stitch.py", line 274, in shape
AttributeError: 'LineString' object has no attribute 'geoms'

**Comment by kaalleen** [comment]
Try to remove small elements from your document.

**Comment by kaalleen** [comment]
Duplicate of https://github.com/inkstitch/inkstitch/issues/1742
