### ISSUE TITLE
AttributeError: 'Point' object has no attribute 'geoms'

### ISSUE THREAD

**Issue by kympowell5** [inkstitch/inkstitch#2292]
Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\cleanup.py", line 41, in effect
  File "lib\elements\fill_stitch.py", line 274, in shape
AttributeError: 'Point' object has no attribute 'geoms'
![inkstitch_test](https://github.com/inkstitch/inkstitch/assets/62775266/a3f0cc7a-f7bc-4a1c-bb9c-0ee04f3a8cf4)

**Comment by kaalleen** [comment]
Thank you for your error report.
Remove path 350 from your document. It is a circle with radius 0.
The next Ink/Stitch version will just ignore the circle and will not fail on it.
