### ISSUE TITLE
 ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by pullingakatherine** [inkstitch/inkstitch#2301]
Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 556, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 590, in do_underlay
  File "lib\debug.py", line 133, in decorated
  File "lib\stitches\auto_fill.py", line 62, in auto_fill
  File "lib\stitches\fill.py", line 163, in intersect_region_with_grating
ZeroDivisionError: float division by zero

**Comment by kaalleen** [comment]
Try to remove small elements from your document. Additionally make sure, that you do not have very thin fills. Widen them a little or see if maybe an other stitch type would be better for your use case (such as satin or even running stitch).

**Comment by kaalleen** [comment]
Fixed in latest release.
