### ISSUE TITLE
Error while saving as EXP file

### ISSUE THREAD

**Issue by dbair** [inkstitch/inkstitch#2302]
Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\output.py", line 56, in effect
  File "lib\extensions\base.py", line 200, in elements_to_stitch_groups
  File "lib\elements\element.py", line 329, in embroider
  File "lib\elements\element.py", line 387, in validate
  File "lib\elements\fill_stitch.py", line 321, in validation_errors
  File "lib\elements\fill_stitch.py", line 274, in shape
AttributeError: 'LineString' object has no attribute 'geoms'
![Camper-in-Woods-American-Flag-580x387-Colored](https://github.com/inkstitch/inkstitch/assets/12084878/3cb7d814-69e8-4118-beea-746c554c1e49)

**Comment by kaalleen** [comment]
![2302](https://github.com/inkstitch/inkstitch/assets/36401965/461fb6ff-f5e0-4771-b1bd-0bc46feb2821)

Delete the two paths in the image.

Also you need to rework some parts of your design. For example the blue part. Make a simple star with one (self crossing) stroke out of white thread and duplicate it several times. Delete the holes from the blue and stitch your white stars on top. This would actually reduce the stitch count and will look much nicer.

**Comment by bianchifan** [comment]
Are your shure 260000 stitches??
Two complete stichouts in one color and a color stitch on top?
Your EXP on LInux MInt..
[239142307-3cb7d814-69e8-4118-beea-746c554c1e49.zip](https://github.com/inkstitch/inkstitch/files/11505263/239142307-3cb7d814-69e8-4118-beea-746c554c1e49.zip)

Your SVG with some changes
![239142307-3cb7d814-69e8-4118-beea-746c554c1e49-2](https://github.com/inkstitch/inkstitch/assets/17491743/c5b14259-1951-4435-bb9a-550cdf231be9)

In this EXP the caravan is still stiched twice, first in green and brown on top
[239142307-3cb7d814-69e8-4118-beea-746c554c1e49-2.zip](https://github.com/inkstitch/inkstitch/files/11505283/239142307-3cb7d814-69e8-4118-beea-746c554c1e49-2.zip)

I'm quite shure its not the result you wanted, you have to rework you SVG...

**Comment by dbair** [comment]
Thank you for the comments.
I am a complete NOOB so appreciate your comments and help.
I will continue to work with it, search for more online trainings, etc.
