### ISSUE TITLE
AttributeError: 'LineString' object has no attribute 'geoms'

### ISSUE THREAD

**Issue by vnx86b** [inkstitch/inkstitch#2304]
Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 231, in run
  File "lib/extensions/cleanup.py", line 41, in effect
  File "lib/elements/fill_stitch.py", line 274, in shape
AttributeError: 'LineString' object has no attribute 'geoms'

**Comment by kaalleen** [comment]
Watch out for very small fill objects and remove them from your document

**Comment by kaalleen** [comment]
Fixed in latest release
