### ISSUE TITLE
 IndexError: string index out of range

### ISSUE THREAD

**Issue by mariestelle** [inkstitch/inkstitch#2309]
path557: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 556, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 590, in do_underlay
  File "lib\debug.py", line 133, in decorated
  File "lib\stitches\auto_fill.py", line 62, in auto_fill
  File "lib\stitches\fill.py", line 163, in intersect_region_with_grating
ZeroDivisionError: float division by zero

**Comment by kaalleen** [comment]
Thank you for your error report. We have seen this one a lot and it will be fixed in a few days when we release our next version.
Still, you most probably need to rework your svg for good embroidery (even if it runs through). Remove small elements from your document (using cleanup documents in the next version (and probably now) will help) and watch out for thin fill elements and widen them or depending on your shape consider to use satin or running stitch instead.

**Comment by kaalleen** [comment]
Closing. Solved in latest release.
