### ISSUE TITLE
inkex error in elements_selected when group has an empty id string

### ISSUE THREAD

**Issue by rcoyote** [inkstitch/inkstitch#2311]
Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\convert_to_satin.py", line 31, in effect
  File "lib\extensions\base.py", line 185, in get_elements
  File "lib\extensions\base.py", line 182, in get_nodes
  File "lib\extensions\base.py", line 168, in descendants
  File "lib\extensions\base.py", line 161, in descendants
  File "inkex\elements\_selected.py", line 59, in __contains__
  File "inkex\elements\_selected.py", line 98, in _to_key
IndexError: string index out of range
![brucey](https://github.com/inkstitch/inkstitch/assets/134247604/6c6249bb-95d3-4049-8f92-831fd0a061dc)

**Comment by kaalleen** [comment]
Thank you for sharing. Definitely something we should inform the inkex team about.

Your group does have an empty id and inkex doesn't like it. So you could select your group, ungroup and re-group again to solve your problem.
