### ISSUE TITLE
Problem rendering stitch plan

### ISSUE THREAD

**Issue by Embroiderly** [inkstitch/inkstitch#2312]
Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\stitch_plan_preview.py", line 39, in effect
  File "lib\extensions\base.py", line 200, in elements_to_stitch_groups
  File "lib\elements\element.py", line 329, in embroider
  File "lib\elements\element.py", line 387, in validate
  File "lib\elements\fill_stitch.py", line 321, in validation_errors
  File "lib\elements\fill_stitch.py", line 274, in shape
AttributeError: 'LineString' object has no attribute 'geoms'

![flyingull](https://github.com/inkstitch/inkstitch/assets/134275029/b31a904b-35d4-44ae-88c5-6908a2e900ce)

**Comment by Embroiderly** [comment]
Actually just found a load of random paths underneath the beak, dunno where they came from, it works now that they're gone.
