### ISSUE TITLE
autofill: NetworkXNoPath

### ISSUE THREAD

**Issue by itanishy** [inkstitch/inkstitch#2354]
After trying Params, i've received those messages.

OS: Windows 10
CPU: Ryzen 5 3600
GPU: AMD RX6700xt
Ram: 16GBs

Ink/Stitch Version: v3.0.0 (windows)

Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 729, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 781, in do_auto_fill
  File "lib\debug.py", line 231, in decorated
  File "lib\stitches\auto_fill.py", line 76, in auto_fill
  File "lib\debug.py", line 231, in decorated
  File "lib\stitches\auto_fill.py", line 647, in path_to_stitches
  File "lib\stitches\auto_fill.py", line 608, in travel
  File "networkx\classes\backends.py", line 148, in wrapper
  File "networkx\algorithms\shortest_paths\generic.py", line 173, in shortest_path
  File "networkx\algorithms\shortest_paths\weighted.py", line 2398, in bidirectional_dijkstra
networkx.exception.NetworkXNoPath: No path between (154.23899068456612, 157.7952755905512) and (138.31662151247616, 158.23342570063068).
![pp,504x498-pad,600x600,f8f8f8](https://github.com/inkstitch/inkstitch/assets/102188712/d9c14cb0-27f0-4dd3-bda6-aedf013a3d72)

**Comment by kaalleen** [comment]
Thank you for reporting your issue. Everytime you see a traceback it is a bug in Ink/Stitch.

However you'll need to rework your svg to make it usable for embroidery. You need clean outlines. Best if you redraw manually with the bezier tool.

**Comment by Paillier** [comment]
Good morning,
I just did my first try, I think I have correctly installed inkscape and inkstitch, but when I click on "parameter" in inkstitch nothing happens, I'm attaching a screenshot, it looks like parameter is empty... I don't I don't see a window opening and no point simulator appears.... can you help me, I have a French version. THANKS. Chris
![copie écran](https://github.com/inkstitch/inkstitch/assets/136691007/38391929-a9cf-4254-84a6-08bd7b289619)
![copie écran](https://github.com/inkstitch/inkstitch/assets/136691007/26a3b4b3-c8a5-4313-8b06-6fa6db3bb389)

**Comment by kaalleen** [comment]
We've some reports about similar issues #2338 
Which cpu do have?
