### ISSUE TITLE
satin: ZeroDivisionError

### ISSUE THREAD

**Issue by fourlittles** [inkstitch/inkstitch#2362]
Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.
![Uploading ts logo.svg…]()

Ink/Stitch Version: v3.0.0 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 250, in run
  File "lib/extensions/output.py", line 56, in effect
  File "lib/extensions/base.py", line 133, in elements_to_stitch_groups
  File "lib/elements/element.py", line 556, in embroider
  File "lib/elements/element.py", line 616, in validate
  File "lib/elements/satin_column.py", line 652, in validation_errors
  File "lib/elements/satin_column.py", line 1247, in to_stitch_groups
  File "lib/elements/satin_column.py", line 1021, in do_center_walk
  File "lib/debug.py", line 231, in decorated
  File "lib/elements/satin_column.py", line 971, in plot_points_on_rails
ZeroDivisionError: float division by zero

**Comment by kaalleen** [comment]
Uh, thanks. Somehow the file upload failed. Would you mind to send it again?
