### ISSUE TITLE
Satin Column: ZeroDivisionError

### ISSUE THREAD

**Issue by maggiepiwow** [inkstitch/inkstitch#2385]
Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v3.0.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\output.py", line 56, in effect
  File "lib\extensions\base.py", line 133, in elements_to_stitch_groups
  File "lib\elements\element.py", line 556, in embroider
  File "lib\elements\element.py", line 616, in validate
  File "lib\elements\satin_column.py", line 652, in validation_errors
  File "lib\elements\satin_column.py", line 1260, in to_stitch_groups
  File "lib\elements\satin_column.py", line 1088, in do_satin
  File "lib\debug.py", line 231, in decorated
  File "lib\elements\satin_column.py", line 915, in plot_points_on_rails
ZeroDivisionError: float division by zero
![medusa 6 inkscape](https://github.com/inkstitch/inkstitch/assets/137470830/10d3bc8f-def8-432a-bd3e-cb6cc4438017)

**Comment by kaalleen** [comment]
Thank you for posting your issue. We've seen this bug before, the svg is what we were still missing out. This will help us to fix the issue for the upcoming bug fix release!
