### ISSUE TITLE
Autoroute Satin: LineStrings must have at least 2 coordinate tuples

### ISSUE THREAD

**Issue by maggiepiwow** [inkstitch/inkstitch#2387]
Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v3.0.0 (windows)

Traceback (most recent call last):
  File "shapely\speedups\_speedups.pyx", line 90, in shapely.speedups._speedups.geos_linestring_from_py
AttributeError: 'list' object has no attribute '__array_interface__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\auto_satin.py", line 69, in effect
  File "lib\stitches\auto_satin.py", line 342, in auto_satin
  File "lib\stitches\auto_satin.py", line 385, in build_graph
  File "lib\stitches\auto_satin.py", line 97, in break_up
  File "lib\stitches\auto_satin.py", line 117, in center_line
  File "lib\elements\satin_column.py", line 833, in center_line
  File "shapely\geometry\linestring.py", line 47, in __init__
  File "shapely\speedups\_speedups.pyx", line 156, in shapely.speedups._speedups.geos_linestring_from_py
ValueError: LineStrings must have at least 2 coordinate tuples

![medusa 6 embroider thin inkscape](https://github.com/inkstitch/inkstitch/assets/137470830/22a5f671-ae1b-404f-baf1-6b8240c12303)

**Comment by kaalleen** [comment]
Thank you for bringing this to our attention. We need to fix this. 

... But just a little hint for your design ... If you'll try to stitch this out, it won't work very well. Satins that small will be a pain for the embroidery machine and the fabric. Consider to use running stitch instead.

**Comment by maggiepiwow** [comment]
Thank you! And yes, I realized that when test running it on some scrap fabric :/
