### ISSUE TITLE
PDF Export not working on Windows 10 with Inkstitch 3.0

### ISSUE THREAD

**Issue by Aktunbuzo** [inkstitch/inkstitch#2395]
When trying to export a pdf I get a Python error on Windows 10 and Inkstitch 3.0. I am using the Sulky Rayon color palette distributed with Inkstitch. Below is the error message:

Ink/Stitch Version: v3.0.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\print_pdf.py", line 315, in effect
  File "lib\threads\catalog.py", line 121, in ThreadCatalog
  File "lib\threads\catalog.py", line 21, in __init__
  File "lib\threads\catalog.py", line 45, in load_palettes
  File "lib\threads\palette.py", line 25, in __init__
  File "lib\threads\palette.py", line 42, in parse_palette_file
  File "codecs.py", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

**Comment by Aktunbuzo** [comment]
I have fixed this issue. Apparently, I had a gpl palette file encoded in utf-16, not utf-8. Once I saved it as utf-8 and restarted, I am now able to use the pdf export.
