### ISSUE TITLE
Circular fill: IndexError in _apply_start_end_commands

### ISSUE THREAD

**Issue by bodlygo** [inkstitch/inkstitch#2411]
Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues/new

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 726, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 921, in do_circular_fill
  File "lib\stitches\circular_fill.py", line 62, in circular_fill
  File "lib\stitches\circular_fill.py", line 106, in _apply_start_end_commands
IndexError: list index out of range

**Comment by kaalleen** [comment]
Do you still have the svg file which was causing tthe error? It would help a lot in order to fix the error.

**Comment by kaalleen** [comment]
This error might have been fixed for the next release. Without a file I can't tell for sure.
If this error shows up again with any version greater than 3.1.0 please open a new issue.
