### ISSUE TITLE
shapely.speedups ValueError

### ISSUE THREAD

**Issue by marcas-jamieson** [inkstitch/inkstitch#2414]
Traceback (most recent call last):
  File "shapely\speedups\_speedups.pyx", line 90, in shapely.speedups._speedups.geos_linestring_from_py
AttributeError: 'list' object has no attribute '__array_interface__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\troubleshoot.py", line 29, in effect
  File "lib\elements\satin_column.py", line 443, in validation_errors
  File "lib\elements\satin_column.py", line 253, in rails
  File "lib\elements\satin_column.py", line 253, in <listcomp>
  File "lib\elements\satin_column.py", line 329, in rail_indices
  File "lib\elements\satin_column.py", line 329, in <listcomp>
  File "shapely\geometry\linestring.py", line 46, in __init__
  File "shapely\speedups\_speedups.pyx", line 156, in shapely.speedups._speedups.geos_linestring_from_py
ValueError: LineStrings must have at least 2 coordinate tuples

![beast in black](https://github.com/inkstitch/inkstitch/assets/138801596/7454ac57-772f-4335-970e-dabbed86ce97)

**Comment by kaalleen** [comment]
Which Ink/Stitch version do you you on which operating system?
