### ISSUE TITLE
autofill: NetworkXNoPath

### ISSUE THREAD

**Issue by karmavibe** [inkstitch/inkstitch#2415]
Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 729, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 781, in do_auto_fill
  File "lib\debug.py", line 231, in decorated
  File "lib\stitches\auto_fill.py", line 80, in auto_fill
  File "lib\debug.py", line 231, in decorated
  File "lib\stitches\auto_fill.py", line 671, in path_to_stitches
  File "lib\stitches\auto_fill.py", line 632, in travel
  File "networkx\classes\backends.py", line 148, in wrapper
  File "networkx\algorithms\shortest_paths\generic.py", line 173, in shortest_path
  File "networkx\algorithms\shortest_paths\weighted.py", line 2398, in bidirectional_dijkstra
networkx.exception.NetworkXNoPath: No path between (119.29600279260805, 92.59842519685107) and (119.78851034867569, 92.95059841640808).

**Comment by kaalleen** [comment]
Could you post your svg?
It is possible, that your svg has paths which are not suited for embroidery (many  small holes or a lot of small sharp edges). In that case you may want to simplify your svg.

**Comment by kaalleen** [comment]
Closing in favor of  #2056 which has an svg file
