### ISSUE TITLE
Lettering: SetSelection TypeError

### ISSUE THREAD

**Issue by Psim0n** [inkstitch/inkstitch#2429]
Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\lettering.py", line 494, in effect
  File "lib\extensions\lettering.py", line 101, in __init__
  File "lib\extensions\lettering.py", line 130, in apply_settings
TypeError: Choice.SetSelection(): argument 1 has unexpected type 'DotDict'
![Dream Duds Label Pyjamasaurus Rex Size 3T](https://github.com/inkstitch/inkstitch/assets/139928103/73b84f45-1c4e-4535-8107-110106ebccbd)

**Comment by lexelby** [comment]
Well, that shouldn't happen!  Thank you for the bug report, we'll check it out.

**Comment by kaalleen** [comment]
There is no Ink/Stitch lettering in your file only manual stitches.
Do you remember what you did before the error showed up?
Were you creating a new text? Did you select a special trim option, etc.

**Comment by kaalleen** [comment]
Closing. Method has been reworked since this error report.
