### ISSUE TITLE
Unexpected error:  invalid literal for int() with base 10: 'contour_fill'

### ISSUE THREAD

**Issue by skippyee** [inkstitch/inkstitch#2432]
This error comes up when I try to run params for this svg:
![svg](https://github.com/inkstitch/inkstitch/assets/140133048/bd639fc7-aa63-4e8c-8438-6196ee88aa2b)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\params.py", line 721, in effect
  File "lib\extensions\params.py", line 432, in __init__
  File "lib\extensions\params.py", line 700, in create_tabs
  File "lib\extensions\params.py", line 82, in __init__
  File "lib\extensions\params.py", line 349, in __do_layout
ValueError: invalid literal for int() with base 10: 'contour_fill'

**Comment by skippyee** [comment]
closing - updating inkstitch to the most recent release fixed this
