### ISSUE TITLE
fill_stitch: AttributeError: 'LineString' object has no attribute 'geoms'

### ISSUE THREAD

**Issue by RO021093** [inkstitch/inkstitch#2433]
Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 231, in run
  File "lib/extensions/output.py", line 56, in effect
  File "lib/extensions/base.py", line 200, in elements_to_stitch_groups
  File "lib/elements/element.py", line 329, in embroider
  File "lib/elements/element.py", line 387, in validate
  File "lib/elements/fill_stitch.py", line 321, in validation_errors
  File "lib/elements/fill_stitch.py", line 274, in shape
AttributeError: 'LineString' object has no attribute 'geoms'

For the last week I've had intermittent issues saving my SVG files as .PES files 
![Untitled 21_adobe_express](https://github.com/inkstitch/inkstitch/assets/140174683/c3a2c5aa-5e09-407a-bcf6-b936ff9690b4)

**Comment by lexelby** [comment]
What version of Ink/Stitch at you running?

**Comment by RO021093** [comment]
Ink/stitch v2.2.0 (osx)

**Comment by RO021093** [comment]
> What version of Ink/Stitch at you running?

Ink/stitch v2.2.0 (osx)

**Comment by kaalleen** [comment]
You may want to update to 3.0.1 The issue should be fixed.
With the new version also try to run Troubleshoot > Cleanup document to remove small elements from your document (path1363).

For a nicer stitchout you also could have a look at satin columns, which are better suited for the outline. Also some of the shapes (e.g. one of the eyes) aren't well prepared for embroidery.
