### ISSUE TITLE
parse_command: IndexError

### ISSUE THREAD

**Issue by EddieNereid** [inkstitch/inkstitch#2434]
I've been trying to create a custom satin stitch column and every time I try opening the params menu I get this error message. It happens for trying to open params for other objects too. It's just this file that it's happening with, I'm not sure what I've done differently to other files I've made.

Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\params.py", line 721, in effect
  File "lib\extensions\params.py", line 432, in __init__
  File "lib\extensions\params.py", line 684, in create_tabs
  File "lib\extensions\params.py", line 614, in get_nodes_by_class
  File "lib\extensions\base.py", line 182, in get_nodes
  File "lib\extensions\base.py", line 168, in descendants
  File "lib\extensions\base.py", line 168, in descendants
  File "lib\extensions\base.py", line 168, in descendants
  File "lib\extensions\base.py", line 141, in descendants
  File "lib\elements\element.py", line 289, in has_command
  File "lib\elements\element.py", line 285, in get_commands
  File "lib\elements\element.py", line 281, in commands
  File "lib\commands.py", line 187, in find_commands
  File "lib\commands.py", line 115, in __init__
  File "lib\commands.py", line 125, in parse_command
IndexError: list index out of range

Ink/Stitch Version: v2.2.0 (windows)

![Hi I'm a delight](https://github.com/inkstitch/inkstitch/assets/140246910/6e4c5823-9526-4e6e-ac45-7196bb50301f)

**Comment by bianchifan** [comment]
Your problem seems to depend on your used font. Making all letters invisible it works.
Making all letter invisible but only one the error message turns up.
Try to use another font until the font specialists will find a better solution.

**Comment by kaalleen** [comment]
This is still happening with v3.0.1 !

**Comment by kaalleen** [comment]
Looks like the commands have been transformed into paths at some point. And one of the connectors lost path information.
To fix the error in your file, you can go ahead and simply remove all the commands through troubleshoot > remove embroidery settings > remove commands
