### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by jarhart53** [inkstitch/inkstitch#2446]
Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\output.py", line 57, in effect
  File "lib\stitch_plan\stitch_plan.py", line 46, in stitch_groups_to_stitch_plan
  File "lib\threads\color.py", line 76, in __ne__
  File "lib\threads\color.py", line 70, in __eq__
  File "lib\threads\color.py", line 36, in __init__
TypeError: 'NoneType' object is not iterable

![FINAL_BEAR](https://github.com/inkstitch/inkstitch/assets/140536914/4f747935-5ff9-437d-ba3d-a1c898febb9d)

**Comment by kaalleen** [comment]
Thank you for reporting the error. This has been fixed already for the next release. But to get it working with the current release you will have to reapply the colors to the black elements.
For better embroidery you may want to switch stitch types for some of them as well.
