### ISSUE TITLE
Circular Fill: networkx.exception.NetworkXNoPath on dev build

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#2452]
I'm running https://github.com/inkstitch/inkstitch/releases/tag/dev-build-bkmgit-remove-stringcase-dependency (though it also happened on lexelby's satins release) and it's throwing an error in a circular fill: the black part of these eyes, which have the white circles cut out of them. It does fine on the preview but fails on saving the stitch file.

![BadEyes](https://github.com/inkstitch/inkstitch/assets/9473609/97c8fb9c-8d9f-491d-9086-4a51cf04b6fd)

```Ink/Stitch Version: remove-stringcase-dependency (linux)

Traceback (most recent call last):
  File "lib/elements/fill_stitch.py", line 725, in to_stitch_groups
  File "lib/elements/fill_stitch.py", line 920, in do_circular_fill
  File "lib/stitches/circular_fill.py", line 81, in circular_fill
  File "lib/stitches/circular_fill.py", line 147, in path_to_stitches
  File "lib/stitches/auto_fill.py", line 634, in travel
  File "networkx/classes/backends.py", line 148, in wrapper
  File "networkx/algorithms/shortest_paths/generic.py", line 173, in shortest_path
  File "networkx/algorithms/shortest_paths/weighted.py", line 2398, in bidirectional_dijkstra
networkx.exception.NetworkXNoPath: No path between (212.2426216523613, 99.02826252770741) and (217.80560875071149, 96.94003822030639).
```

(aside: it would be cool if we could specify the center of the circular fill. I tried using it on "🫠" and it woulda been cool if the circle centered on the face)

**Comment by kaalleen** [comment]
This can be prevented when you manually set an end point to the fill. This shouldn't happen though of course, so, thank you for the file!

In fact you can set the center point for circular fills: https://inkstitch.org/docs/stitches/circular-fill/#set-spiral-center

**Comment by tyrosinase** [comment]
Oh, it didn't occur to me to look in comments. That makes much more sense than trying to do coordinates in Params. (It probably got discussed here but I was very much not paying close attention during the move.)

Having some text to that effect appear in the Params dialog would help there, I think.

**Comment by kaalleen** [comment]
Let's keep that in mind when we design a new gui system :)
