### ISSUE TITLE
Save a Copy: AssertionError: too many color changes, (11986) out of bounds (0, 255)

### ISSUE THREAD

**Issue by TiliaCorda** [inkstitch/inkstitch#2458]
File - Save a Copy
Select ZIP
Check all file format 
wait for 5 minutes 

Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\zip.py", line 68, in effect
  File "lib\output.py", line 109, in write_embroidery_file
  File "pyembroidery\EmbPattern.py", line 1727, in static_write
  File "pyembroidery\EmbPattern.py", line 1644, in write_embroidery
  File "pyembroidery\PecWriter.py", line 32, in write
  File "pyembroidery\PecWriter.py", line 40, in write_pec
  File "pyembroidery\PecWriter.py", line 64, in write_pec_header
AssertionError: too many color changes, (11986) out of bounds (0, 255)

Maybe the _Desity Map_ function is the problem?
![satoshi-szobor-simple-v1](https://github.com/inkstitch/inkstitch/assets/63737882/122c2207-e8f7-487b-9946-cd326f9298a0)

**Comment by lexelby** [comment]
I'm not sure what happened here -- the design looks fairly simple, but hidden in there are almost 12000 color changes.  That means that in your SVG, when Ink/Stitch processes objects in order, the object color is different from one object to the next.  It also means that there are 12,000 objects in your SVG!

Something has gone wrong here, and that's why Ink/Stitch blew up.

**Comment by kaalleen** [comment]
Let's add a ignore layer command to the density map. Nobody will ever want (or be able) to stitch it out.
