### ISSUE TITLE
"an unexpected error"

### ISSUE THREAD

**Issue by linneakcruz** [inkstitch/inkstitch#2459]
Ink/Stitch Version: v3.0.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\output.py", line 56, in effect
  File "lib\extensions\base.py", line 133, in elements_to_stitch_groups
  File "lib\elements\element.py", line 556, in embroider
  File "lib\elements\element.py", line 616, in validate
  File "lib\elements\satin_column.py", line 652, in validation_errors
  File "lib\elements\satin_column.py", line 1260, in to_stitch_groups
  File "lib\elements\satin_column.py", line 1088, in do_satin
  File "lib\debug.py", line 231, in decorated
  File "lib\elements\satin_column.py", line 915, in plot_points_on_rails
ZeroDivisionError: float division by zero

![verse](https://github.com/inkstitch/inkstitch/assets/43259389/2316d904-8b90-4e23-b0ba-480959712e7e)

**Comment by kaalleen** [comment]
There has been an update to Ink/Stitch v 3.0.1 
It should fix your issue.
