### ISSUE TITLE
Can't save .pes file 

### ISSUE THREAD

**Issue by hgadams** [inkstitch/inkstitch#2462]
Hi all, 

I have an .svg file open in Inkscape, which I'm trying to scale smaller (width of 6 inches) and save as a .pes.   I am able to save the file as a .pes when the width is 12 inches, but for some reason when I scale the width down to 6 inches I get the following error:

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 231, in run
  File "lib/extensions/output.py", line 56, in effect
  File "lib/extensions/base.py", line 200, in elements_to_stitch_groups
  File "lib/elements/element.py", line 329, in embroider
  File "lib/elements/element.py", line 387, in validate
  File "lib/elements/fill_stitch.py", line 321, in validation_errors
  File "lib/elements/fill_stitch.py", line 274, in shape
AttributeError: 'LineString' object has no attribute 'geoms'

Any ideas how to fix this issue? TIA. 
![Embroiderysmall](https://github.com/inkstitch/inkstitch/assets/141383183/87b7bde1-ff45-4250-91df-8d2f9911f4c8)

**Comment by kaalleen** [comment]
Do you use Ink/Stitch v 3.0.1?

To have a nice stitch out, this design will need some more work. The font for example would look nicer as a satin. You could also have a look through the font library to see which font fits best and adapt it to your needs https://inkstitch.org/fonts/font-library/

**Comment by kaalleen** [comment]
This is supposed to be fixed with the newest version of Ink/Stitch. Therefore I'll close this issue. Please open a new issue, if this is still a problem with the current release.
