### ISSUE TITLE
Can't save my file

### ISSUE THREAD

**Issue by DiversLou** [inkstitch/inkstitch#2467]
There is what pops up on my screen when I try to save my document:

Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v3.0.1 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 250, in run
  File "lib/extensions/output.py", line 57, in effect
  File "lib/stitch_plan/stitch_plan.py", line 46, in stitch_groups_to_stitch_plan
  File "lib/threads/color.py", line 76, in __ne__
  File "lib/threads/color.py", line 70, in __eq__
  File "lib/threads/color.py", line 36, in __init__
TypeError: 'NoneType' object is not iterable

What to do?
![DIVERÇITY](https://github.com/inkstitch/inkstitch/assets/141699486/348b5afb-3427-4e55-be35-063e136059e0)

**Comment by bianchifan** [comment]
You may have a closer look to your "F", the black "triangle on the inner bow cannot be processed, you should remove it - path4938.

**Comment by Marif91** [comment]
Plusieurs chemins ont un contour ou un fond "indéfini", il faut mettre une couleur ou signaler qu'il n'y en a aucune.
