### ISSUE TITLE
TopologyException: side location conflict

### ISSUE THREAD

**Issue by isobelKeen** [inkstitch/inkstitch#2472]
Hi all,
I'm trying to Break Apart Fill Objects for a shape that's been traced from a photo and I'm getting this error.
hapely.geos - ERROR - TopologyException: side location conflict at 1417.0741999999996 382.64060000000006. This can occur if the input geometry is invalid.

Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: 3.0.1 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 231, in run
  File "lib/extensions/break_apart.py", line 56, in effect
  File "lib/extensions/break_apart.py", line 90, in combine_overlapping_polygons
  File "lib/extensions/break_apart.py", line 90, in combine_overlapping_polygons
  File "lib/extensions/break_apart.py", line 90, in combine_overlapping_polygons
  [Previous line repeated 4 more times]
  File "lib/extensions/break_apart.py", line 81, in combine_overlapping_polygons
  File "shapely/geometry/base.py", line 809, in overlaps
  File "shapely/predicates.py", line 18, in __call__
  File "shapely/topology.py", line 42, in _check_topology
  File "shapely/predicates.py", line 15, in __call__
  File "shapely/geos.py", line 610, in errcheck_predicate
shapely.errors.PredicateError: Failed to evaluate <_FuncPtr object at 0x1245c8d00>

**Comment by kaalleen** [comment]
Uh, interesting. What is your macOS version?
Would you mind to share your svg file?
If you don't want to post it publicly I can share a link where you can send it to our developers only.

**Comment by kaalleen** [comment]
No further response. Closing, it refers to an older Ink/Stitch version. Please open a new issue if the problem shows up again. In that case a svg file would be most helpful to fix the bug.
