### ISSUE TITLE
Unexpected error in InkStitch

### ISSUE THREAD

**Issue by cmhammond65** [inkstitch/inkstitch#2474]
nk/Stitch Version: v3.0.1 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 250, in run
  File "lib/extensions/troubleshoot.py", line 33, in effect
  File "lib/elements/satin_column.py", line 652, in validation_errors
  File "lib/elements/satin_column.py", line 1262, in to_stitch_groups
  File "lib/elements/satin_column.py", line 1090, in do_satin
  File "lib/debug.py", line 231, in decorated
  File "lib/elements/satin_column.py", line 898, in plot_points_on_rails
  File "lib/elements/satin_column.py", line 629, in flattened_sections
  File "lib/elements/satin_column.py", line 629, in <listcomp>
IndexError: tuple index out of range
![Louella Butterfly](https://github.com/inkstitch/inkstitch/assets/142117357/44f0fb62-833d-41fa-a77d-079b8b086e08)

**Comment by Marif91** [comment]
Menu Inkstitch-Résolution de problèmes- Dépistage...
