### ISSUE TITLE
Unexpected error - unable to save SVG as PES

### ISSUE THREAD

**Issue by reaganostdiek** [inkstitch/inkstitch#2475]
Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v2.2.0 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 231, in run
  File "lib/extensions/output.py", line 56, in effect
  File "lib/extensions/base.py", line 200, in elements_to_stitch_groups
  File "lib/elements/element.py", line 329, in embroider
  File "lib/elements/element.py", line 387, in validate
  File "lib/elements/fill_stitch.py", line 321, in validation_errors
  File "lib/elements/fill_stitch.py", line 274, in shape
AttributeError: 'LineString' object has no attribute 'geoms'
![GrandPrismaticSpring_5x7](https://github.com/inkstitch/inkstitch/assets/142118400/44a921f0-463d-4fe6-955a-a17b5dc90a83)

**Comment by Marif91** [comment]
Menu Extensions-Inkstitch-Résolution de Problèmes- Dépistage.
Ce motif comporte des formes beaucoup trop petites et des lignes qui se croisent.

Installer inkstitch 3.0.1 et Nettoyer le document !

**Comment by kaalleen** [comment]
An update to version 3.0.1 would solve the error (as marif91 said). For a nice stitch out it would need some more work though.
