### ISSUE TITLE
Don't know what this means, but I can't troubleshoot my .dst file

### ISSUE THREAD

**Issue by pideystitches** [inkstitch/inkstitch#2487]
I'm not a programmer.  I have no idea what's going on here and I hope someone with much better chops than I have can let me know what to do.  I can't run the visualizer and I can't troubleshoot this.  The same error comes up with visualizer, troubleshoot and when I try to save as .dst.  Thank you, any and all who can help this hopeless n00b.  :-)

Ink/Stitch Version: 3.0.1 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 231, in run
  File "lib/extensions/troubleshoot.py", line 33, in effect
  File "lib/elements/satin_column.py", line 652, in validation_errors
  File "lib/elements/satin_column.py", line 1262, in to_stitch_groups
  File "lib/elements/satin_column.py", line 1090, in do_satin
  File "lib/debug.py", line 231, in decorated
  File "lib/elements/satin_column.py", line 898, in plot_points_on_rails
  File "lib/elements/satin_column.py", line 629, in flattened_sections
  File "lib/elements/satin_column.py", line 629, in <listcomp>
IndexError: tuple index out of range

![DM patch for stitchout](https://github.com/inkstitch/inkstitch/assets/142741456/42a7f815-47ce-4328-909d-9d48332a0c1c)

**Comment by bianchifan** [comment]
It seems that you have accidently uncombined some satin letters.
For example path2971-1-5 thru line2981-6-3 should be combined and defined as satin.
But they are all single lines with start position and trim command defined internally as satin.

There is a lot of mismatch in you svg.

**Comment by kaalleen** [comment]
Closing since this should be fixed in current development releases.
This error is a bit annoying and will be the one that is posted the most until the next release.

I haven't had a look at your file, but most commonly this is caused, when on a selection of strokes and satins the satin param is applied. It will also apply on the simple strokes which then will cause the error.
