### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by jjSkwirl** [inkstitch/inkstitch#2496]
I'm new to Ink/Stitch.  I figured I'd copy/paste my most recent crash.  I really don't know what is happening.
Here's what the popup notice wrote:
![test](https://github.com/inkstitch/inkstitch/assets/143758123/246215e3-03f0-4ea9-821f-3e5b93fba75d)

Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\troubleshoot.py", line 33, in effect
  File "lib\elements\satin_column.py", line 652, in validation_errors
  File "lib\elements\satin_column.py", line 1249, in to_stitch_groups
  File "lib\elements\satin_column.py", line 1023, in do_center_walk
  File "lib\debug.py", line 231, in decorated
  File "lib\elements\satin_column.py", line 898, in plot_points_on_rails
  File "lib\elements\satin_column.py", line 629, in flattened_sections
  File "lib\elements\satin_column.py", line 629, in <listcomp>
IndexError: tuple index out of range

**Comment by kaalleen** [comment]
Thank you for your error report, The issue has been fixed in current development releases.
If you'd like to test, here is a link: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kall-test

**Comment by kaalleen** [comment]
Closing. This issue is supposed to be fixed in main. Please open a new issue, if this still shows up in a newer version of Ink/Stitch.
