### ISSUE TITLE
Unexpected error when saving to .exp file

### ISSUE THREAD

**Issue by Ampsters** [inkstitch/inkstitch#2500]
Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\troubleshoot.py", line 33, in effect
  File "lib\elements\satin_column.py", line 652, in validation_errors
  File "lib\elements\satin_column.py", line 1262, in to_stitch_groups
  File "lib\elements\satin_column.py", line 1090, in do_satin
  File "lib\debug.py", line 231, in decorated
  File "lib\elements\satin_column.py", line 898, in plot_points_on_rails
  File "lib\elements\satin_column.py", line 629, in flattened_sections
  File "lib\elements\satin_column.py", line 629, in <listcomp>
IndexError: tuple index out of range

![Mountain Rescue Badges Berg](https://github.com/inkstitch/inkstitch/assets/143990627/07e58a93-0e73-4693-bdf5-b92855dd6c36)

**Comment by kaalleen** [comment]
Your supposed to be running stitches in the PMB lettering section do have a satin column setting. It should work fine, when you revert those to running stitches.

For the next Ink/Stitch version this issue has been fixed. Sorry for your trouble.

**Comment by kaalleen** [comment]
Btw. the edges of your outlines won't look nice. When this is the result of converting line to satin columns, you may want to break your line at a straight segment first, before you run the converter. This will give a much better result.

**Comment by kaalleen** [comment]
Closing, since this should be fixed in the main branch.
