### ISSUE TITLE
PecReader: TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

### ISSUE THREAD

**Issue by kaythought** [inkstitch/inkstitch#2506]
Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "lib/extensions/input.py", line 22, in run
  File "lib/stitch_plan/generate_stitch_plan.py", line 22, in generate_stitch_plan
  File "pyembroidery/EmbPattern.py", line 1560, in static_read
  File "pyembroidery/EmbPattern.py", line 1493, in read_embroidery
  File "pyembroidery/PesReader.py", line 67, in read
  File "pyembroidery/PecReader.py", line 26, in read_pec
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

**Comment by kaalleen** [comment]
Would you mind to send the file which is causing the error? That'd be really helpful.

**Comment by kaalleen** [comment]
Closing in favor of #3041 (still no file received)
