### ISSUE TITLE
Params wont open and Troubleshoot not working

### ISSUE THREAD

**Issue by nurelleH** [inkstitch/inkstitch#2512]
Was working fine and then suddenly stopped working when I was creating a satin column. But params will not open on anything now and troubleshoot gives this error message

 Ink/Stitch Version: v3.0.1 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 250, in run
  File "lib/extensions/troubleshoot.py", line 47, in effect
  File "src/lxml/etree.pyx", line 961, in lxml.etree._Element.remove
ValueError: Element is not a child of this node.

**Comment by kaalleen** [comment]
Do you have the chance to upload the svg (you may reduce it to that satin column - if the error persists)?

**Comment by kaalleen** [comment]
This error should be solved by now.
Please oopen a new issue, when it shows up again in any Ink/Stitch version greater than 3.1.0
