### ISSUE TITLE
satin_column: IndexError: tuple index out of range

### ISSUE THREAD

**Issue by mexc22** [inkstitch/inkstitch#2514]
nk/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\troubleshoot.py", line 33, in effect
  File "lib\elements\satin_column.py", line 652, in validation_errors
  File "lib\elements\satin_column.py", line 1262, in to_stitch_groups
  File "lib\elements\satin_column.py", line 1090, in do_satin
  File "lib\debug.py", line 231, in decorated
  File "lib\elements\satin_column.py", line 898, in plot_points_on_rails
  File "lib\elements\satin_column.py", line 629, in flattened_sections
  File "lib\elements\satin_column.py", line 629, in <listcomp>
IndexError: tuple index out of range

![Teufel (3)](https://github.com/inkstitch/inkstitch/assets/15876028/7e68d0fa-8a5f-4cea-b5f8-d07f2412bfdd)

**Comment by kaalleen** [comment]
You have applied satin columns to some single subpath objects. Satin columns do not work on a single path. The next Ink/Stitch version will ignore the satin column setting and will render them as running stitches.

To solve the issue for your file with the current official release, run `select embroidery elements` under `Extensions > Ink/Stitch > Edit` and make it select satin columns. Then open the params panel and apply a running stitch.

Since these objects also have a fill color, you could also consider to remove the stroke color. It is not really a good idea to have a stroke and a fill on the very same object. If you need both, you could also duplicate the object and have one version as the fill and an other as the stroke. The one with the stroke may need adjustment for the pull and push the fill will perform on the fabric.
