### ISSUE TITLE
Circular fill gets NetworkXNoPath

### ISSUE THREAD

**Issue by lou15123** [inkstitch/inkstitch#2516]
I was trying to save as a .pes in order to go embroider.
---
Ink/Stitch Version: v3.0.1 (osx)

Traceback (most recent call last):
  File "lib/elements/fill_stitch.py", line 726, in to_stitch_groups
  File "lib/elements/fill_stitch.py", line 921, in do_circular_fill
  File "lib/stitches/circular_fill.py", line 81, in circular_fill
  File "lib/stitches/circular_fill.py", line 147, in path_to_stitches
  File "lib/stitches/auto_fill.py", line 632, in travel
  File "networkx/classes/backends.py", line 148, in wrapper
  File "networkx/algorithms/shortest_paths/generic.py", line 173, in shortest_path
  File "networkx/algorithms/shortest_paths/weighted.py", line 2398, in bidirectional_dijkstra
networkx.exception.NetworkXNoPath: No path between (14.97302839757158, 186.50107894809332) and (4.081889763779512, 179.42012489467146).
![culturalcenterlogo2_optimized](https://github.com/inkstitch/inkstitch/assets/145283631/40308654-32cf-4296-9874-8e5eb4b720bf)

**Comment by tyrosinase** [comment]
For those outer circles, you're going to want to turn them into a satin stitch instead of a circular fill. That said, it should give you a message rather than throwing an error.

Meanwhile, I'm getting the same thing in a pre-release: Ink/Stitch Version: preferences-title (linux)

It's an odd small shape, and mirroring it vertically makes it work. (Or at least save without an error. I'm probably overoptimistic about it actually working in the physical stitchout.)

![ShrampyBad](https://github.com/inkstitch/inkstitch/assets/9473609/7accc8a6-d999-4ad6-b51c-7a7881c873b8)
