### ISSUE TITLE
Unable to use contour fill in v3.0.1

### ISSUE THREAD

**Issue by kryspetrie** [inkstitch/inkstitch#2518]
Ink/Stitch Version: v3.0.1 (osx)

Traceback (most recent call last):
  File "lib/elements/fill_stitch.py", line 720, in to_stitch_groups
  File "lib/elements/fill_stitch.py", line 817, in do_contour_fill
  File "lib/stitches/contour_fill.py", line 519, in single_spiral
  File "lib/stitches/contour_fill.py", line 531, in _spiral_fill
  File "lib/stitches/contour_fill.py", line 581, in _make_spiral
UnboundLocalError: local variable 'spiral_part' referenced before assignment

**Comment by kaalleen** [comment]
This error should be fixed in newer development branches. You can try them out if you like.

**Comment by Kayc1985** [comment]
> This error should be fixed in newer development branches. You can try them out if you like.

How can I find them 
I'm unable to use any of the edit elements it keeps giving me an black box with error

**Comment by kaalleen** [comment]
You could try for example this one here: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kall-test
