### ISSUE TITLE
Wont save a DST File

### ISSUE THREAD

**Issue by MovieMan1985** [inkstitch/inkstitch#2519]
hi i am trying to make an image that i have as a svg file convert it to a dst file but i says it wont save because of this message or error 

Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v3.0.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\output.py", line 56, in effect
  File "lib\extensions\base.py", line 133, in elements_to_stitch_groups
  File "lib\elements\element.py", line 565, in embroider
![float2](https://github.com/inkstitch/inkstitch/assets/144575835/948d77ca-d187-4d01-be73-21590edbe4fc)

**Comment by kaalleen** [comment]
I believe this could be fixed in the latest release. Could you try to update to 3.0.1?
