### ISSUE TITLE
Error Message when trying to save as  InkStitch EXP file

### ISSUE THREAD

**Issue by ambrobri12** [inkstitch/inkstitch#2524]
Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\output.py", line 57, in effect
  File "lib\stitch_plan\stitch_plan.py", line 35, in stitch_groups_to_stitch_plan
  File "lib\stitch_plan\stitch_plan.py", line 115, in new_color_block
  File "lib\stitch_plan\color_block.py", line 16, in __init__
  File "lib\stitch_plan\color_block.py", line 51, in color
  File "lib\threads\color.py", line 36, in __init__
TypeError: 'NoneType' object is not iterable

![Bay View Landscape no tagline black 9 24](https://github.com/inkstitch/inkstitch/assets/145942266/b602af4c-35ba-44c0-9145-55ddcfbbbff2)

**Comment by kaalleen** [comment]
Which Ink/Stitch version do you use (info available in Extensions > Ink/Stitch > About)?
If it is not 3.0.1, try to update Ink/Stitch.

**Comment by kaalleen** [comment]
Closing in favor of #2562 which indicates that this is happening with 3.0.1 on windows.

**Comment by kaalleen** [comment]
Issue has been fixed in current main.
