### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by ThaslimaShafi** [inkstitch/inkstitch#2526]
Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "lib\extensions\input.py", line 22, in run
  File "lib\stitch_plan\generate_stitch_plan.py", line 22, in generate_stitch_plan
  File "pyembroidery\EmbPattern.py", line 1560, in static_read
  File "pyembroidery\EmbPattern.py", line 1493, in read_embroidery
  File "pyembroidery\PesReader.py", line 67, in read
  File "pyembroidery\PecReader.py", line 26, in read_pec
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

**Comment by ThaslimaShafi** [comment]
Can we convert svg file to pes format..?

**Comment by kaalleen** [comment]
You should be able to save a svg file into pes format, yes. You may need to alter some path to work well with embroidery though.

But it seems as if you fail to open a pec file?

**Comment by kaalleen** [comment]
If we could see the pec file that would be great (if possible). If you need to send it privately I can provide a link for that too.

**Comment by ThaslimaShafi** [comment]
Yes I'm unable to open a pec file.
What can I do?

**Comment by kaalleen** [comment]
It is a bug in Ink/Stitch that we need to fix. But until now we haven't received a file which is causing the error.
So this would be very helpful if we get a file from you.

You can do one of the following:
* Zip the file and upload it here
* Or if there are license issues upload it to https://lexneva.name/owncloud/index.php/s/NCcJbJqnKmL7nES
