### ISSUE TITLE
satin_column: IndexError: tuple index out of range

### ISSUE THREAD

**Issue by ByBettyB** [inkstitch/inkstitch#2537]
Hello, 

I really just started to involve in InkStitch to create my own embroderies. When I start parameter simulation, everything works well. But when I want to start realistic simulation, this does not work, as well as the export. Can you please help with this error message?

Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\troubleshoot.py", line 33, in effect
  File "lib\elements\satin_column.py", line 652, in validation_errors
  File "lib\elements\satin_column.py", line 1262, in to_stitch_groups
  File "lib\elements\satin_column.py", line 1090, in do_satin
  File "lib\debug.py", line 231, in decorated
  File "lib\elements\satin_column.py", line 898, in plot_points_on_rails
  File "lib\elements\satin_column.py", line 629, in flattened_sections
  File "lib\elements\satin_column.py", line 629, in <listcomp>
IndexError: tuple index out of range

**Comment by ByBettyB** [comment]
![Inkscape Logo Error](https://github.com/inkstitch/inkstitch/assets/146827859/70e62287-f1ca-4a17-b2d0-bb291961805d)

**Comment by bianchifan** [comment]
It should be a problem with with the actual version.
Your "AutoSatin Running Stitches " won'T be interpreted as runnin' stitches but as satins.
Looking at the params shows the method runnin' indeed, but the param "Running stitch along paths" isn't checked!
![Bildschirmfoto vom 2023-10-03 16-12-26](https://github.com/inkstitch/inkstitch/assets/17491743/21fd5ae8-5a84-4855-9338-421f5677b747)
So all your AutoSatin runs are SATIN_COLUMMNs!!!
![Bildschirmfoto vom 2023-10-03 16-14-35](https://github.com/inkstitch/inkstitch/assets/17491743/ec60c785-1c4a-4fff-ac74-6cfc1a4541d0)

BTW..
You do not need to interupt your "B", you can stitch it over, just one way.
I'm shure it will work and look nice.
And perhaps you will like an underlay...

**Comment by kaalleen** [comment]
Closing as it is fixed in current tdevelopment branches
