### ISSUE TITLE
fill: Multi-part geometries do not provide a coordinate sequence

### ISSUE THREAD

**Issue by edytovar** [inkstitch/inkstitch#2549]
Failed on  path1: Error during autofill! This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues/new

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 714, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 759, in do_underlay
  File "lib\debug.py", line 231, in decorated
  File "lib\stitches\auto_fill.py", line 78, in auto_fill
  File "lib\debug.py", line 231, in decorated
  File "lib\stitches\auto_fill.py", line 315, in build_travel_graph
  File "lib\stitches\auto_fill.py", line 452, in build_travel_edges
  File "lib\stitches\auto_fill.py", line 410, in travel_grating
  File "lib\stitches\fill.py", line 155, in intersect_region_with_grating
  File "shapely\geometry\base.py", line 960, in coords
NotImplementedError: Multi-part geometries do not provide a coordinate sequence

![bounce11](https://github.com/inkstitch/inkstitch/assets/45248568/42db7dbc-d42f-435a-a5cc-ed25e61c7194)

**Comment by tyrosinase** [comment]
You've got a ways to go before you're ready to generate a stitch file from that shape. There's a tutorial at https://silverseams.com/tutorials/digitizing-outlined-graphics.html that will get you on your way.

**Comment by kaalleen** [comment]
As @tyrosinase said, this needs to be better prepared for embroidery. Still we want to avoid to display messages like this. We definitely need to fix the code for this one. So we are grateful for your error report :)

I will change the title. But want to remember: error on black outline
