### ISSUE TITLE
Inkstitch isn't working

### ISSUE THREAD

**Issue by samlee1489** [inkstitch/inkstitch#2553]
Every time I tried using the Inkstitch simulator, the design won't load. When I try to save the file as a PES file on my flash drive, it says it can't and to troubleshoot objects to correct errors. When I go to Troubleshoot, this message pops up - - - -

Ink/Stitch Version: v3.0.1 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 250, in run
  File "lib/extensions/troubleshoot.py", line 33, in effect
  File "lib/elements/satin_column.py", line 652, in validation_errors
  File "lib/elements/satin_column.py", line 1262, in to_stitch_groups
  File "lib/elements/satin_column.py", line 1090, in do_satin
  File "lib/debug.py", line 231, in decorated
  File "lib/elements/satin_column.py", line 898, in plot_points_on_rails
  File "lib/elements/satin_column.py", line 629, in flattened_sections
  File "lib/elements/satin_column.py", line 629, in <listcomp>
IndexError: tuple index out of range

File - - - 
![AllTooWell](https://github.com/inkstitch/inkstitch/assets/147952284/7ffa968a-857b-4ffc-8fe9-43bd6c6e3f06)

**Comment by kaalleen** [comment]
That's an annoying error in the current release. This usually happens when a running stitch has a satin column param. This in turn happens, when you select a group of satins and running stitches and apply the satin params to it.

Here the (hopefully) fixed file
![2553-corrected](https://github.com/inkstitch/inkstitch/assets/36401965/8c1d53e0-a672-44f6-bd8d-be7aba164405)

**Comment by samlee1489** [comment]
Thank you! So should I just not group the running and satin stitches together? Samantha LeeOn Oct 15, 2023, at 2:28 AM, Kaalleen ***@***.***> wrote:﻿
That's an annoying error in the current release. This usually happens when a running stitch has a satin column param. This in turn happens, when you select a group of satins and running stitches and apply the satin params to it.
Here the (hopefully) fixed file

**Comment by kaalleen** [comment]
You just have to ensure, that only satins are selected when you apply satin params, no need to avoid grouping.
