### ISSUE TITLE
contour_fill: Index out of bounds

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#2560]
Ooh, I got a new one!

Trying to save as a JEF, got this (followed by a "could not be saved.")

Can't remember where to send the SVG, so holler if you need it.

```Ink/Stitch Version: remove-empty-groups (linux)

Traceback (most recent call last):
  File "lib/elements/element.py", line 594, in handle_unexpected_exceptions
  File "lib/elements/element.py", line 562, in embroider
  File "lib/elements/fill_stitch.py", line 715, in to_stitch_groups
  File "lib/elements/fill_stitch.py", line 793, in do_contour_fill
  File "lib/stitches/contour_fill.py", line 148, in offset_polygon
  File "lib/stitches/contour_fill.py", line 203, in _convert_polygon_to_nodes
  File "shapely/geometry/polygon.py", line 346, in orient
  File "shapely/algorithms/cga.py", line 11, in signed_area
IndexError: index 1 is out of bounds for axis 0 with size 0```

**Comment by tyrosinase** [comment]
Apparently I missed copying the version: remove-empty-groups release, LInux.

**Comment by tyrosinase** [comment]
Update: I've isolated the object!

Hopefully Github won't mangle it.

![BadCircle](https://github.com/inkstitch/inkstitch/assets/9473609/dbd46ea5-83ae-4224-a740-abd1cded0cad)

**Comment by tyrosinase** [comment]
(also if it helps narrow it down: it used to work, though it's been maybe a year since I touched the file)

**Comment by kaalleen** [comment]
We updated the shapely version recently and it fixed other issues. Apparently also generated new ones.
