### ISSUE TITLE
satin_column: IndexError: tuple index out of range

### ISSUE THREAD

**Issue by shinsejin** [inkstitch/inkstitch#2561]
Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\convert_to_stroke.py", line 38, in effect
  File "lib\elements\satin_column.py", line 832, in center_line
  File "lib\debug.py", line 231, in decorated
  File "lib\elements\satin_column.py", line 898, in plot_points_on_rails
  File "lib\elements\satin_column.py", line 629, in flattened_sections
  File "lib\elements\satin_column.py", line 629, in <listcomp>
IndexError: tuple index out of range

![image](https://github.com/inkstitch/inkstitch/assets/148303806/a3032785-0071-4f22-85c1-fcabb1af6506)

**Comment by tyrosinase** [comment]
If you're not afraid of pre-release versions, the satin conversion is much improved (I'm guessing that the northwest and southeast corners are *supposed* to look like the southwest and northeast ones) and will probably fix that issue. I'm running https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-remove-empty-groups with no significant issues though one of the devs may be along with an even better suggestion.

**Comment by kaalleen** [comment]
Yes, thank you. This should be fixed in current dev releases.
