### ISSUE TITLE
error message on applying params

### ISSUE THREAD

**Issue by doubleDax** [inkstitch/inkstitch#2565]
An error message showed after clicking apply and close on the params window.  The error message appeared after the window closed, and the modifications didn't get applied.  I was attempting set stitch patterns for multiple shapes at once, so they all looked similar (I think I decided on circular fill in the end, but I could be remembering wrong). 

I am new to this extension (and version of inkscape), and could easily be doing something wrong.  I have also had issues with preview while using params window, but am unsure if that's related to this issue (initially opening sometimes, but not others with exact same settings and a very similar file, and sometimes, freezing).  

As requested in the error message, message and file I was working on when it appeared are included.  I am on Ubuntu 20.04.6 LTS, Inkscape version 1.3 (1:1.3+202307231459+0e150ed6c4), and the ink/stitch extension is version 3.0.1.  

error message text: 
Failed on  path3: Error during autofill! This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues/new

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v3.0.1 (linux)

Traceback (most recent call last):
  File "lib/elements/fill_stitch.py", line 726, in to_stitch_groups
  File "lib/elements/fill_stitch.py", line 921, in do_circular_fill
  File "lib/stitches/circular_fill.py", line 81, in circular_fill
  File "lib/stitches/circular_fill.py", line 147, in path_to_stitches
  File "lib/stitches/auto_fill.py", line 632, in travel
  File "networkx/classes/backends.py", line 148, in wrapper
  File "networkx/algorithms/shortest_paths/generic.py", line 173, in shortest_path
  File "networkx/algorithms/shortest_paths/weighted.py", line 2398, in bidirectional_dijkstra
networkx.exception.NetworkXNoPath: No path between (193.84575711092342, 146.48738624233582) and (188.97637, 120.94531).

Failed on  path3: Error during autofill! This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues/new

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v3.0.1 (linux)

Traceback (most recent call last):
  File "lib/elements/fill_stitch.py", line 726, in to_stitch_groups
  File "lib/elements/fill_stitch.py", line 921, in do_circular_fill
  File "lib/stitches/circular_fill.py", line 81, in circular_fill
  File "lib/stitches/circular_fill.py", line 147, in path_to_stitches
  File "lib/stitches/auto_fill.py", line 632, in travel
  File "networkx/classes/backends.py", line 148, in wrapper
  File "networkx/algorithms/shortest_paths/generic.py", line 173, in shortest_path
  File "networkx/algorithms/shortest_paths/weighted.py", line 2398, in bidirectional_dijkstra
networkx.exception.NetworkXNoPath: No path between (193.84575711092342, 146.48738624233582) and (188.97637, 120.94531).

![UVWarningSunStitchPlanError](https://github.com/inkstitch/inkstitch/assets/113312789/fb657cad-c008-4111-8d22-6bfd05562bd7)

**Comment by kaalleen** [comment]
Thank you for the error report and sending your file along.
It is a bug in Ink/Stitch. But we have seen this error before: #2516
Therefore I will close this issue in favor of the existing one.
