### ISSUE TITLE
DLL load failed while importing win32api

### ISSUE THREAD

**Issue by Jorazon** [inkstitch/inkstitch#2567]
Fresh installs of Inkscape 1.3, Ink/Stitch - v3.0.1, and Python 3.12.0 on Windows 10.
When trying to do anything with inkstitch I get the following message:
```
Traceback (most recent call last):
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_win32comgenpy.py", line 58, in <module>
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_win32comgenpy.py", line 42, in _pyi_rthook
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "win32com\__init__.py", line 9, in <module>
ImportError: DLL load failed while importing win32api: The specified procedure could not be found.
```
Previously had Ink/Stitch - v2.1.2 installed which worked.

**Comment by kaalleen** [comment]
Oh, interesting. Can you check if this development build works for you?
https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kall-test

**Comment by Jorazon** [comment]
Everything seems to be working normally with this build. Thanks.

**Comment by kaalleen** [comment]
Great. Thank you for the feedback!
