### ISSUE TITLE
Improve error message when there are too many color changes

### ISSUE THREAD

**Issue by ethanforns** [inkstitch/inkstitch#2574]
Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\output.py", line 65, in effect
  File "lib\output.py", line 109, in write_embroidery_file
  File "pyembroidery\EmbPattern.py", line 1727, in static_write
  File "pyembroidery\EmbPattern.py", line 1644, in write_embroidery
  File "pyembroidery\PesWriter.py", line 50, in write
  File "pyembroidery\PesWriter.py", line 110, in write_version_1
![PHAA Embroidery with text](https://github.com/inkstitch/inkstitch/assets/149087604/7a54067c-15bd-4e01-8c2c-a248806c7050)

  File "pyembroidery\PecWriter.py", line 40, in write_pec
  File "pyembroidery\PecWriter.py", line 64, in write_pec_header
AssertionError: too many color changes, (401) out of bounds (0, 255)

**Comment by tyrosinase** [comment]
Hmm, it should probably be giving you a nicer message, but the underlying problem is that your graphic isn't ready to turn into a stitch file yet.

To change the color of lettering, don't give it a fill, but instead change the stroke color. (That's why it's complaining about too many color changes: each piece of each letter is bouncing between doing the white fill and then the black satins.)

You'll also need to convert the mandala part into satin: https://silverseams.com/tutorials/digitizing-outlined-graphics.html

That actually won't be too hard, since you can just make one of each petal and then rotate/duplicate it. You may want to clean up the joins a little, depending on your final size: https://silverseams.com/tutorials/satin-joins-and-corners.html
