### ISSUE TITLE
issus when fixe or verifing my vector design

### ISSUE THREAD

**Issue by fauveriane** [inkstitch/inkstitch#2575]
**Hello, Ink Stitch keep having an error and told me to make an "issus" with this:**

Ink/Stitch Version: v3.0.1 (osx)

Traceback (most recent call last):
  File "shapely/geometry/multipolygon.py", line 189, in geos_multipolygon_from_polygons
TypeError: 'Polygon' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 250, in run
  File "lib/extensions/troubleshoot.py", line 33, in effect
  File "lib/elements/fill_stitch.py", line 608, in validation_errors
  File "lib/elements/fill_stitch.py", line 542, in shape
  File "lib/elements/fill_stitch.py", line 592, in _get_clipped_path
  File "shapely/geometry/multipolygon.py", line 60, in __init__
  File "shapely/geometry/multipolygon.py", line 191, in geos_multipolygon_from_polygons
AttributeError: 'list' object has no attribute '_ndim'

**I've also put my SVG file, hope it can be fixed !**
![Patch Osselait Mexican](https://github.com/inkstitch/inkstitch/assets/149110842/fdf0b635-d9be-41df-891c-5084e9e77fad)

**Comment by claudinepeyrat06** [comment]
All your satin columns are fine (but you could run autosatin to get rid of all the jumps)

However:

- Some of your fill objects are too small  for fill and should be turned into satin columns
- Other fill objects have their border self crossing.

what you could do is :

- first breakapart your fill (using Tools : Fill / Break apart fill  objects)
- then use Troubleshoot/Trooble shool objects to get  a report of what is wrong.

**Comment by kaalleen** [comment]
Closing. Fixed in #2577
