### ISSUE TITLE
Inkstitch error

### ISSUE THREAD

**Issue by Ezeakial** [inkstitch/inkstitch#2581]
[](url)Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v3.0.1 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 250, in run
  File "lib/extensions/troubleshoot.py", line 33, in effect
  File "lib/elements/satin_column.py", line 652, in validation_errors
  File "lib/elements/satin_column.py", line 1262, in to_stitch_groups
  File "lib/elements/satin_column.py", line 1090, in do_satin
  File "lib/debug.py", line 231, in decorated
  File "lib/elements/satin_column.py", line 898, in plot_points_on_rails
  File "lib/elements/satin_column.py", line 629, in flattened_sections
  File "lib/elements/satin_column.py", line 629, in <listcomp>
IndexError: tuple index out of r
![Team Capatain Patch3](https://github.com/inkstitch/inkstitch/assets/149443476/52780f91-00cb-401a-8497-dde5d17d55c3)
ange

**Comment by kaalleen** [comment]
This mostly happens in the current version when you select no satins along with satins and then apply satin params.
Running stitches receive a satin param and this fails. The next Ink/Stitch version will be more forgiving.

Remove the satin param from your running stitches and you'll be fine.

**Comment by kaalleen** [comment]
Closing, since this is fixed in current dev builds.
