### ISSUE TITLE
Error when starting the app

### ISSUE THREAD

**Issue by Mihovna** [inkstitch/inkstitch#2582]
Hello! After installing the application, I found the EXE file in the path AppData\Roaming\inkscape\extensions\inkstitch\inkstitch\bin. Is this the correct file?

When starting it gives an unhandled exception in script

Traceback (most recent call last):
  File "inkstitch.py", line 62, in <module>
AttributeError: 'NoneType' object has no attribute 'title'

**Comment by kaalleen** [comment]
Ink/Stitch is an Inscape plugin, it doesn't run on itself. Once installed it will be accessible through Inkscape (Extensions > Ink/Stitch).

**Comment by lexelby** [comment]
Maybe we should detect this and pop up a message?

**Comment by kaalleen** [comment]
I think we do that now.

**Comment by jadefourcade** [comment]
bonjour mois j'ai ce probleme comment le resoudre merci d'avance 

Traceback (most recent call last):
  File "PyInstaller\loader\pyimod03_ctypes.py", line 77, in __init__
  File "ctypes\__init__.py", line 373, in __init__
OSError: [WinError 193] %1 n’est pas une application Win32 valide

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "inkstitch.py", line 125, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "lib\extensions\__init__.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "lib\extensions\about.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "lib\extensions\base.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "lib\elements\__init__.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "lib\elements\fill_stitch.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "lib\stitches\__init__.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "lib\stitches\auto_fill.py", line 28, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "lib\utils\smoothing.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\__init__.py", line 162, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\_distributor_init.py", line 26, in <module>
  File "PyInstaller\loader\pyimod03_ctypes.py", line 79, in __init__
pyimod03_ctypes.install.<locals>.PyInstallerImportError: Failed to load dynlib/dll 'C:\\Users\\jade\\AppData\\Roaming\\inkscape\\extensions\\inkstitch\\inkstitch\\bin\\scipy\\.libs\\libopenblas.67LVI5PIPIPYANQC3VAWDE6KZKQBFZON.gfortran-win32.dll'. Most likely this dynlib/dll was not found when the application was frozen.
