### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by CCCCCCCCCassie** [inkstitch/inkstitch#2583]
Ink/Stitch Version: v3.0.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\troubleshoot.py", line 33, in effect
  File "lib\elements\satin_column.py", line 652, in validation_errors
  File "lib\elements\satin_column.py", line 1260, in to_stitch_groups
  File "lib\elements\satin_column.py", line 1088, in do_satin
  File "lib\debug.py", line 231, in decorated
  File "lib\elements\satin_column.py", line 915, in plot_points_on_rails
ZeroDivisionError: float division by zero

![VINCENZA](https://github.com/inkstitch/inkstitch/assets/149859366/fe5cd134-f9e1-4245-babb-da4d1a7a3b68)

I believe the error is regarding Layer "E stich" > Path 3

**Comment by kaalleen** [comment]
I had a brief look at your file:
* In the Satin layer combine path1 and path2.
* In Satin the nose is disconnected in two spots. Join those at the nose tip.
* In E-Stitch disconnect the outline from the part inside as you did in the satin layer (break apart and then recombine only those rungs and rails that belong to the specific part).

**Comment by kaalleen** [comment]
Additionally there is a new version (3.0.1) out there, which has a few bug fixes.

**Comment by kaalleen** [comment]
Closing. This should be fixed in current versions. If not, please open a new issue.
