### ISSUE TITLE
unexpected bug while using "cut"

### ISSUE THREAD

**Issue by Fecix** [inkstitch/inkstitch#2589]
Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\object_commands.py", line 38, in effect
  File "lib\commands.py", line 397, in add_commands
  File "lib\commands.py", line 350, in get_command_pos
AttributeError: 'MultiPolygon' object has no attribute 'exterior'

![2023_11_05_id4_Julia_basting_stitches_cut](https://github.com/inkstitch/inkstitch/assets/150067272/6090900d-698a-4fed-a88b-221d1b89bf5a)

**Comment by kaalleen** [comment]
On which part of the design did you try adding a command?

**Comment by kaalleen** [comment]
Ink/Stitch has a newer release (currently 3.0.1) to which you could update. I think this should fix your issue.
