### ISSUE TITLE
satin_column: IndexError: tuple index out of range

### ISSUE THREAD

**Issue by TracyD-66** [inkstitch/inkstitch#2597]
Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v3.0.1 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 250, in run
  File "lib/extensions/troubleshoot.py", line 33, in effect
  File "lib/elements/satin_column.py", line 652, in validation_errors
  File "lib/elements/satin_column.py", line 1262, in to_stitch_groups
  File "lib/elements/satin_column.py", line 1090, in do_satin
  File "lib/debug.py", line 231, in decorated
  File "lib/elements/satin_column.py", line 898, in plot_points_on_rails
  File "lib/elements/satin_column.py", line 629, in flattened_sections
  File "lib/elements/satin_column.py", line 629, in <listcomp>
IndexError: tuple index out of range

**Comment by tyrosinase** [comment]
This has come up before (starting with #2046). Take a look at issue #2514 and see if that solves your problem. If it doesn't, and you can upload the problem SVG here, that will help with tracking it down.

**Comment by kaalleen** [comment]
I will close this issue since it is fixed in current development releases. If you are still seeing issues with this, feel free to continue posting messages to this or a new thread.
