### ISSUE TITLE
Letters to Font error

### ISSUE THREAD

**Issue by Smoofinator** [inkstitch/inkstitch#2600]
Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\letters_to_font.py", line 64, in effect
UnboundLocalError: local variable 'group' referenced before assignment

**Comment by kaalleen** [comment]
The error message has been fixed in current development releases... but ... it indiactes, that no glyph was found. How are your letter files named? You may need to adapt their names so that they can be recognized. For eaxample A.pes a.pes, B.pes, etc
