### ISSUE TITLE
polyline:  ValueError: LineStrings must have at least 2 coordinate tuples

### ISSUE THREAD

**Issue by gsusalvarado** [inkstitch/inkstitch#2602]
Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "shapely\speedups\_speedups.pyx", line 90, in shapely.speedups._speedups.geos_linestring_from_py
AttributeError: 'CubicSuperPath' object has no attribute '__array_interface__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\object_commands.py", line 37, in effect
  File "lib\elements\polyline.py", line 52, in shape
  File "shapely\geometry\linestring.py", line 47, in __init__
  File "shapely\speedups\_speedups.pyx", line 156, in shapely.speedups._speedups.geos_linestring_from_py
ValueError: LineStrings must have at least 2 coordinate tuples

**Comment by kaalleen** [comment]
We should definitely fix this. But the only commands that would actually work on a polyline are trim and stop and you can set them in the params dialog as well. In case you want more embroidery options, convert your polyline to a path (Path > Object to path).

**Comment by gsusalvarado** [comment]
@kaalleen  thanks
