### ISSUE TITLE
auto_run: NetworkXNoPath

### ISSUE THREAD

**Issue by rlgafter** [inkstitch/inkstitch#2604]
I ran auto-route running stitch with: Add notes at intersections checked, preserve order of running stitches checked and trim jump stitches checked

Live preview was not checked

Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\auto_run.py", line 35, in effect
  File "lib\stitches\auto_run.py", line 130, in autorun
  File "lib\stitches\utils\autoroute.py", line 33, in find_path
  File "networkx\classes\backends.py", line 148, in wrapper
  File "networkx\algorithms\shortest_paths\generic.py", line 171, in shortest_path
  File "networkx\algorithms\shortest_paths\unweighted.py", line 240, in bidirectional_shortest_path
  File "networkx\algorithms\shortest_paths\unweighted.py", line 308, in _bidirectional_pred_succ
networkx.exception.NetworkXNoPath: No path between POINT (131.90425690949743 462.4242986837471) and POINT (753.4363209717602 463.81675962375994).

![square 1](https://github.com/inkstitch/inkstitch/assets/135143711/3897d374-d82a-40ea-9ea7-50e7161d5825)

**Comment by rlgafter** [comment]
I reran auto route running stitch with preserve order of running stitches, unchecked - everything else the same and there was no error generated
