### ISSUE TITLE
color_block: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by zabkowi4** [inkstitch/inkstitch#2619]
getting this error message when trying to run a preview of my design in Inkscape-ink/stitch. This is the error message 

 Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\stitch_plan_preview.py", line 42, in effect
  File "lib\stitch_plan\stitch_plan.py", line 35, in stitch_groups_to_stitch_plan
  File "lib\stitch_plan\stitch_plan.py", line 115, in new_color_block
  File "lib\stitch_plan\color_block.py", line 16, in __init__
  File "lib\stitch_plan\color_block.py", line 51, in color
  File "lib\threads\color.py", line 36, in __init__
TypeError: 'NoneType' object is not iterable

**Comment by kaalleen** [comment]
Which Ink/Stitch version are you using?

**Comment by kaalleen** [comment]
Closing. Issue has been fixed in current main.
Please try to apply a color through the color palette shown at the bottom of the inkscape window (right click for fill, left click for stroke)
