### ISSUE TITLE
Clone: NotImplementedError: shape()

### ISSUE THREAD

**Issue by OddBall96** [inkstitch/inkstitch#2620]
Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\object_commands.py", line 37, in effect
  File "lib\elements\element.py", line 409, in shape
NotImplementedError: ('INTERNAL ERROR: %s must implement shape()', <class 'lib.elements.clone.Clone'>)

**Comment by kaalleen** [comment]
Thank you for the error report! Definitely a bug in Ink/Stitch that needs a fix.
