### ISSUE TITLE
AttributeError: 'LineString' object has no attribute 'geoms'

### ISSUE THREAD

**Issue by wizzardarena** [inkstitch/inkstitch#2622]
i usually create the vector in Ai and then turn it into dst in inkscape. and then this is happens. i dont know what am i supposed to do

Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\output.py", line 56, in effect
  File "lib\extensions\base.py", line 200, in elements_to_stitch_groups
  File "lib\elements\element.py", line 329, in embroider
  File "lib\elements\element.py", line 387, in validate
  File "lib\elements\fill_stitch.py", line 321, in validation_errors
  File "lib\elements\fill_stitch.py", line 274, in shape
AttributeError: 'LineString' object has no attribute 'geoms'

**Comment by tyrosinase** [comment]
This is fixed in the current release; reopen this issue if it gives you an error after upgrading.

(If you can't upgrade, the work-around is finding the too-small-for-a-stitch shapes, usually artifacts of bitmap conversion, and deleting them)
