### ISSUE TITLE
Auto-Route Satin Columns bug

### ISSUE THREAD

**Issue by iraytrace** [inkstitch/inkstitch#2648]
When trying to auto-route the entire pattern in the Rune_bug.svg file I get the following error:

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\auto_satin.py", line 67, in effect
  File "lib\extensions\auto_satin.py", line 67, in <listcomp>
  File "lib\elements\satin_column.py", line 832, in center_line
  File "lib\debug.py", line 231, in decorated
  File "lib\elements\satin_column.py", line 898, in plot_points_on_rails
  File "lib\elements\satin_column.py", line 629, in flattened_sections
  File "lib\elements\satin_column.py", line 629, in <listcomp>
IndexError: tuple index out of range

![Rune_bug](https://github.com/inkstitch/inkstitch/assets/3651273/c850c087-20f7-4b8b-bd3f-f3a3f6f541b2)

**Comment by kaalleen** [comment]
Thank you for your error report. The issue has been fixed for current development releases. This is a bit of an annoying issue with the current official release. It happens, when single lines are selected along with satin columns when a satin column param is applied.

In your file you may not expect single lines. But there is one. To fix your file, combine the selected element in the image with the rest of the satin column and reapply the satin column in the params dialog.
![tuple_satin](https://github.com/inkstitch/inkstitch/assets/36401965/4e88684f-192a-4009-b532-9fc4a8ed6e20)

**Comment by kaalleen** [comment]
Closing since this should be fixed in more recent development builds. If combining the suggested paths doesn't help, please feel free to open an other issue or post more content here.
