### ISSUE TITLE
autofill: NetworkXNoPath

### ISSUE THREAD

**Issue by JuliaB60** [inkstitch/inkstitch#2659]
Failed on  path5318: Error during autofill! This means it is a bug in Ink/Stitch.

Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 714, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 759, in do_underlay
  File "lib\debug.py", line 231, in decorated
  File "lib\stitches\auto_fill.py", line 80, in auto_fill
  File "lib\debug.py", line 231, in decorated
  File "lib\stitches\auto_fill.py", line 671, in path_to_stitches
  File "lib\stitches\auto_fill.py", line 632, in travel
  File "networkx\classes\backends.py", line 148, in wrapper
  File "networkx\algorithms\shortest_paths\generic.py", line 173, in shortest_path
  File "networkx\algorithms\shortest_paths\weighted.py", line 2398, in bidirectional_dijkstra
networkx.exception.NetworkXNoPath: No path between (122.97088346956203, 10.921861349637481) and (121.88976377952757, 16.250288836979642).
![MGE Chase Hat](https://github.com/inkstitch/inkstitch/assets/105676377/189d4188-af77-4d57-b5f2-ff0b9cad8ec9)

**Comment by kaalleen** [comment]
Thank you for your error report. Sending the file along is really, really helpful. This definitely needs to get fixed in Ink/Stitch.

Meanwhile you can fix your file by setting start- and end commands to your fill objects. Alternatively for letters in that size it would make a lot of sense to convert them into satin columns. They would turn out much nicer then.

In case you are interested, here a little bit more insight into the problem. Ink/Stitch tries to set a start position according to the end position of the previous element. In your case you stitch out an outline beforehand. On some letters this includes the holes inside the letters (in A, O,and R). Therefore Ink/Stitch tries to start in the inside. This usually shouldn't be a problem. In your case though, you have small letters and even smaller holes inside the letters. The distance of the underlay is wide enough not to connect to the hole and therefore the starting point doesn't connect to the graph.
