### ISSUE TITLE
legacy_fill: intersect_region_with_grating: ValueError

### ISSUE THREAD

**Issue by flutemaestro830** [inkstitch/inkstitch#2664]
Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\output.py", line 56, in effect
  File "lib\extensions\base.py", line 133, in elements_to_stitch_groups
  File "lib\elements\element.py", line 558, in embroider
  File "lib\elements\fill_stitch.py", line 703, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 739, in do_legacy_fill
  File "lib\stitches\fill.py", line 18, in legacy_fill
  File "lib\stitches\fill.py", line 98, in intersect_region_with_grating
ValueError: not enough values to unpack (expected 4, got 0)

**Comment by kaalleen** [comment]
Do you still have the svg file? It could be valuable to fix the issue.

**Comment by flutemaestro830** [comment]
Yes I do!

**Comment by kaalleen** [comment]
That is great news. Would you mind to send it via GitHub upload? I'm afraid sending a file via mail will not work.

**Comment by flutemaestro830** [comment]
Sure, no problem.

**Comment by flutemaestro830** [comment]
Ok so it looks like the file got overwritten. When I tried to recreate the issue this morning I couldn't. Admittedly I am brand new and after this happened yesterday watched ~2 hours of youtube tutorials. It's possible I was just missing a step.

**Comment by kaalleen** [comment]
Ah too sad. Well, let's hope then somebody else will come up with the same issue and still has the svg.
Good though, that you could solve your issue.

**Comment by kaalleen** [comment]
We received the very same error with an svg file attached (#2671). So I'll close this one.
