### ISSUE TITLE
fill: ValueError in intersect_region_with_grating

### ISSUE THREAD

**Issue by Rodifan** [inkstitch/inkstitch#2671]
Hey, I can't save my file in .dst

Here's the attached file.
![sp_dotd](https://github.com/inkstitch/inkstitch/assets/155569597/4e73ffc0-9a8b-4127-96c8-66f64a19d221)

It might have something to do with the line path direction or the reverse rails function. This is the error that I got when I was trying to save my file:

Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run

  File "lib\extensions\output.py", line 56, in effect
  File "lib\extensions\base.py", line 133, in elements_to_stitch_groups
  File "lib\elements\element.py", line 558, in embroider
  File "lib\elements\fill_stitch.py", line 703, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 739, in do_legacy_fill
  File "lib\stitches\fill.py", line 18, in legacy_fill
  File "lib\stitches\fill.py", line 98, in intersect_region_with_grating
ValueError: not enough values to unpack (expected 4, got 0)

**Comment by kaalleen** [comment]
Interesting. Thank you for the file.
Have a look at path33 in first A and path50 in second A. They both have a fill, which I suppose is not your intention.
This is a bug in Ink/Stitch, but if you remove those fills, you can go on with your design.

I tested in with a dev version as well. It seems to work in there. So I think it is fixed. I have no time right now to really make sure. So I just leave this as a note.

**Comment by Rodifan** [comment]
I'd have overlooked that. Thank you very much for your help.

**Comment by kaalleen** [comment]
You are welcome
