### ISSUE TITLE
Ink/Stitch Version: 3.0.1 (osx)

### ISSUE THREAD

**Issue by VicTG68** [inkstitch/inkstitch#2672]
Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 231, in run
  File "lib/extensions/object_commands.py", line 37, in effect
  File "lib/elements/element.py", line 409, in shape
NotImplementedError: ('INTERNAL ERROR: %s must implement shape()', <class 'lib.elements.clone.Clone'>)

**Comment by kaalleen** [comment]
In 3.0.1 you'll need to unlink your clone in order to be able to set commands.
The next Ink/Stitch version will handle this better.
