### ISSUE TITLE
Failed on  path119: Error during autofill! This means it is a bug in Ink/Stitch.

### ISSUE THREAD

**Issue by estephens38** [inkstitch/inkstitch#2679]
![AGM Peter](https://github.com/inkstitch/inkstitch/assets/43047516/c5b309a9-f3d3-42da-bd62-2461176d7054)

Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 729, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 781, in do_auto_fill
  File "lib\debug.py", line 231, in decorated
  File "lib\stitches\auto_fill.py", line 80, in auto_fill
  File "lib\debug.py", line 231, in decorated
  File "lib\stitches\auto_fill.py", line 671, in path_to_stitches
  File "lib\stitches\auto_fill.py", line 632, in travel
  File "networkx\classes\backends.py", line 148, in wrapper
  File "networkx\algorithms\shortest_paths\generic.py", line 173, in shortest_path
  File "networkx\algorithms\shortest_paths\weighted.py", line 2398, in bidirectional_dijkstra
networkx.exception.NetworkXNoPath: No path between (102.94050093603167, 234.33070866141736) and (102.99109344929249, 233.4710903117127)

**Comment by tyrosinase** [comment]
Oh that's... fun. It's recognizing the trims as trims and yet not recognizing the trims as trims. As a workaround: `Extensions > Inkstitch > Commands > View > Display/hide` will make it stop trying to stitch the trim symbols.

**Comment by kaalleen** [comment]
Try to add start/end commands on elements in question. Most of these networkx issues have to do with bad starts/endings.
I'll close the issue this is has been fixed for the next release. If you still have questions about your design you can post them here.

**Comment by kaalleen** [comment]
Oh, I didn't test the file, just saw the error message. tyrosinase seems to think it has something to do with the commands being converted to paths. Sorry if I caused any confusion here :D

**Comment by kaalleen** [comment]
With current main it renders just fine (rendering the converted commands as well).
So I'll keep the issue closed.
