### ISSUE TITLE
Select Elements: FileNotFoundError

### ISSUE THREAD

**Issue by wayward710** [inkstitch/inkstitch#2683]
This occurred while trying to edit the embroidery elements (Windows 10, most recent release). Attached is the SVG file.
![bsides2](https://github.com/inkstitch/inkstitch/assets/3958029/7b4c67d3-78f9-40fe-9d4c-f2d893f21518)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\select_elements.py", line 47, in effect
  File "subprocess.py", line 858, in __init__
  File "subprocess.py", line 1311, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by kaalleen** [comment]
It doesn't seem to find the path to your python executable. You can follow this instructions and set it up manually: https://inkstitch.org/docs/edit/#troubleshoot
