### ISSUE TITLE
PEC/PES export: too many color changes

### ISSUE THREAD

**Issue by estephens38** [inkstitch/inkstitch#2688]
Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\output.py", line 65, in effect
  File "lib\output.py", line 109, in write_embroidery_file
  File "pyembroidery\EmbPattern.py", line 1727, in static_write
  File "pyembroidery\EmbPattern.py", line 1644, in write_embroidery
  File "pyembroidery\PesWriter.py", line 50, in write
  File "pyembroidery\PesWriter.py", line 110, in write_version_1
  File "pyembroidery\PecWriter.py", line 40, in write_pec
  File "pyembroidery\PecWriter.py", line 64, in write_pec_header
AssertionError: too many color changes, (843) out of bounds (0, 255)

![915al-yllLL _AC_UF1000_1000_QL80_-removebg-preview(1)](https://github.com/inkstitch/inkstitch/assets/43047516/dcc43e91-433b-4e54-ada8-3311672d5f25)

**Comment by kaalleen** [comment]
Nice design... but it has way too many color changes (843) while it should have max. 255.
I haven't opened the file in Inskcape, but maybe you can group colors (select one and then select same fill color, then group). Run clean up document in the Ink/Stitch extension troubleshoot section which will delete small elements.
But maybe it'd be better to redraw and simplify a lot of it. With a little work this can turn out nice.

**Comment by estephens38** [comment]
Hi, how is the easiest way for my to redraw and clean up? Any
recommendations?

**Comment by kaalleen** [comment]
Here is a rough sketch on how you could try to simplify the shapes. Try to draw the bigger shapes and add details with loose stitching on top of it. Or even better if you go ahead and work in some details with a simple bezier curve into the stitch plan.
![Bildschirmfoto vom 2024-01-17 18-51-14](https://github.com/inkstitch/inkstitch/assets/36401965/2c45928d-0b0b-4d79-a1e1-4644bbf66fdd)

**Comment by kaalleen** [comment]
Closing in favor of https://github.com/inkstitch/inkstitch/issues/2574

You can still comment on this thread if you have further questions.
