### ISSUE TITLE
Satin Stitch bug

### ISSUE THREAD

**Issue by ITCD2024** [inkstitch/inkstitch#2689]
Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\troubleshoot.py", line 33, in effect
  File "lib\elements\satin_column.py", line 652, in validation_errors
  File "lib\elements\satin_column.py", line 1262, in to_stitch_groups
  File "lib\elements\satin_column.py", line 1090, in do_satin
  File "lib\debug.py", line 231, in decorated
  File "lib\elements\satin_column.py", line 898, in plot_points_on_rails
  File "lib\elements\satin_column.py", line 629, in flattened_sections
  File "lib\elements\satin_column.py", line 629, in <listcomp>
IndexError: tuple index out of range

**Comment by kaalleen** [comment]
Thank you for the error report. This is an annoying bug in the current Ink/Stitch version, which has been fixed for future versions. Most probably you accidentally turned a single stroke into a satin column. Try to track it down and turn it back into a running stitch.

**Comment by bkgoodman** [comment]
I ran into this too. It had other effects, like live-preview hanging, etc.  
  
The notible thing is, though: I only have one object, and it is NOT a Satin Column/stitch. The ONLY thing it has is an "Automatically Routed" - "Auto Fill" object. But - it appears to happen when the path in question contains a stroke color - i.e. the error goes away if there is no stroke color on the object - EVEN IF there are no "stroke" (Inkstitch) Params associated with the object.

**Comment by kaalleen** [comment]
I'll close the issue since this error is fixed for the next release. You can still post your design related questions here.

@bkgoodman Open the params dialog for the fill and stroke object and reapply a running stitch. It possibly has a satin column setting.
