### ISSUE TITLE
Crashing when I run Params

### ISSUE THREAD

**Issue by mg1933** [inkstitch/inkstitch#2692]
Troubleshooting all objects and they seem fine...but it can't run Params (and thus build a PES) Thanks.
![NewXHDuck](https://github.com/inkstitch/inkstitch/assets/157073432/944dd654-8331-4fda-ab97-d57de902f8f2)

----
Ink/Stitch Version: v3.0.1 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 250, in run
  File "lib/extensions/output.py", line 57, in effect
  File "lib/stitch_plan/stitch_plan.py", line 35, in stitch_groups_to_stitch_plan
  File "lib/stitch_plan/stitch_plan.py", line 115, in new_color_block
  File "lib/stitch_plan/color_block.py", line 16, in __init__
  File "lib/stitch_plan/color_block.py", line 51, in color
  File "lib/threads/color.py", line 36, in __init__
TypeError: 'NoneType' object is not iterable

**Comment by tyrosinase** [comment]
That looks like a known (and fixed, if you want to run a pre-release version) problem where non-Inkscape-created files don't have a color that Ink/Stitch recognizes. Workaround: select your objects, pick an appropriate color from the palette at the bottom of the screen.

**Comment by mg1933** [comment]
Yes, thank you (!), changing the colors from Ink/Stitch's color palette works and I was able to build the Params I wanted. But I haven't encountered this before, and all of my media has been created outside of Ink Stitch, so I am unclear why it suddenly became an issue. Which pre-release version will solve this?
