### ISSUE TITLE
Ink/Stitch Version: v3.0.1 (windows)

### ISSUE THREAD

**Issue by Grand0ldman** [inkstitch/inkstitch#2693]
Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\troubleshoot.py", line 33, in effect

  File "lib\elements\satin_column.py", line 652, in validation_errors
  File "lib\elements\satin_column.py", line 1262, in to_stitch_groups
  File "lib\elements\satin_column.py", line 1090, in do_satin
  File "lib\debug.py", line 231, in decorated
  File "lib\elements\satin_column.py", line 898, in plot_points_on_rails
  File "lib\elements\satin_column.py", line 629, in flattened_sections
  File "lib\elements\satin_column.py", line 629, in <listcomp>
IndexError: tuple index out of range
![Inkstitch rapport 20240119](https://github.com/inkstitch/inkstitch/assets/157138613/22e8428b-46f7-4e1a-ab4d-af4a23398460)

**Comment by gusvisser** [comment]
![image](https://github.com/inkstitch/inkstitch/assets/85417086/71a69838-5174-46c4-83f6-e46e95d8a650)
the issue appears to me that you have one rung what is not combined with your satin and a satin param was applied to it and also check the params on your running stitches and also there are a lot of jumps within a letter what i would reccommend to clean up

**Comment by kaalleen** [comment]
I'll close the issue since this error is fixed for the next release. You can still post your design related questions here.
