### ISSUE TITLE
Error in Autofill

### ISSUE THREAD

**Issue by agapant** [inkstitch/inkstitch#2695]
inkscape version 1.3.2
![illusion-optical-fehler](https://github.com/inkstitch/inkstitch/assets/157322031/441c9f61-87f0-4744-9036-b2e56661534c)

The issue happens after I switch the line distance from 0.25 to 0.4 mm 

Ink/Stitch Version: 3.0.1 (osx)

Traceback (most recent call last):
  File "lib/elements/fill_stitch.py", line 726, in to_stitch_groups
  File "lib/elements/fill_stitch.py", line 921, in do_circular_fill
  File "lib/stitches/circular_fill.py", line 81, in circular_fill
  File "lib/stitches/circular_fill.py", line 147, in path_to_stitches
  File "lib/stitches/auto_fill.py", line 632, in travel
  File "networkx/algorithms/shortest_paths/generic.py", line 162, in shortest_path
  File "networkx/algorithms/shortest_paths/weighted.py", line 2117, in bidirectional_dijkstra
networkx.exception.NetworkXNoPath: No path between (15.750862767816683, 213.07249530450935) and (4.535433070866137, 210.2752620312677).

**Comment by gusvisser** [comment]
I had a look at your svg and i think the reason for your error is that the lines in your design are not wide enough for the stitch path to travel through i think you have two options one is to convert the whole shape into multi satin line or you need to break it up into multiple pieces inorder to use a fill but i think it would turn out the nicest as satin stitches

Gus Visser

**Comment by kaalleen** [comment]
Thanks for the bug report. It is always really helpful to see a error message posted, especially with an attached svg. This type of errors are hopefully fixed for the next version. In current versions it could help to set a manual start- and/or ending point. Start or ending points are usually causing this type of errors. A rework as gusvisser suggest may help your design to improve though. I'll close the issue now, since the original error has been fixed in main. If you have further questions, it is ok to go on and ask questions in this thread even when closed.
