### ISSUE TITLE
Too many color changes error

### ISSUE THREAD

**Issue by cocobean15** [inkstitch/inkstitch#2698]
Ink/Stitch Version: v3.0.1 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 250, in run
  File "lib/extensions/output.py", line 65, in effect
  File "lib/output.py", line 109, in write_embroidery_file
  File "pyembroidery/EmbPattern.py", line 1727, in static_write
  File "pyembroidery/EmbPattern.py", line 1644, in write_embroidery
  File "pyembroidery/PesWriter.py", line 50, in write
  File "pyembroidery/PesWriter.py", line 110, in write_version_1
  File "pyembroidery/PecWriter.py", line 40, in write_pec
  File "pyembroidery/PecWriter.py", line 64, in write_pec_header
AssertionError: too many color changes, (353) out of bounds (0, 255)
![frog](https://github.com/inkstitch/inkstitch/assets/157664732/b7878773-1628-4879-9b7c-8af22e111132)

**Comment by gusvisser** [comment]
i had a look at your file and there are a lot of issues going on you have all your objects still have a line assigned to it and there are too many small objects what are not suitable for embroidery and for the size of a lot of objects a fill stitch is not reccommended either so there is a lot of cleaning up to do before it would be a succesfull embroidery

Gus Visser

**Comment by kaalleen** [comment]
Closing in favor of #2574

You can still comment on this thread if you have further questions.
