### ISSUE TITLE
Shapely error: Can't create MultiLineString with empty component 

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#2704]
For what it's worth: this is a file that worked fine in original size, but dies a tragic death after being scaled on the command line to 57%. 

```
Ink/Stitch Version: initial (linux)

Traceback (most recent call last):
  File "lib/elements/element.py", line 603, in handle_unexpected_exceptions
  File "lib/elements/element.py", line 571, in embroider
  File "lib/elements/fill_stitch.py", line 762, in to_stitch_groups
  File "lib/elements/fill_stitch.py", line 814, in do_underlay
  File "lib/debug.py", line 231, in decorated
  File "lib/stitches/auto_fill.py", line 84, in auto_fill
  File "lib/debug.py", line 231, in decorated
  File "lib/stitches/auto_fill.py", line 326, in build_travel_graph
  File "lib/stitches/auto_fill.py", line 481, in build_travel_edges
  File "lib/utils/geometry.py", line 109, in ensure_multi_line_string
  File "shapely/geometry/multilinestring.py", line 52, in __new__
shapely.errors.EmptyPartError: Can't create MultiLineString with empty component
```
(yes, probably about time to try out a newer release; if there's one that needs some testing I will happily switch to that one and see if I can break it)

![DemoLogo_Small_bad](https://github.com/inkstitch/inkstitch/assets/9473609/1458d84f-f20f-45cb-b0d4-41ba464525b8)

**Comment by kaalleen** [comment]
Seems to work fine with current main. I'm not sure though if I can recommend any current dev release at the moment. They all do have some shapely/geos issues which you probably don't want to face. I don't really want to fix those issues since time (and a shapely update) will help us to solve those issues and we are not even close to a next official version.

**Comment by kaalleen** [comment]
Oh, you are using initial... Well, maybe it doesn't matter then ... Those issue are already in the version you are currently using (I think) ...

Try this one (new fonts): https://github.com/inkstitch/inkstitch/releases/tag/dev-build-safire3002-add-instrument-and-reenie

**Comment by tyrosinase** [comment]
Yeah, I wasn't quite sure where we were on the shapely situation so figured that might be of some use but yeah, no worries if we're waiting on an update. We can close the issue unless you want to keep track of my problematic shape to test against something in the future.

**Comment by kaalleen** [comment]
Always helpful to see those errors :)
I'm going to close this, since it is fixed in main (although the build system isn't).
