### ISSUE TITLE
Failed on  path15: Error during autofill! This means it is a bug in Ink/Stitch.

### ISSUE THREAD

**Issue by nesges** [inkstitch/inkstitch#2706]
When I try to save the file as .pes:

```
Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 714, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 759, in do_underlay
  File "lib\debug.py", line 231, in decorated
  File "lib\stitches\auto_fill.py", line 80, in auto_fill
  File "lib\debug.py", line 231, in decorated
  File "lib\stitches\auto_fill.py", line 671, in path_to_stitches
  File "lib\stitches\auto_fill.py", line 632, in travel
  File "networkx\classes\backends.py", line 148, in wrapper
  File "networkx\algorithms\shortest_paths\generic.py", line 173, in shortest_path
  File "networkx\algorithms\shortest_paths\weighted.py", line 2398, in bidirectional_dijkstra
networkx.exception.NetworkXNoPath: No path between (45.35433070866111, 529.9746204961511) and (44.32572296262518, 538.85875205879).
```

![beholder4](https://github.com/inkstitch/inkstitch/assets/1583898/b80c89eb-213c-4198-8853-2f91ffd12006)

**Comment by kaalleen** [comment]
I did not test your file. But I would suppose that setting a start- and end command and those elements that fail with this error will fix the issue for you.

**Comment by nesges** [comment]
That did the trick! Thank you! I tried setting a start or end command before, but never tried setting both at the same time

**Comment by kaalleen** [comment]
Great, thanks for the feedback. Glad I could help :)
