### ISSUE TITLE
fill: Multi-part geometries do not provide a coordinate sequence

### ISSUE THREAD

**Issue by keehcyma** [inkstitch/inkstitch#2709]
Ink/Stitch Version: v3.0.1 (windows)
![peachesandcream_v2_tilt_2](https://github.com/inkstitch/inkstitch/assets/17548867/3b2af6a2-0866-4b9b-b1c1-4dd892a521d6)

Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 714, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 759, in do_underlay
  File "lib\debug.py", line 231, in decorated
  File "lib\stitches\auto_fill.py", line 78, in auto_fill
  File "lib\debug.py", line 231, in decorated
  File "lib\stitches\auto_fill.py", line 315, in build_travel_graph
  File "lib\stitches\auto_fill.py", line 450, in build_travel_edges
  File "lib\stitches\auto_fill.py", line 410, in travel_grating
  File "lib\stitches\fill.py", line 155, in intersect_region_with_grating
  File "shapely\geometry\base.py", line 960, in coords
NotImplementedError: Multi-part geometries do not provide a coordinate sequence

**Comment by gusvisser** [comment]
I had a look at your file and your design needs a lot of work yet because your outline yellow is only 0.5mm wide that will not work as a fill stitch and in places there is a small area as a fill but still in more then one object and some areas should be done as a satin instead of a fill so i reccommend to learn a little more on what stitch type to use for what type of objects and how to create them all this info for stitch types is available in the inkstitch webpage

Gus Visser

**Comment by kaalleen** [comment]
I'll close the issue since the problem has been fixed already for the next release version.
If you have further questions to your design you can still post them here.
