### ISSUE TITLE
satin_column: IndexError: tuple index out of range

### ISSUE THREAD

**Issue by PhilCoan** [inkstitch/inkstitch#2710]
![Correct Craft](https://github.com/inkstitch/inkstitch/assets/158581729/4c64b31c-e128-4c04-bb54-b0560fea4027)

nk/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\auto_satin.py", line 67, in effect
  File "lib\extensions\auto_satin.py", line 67, in <listcomp>
  File "lib\elements\satin_column.py", line 832, in center_line
  File "lib\debug.py", line 231, in decorated
  File "lib\elements\satin_column.py", line 898, in plot_points_on_rails
  File "lib\elements\satin_column.py", line 629, in flattened_sections
  File "lib\elements\satin_column.py", line 629, in <listcomp>
IndexError: tuple index out of range

**Comment by kaalleen** [comment]
Your satin c is actually made of single paths. Select all the paths and go to Path > Combine (Ctrl + K)
Then also combine a node to connect a path that shouldn't be split up. I'll attach an image since it is easier to show than to explain it with words. Select the two nodes at the red marked spot and click on the marked button (Shift + J).

**Comment by kaalleen** [comment]
I'll close the issue since the error has been fixed for the next release. You can still answer to this thread if you have further questions.
