### ISSUE TITLE
AutoFill: TopologicalError

### ISSUE THREAD

**Issue by alison1der** [inkstitch/inkstitch#2713]
Failed on  rect819: Error during autofill! This means it is a bug in Ink/Stitch.
![Eras Embroidery](https://github.com/inkstitch/inkstitch/assets/159199364/d16f280a-a82f-4e21-ab53-33fc39559e0d)

Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 714, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 759, in do_underlay
  File "lib\debug.py", line 231, in decorated
  File "lib\stitches\auto_fill.py", line 78, in auto_fill
  File "lib\debug.py", line 231, in decorated
  File "lib\stitches\auto_fill.py", line 315, in build_travel_graph
  File "lib\stitches\auto_fill.py", line 463, in build_travel_edges
  File "shapely\geometry\base.py", line 700, in symmetric_difference
  File "shapely\topology.py", line 73, in __call__
  File "shapely\topology.py", line 42, in _check_topology
shapely.errors.TopologicalError: This operation could not be performed. Reason: unknown

shapely.geos - ERROR - bad allocation

**Comment by Marif91** [comment]
Impossible de broder ce design beaucoup trop petit....

**Comment by kaalleen** [comment]
Seems to render out with the current version. Although I think this was more of a geos versioning problem, because it keeps popping up. I'll close it nevertheless. Let's see if the problem will show up for users with the upcoming release.
Please report if this is happening with any upcoming Ink/Stitch version.
