### ISSUE TITLE
OpenSUSE linux error on params libnsl.so.1

### ISSUE THREAD

**Issue by buzzmandt** [inkstitch/inkstitch#2716]
I recently updated my OpenSUSE Tumblweed Linux and now params produces the following error. As far as I can tell all other extensions still work. I have 3 computers with tumbleweed and params is broke since the update. visualize just fails without an error. Any ideas?

```
Traceback (most recent call last):
  File "inkstitch.py", line 29, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "lib/extensions/__init__.py", line 30, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "lib/extensions/lettering.py", line 13, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "wx/__init__.py", line 17, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "wx/core.py", line 12, in <module>
ImportError: libnsl.so.1: cannot open shared object file: No such file or directory
[3418] Failed to execute script 'inkstitch' due to unhandled exception!

```

**Comment by bkmgit** [comment]
You may need an older version of libnsl Suse seems to have libnsl.so.3 https://build.opensuse.org/package/view_file/openSUSE:Factory/libnsl/libnsl.spec?expand=1

**Comment by bkmgit** [comment]
What versions of Inkscape and Ink/Stitch are you using and how were they installed?

**Comment by buzzmandt** [comment]
This is now solved. It appears that the last big update also updated libnsl to libnsl3, removing libnsl1. Fix was as simple as install libnsl1. Thanks all.

**Comment by BahuMan** [comment]
@buzzmandt can you tell me how you installed libnsl.so.1 ? (relatively new Tumbleweed user here)

**Comment by buzzmandt** [comment]
Sorry, that information might be handy, right? 

If you haven't done so, install opi
`sudo zypper in opi`

(Play around with opi, it's handy as all get out)

Once it's installed or you already have it simply do in terminal:
`opi libnsl1`

Choose option 2 (the one that started with devel:) follow the prompts, inkstitch works again :)
