### ISSUE TITLE
Error generated when choosing Troubleshoot Elements

### ISSUE THREAD

**Issue by kzembower** [inkstitch/inkstitch#2717]
Initial error, on saving Inkscape file:
```
Failed on  path5596: Satin column: Object has too few subpaths.  A satin column should have at least two subpaths (the rails).

Please run Extensions > Ink/Stitch > Troubleshoot > Troubleshoot objects. This will indicate the errorneus position.
![Kevin_NameBadge_Callsign_logo](https://github.com/inkstitch/inkstitch/assets/1446154/b62916c3-d782-466e-b53d-932487c142ce)

```
This error was generated when I choose Extensions->Ink/Stitch->Troubleshoot->Troubleshoot Elements:
```
Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

Ink/Stitch Version: v3.0.1 (linux)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 250, in run
  File "lib/extensions/troubleshoot.py", line 33, in effect
  File "lib/elements/satin_column.py", line 652, in validation_errors
  File "lib/elements/satin_column.py", line 1262, in to_stitch_groups
  File "lib/elements/satin_column.py", line 1090, in do_satin
  File "lib/debug.py", line 231, in decorated
  File "lib/elements/satin_column.py", line 898, in plot_points_on_rails
  File "lib/elements/satin_column.py", line 629, in flattened_sections
  File "lib/elements/satin_column.py", line 629, in <listcomp>
IndexError: tuple index out of range
```
File attached.
Inkscape debug info:
```
Inkscape 1.3.2 (1:1.3.2+202311252150+091e20ef0f)

    GLib version:     2.72.4
    GTK version:      3.24.33
    glibmm version:   2.66.2
    gtkmm version:    3.24.5
    libxml2 version:  2.9.13
    libxslt version:  1.1.34
    Cairo version:    1.16.0
    Pango version:    1.50.6
    HarfBuzz version: 2.7.4

    OS version:       Ubuntu 22.04.3 LTS
```

**Comment by kaalleen** [comment]
There must be at least one element in your document which has a satin column setting but is supposed to be a running stitch. This is a bit annoying in the current version. The next version will handle the case much better.
