### ISSUE TITLE
Got unecpected error when trying to save as .pes

### ISSUE THREAD

**Issue by LeonStangenberg** [inkstitch/inkstitch#2724]
Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\output.py", line 56, in effect
  File "lib\extensions\base.py", line 133, in elements_to_stitch_groups
  File "lib\elements\element.py", line 558, in embroider
  File "lib\elements\fill_stitch.py", line 703, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 739, in do_legacy_fill
  File "lib\stitches\fill.py", line 18, in legacy_fill
  File "lib\stitches\fill.py", line 98, in intersect_region_with_grating
ValueError: not enough values to unpack (expected 4, got 0)
![Beide Namen Stickdatei](https://github.com/inkstitch/inkstitch/assets/33554811/aecbf7e0-9a76-4f2e-8b17-bc0eb6b2e5ef)

**Comment by kaalleen** [comment]
Thank you for the error report. I think this has been fixed in current development branches.

Have a look at the w, the fill of all the satin columns is unset, which in svg defaults means black. Therefore it is trying to fill those lines and errors out. Just set fill to none and you should be good.

**Comment by LeonStangenberg** [comment]
Thank you, that was the problem. I was jumping from Illustrator to InkScape and back and somewhere that fill thing happend... Good to know that that was the issue for future reference.
