### ISSUE TITLE
Bug parametre

### ISSUE THREAD

**Issue by Liguorienne** [inkstitch/inkstitch#2728]
Ink/Stitch a rencontré une erreur inattendue. Ceci signifie qu'il s'agit d'un bug dans Ink/Stitch.

Si vous souhaitez aider, merci de 
- copier le message d'erreur en entier ci-dessous
- sauvegarder votre fichier svg
- créer un rapport d'erreur (issue) sur https://github.com/inkstitch/inkstitch/issues

Incluez la description de l'erreur et (si possible) le fichier svg.

Ink/Stitch Version: v3.0.1 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 250, in run
  File "lib/extensions/troubleshoot.py", line 33, in effect
  File "lib/elements/satin_column.py", line 652, in validation_errors
  File "lib/elements/satin_column.py", line 1262, in to_stitch_groups
  File "lib/elements/satin_column.py", line 1090, in do_satin
  File "lib/debug.py", line 231, in decorated
  File "lib/elements/satin_column.py", line 898, in plot_points_on_rails
  File "lib/elements/satin_column.py", line 629, in flattened_sections
  File "lib/elements/satin_column.py", line 629, in <listcomp>
IndexError: tuple index out of range
![IRR8X5](https://github.com/inkstitch/inkstitch/assets/156150758/43715245-709c-4b92-a31d-dded812650cd)

**Comment by kaalleen** [comment]
The blue fills also have a stroke color and are set to satin column. Since those are simple lines Ink/Stitch cannot parse them as satin columns. This has been fixed for the next version. But thank you so much for posting your error along with a file.

**Comment by Liguorienne** [comment]
Thank you very much for the help
