### ISSUE TITLE
Reporting Bug

### ISSUE THREAD

**Issue by MaddySW** [inkstitch/inkstitch#2731]
Ink/Stitch Version: v3.0.1 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 250, in run
  File "lib/extensions/troubleshoot.py", line 33, in effect
  File "lib/elements/satin_column.py", line 652, in validation_errors
  File "lib/elements/satin_column.py", line 1262, in to_stitch_groups
  File "lib/elements/satin_column.py", line 1090, in do_satin
  File "lib/debug.py", line 231, in decorated
  File "lib/elements/satin_column.py", line 898, in plot_points_on_rails
  File "lib/elements/satin_column.py", line 629, in flattened_sections
  File "lib/elements/satin_column.py", line 629, in <listcomp>
IndexError: tuple index out of range
![Hybiscus Flower svg 2024_02_20_08_36_20 0](https://github.com/inkstitch/inkstitch/assets/160627366/9c042bea-6f7a-44b3-b353-9d56c4ff69a8)

**Comment by tyrosinase** [comment]
I think the upcoming release will correctly detect that in Troubleshooting but: you've got an outline on the petal fills that it's trying to treat as a satin.

The actual satins have some breaks in them as well that won't throw errors but will make a little string-art action until they're re-joined.

**Comment by MaddySW** [comment]
That’s good to know and thank you so much for the help! I was wondering about the string-art I was seeing on params, that explains!
