### ISSUE TITLE
Ink stitch no geoms error

### ISSUE THREAD

**Issue by GhostLyiGirl** [inkstitch/inkstitch#2746]
Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\cleanup.py", line 41, in effect
  File "lib\elements\fill_stitch.py", line 274, in shape
AttributeError: 'LineString' object has no attribute 'geoms'
![badge](https://github.com/inkstitch/inkstitch/assets/161746912/01160d07-b8de-47c5-b9e0-ef85d2aabda0)

**Comment by tyrosinase** [comment]
You should upgrade to the current version of Ink/Stitch; this is a known (and fixed) bug in older versions.

Once you do that, it will export without error but Troubleshoot will point out some things that need fixed.
