### ISSUE TITLE
Error during saving 

### ISSUE THREAD

**Issue by Wyvernizgod** [inkstitch/inkstitch#2747]
Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 714, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 759, in do_underlay
  File "lib\debug.py", line 231, in decorated
  File "lib\stitches\auto_fill.py", line 67, in auto_fill
  File "lib\stitches\fill.py", line 155, in intersect_region_with_grating
  File "shapely\geometry\base.py", line 960, in coords
NotImplementedError: Multi-part geometries do not provide a coordinate sequence
![cc-691 2-sarota acantus- s](https://github.com/inkstitch/inkstitch/assets/161785785/7821aff3-986b-4f34-93de-9c1c0534a03c)

**Comment by Marif91** [comment]
Impossible de broder ce motif, il n'est pas optimisé pour du travail avec des fils.

**Comment by kaalleen** [comment]
The error should be fixed in the current development branches. Still, the file isn't very suitable for embroidery as Marif said.
Since the error is fixed, I'll close the issue. If you have more questions, please don't hesitate to post them here.
