### ISSUE TITLE
erreur pour lettrage le long d'un chemin

### ISSUE THREAD

**Issue by mamilene** [inkstitch/inkstitch#2753]
Impossible d’obtenir un lettrage suivant un chemin avec la police Dino mouse 72, alors que je peux l'obtenir avec d'autres polices

Message d’erreur :

Traceback (most recent call last):

File "inkstitch.py", line 84, in <module>

File "inkex\base.py", line 250, in run

File "lib\extensions\lettering_along_path.py", line 37, in effect

File "lib\extensions\lettering_along_path.py", line 37, in <listcomp>

TypeError: object of type 'NoneType' has no len()
![lettrage le long d'un chemin](https://github.com/inkstitch/inkstitch/assets/126922092/7b68b282-6681-4638-962f-11024c9c6627)

**Comment by kaalleen** [comment]
Thank you for your error report. Definitely a bug we need to fix.

In `A` and in `a` are sub-groups in the glyph-group. Ungroup them (only the sub-groups `g4770` and `g16040`) and the lettering along path extension will work fine.
