### ISSUE TITLE
Agencement automatique des points droits

### ISSUE THREAD

**Issue by Ely22** [inkstitch/inkstitch#2756]
I got the following error while trying to automatically agence straight points : 
![graminV2_light](https://github.com/inkstitch/inkstitch/assets/26736811/bcd5a4d9-f94e-4d60-a082-5e1f8758a9d8)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\auto_run.py", line 35, in effect
  File "lib\stitches\auto_run.py", line 125, in autorun
  File "lib\stitches\utils\autoroute.py", line 32, in find_path
  File "networkx\algorithms\shortest_paths\generic.py", line 165, in shortest_path
  File "networkx\algorithms\shortest_paths\unweighted.py", line 224, in bidirectional_shortest_path
  File "networkx\algorithms\shortest_paths\unweighted.py", line 292, in _bidirectional_pred_succ
networkx.exception.NetworkXNoPath: No path between POINT (177.7058286968022 559.0384312531) and POINT (275.39905810160053 159.69067259612405).

**Comment by tyrosinase** [comment]
What version of Ink/Stitch are you running? This looks like the same error as #2604, which is fixed by #2645.

**Comment by Ely22** [comment]
Hello, I was on Inkscape 1.2.2, so It might indeed be fixed in the next
version. Thank you !

**Comment by kaalleen** [comment]
I think the fix isn't in any official release yet. The error is only showing up with the preserve order option enabled. Maybe you can disable it?

**Comment by tyrosinase** [comment]
Oh wait, 2645 isn't in the current?

(I really should learn how Github shows what is in what branches/releases/whatsits. I was just thinking the date looked old enough.)

**Comment by kaalleen** [comment]
Ha yes, it's almost a year since the last release. Time moves on so quickly.
Maybe this page here can help you to keep track of what happened after the release: https://inkstitch.org/upcoming/
I always try to keep it up to date.
