### ISSUE TITLE
cant save my file as a stitch files

### ISSUE THREAD

**Issue by kylacrawford88** [inkstitch/inkstitch#2759]
Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\output.py", line 56, in effect
  File "lib\extensions\base.py", line 133, in elements_to_stitch_groups
  File "lib\elements\element.py", line 558, in embroider
  File "lib\elements\fill_stitch.py", line 703, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 739, in do_legacy_fill
  File "lib\stitches\fill.py", line 18, in legacy_fill
  File "lib\stitches\fill.py", line 98, in intersect_region_with_grating
ValueError: not enough values to unpack (expected 4, got 0)

![sketch loom label 2](https://github.com/inkstitch/inkstitch/assets/162386760/424905df-7d93-4580-94a7-441d7db24c3

**Comment by kaalleen** [comment]
Seems as if the upload didn't work. The error message is known as supposed to be fixed in the next official release.
Usually the problem appeared, when there was a fill on for example satin columns. So it'd be best if you check your color settings on your paths.

**Comment by kylacrawford88** [comment]
Thank you, I had a few stray paths
