### ISSUE TITLE
lxml.etree._Element' object has no attribute 'root' (tartan pre-release)

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#2763]
Got an interesting error in a satin-to-stroke: 

```Debian GNU/Linux 12 (bookworm)

Ink/Stitch Version: tartan (linux)

Traceback (most recent call last):
  File "inkstitch.py", line 137, in <module>
  File "inkex/base.py", line 252, in run
  File "lib/extensions/convert_to_stroke.py", line 52, in effect
  File "inkex/elements/_base.py", line 741, in insert
  File "inkex/elements/_base.py", line 691, in __element_adder
  File "inkex/elements/_base.py", line 684, in _remove_from_tree_callback
AttributeError: 'lxml.etree._Element' object has no attribute 'root'
```
![BadSatinToStroke](https://github.com/inkstitch/inkstitch/assets/9473609/bc5999da-065b-43e9-a5db-18325f1a2a8a)

FWIW I was just doing a little manual routing; letting autoroute do its thing didn't cause any issues (I assume it shares some code).

**Comment by kaalleen** [comment]
Thank you for this. This happens due to some outdated parts of the code.
