### ISSUE TITLE
Too many color changes

### ISSUE THREAD

**Issue by estephens38** [inkstitch/inkstitch#2768]
Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\output.py", line 65, in effect
  File "lib\output.py", line 109, in write_embroidery_file
  File "pyembroidery\EmbPattern.py", line 1727, in static_write
  File "pyembroidery\EmbPattern.py", line 1644, in write_embroidery
  File "pyembroidery\PesWriter.py", line 50, in write
  File "pyembroidery\PesWriter.py", line 110, in write_version_1
  File "pyembroidery\PecWriter.py", line 40, in write_pec
  File "pyembroidery\PecWriter.py", line 64, in write_pec_header
AssertionError: too many color changes, (434) out of bounds (0, 255)

**Comment by tyrosinase** [comment]
This is the same issue as #2574, which has some input on how to fix the underlying issue.

**Comment by estephens38** [comment]
This is a file I purchased, so I am not sure which of those steps to take
specific to this file. Can you please clarify a bit more on which parts
need to be adjusted?

*Elizabeth Stephens*
***@***.***
(706)224-7811

**Comment by tyrosinase** [comment]
Hard to say without seeing the file, but what is happening is exactly what the error message says: there are more color changes than the PES format is capable of expressing (I think the limit is a single byte, so 255 or 256). Even if the file could handle it, you really don't want to rethread your machine that often, so you need to arrange your file so that objects of the same color are grouped together.

If you have objects with both a fill and stroke (of different colors), you will want to duplicate the object and set one to the fill and the other to the stroke, so that you can restack them with their respective colors.
