### ISSUE TITLE
Can't get PES file (param will not build)

### ISSUE THREAD

**Issue by mg1933** [inkstitch/inkstitch#2783]
shapely.geos - ERROR - TopologyException: side location conflict at 58.168179407717339 88.757252996743546. This can occur if the input geometry is invalid.
shapely.geos - INFO - Self-intersection at or near point 56.707715330536651 87.297501003844403

Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v3.0.1 (osx)

Traceback (most recent call last):
  File "shapely/geometry/multipolygon.py", line 189, in geos_multipolygon_from_polygons
TypeError: 'Polygon' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 250, in run
  File "lib/extensions/troubleshoot.py", line 33, in effect
  File "lib/elements/fill_stitch.py", line 608, in validation_errors
  File "lib/elements/fill_stitch.py", line 542, in shape
  File "lib/elements/fill_stitch.py", line 592, in _get_clipped_path
  File "shapely/geometry/multipolygon.py", line 60, in __init__
  File "shapely/geometry/multipolygon.py", line 191, in geos_multipolygon_from_polygons
AttributeError: 'list' object has no attribute '_ndim'
![Ava](https://github.com/inkstitch/inkstitch/assets/157073432/b4df5622-7e84-4c94-b49e-cc0621b57393)

**Comment by kaalleen** [comment]
This seems to work ok in newer versions.
For now you'll have to:
* Select all elements
* Object > Clip > Release Clip
* You'll then see a lot of black squares. You can select them all by click, hold alt and drag over an edge of the black squares.
* Then delete them.
Everything should render now ok, But it should be optimized for better embroidery quality.
