### ISSUE TITLE
Cannot save files as DST due to satin stich error

### ISSUE THREAD

**Issue by Helpplz11** [inkstitch/inkstitch#2786]
Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\troubleshoot.py", line 33, in effect
  File "lib\elements\satin_column.py", line 652, in validation_errors
  File "lib\elements\satin_column.py", line 1262, in to_stitch_groups
  File "lib\elements\satin_column.py", line 1090, in do_satin
  File "lib\debug.py", line 231, in decorated
  File "lib\elements\satin_column.py", line 898, in plot_points_on_rails
  File "lib\elements\satin_column.py", line 629, in flattened_sections
  File "lib\elements\satin_column.py", line 629, in <listcomp>
IndexError: tuple index out of range

![drawing](https://github.com/inkstitch/inkstitch/assets/163626109/15b1ea80-d51d-48d6-b4c4-c5d2feaa272a)

**Comment by kaalleen** [comment]
![satin_path](https://github.com/inkstitch/inkstitch/assets/36401965/07a234be-508a-4dba-8973-3185b820809b)

These two are marked as satin column although they have only one path. Select them and open the params dialog and set this to running stitch.
