### ISSUE TITLE
Error in auto route satin columns

### ISSUE THREAD

**Issue by kejessop** [inkstitch/inkstitch#2788]
I keep getting this error when trying to auto route satin columns, but I am not sure what is causing it.

Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\auto_satin.py", line 74, in effect
  File "lib\stitches\auto_satin.py", line 349, in auto_satin
  File "lib\stitches\auto_satin.py", line 486, in operations_to_elements_and_trims
  File "lib\stitches\auto_satin.py", line 77, in to_satin
  File "lib\elements\satin_column.py", line 720, in split
  File "lib\elements\satin_column.py", line 786, in _assign_rungs_to_split_rails
  File "lib\elements\satin_column.py", line 786, in <genexpr>
AttributeError: 'NoneType' object has no attribute 'intersects'

![hrj](https://github.com/inkstitch/inkstitch/assets/163787105/687a11e0-c37b-4ca6-afdb-4e697da4be65)

**Comment by tyrosinase** [comment]
You have fills, albeit transparent, on those objects. (Which should give you a cleaner error, but doesn't on the current release.)

**Comment by kaalleen** [comment]
As far as I know this is fixed in current development branches and does the job without any error now.

**Comment by kaalleen** [comment]
I hope removing the fill did help you to solve the issue.
I'll close this one as it is fixed in current dev versions.
If you have more questions, you can still post them here.
