### ISSUE TITLE
Error with preview of fill stitch

### ISSUE THREAD

**Issue by GiGi639** [inkstitch/inkstitch#2789]
Bug when trying view simulator/realistic preview of a fill stitch. Error only occurs when the running stitch is unselected in params. 
SVG attached.

From troubleshoot:
Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\troubleshoot.py", line 33, in effect
  File "lib\elements\satin_column.py", line 652, in validation_errors
  File "lib\elements\satin_column.py", line 1262, in to_stitch_groups
  File "lib\elements\satin_column.py", line 1090, in do_satin
  File "lib\debug.py", line 231, in decorated
  File "lib\elements\satin_column.py", line 898, in plot_points_on_rails
  File "lib\elements\satin_column.py", line 629, in flattened_sections
  File "lib\elements\satin_column.py", line 629, in <listcomp>
IndexError: tuple index out of range

![error](https://github.com/inkstitch/inkstitch/assets/163847560/4cc65473-0432-44cc-bafe-dfb3c8413bd6)

**Comment by GiGi639** [comment]
> Separate the objects into fill-with-no-stroke and stroke-with-no-fill. Ink/Stitch sometimes handles them okay combined, but it's really not intended to do so. It needs to separate the parameters, so it needs to be two objects.

They were two separate objects, I copied them to a new  file to upload here. Issue is present even if I delete one.

**Comment by tyrosinase** [comment]
No, I mean duplicate each object, and remove the fill from one version and the stroke from the other. Otherwise you can't set the parameters properly.

**Comment by GiGi639** [comment]
I don't want the stroke at all, I just want the fill, but it won't save unless I also have the stroke.

**Comment by tyrosinase** [comment]
Hmm. I'm pretty sure the underlying problem is fixed in the next release (I'm able to save it to PES and JEF, but I'm also on Linux rather than Mac). But I think your file got hung up on thinking it's a satin column.

If you go into `Troubleshoot > Remove embroidery settings` it will clear everything. Then you should be able to remove the stroke, then set your fill parameters again and it should be happy.

**Comment by GiGi639** [comment]
I had tried that, but had the same issue. 
I ended up deleting them and re-drawing them and it seems to have fixed the issue. So not sure what I've done differently...
Thanks for your help!
