### ISSUE TITLE
Windows directory path issue

### ISSUE THREAD

**Issue by Edofin** [inkstitch/inkstitch#279]
When I run "Embroidery...", Windows goes to write the pes file and chokes.  It looks like it's doubling all of the Backslashes..
I put "C:\Users\%USERNAME%\Documents\Embroidery\" in the Directory field.

```
Traceback (most recent call last):

  File "inkstitch.py", line 24, in <module>

    binary_name = script_name

  File "inkscape-0.92.3\share\extensions\inkex.py", line 283, in affect

  File "lib\extensions\embroider.py", line 85, in effect

  File "lib\output.py", line 114, in write_embroidery_file

  File "site-packages\pyembroidery\PyEmbroidery.py", line 593, in write

  File "site-packages\pyembroidery\PyEmbroidery.py", line 541, in write_embroidery

IOError: [Errno 2] No such file or directory: 'C:\\Users\\%USERNAME%\\Documents\\Embroidery\\Quik Massage Logo - Embroidery.pes'
```

**Comment by lexelby** [comment]
Hi, thanks for reporting your issue, and welcome to the project!

The doubled slashes aren't actually a problem; that's just how Python shows text with forward slashes when it's printing an error.

I didn't think to make Ink/Stitch handle %variables like that, but it's a great idea and it is super easy to do.  For now, does it work if you enter your actual username in the path?

The other problem here is that you're getting that error traceback.  Ink/Stitch should show you a friendly error message if it can't find the directory you enter.

**Comment by jastinegaming** [comment]
When i used params this is what happens whats the solution about this?
Traceback (most recent call last):

  File "inkstitch.py", line 4, in <module>

    from lib.utils import save_stderr, restore_stderr

  File "C:\Users\DenDenDen\AppData\Roaming\inkscape\extensions\lib\utils\__init__.py", line 1, in <module>

    from geometry import *

  File "C:\Users\DenDenDen\AppData\Roaming\inkscape\extensions\lib\utils\geometry.py", line 1, in <module>

    from shapely.geometry import LineString, Point as ShapelyPoint

ImportError: No module named shapely.geometry
