### ISSUE TITLE
Traceback? Do not understand what any of this means. How do I fix to where I can save as a .pec or .pes file?

### ISSUE THREAD

**Issue by madibliss** [inkstitch/inkstitch#2794]
Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\output.py", line 57, in effect
  File "lib\stitch_plan\stitch_plan.py", line 35, in stitch_groups_to_stitch_plan
  File "lib\stitch_plan\stitch_plan.py", line 115, in new_color_block
  File "lib\stitch_plan\color_block.py", line 16, in __init__
  File "lib\stitch_plan\color_block.py", line 51, in color
  File "lib\threads\color.py", line 36, in __init__
TypeError: 'NoneType' object is not iterable

**Comment by tyrosinase** [comment]
The current Ink/Stitch will give you a more understandable error, and has fixed this issue.
