### ISSUE TITLE
Failed to export

### ISSUE THREAD

**Issue by tpackerbacker** [inkstitch/inkstitch#2796]
Failed on  path20-0-7: Error during autofill! This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues/new

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 729, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 781, in do_auto_fill
  File "lib\debug.py", line 231, in decorated
  File "lib\stitches\auto_fill.py", line 80, in auto_fill
  File "lib\debug.py", line 231, in decorated
  File "lib\stitches\auto_fill.py", line 671, in path_to_stitches
  File "lib\stitches\auto_fill.py", line 632, in travel
  File "networkx\classes\backends.py", line 148, in wrapper
  File "networkx\algorithms\shortest_paths\generic.py", line 173, in shortest_path
  File "networkx\algorithms\shortest_paths\weighted.py", line 2398, in bidirectional_dijkstra
networkx.exception.NetworkXNoPath: No path between (406.60896770493986, 323.1496062992126) and (406.76763000000005, 323.89537453124996).

**Comment by tyrosinase** [comment]
Setting a start/end point for the fill will work around this; it should be fixed in the next release.
