### ISSUE TITLE
Lettering

### ISSUE THREAD

**Issue by njlvr** [inkstitch/inkstitch#2799]
Hello Kaleen,
I've bugged the →.svg of the 'Phags-pa font I am developing.
In a new file as soon as I open the Lettering tool I get this error
I've been correcting the horiz-adv-x attribute of some glyphs manually, maybe the bug is in that area
The →.svg file opens correctly in Inkscape
I'm trying to figure out the problem and will let you know if I find something

Cheers
    enjoliveur

Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\lettering.py", line 494, in effect
  File "lib\extensions\lettering.py", line 62, in __init__
  File "lib\extensions\lettering.py", line 195, in set_font_list
wx._core.wxAssertionError: C++ assertion "(unsigned int)index == pos+i" failed at ..\..\src\msw\bmpcbox.cpp(268) in wxBitmapComboBox::DoInsertItems(): Invalid index for wxBitmapComboBox item

**Comment by njlvr** [comment]
![→](https://github.com/inkstitch/inkstitch/assets/64724381/aaeb5ef4-4938-465e-ab39-1eb5dd63c8f2)

**Comment by njlvr** [comment]
Hello again
I sanitized the file with https://svg.enshrined.co.uk/ and lo! it's working again
I've tried to compare the sanitized and the dirty file but since the file got reorganized entirely there are too many differences ))):
I'm back to work, the Inkstich bug remains though ((: 
I suppose you have enough work already
