### ISSUE TITLE
SVG Font >Editor

### ISSUE THREAD

**Issue by njlvr** [inkstitch/inkstitch#2804]
Hello ink/stitch,
I need your help.
I'm developing the 'Phags-pa font in Satin Columns and I keep running in this error.
When with the SVG Font Editor I push the advance (horiz-adv-x) from 1800 to 2000 on the uniA952.init glyph I can't regenerate the font.json file.
I get the following:
Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\lettering_generate_json.py", line 49, in effect
  File "lib\lettering\kerning.py", line 25, in horiz_adv_x
  File "lib\lettering\kerning.py", line 25, in <listcomp>
ValueError: invalid literal for int() with base 10: '2000,00'

When I make the modification manually in the ->.svg and font.json it works fine.
The error seems easy to correct but I don't have the sources installed currently

Thanks

**Comment by njlvr** [comment]
![→](https://github.com/inkstitch/inkstitch/assets/64724381/677b2023-fb0e-4c4d-8f69-e7c4254a187d)
[font.json](https://github.com/inkstitch/inkstitch/files/14787675/font.json)

**Comment by kaalleen** [comment]
Thank you for the error report and posting your solution as well. I wonder why the comma would end up in the svg. inkscape should know better. Actually my regional standard is comma as well and I can't manage to get the comma written into the file through the svg editor. Anyway, it obviously needs a fix here.

**Comment by kaalleen** [comment]
Which Inkscape version do you use?

**Comment by njlvr** [comment]
Hi Kalleen,
I'm on Inkscape 1.3.2 (091e20e, 2023-11-25, custom)
Should I report the bug to Inkscape instead?
‌
Thanks
 

De : "Kaalleen" ***@***.***>
A : "inkstitch/inkstitch" ***@***.***>,"enjoliveur" ***@***.***>,"Author" ***@***.***>
Envoyé: mardi 2 Avril 2024 18:52
Objet : Re: [inkstitch/inkstitch] SVG Font >Editor (Issue #2804)
 

 

Which Inkscape version do you use?

**Comment by kaalleen** [comment]
Hm, not sure. Ink/Stitch shouldn't fail on it. On the other hand I don't think the svg specs would expect a comma sign there. Maybe we should investigate it first.

**Comment by kaalleen** [comment]
@njlvr Uhm, sorry. I forgot about this issue.

I think it'd be a good idea to report it to Inkscape. In the line of don't save a comma value into the svg, but use a dot as a decimal separator. Would you do that?

**Comment by kaalleen** [comment]
Maybe test first if this is still happening with 1.4
