### ISSUE TITLE
Too many color changes

### ISSUE THREAD

**Issue by Brodli4** [inkstitch/inkstitch#2815]
nk/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\output.py", line 65, in effect
  File "lib\output.py", line 109, in write_embroidery_file
  File "pyembroidery\EmbPattern.py", line 1727, in static_write
  File "pyembroidery\EmbPattern.py", line 1644, in write_embroidery
  File "pyembroidery\PesWriter.py", line 50, in write
  File "pyembroidery\PesWriter.py", line 110, in write_version_1
  File "pyembroidery\PecWriter.py", line 40, in write_pec
  File "pyembroidery\PecWriter.py", line 64, in write_pec_header
AssertionError: too many color changes, (1617) out of bounds (0, 255)

**Comment by tyrosinase** [comment]
The error message needs improved, but the way to fix your file is found in #2574. I'm going to close this as a duplicate (though you can continue to reply here if you need clarification).
