### ISSUE TITLE
satin_column.py: tuple index out of range

### ISSUE THREAD

**Issue by VERCHOO** [inkstitch/inkstitch#2822]
Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

Error occurred when trying to save to my required .dst format.

Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\troubleshoot.py", line 33, in effect
  File "lib\elements\satin_column.py", line 652, in validation_errors
  File "lib\elements\satin_column.py", line 1262, in to_stitch_groups
  File "lib\elements\satin_column.py", line 1090, in do_satin
  File "lib\debug.py", line 231, in decorated
  File "lib\elements\satin_column.py", line 898, in plot_points_on_rails
  File "lib\elements\satin_column.py", line 629, in flattened_sections
  File "lib\elements\satin_column.py", line 629, in <listcomp>
IndexError: tuple index out of range

**Comment by tyrosinase** [comment]
This is a known bug fixed in an upcoming release, but the underlying problem is that you have at least one object marked as a satin column that only has one rail - either a running stitch that got accidentally marked as satin, or a satin whose other rail got deleted or whose rails got combined.

**Comment by VERCHOO** [comment]
Thanks for jumping on this so quickly.  However, I did re-create the path that was giving an error on another design, and the error would just move to the next path up the list.  When is the upcoming version slated for release?

**Comment by tyrosinase** [comment]
I'm not sure (it is always a surprise to me) but if you look on the main page, if you click on the `+340 releases` it will take you to all kinds of working releases. That fix is fairly old, so it should be incorporated in almost all of them so you can pick one that sounds fun (I'm playing with the tartan ones myself) or just one that sounds pretty safe (e.g. font fixes).

![image](https://github.com/inkstitch/inkstitch/assets/9473609/3fd4a340-3921-47a7-8953-f97b02b53682)
