### ISSUE TITLE
Ink/Stitch Error

### ISSUE THREAD

**Issue by mee002** [inkstitch/inkstitch#2823]
Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 714, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 759, in do_underlay
  File "lib\debug.py", line 231, in decorated
  File "lib\stitches\auto_fill.py", line 80, in auto_fill
  File "lib\debug.py", line 231, in decorated
  File "lib\stitches\auto_fill.py", line 671, in path_to_stitches
  File "lib\stitches\auto_fill.py", line 632, in travel
  File "networkx\classes\backends.py", line 148, in wrapper
  File "networkx\algorithms\shortest_paths\generic.py", line 173, in shortest_path
  File "networkx\algorithms\shortest_paths\weighted.py", line 2398, in bidirectional_dijkstra
networkx.exception.NetworkXNoPath: No path between (204.64878599938504, 94.31961298224536) and (203.9861967305047, 95.74874927958751).
![ghost dog](https://github.com/inkstitch/inkstitch/assets/165967920/fb692b0a-ee1c-4bdb-9fee-001fbfed8c18)

**Comment by tyrosinase** [comment]
Setting a start/end point for the fill will work around this; it should be fixed in the next release.
