### ISSUE TITLE
Too many color changes

### ISSUE THREAD

**Issue by reboiled** [inkstitch/inkstitch#2827]
Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\output.py", line 65, in effect
  File "lib\output.py", line 109, in write_embroidery_file
  File "pyembroidery\EmbPattern.py", line 1727, in static_write
  File "pyembroidery\EmbPattern.py", line 1644, in write_embroidery
  File "pyembroidery\PecWriter.py", line 32, in write
  File "pyembroidery\PecWriter.py", line 40, in write_pec
  File "pyembroidery\PecWriter.py", line 64, in write_pec_header
AssertionError: too many color changes, (789) out of bounds (0, 255)

every time i use Ink/Stitch i alwase get this error i don't know how to fix it and i watched every youtube vid about it but nothing worked
![Uploading Screenshot 2024-04-05 133006.png…]()

**Comment by tyrosinase** [comment]
The error message needs improved, but the way to fix your file is found in #2574. I'm going to close this as a duplicate (though you can continue to reply here if you need clarification, and reopen it if that's not what's happening in your file - the screenshot didn't come through).
