### ISSUE TITLE
Inkstitch zigzag to satin stitch error

### ISSUE THREAD

**Issue by ChanteeH** [inkstitch/inkstitch#2852]
Hi all! I have an Eversew embroidery machine and I'm really new to this whole thing. I'm trying to get my embroidery pattern set up and it's currently a zigzag saved as an xxx file (because that's what the machine will recognize). I've attached the file if that helps any.
![Unbenanntes_ProjektReduxSingleForTest](https://github.com/inkstitch/inkstitch/assets/167699318/ecf589f8-d66a-4b5d-b155-22322cbb170d)

Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\zigzag_line_to_satin.py", line 41, in effect
  File "lib\extensions\zigzag_line_to_satin.py", line 167, in _smooth_path
  File "inkex\transforms.py", line 1178, in point_at_length
ZeroDivisionError: float division by zero

**Comment by tyrosinase** [comment]
According to kaalleen in #2765 this is fixed in the upcoming release. See if the comments in that issue give you a workaround in the meantime.

**Comment by kaalleen** [comment]
Yes, it should be fixed. Though it won't produce any usable result on the posted design.
This is how it is used: https://inkstitch.org/docs/satin-tools/#zigzag-line-to-satin

**Comment by kaalleen** [comment]
I closed the issue, because the original error has been fixed.
If you have further questions, you can still use this issue to post them.
