### ISSUE TITLE
EmptyPartError in ensure_multi_line_string

### ISSUE THREAD

**Issue by dhard00** [inkstitch/inkstitch#2861]
Traceback (most recent call last):
  File "lib/elements/element.py", line 594, in handle_unexpected_exceptions
  File "lib/elements/element.py", line 562, in embroider
  File "lib/elements/fill_stitch.py", line 724, in to_stitch_groups
  File "lib/elements/fill_stitch.py", line 772, in do_auto_fill
  File "lib/debug.py", line 231, in decorated
  File "lib/stitches/auto_fill.py", line 80, in auto_fill
  File "lib/debug.py", line 231, in decorated
  File "lib/stitches/auto_fill.py", line 317, in build_travel_graph
  File "lib/stitches/auto_fill.py", line 467, in build_travel_edges
  File "lib/utils/geometry.py", line 109, in ensure_multi_line_string
  File "shapely/geometry/multilinestring.py", line 52, in __new__
shapely.errors.EmptyPartError: Can't create MultiLineString with empty component

**Comment by kaalleen** [comment]
Thank you for the error report. Do you still have the svg file which was causing the error? It would help a lot in order to solve the issue.
