### ISSUE TITLE
Error Message (Cannot save file as PES or PEC)

### ISSUE THREAD

**Issue by ShermanCSB** [inkstitch/inkstitch#2880]
File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\troubleshoot.py", line 33, in effect
  File "lib\elements\satin_column.py", line 652, in validation_errors
  File "lib\elements\satin_column.py", line 1262, in to_stitch_groups
  File "lib\elements\satin_column.py", line 1090, in do_satin
  File "lib\debug.py", line 231, in decorated
  File "lib\elements\satin_column.py", line 898, in plot_points_on_rails
  File "lib\elements\satin_column.py", line 629, in flattened_sections
  File "lib\elements\satin_column.py", line 629, in <listcomp>
IndexError: tuple index out of range

![ErrorFILE](https://github.com/inkstitch/inkstitch/assets/168975069/0aad859f-6b32-4879-847c-84244f786a9a)

**Comment by tyrosinase** [comment]
This is a known bug, fixed in dev releases. To work around it (if you don't want to install a dev release), take a look at issue #2514 and see if that solves your problem.

**Comment by ShermanCSB** [comment]
Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\select_elements.py", line 47, in effect
  File "subprocess.py", line 858, in __init__
  File "subprocess.py", line 1311, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
 
@tyrosinase I have this error message popped up when I tried using the solution at issue #2514. 
Will reinstalling the application solve this issue? Please advice

**Comment by tyrosinase** [comment]
I'm not a WIndows person so I might be wrong, but I'm pretty sure that's a separate problem: it can't find the Python executable. Try the fix for that here https://inkstitch.org/docs/edit/#troubleshoot and see if that does it.

**Comment by kaalleen** [comment]
The select elements extension did break with an inkscape update but should be fixed for the next Ink/Stitch release.

For now you can use the objects and layers dialog. Select all the paths labeled as "Points droits pour auto-remplissage satin ##" and run params. Mark them as running stitches and you should be fine.
