### ISSUE TITLE
Error with satin stich creation

### ISSUE THREAD

**Issue by MadMurdocIII** [inkstitch/inkstitch#2882]
Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\auto_satin.py", line 67, in effect
  File "lib\extensions\auto_satin.py", line 67, in <listcomp>
  File "lib\elements\satin_column.py", line 832, in center_line
  File "lib\debug.py", line 231, in decorated
  File "lib\elements\satin_column.py", line 898, in plot_points_on_rails
  File "lib\elements\satin_column.py", line 629, in flattened_sections
  File "lib\elements\satin_column.py", line 629, in <listcomp>
IndexError: tuple index out of range

**Comment by tyrosinase** [comment]
This is a known bug, fixed in dev releases. To work around it (if you don't want to install a dev release), take a look at issue #2514 and see if that solves your problem.
