### ISSUE TITLE
Try to save my svg to vp3

### ISSUE THREAD

**Issue by xdexx7** [inkstitch/inkstitch#2889]
I just tried to save my file as vp3, but the program gives me the following error message. When I try to troubleshoot the file via Inkstitch I get the following error message.

(Ink/Stitch Version: v3.0.1 (windows))

Saving message:
Failed on  Red (rect2-1-7): Satin column: Object has too few subpaths.  
A satin column should have at least two subpaths (the rails).

Please run Extensions > Ink/Stitch > Troubleshoot > Troubleshoot objects. This will indicate the errorneus position.

After Troubleshoot Message:
Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\troubleshoot.py", line 33, in effect
  File "lib\elements\satin_column.py", line 652, in validation_errors
  File "lib\elements\satin_column.py", line 1262, in to_stitch_groups
  File "lib\elements\satin_column.py", line 1090, in do_satin
  File "lib\debug.py", line 231, in decorated
  File "lib\elements\satin_column.py", line 898, in plot_points_on_rails
  File "lib\elements\satin_column.py", line 629, in flattened_sections
  File "lib\elements\satin_column.py", line 629, in <listcomp>
IndexError: tuple index out of range

**Comment by tyrosinase** [comment]
This is a known bug, fixed in dev releases. On the current release, you just have to figure out what the problem column is by hand (if you have a lot of them, you should be able to select just part of your image and do a preview, to narrow it down).

If you want to try a dev release, it's pretty easy. The hardest part is picking which one to try out, but right now everything's pretty close to release and you can just grab whatever one comes up first. There are some notes on doing it at https://silverseams.com/2024/04/installing-pre-releases.html. Holler if you run into any trouble with it.
