### ISSUE TITLE
Fill compensation bug in test version treffen-2024 (linux)

### ISSUE THREAD

**Issue by danielkschneider** [inkstitch/inkstitch#2910]
Ubuntu 22.04.3 LTS

Ink/Stitch Version: treffen-2024 (linux)

Traceback (most recent call last):
  File "lib/elements/element.py", line 640, in handle_unexpected_exceptions
  File "lib/elements/element.py", line 604, in embroider
  File "lib/elements/fill_stitch.py", line 945, in to_stitch_groups
  File "lib/elements/fill_stitch.py", line 1027, in do_auto_fill
  File "lib/debug/debug.py", line 166, in decorated
  File "lib/stitches/auto_fill.py", line 94, in auto_fill
  File "lib/stitches/fill.py", line 158, in intersect_region_with_grating
  File "shapely/geometry/base.py", line 599, in intersection
  File "shapely/decorators.py", line 77, in wrapped
  File "shapely/set_operations.py", line 131, in intersection
shapely.errors.GEOSException: TopologyException: side location conflict at 190.19735524875298 133.79112593957416. This can occur if the input geometry is invalid.

![patch-100mm-ghost-satin-irregular-last](https://github.com/inkstitch/inkstitch/assets/2872643/09a0a19c-c224-437e-96cd-9c1e2e27bc81)

I did check the "ghosts" and ran remove duplicate nodes + segments plus close path repair routines. The geometry does look OK.
[Edit] I also re-tested the same file with inkstitch_0.0.1.lexelby.auto.fill.gap.fix_amd64.deb and there was no error.

**Comment by lexelby** [comment]
Got it, thanks!  I think I know what's going on here and how to fix it.

I'm gonna close this issue in favor of discussing in the PR.
