### ISSUE TITLE
Won't let me save files as PES due to a bug in Ink/Stitch

### ISSUE THREAD

**Issue by hhsewing** [inkstitch/inkstitch#2921]
nk/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: 3.0.1 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 231, in run
  File "lib/extensions/output.py", line 65, in effect
  File "lib/output.py", line 109, in write_embroidery_file
  File "pyembroidery/EmbPattern.py", line 1727, in static_write
  File "pyembroidery/EmbPattern.py", line 1644, in write_embroidery
  File "pyembroidery/PesWriter.py", line 50, in write
  File "pyembroidery/PesWriter.py", line 110, in write_version_1
  File "pyembroidery/PecWriter.py", line 40, in write_pec
  File "pyembroidery/PecWriter.py", line 64, in write_pec_header
AssertionError: too many color changes, (443) out of bounds (0, 255)

**Comment by tyrosinase** [comment]
The error message needs improved, but the way to fix your file is found in #2574. I'm going to close this as a duplicate (though you can continue to reply here if you need clarification, and reopen it if that's not what's happening in your file).
