### ISSUE TITLE
Ink Stitch error

### ISSUE THREAD

**Issue by Compass2003** [inkstitch/inkstitch#2939]
Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\simulator.py", line 17, in effect
  File "lib\extensions\base.py", line 118, in get_elements
  File "lib\extensions\base.py", line 115, in get_nodes
![JUMP POOD](https://github.com/inkstitch/inkstitch/assets/170590253/e2563b4f-ce82-412f-a4f8-439ae0f439f0)

Issue started when trying to visualize the stitch out. I have the most current ink stitch and ink scape.

**Comment by Compass2003** [comment]
Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v3.0.1 (windows)


Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "lib\extensions\input.py", line 22, in run
  File "lib\stitch_plan\generate_stitch_plan.py", line 22, in generate_stitch_plan
  File "pyembroidery\EmbPattern.py", line 1560, in static_read
  File "pyembroidery\EmbPattern.py", line 1493, in read_embroidery
  File "pyembroidery\PesReader.py", line 66, in read
TypeError: 'NoneType' object cannot be interpreted as an integer


This happened while trying to open a file my friend sent me

**Comment by kaalleen** [comment]
Can you delete the command at the dogs ear. It is broken and it is causing issues. I tested your file on current development versions only. So I am not completely sure this will solve the problem full for you. In dev versions it does.

I moved your second issue into a new thread, so we can discuss it separately. Can you send the pes file? If it cannot be posted publicly I can send you a link to send it to developers only.
