### ISSUE TITLE
Unable to save Error

### ISSUE THREAD

**Issue by digitaldiane** [inkstitch/inkstitch#2940]
Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: 3.0.1 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 231, in run
  File "lib/extensions/output.py", line 57, in effect
  File "lib/stitch_plan/stitch_plan.py", line 35, in stitch_groups_to_stitch_plan
  File "lib/stitch_plan/stitch_plan.py", line 115, in new_color_block
  File "lib/stitch_plan/color_block.py", line 16, in __init__
  File "lib/stitch_plan/color_block.py", line 51, in color
  File "lib/threads/color.py", line 36, in __init__
TypeError: 'NoneType' object is not iterable

**Comment by kaalleen** [comment]
Please try to apply a color through the color palette shown at the bottom of the inkscape window (right click for fill, left click for stroke)

**Comment by kaalleen** [comment]
Issue is supposed to be fixed in main. Please reopen if this happens again with any upcoming Ink/Stitch version.
