### ISSUE TITLE
Pb de broderie satin

### ISSUE THREAD

**Issue by YES4664** [inkstitch/inkstitch#2944]
Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\output.py", line 56, in effect
  File "lib\extensions\base.py", line 133, in elements_to_stitch_groups
  File "lib\elements\element.py", line 558, in embroider
  File "lib\elements\fill_stitch.py", line 703, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 739, in do_legacy_fill
  File "lib\stitches\fill.py", line 18, in legacy_fill
  File "lib\stitches\fill.py", line 98, in intersect_region_with_grating
ValueError: not enough values to unpack (expected 4, got 0)
![ROUTE46](https://github.com/inkstitch/inkstitch/assets/170959263/6a1b5f4a-2587-4e42-a37b-cb867fcc53a9)

**Comment by tyrosinase** [comment]
This is fixed in the upcoming release, but in the meantime: remove the fill from your satin to fix the error.
