### ISSUE TITLE
satin_column.py: tuple index out of range

### ISSUE THREAD

**Issue by FlameGoddess** [inkstitch/inkstitch#2947]
I was trying to add a running stitch to tack but I can't get a realistic preview. I took out the last running stitch but it's still got issues.

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\troubleshoot.py", line 33, in effect
  File "lib\elements\satin_column.py", line 652, in validation_errors
  File "lib\elements\satin_column.py", line 1262, in to_stitch_groups
  File "lib\elements\satin_column.py", line 1090, in do_satin
  File "lib\debug.py", line 231, in decorated
  File "lib\elements\satin_column.py", line 898, in plot_points_on_rails
  File "lib\elements\satin_column.py", line 629, in flattened_sections
  File "lib\elements\satin_column.py", line 629, in <listcomp>
IndexError: tuple index out of range
![mid ga logo no bow patch](https://github.com/inkstitch/inkstitch/assets/171063120/343c8a71-daba-42c1-a180-83a7419d665f)

**Comment by tyrosinase** [comment]
This is a known bug, fixed in dev releases. To work around it (if you don't want to install a dev release), take a look at issue #2514 and see if that solves your problem - it's almost certainly a single line marked as a satin.

**Comment by FlameGoddess** [comment]
Thanks, I think then it was a running stitch that I added for tacking some backing on that got confused since I put it as the same color.
