### ISSUE TITLE
PES Reader: NoneType object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by kaalleen** [inkstitch/inkstitch#2955]
Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "lib\extensions\input.py", line 22, in run
  File "lib\stitch_plan\generate_stitch_plan.py", line 22, in generate_stitch_plan
  File "pyembroidery\EmbPattern.py", line 1560, in static_read
  File "pyembroidery\EmbPattern.py", line 1493, in read_embroidery
  File "pyembroidery\PesReader.py", line 66, in read
TypeError: 'NoneType' object cannot be interpreted as an integer

This happened while trying to open a file my friend sent me

_Originally posted by @Compass2003 in https://github.com/inkstitch/inkstitch/issues/2939#issuecomment-2127790935_

**Comment by kaalleen** [comment]
Closing in favor of #3041 (still no file received)
