### ISSUE TITLE
Ink/Stitch eroneously classifying a Fillstitch as a Satin Stitch, Wont save as a .Jef

### ISSUE THREAD

**Issue by Fluffynator** [inkstitch/inkstitch#2956]
Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\troubleshoot.py", line 33, in effect
  File "lib\elements\satin_column.py", line 652, in validation_errors
  File "lib\elements\satin_column.py", line 1262, in to_stitch_groups
  File "lib\elements\satin_column.py", line 1090, in do_satin
  File "lib\debug.py", line 231, in decorated
  File "lib\elements\satin_column.py", line 898, in plot_points_on_rails
  File "lib\elements\satin_column.py", line 629, in flattened_sections
  File "lib\elements\satin_column.py", line 629, in <listcomp>
IndexError: tuple index out of range

![AssClass Vector](https://github.com/inkstitch/inkstitch/assets/25840667/aceddad2-39a5-4789-8f82-62236d9fc71e)

**Comment by tyrosinase** [comment]
Not sure how it gets hung up like that, but if you go into Troubleshooting and clear the embroidery settings and re-set any changes you made to the Fill params, it will get rid of the problematic satin settings.
