### ISSUE TITLE
Ink Stitch issue

### ISSUE THREAD

**Issue by Tuck3r23** [inkstitch/inkstitch#2957]
Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\troubleshoot.py", line 33, in effect
  File "lib\elements\satin_column.py", line 652, in validation_errors
  File "lib\elements\satin_column.py", line 1262, in to_stitch_groups
  File "lib\elements\satin_column.py", line 1090, in do_satin
  File "lib\debug.py", line 231, in decorated
  File "lib\elements\satin_column.py", line 898, in plot_points_on_rails
  File "lib\elements\satin_column.py", line 629, in flattened_sections
  File "lib\elements\satin_column.py", line 629, in <listcomp>
IndexError: tuple index out of range

![Cardinals wordmark](https://github.com/inkstitch/inkstitch/assets/171505321/0cc99d53-a990-4446-86e1-5c40db79f605)

**Comment by Tuck3r23** [comment]
I have set each letter to a satin column in params and the preview in params looks correct but does not turn out how params shows

**Comment by tyrosinase** [comment]
![image](https://github.com/inkstitch/inkstitch/assets/9473609/d3199e5d-2582-453a-ae53-3880e652e842)

You have a number of things set to satin that are single-path; params ignores them but the actual stitchout doesn't. Troubleshooting will catch it if you update to a dev release, but if you clean those up the current release will handle it fine.
