### ISSUE TITLE
unexpected error

### ISSUE THREAD

**Issue by rmhoward33322** [inkstitch/inkstitch#2963]
Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\params.py", line 793, in effect
wx._core.wxAssertionError: C++ assertion "idx < m_size" failed at C:\PROJECTS\bb2\dist-win32-py38\build\ext\wxWidgets\include\wx/vector.h(498) in wxVector<class wxDisplayImpl *>::at(): 

![Victory Sports Logo 2020_Official exploded](https://github.com/inkstitch/inkstitch/assets/128925768/e4a81b36-03b7-4449-a9b5-56d5e7e084b7)

**Comment by kaalleen** [comment]
It looks as if you don't use one of our builds. Can you describe how you installed Ink/Stitch?

**Comment by rmhoward33322** [comment]
I looked up ink/stitch in google.

Took me to inkstitch.org

Under the heading “NEWS” there were 4 version choices, I selected 3.01, downloaded and installed it.

**Comment by kaalleen** [comment]
Huh, ok. The path looks a bit strange I thought... Well... then let's investigate.
Which display do you have and what is your screen resolution?

**Comment by rmhoward33322** [comment]
Not sure what you are asking about the display, it’s the screen on my laptop, resolution is 3840 x 2400.

**Comment by kaalleen** [comment]
Because the error message indicates, that it is having issues with your display.
Would you mind to try out a recent development build to see if you are still seeing the error message?
Try for example: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-rejbasket-version-geos-update
Pick the exe file for your system (most probably 64bit).

**Comment by kaalleen** [comment]
You will also need to simplify your design. Those small dots aren't well suited for embroidery. It would be a hard challenge to stitch them out.

**Comment by rmhoward33322** [comment]
When I received the error, I didn’t have the small dots selected. In fact the only thing selected was



And the program did a poor job of emulating the image.

**Comment by kaalleen** [comment]
> When I received the error, I didn’t have the small dots selected. In fact the only thing selected was

> And the program did a poor job of emulating the image.

Does this means, that it sometimes works and sometimes not? I would have expected, that the error isn't depending on the current selected elements...

Do you know how to try recent development builds?

**Comment by rmhoward33322** [comment]
I was never able to get the ribbon to translate properly. It always cuts off the ends. This happens when I have just one layer selected or I had all of the layers selected. But the error only displayed when I had the ribbon layer selected by itself. I am new to Inkscape/Inkstitch. I haven’t tried development builds

**Comment by kaalleen** [comment]
Ok, that is an interesting bit of information.

> I haven’t tried development builds

Take for example this build here: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-capellan-fix-filter-whitespace

We are close to a release, so any error report on current development releases is very valuable for us.

**Comment by rmhoward33322** [comment]
How do I use the dev build? Do I uninstall the current installation and install the dev build? I don’t see an install program. If I try to run inkstitch.exe in the bin directory I get this:



thanks

**Comment by tyrosinase** [comment]
I should probably rewrite this to be more general (it was in the context of trying out some new satin features) but https://silverseams.com/2024/04/installing-pre-releases.html will get you on the right track.

**Comment by kaalleen** [comment]
Pick the exe file for your system and run it. It will automatically overwrite previous inkstitch versions.

The installation process doesn't differ from the one for official releases: https://inkstitch.org/docs/install-windows/

**Comment by kaalleen** [comment]
No additional information was send. Meanwhile wxpython has been updated. Issue is probably outdated. Closing.
