### ISSUE TITLE
Unable to save as a .pes file

### ISSUE THREAD

**Issue by PCrosby1** [inkstitch/inkstitch#2977]
following message keeps showing:

e to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\output.py", line 65, in effect
  File "lib\output.py", line 109, in write_embroidery_file
  File "pyembroidery\EmbPattern.py", line 1727, in static_write
  File "pyembroidery\EmbPattern.py", line 1644, in write_embroidery
  File "pyembroidery\PesWriter.py", line 50, in write
  File "pyembroidery\PesWriter.py", line 110, in write_version_1
  File "pyembroidery\PecWriter.py", line 40, in write_pec
  File "pyembroidery\PecWriter.py", line 64, in write_pec_header
AssertionError: too many color changes, (419) out of bounds (0, 255)

**Comment by tyrosinase** [comment]
I believe this is fixed in 3.1.0, but only in that it will give you a cleaner error message. The last line here is the key: you have 419 color changes, and PES files can only handle 255.

Without seeing your image I can't be sure, but 99% of the time it's a conversion of a pre-existing SVG or a traced bitmap. For images destined for the screen, it doesn't matter how many times it switches between drawing two or more colors, but for an embroidery machine that means a thread change every time. Group your colors so that's not happening - in particular, if you have objects that have one color for fill and a different color for outline, break them up into separate fill-only and outline-only objects because Ink/Stitch can only stitch the entire object, both colors, before proceeding to the next.
