### ISSUE TITLE
Save As PES

### ISSUE THREAD

**Issue by DyeMadeIt** [inkstitch/inkstitch#2983]
Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "shapely\geometry\multipolygon.py", line 189, in geos_multipolygon_from_polygons
TypeError: 'Polygon' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\output.py", line 56, in effect
  File "lib\extensions\base.py", line 133, in elements_to_stitch_groups
  File "lib\elements\element.py", line 556, in embroider
  File "lib\elements\element.py", line 616, in validate
  File "lib\elements\fill_stitch.py", line 608, in validation_errors
  File "lib\elements\fill_stitch.py", line 542, in shape
  File "lib\elements\fill_stitch.py", line 592, in _get_clipped_path
  File "shapely\geometry\multipolygon.py", line 60, in __init__
  File "shapely\geometry\multipolygon.py", line 191, in geos_multipolygon_from_polygons
AttributeError: 'list' object has no attribute '_ndim'

**Comment by DyeMadeIt** [comment]
It is probably my error... but thought I would share as requested.

**Comment by kaalleen** [comment]
It's always good to keep us informed about error messages with a traceback. So keep up posting them, when they appear!!
This particular one is supposed to be fixed fir the next release. You can try recent development releases if you wish or try to avoid very small objects in your document.

**Comment by DyeMadeIt** [comment]
Recent development releases.... I'm new to InkStitch... where is this found
or better yet, will you please provide me with a link?

Thank you 😊

**Comment by tyrosinase** [comment]
There should probably be something in the docs about this, but here's an unofficial blog entry on doing it: https://silverseams.com/2024/04/installing-pre-releases.html

**Comment by DyeMadeIt** [comment]
Thanks, I'll check it out.
