### ISSUE TITLE
issue with linear gradient fill

### ISSUE THREAD

**Issue by Augusa** [inkstitch/inkstitch#3001]
message:
Windows 10 version: 10.0.22631

Ink/Stitch Version: short-relative-lock (windows)

Traceback (most recent call last):
  File "lib\elements\element.py", line 640, in handle_unexpected_exceptions
  File "lib\elements\element.py", line 604, in embroider
  File "lib\elements\fill_stitch.py", line 924, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 1182, in do_linear_gradient_fill
  File "lib\stitches\linear_gradient_fill.py", line 27, in linear_gradient_fill
  File "lib\stitches\linear_gradient_fill.py", line 209, in _get_color_lines
IndexError: list index out of range
![i--qfond](https://github.com/inkstitch/inkstitch/assets/54963659/67fff5e6-7b3a-4613-9059-c459c68fa769)

**Comment by kaalleen** [comment]
Thank you for the error report and the file.
I prepared a fix, would you mind testing?
Here is the link: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-fix-linear-gradient

**Comment by Augusa** [comment]
Everything looks to be ok.
I no more had the issue since I send the message.
Thanks for your new release
________________________________
De : Kaalleen ***@***.***>
Envoyé : jeudi 20 juin 2024 18:52
À : inkstitch/inkstitch ***@***.***>
Cc : Augusa ***@***.***>; Author ***@***.***>
Objet : Re: [inkstitch/inkstitch] issue with linear gradient fill (Issue #3001)


Thank you for the error report and the file.
I prepared a fix, would you mind testing?
Here is the link: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-fix-linear-gradient
