### ISSUE TITLE
Ink/stitch is not rendering my satin stitch.  

### ISSUE THREAD

**Issue by sjcgalex** [inkstitch/inkstitch#3005]
https://github.com/inkstitch/inkstitch/issues 

Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\troubleshoot.py", line 33, in effect
  File "lib\elements\satin_column.py", line 652, in validation_errors
  File "lib\elements\satin_column.py", line 1262, in to_stitch_groups
  File "lib\elements\satin_column.py", line 1090, in do_satin
  File "lib\debug.py", line 231, in decorated
  File "lib\elements\satin_column.py", line 898, in plot_points_on_rails
  File "lib\elements\satin_column.py", line 629, in flattened_sections
  File "lib\elements\satin_column.py", line 629, in <listcomp>
IndexError: tuple index out of range

![weglogo](https://github.com/inkstitch/inkstitch/assets/173407435/e3ad938b-4a93-4a68-b34d-4342c010fa17)

**Comment by bianchifan** [comment]
Perhaps you like to try a current development version.
A second try you may give the attached svg and notice the little differences.

![Weg](https://github.com/inkstitch/inkstitch/assets/17491743/0cafd126-f95e-4f82-86fa-93e936354f40)

**Comment by sjcgalex** [comment]
Thanks so much.  After I sent this error I went in and started
troubleshooting.  One of the rungs on the letter G was not grouped; I did
that and it worked like I needed it to.  Thanks so much for your attention
in this matter.

Best regards

Sylvia Galan
*"Vegan for the animals forever"*
IMDB <http://www.imdb.com/name/nm2881112/>
800casting <https://800casting.com/profile/42245#img=1712842090180>
Casting Networks
<https://app.castingnetworks.com/talent/public-profile/79f4b586-666e-11ed-8232-cbdfbba01158>
Actors Access <https://resumes.actorsaccess.com/sylviagalan>
