### ISSUE TITLE
Save as dst

### ISSUE THREAD

**Issue by aynaad** [inkstitch/inkstitch#3014]
Ink/Stitch Version: v3.0.1 (osx)

Traceback (most recent call last):
  File "shapely/geometry/multipolygon.py", line 189, in geos_multipolygon_from_polygons
TypeError: 'Polygon' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 250, in run
  File "lib/extensions/output.py", line 56, in effect
  File "lib/extensions/base.py", line 133, in elements_to_stitch_groups
  File "lib/elements/element.py", line 556, in embroider
  File "lib/elements/element.py", line 616, in validate
  File "lib/elements/fill_stitch.py", line 608, in validation_errors
  File "lib/elements/fill_stitch.py", line 542, in shape
  File "lib/elements/fill_stitch.py", line 592, in _get_clipped_path
  File "shapely/geometry/multipolygon.py", line 60, in __init__
  File "shapely/geometry/multipolygon.py", line 191, in geos_multipolygon_from_polygons
AttributeError: 'list' object has no attribute '_ndim'

**Comment by tyrosinase** [comment]
This is the same issue #2983, fixed in upcoming releases. That issue has info on using a pre-release, or you can just find the very tiny (unstitchably tiny) object and delete it.

I'll close the issue, but you can still comment if you need more help.
