### ISSUE TITLE
PES: TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

### ISSUE THREAD

**Issue by papelivan** [inkstitch/inkstitch#3041]
Ink/Stitch Version: v3.0.1 (windows)
Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "lib\extensions\input.py", line 22, in run
  File "lib\stitch_plan\generate_stitch_plan.py", line 22, in generate_stitch_plan
  File "pyembroidery\EmbPattern.py", line 1560, in static_read
  File "pyembroidery\EmbPattern.py", line 1493, in read_embroidery
  File "pyembroidery\PesReader.py", line 67, in read
  File "pyembroidery\PecReader.py", line 26, in read_pec
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

**Comment by Marif91** [comment]
Ce qui nous aiderait à comprendre c'est ton fichiers svg. As-tu suivi un tuto ?

**Comment by kaalleen** [comment]
I think @papelivan is trying to open a pes file.

Would it be possible for you to send us your pes file? We have seen this error report before, but haven't received any file so we haven't been able to fix the issue (#2506)

If you cannot upload the file for copyright issues, you can also send it to developers through web upload. We will only use it to fix the issue: https://lexneva.name/owncloud/index.php/s/NCcJbJqnKmL7nES

Please notify us about your upload here afterwards.

**Comment by kaalleen** [comment]
In the discussion of issue https://github.com/inkstitch/inkstitch/issues/4088 it turned out, that this error shows up, when a user tries to open empty embroidery files. Well, maybe not empty. When Ink/Stitch tried to save a file with only one image in there, it warns the user about that there is no embroiderable element, but still saves the file (in svg format, with e.g. pes file extension). When a user tries to open this file, this error message will show up.
