### ISSUE TITLE
new issue

### ISSUE THREAD

**Issue by pixi231** [inkstitch/inkstitch#3043]
Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 720, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 824, in do_contour_fill
  File "lib\stitches\contour_fill.py", line 524, in double_spiral
  File "lib\stitches\contour_fill.py", line 531, in _spiral_fill
  File "lib\stitches\contour_fill.py", line 564, in _make_fermat_spiral
  File "lib\stitches\contour_fill.py", line 581, in _make_spiral
UnboundLocalError: local variable 'spiral_part' referenced before assignment

shapely.geos - INFO - Self-intersection at or near point 184.50117411023621 44.301174110236225
shapely.geos - INFO - Self-intersection at or near point 184.50117411023621 44.301174110236225
shapely.geos - INFO - Self-intersection at or near point 187.00117411023621 75.201174110236238
shapely.geos - INFO - Self-intersection at or near point 187.00117411023621 75.201174110236238
shapely.geos - INFO - Self-intersection at or near point 184.50117411023621 44.301174110236225
shapely.geos - INFO - Self-intersection at or near point 184.50117411023621 44.301174110236225
shapely.geos - INFO - Self-intersection at or near point 187.00117411023621 75.201174110236238
![StepIntoLearning-Logo](https://github.com/inkstitch/inkstitch/assets/174741285/a0b9f7c9-a339-404e-bc39-994b854757a4)

**Comment by tyrosinase** [comment]
This is fixed in an upcoming release (per #2518) - you can try a development release or wait for the upcoming release (though I don't think it's scheduled more specifically than "soon" yet).
