### ISSUE TITLE
Gap Filling for fill stitch  in version 3.1 Beta

### ISSUE THREAD

**Issue by danielkschneider** [inkstitch/inkstitch#3052]
Windows 10 version: 10.0.22631

Ink/Stitch Version: v3.1.0beta (windows)

Traceback (most recent call last):
  File "lib\elements\element.py", line 641, in handle_unexpected_exceptions
  File "lib\elements\element.py", line 605, in embroider
  File "lib\elements\fill_stitch.py", line 961, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 1044, in do_auto_fill
  File "lib\debug\debug.py", line 166, in decorated
  File "lib\stitches\auto_fill.py", line 116, in auto_fill
  File "lib\debug\debug.py", line 166, in decorated
  File "lib\stitches\auto_fill.py", line 900, in path_to_stitches
  File "lib\stitches\fill.py", line 84, in stitch_row
  File "lib\utils\geometry.py", line 294, in unit
ZeroDivisionError: float division by zero

I like the victim SVG ;) The offending object is "face"

![face-with-head-bandage-fluent-inkstitch](https://github.com/inkstitch/inkstitch/assets/2872643/19158f58-a23d-4c46-84f4-11d75b0ff827)

**Comment by kaalleen** [comment]
Thanks for the error report. Victim should be healed soon.

![Bildschirmfoto vom 2024-07-05 20-01-09](https://github.com/inkstitch/inkstitch/assets/36401965/b08e22dc-295c-4504-8a76-81434e21ef1a)

Just a note ... in the document the minimum stitch length is set to zero, not sure if that is a good idea.
