### ISSUE TITLE
Speichern der datei svg. nach pes. funktioniert nicht

### ISSUE THREAD

**Issue by melanie805** [inkstitch/inkstitch#3056]
Es ist ein unerwarteter Fehler aufgetreten. Das heißt, dies ist ein Fehler in Ink/Stitch.

Wenn du uns helfen willst Ink/Stitch zu verbessern,
- kopiere die gesamte Fehlermeldung
- speichere die SVG-Datei ab und
- erstelle einen Fehlerbereicht (New Issue) auf https://github.com/inkstitch/inkstitch/issues/new

Sende die Fehlerbeschreibung und (wenn möglich) auch die SVG-Datei.

Windows 10 version: 10.0.22631

Ink/Stitch Version: v3.1.0beta (windows)

Traceback (most recent call last):
  File "lib\elements\element.py", line 641, in handle_unexpected_exceptions
  File "lib\elements\element.py", line 605, in embroider
  File "lib\elements\fill_stitch.py", line 961, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 1044, in do_auto_fill
  File "lib\debug\debug.py", line 166, in decorated
  File "lib\stitches\auto_fill.py", line 116, in auto_fill
  File "lib\debug\debug.py", line 166, in decorated
  File "lib\stitches\auto_fill.py", line 907, in path_to_stitches
  File "lib\stitches\auto_fill.py", line 857, in travel
  File "networkx\classes\backends.py", line 148, in wrapper
  File "networkx\algorithms\shortest_paths\generic.py", line 173, in shortest_path
  File "networkx\algorithms\shortest_paths\weighted.py", line 2398, in bidirectional_dijkstra
networkx.exception.NetworkXNoPath: No path between (133.6264783344657, 101.55612353419392) and (145.46711642697238, 94.9506299212598).

**Comment by tyrosinase** [comment]
Setting a start and/or end point for the fill at that location will work around the problem. It should be fixed in the next version, which is in beta: https://inkstitch.org/de/2024-07-04-3.1.0beta

I'm going to close the issue, but if it still happens in 3.1.0 let us know and we'll reopen it. If you're having trouble pinpointing the fill, we can probably help with that too.

**Comment by kaalleen** [comment]
I could get hold of the svg file and it is actually a new issue with pull compensation that needs a fix.
