### ISSUE TITLE
Lettering Tool Error

### ISSUE THREAD

**Issue by edamico67** [inkstitch/inkstitch#3057]
Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\lettering.py", line 494, in effect
  File "lib\extensions\lettering.py", line 61, in __init__
  File "lib\extensions\lettering.py", line 169, in update_font_list
  File "lib\extensions\lettering.py", line 158, in font_list
  File "lib\lettering\font.py", line 86, in __init__
  File "lib\lettering\font.py", line 92, in _load_metadata
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

This happens on all svgs, even blank ones.

**Comment by tyrosinase** [comment]
It looks like you have a problematic font file. Have you added/created any?

**Comment by edamico67** [comment]
That was the problem.  I removed the fonts that I previously added and I am
not getting the error message anymore.  Thank You!!!!
