### ISSUE TITLE
macOS (arm): FloatingPoint geos/shapely

### ISSUE THREAD

**Issue by Jecheka** [inkstitch/inkstitch#3063]
ProductName:		macOS
ProductVersion:		14.5
BuildVersion:		23F79

Ink/Stitch Version: v3.1.0beta (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 158, in <module>
  File "inkex/base.py", line 252, in run
  File "lib/extensions/auto_run.py", line 35, in effect
  File "lib/stitches/auto_run.py", line 123, in autorun
  File "lib/stitches/auto_run.py", line 160, in build_graph
  File "lib/stitches/auto_run.py", line 44, in __init__
  File "lib/stitches/auto_run.py", line 79, in _get_intersection_points
  File "shapely/geometry/base.py", line 599, in intersection
  File "shapely/decorators.py", line 77, in wrapped
  File "shapely/set_operations.py", line 131, in intersection
FloatingPointError: invalid value encountered in intersection

**Comment by tyrosinase** [comment]
I am not a Mac person so bear with me. This appears to be the same as #3051 - are you also on an M2 Mac? If you're not, then installing Rosetta should solve the problem. If you've already installed it, or you're on an M2, I'll defer to one of the more Mac-experienced devs.

**Comment by Jecheka** [comment]
I’m on a M1, I’ll give that a try!

**Comment by kaalleen** [comment]
We are most probably going to remove the arm version again. So the next version will only release the intel version of Ink/Stitch for macOS (as all the previous versions before). With rosetta installed it should run fine on arm processors as well.

**Comment by kaalleen** [comment]
Closing in favor of #3047 (as the problem has the same origin). Thank you for the bug report!

**Comment by kaalleen** [comment]
Thank you for testing the beta version. We actually just released beta2 and are searching for testers.
It would be great if you could try that one out and see if everything runs fine for you: https://inkstitch.org/en/2024-07-21-3.1.0beta2
