### ISSUE TITLE
Inkstitch v3.1.0beta windows

### ISSUE THREAD

**Issue by tapaswinimohanta** [inkstitch/inkstitch#3076]
Windows 10 version: 10.0.22631

Ink/Stitch Version: v3.1.0beta (windows)

Traceback (most recent call last):
  File "lib\elements\element.py", line 641, in handle_unexpected_exceptions
  File "lib\elements\element.py", line 605, in embroider
  File "lib\elements\fill_stitch.py", line 961, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 1044, in do_auto_fill
  File "lib\debug\debug.py", line 166, in decorated
  File "lib\stitches\auto_fill.py", line 116, in auto_fill
  File "lib\debug\debug.py", line 166, in decorated
  File "lib\stitches\auto_fill.py", line 900, in path_to_stitches
  File "lib\stitches\fill.py", line 84, in stitch_row
  File "lib\utils\geometry.py", line 294, in unit
ZeroDivisionError: float division by zero
![Green Dino](https://github.com/inkstitch/inkstitch/assets/68766616/c33bdd5e-ebd4-4e0d-a695-a4c5359aa8fc)

**Comment by kaalleen** [comment]
Thank you for the error report and the file, really appreciate it.
This error has been mentioned before and we have a fix over here: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-fix-3052

It would be nice if you can download the fixed version and test it. Installation works the same as for the beta version.

**Comment by kaalleen** [comment]
Btw. that's a really nice file!!

**Comment by tapaswinimohanta** [comment]
> Except I'm looking at the filename and that's no cat! 😆

Uploaded the cat file by mistake at first. Then uploaded the Green Dino file which had the error.

**Comment by tapaswinimohanta** [comment]
> Btw. that's a really nice file!!

Thank you so much. Trying to learn embroidery digitization.

**Comment by tapaswinimohanta** [comment]
> Thank you for the error report and the file, really appreciate it. This error has been mentioned before and we have a fix over here: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-fix-3052
> 
> It would be nice if you can download the fixed version and test it. Installation works the same as for the beta version.

Appreciate your reply.

**Comment by kaalleen** [comment]
I'll close the issue, since it has been addressed in #3052
You can still comment on the issue in here or open a new issue.
