### ISSUE TITLE
Text window overflow

### ISSUE THREAD

**Issue by Tina-Chris** [inkstitch/inkstitch#3087]
I tested the beta.
I found that the text window does not getbreak
I'm on linux gnome. inkscape 1.2.
Might need to run a newer inkscape.
![grafik](https://github.com/user-attachments/assets/c999f2e0-fe9b-4138-895e-52cea2915622)

**Comment by Tina-Chris** [comment]
Now I tried realistic preview. Live Simulation works.
when running Stichplan-Vorschau I get this:

Es ist ein unerwarteter Fehler aufgetreten. Das heißt, dies ist ein Fehler in Ink/Stitch.

Wenn du uns helfen willst Ink/Stitch zu verbessern,
- kopiere die gesamte Fehlermeldung
- speichere die SVG-Datei ab und
- erstelle einen Fehlerbereicht (New Issue) auf https://github.com/inkstitch/inkstitch/issues/new

Sende die Fehlerbeschreibung und (wenn möglich) auch die SVG-Datei.

openSUSE Leap 15.5
Inkscape 1.3.2.

Ink/Stitch Version: v3.1.0beta (linux)

Traceback (most recent call last):
  File "inkstitch.py", line 158, in <module>
  File "inkex/base.py", line 252, in run
  File "lib/extensions/stitch_plan_preview.py", line 61, in effect
  File "lib/extensions/stitch_plan_preview.py", line 123, in rasterize
  File "lib/extensions/utils/inkex_command.py", line 220, in inkscape
  File "lib/extensions/utils/inkex_command.py", line 186, in call
  File "lib/extensions/utils/inkex_command.py", line 152, in _call
inkex.command.ProgramRunError: Return Code: -11: b'Gtk-Message: 15:30:35.382: Failed to load module "canberra-gtk-module"\nGtk-Message: 15:30:35.407: Failed to load module "canberra-gtk-module"\nGtk-Message: 15:30:35.407: Failed to load module "canberra-gtk-module"\nWARNING: unknown type: inkstitch:min_stitch_len_mm\nWARNING: unknown type: inkstitch:collapse_len_mm\nWARNING: unknown type: inkstitch:inkstitch_svg_version\nExporting only object with id="__inkstitch_stitch_plan__"; all other objects hidden.\n\nEmergency save activated!\nEmergency save completed. Inkscape will close now.\nIf you can reproduce this crash, please file a bug at https://inkscape.org/report\nwith a detailed description of the steps leading to the crash, so we can fix it.\n** Message: 15:30:39.002: Error: Inkscape ist auf einen internen Fehler gesto\xc3\x9fen und wird nun geschlossen.\n\n'
b'171.931\n-15.1493\n563.243\n596.525\n'
args: ('Return Code: -11: b\'Gtk-Message: 15:30:35.382: Failed to load module "canberra-gtk-module"\\nGtk-Message: 15:30:35.407: Failed to load module "canberra-gtk-module"\\nGtk-Message: 15:30:35.407: Failed to load module "canberra-gtk-module"\\nWARNING: unknown type: inkstitch:min_stitch_len_mm\\nWARNING: unknown type: inkstitch:collapse_len_mm\\nWARNING: unknown type: inkstitch:inkstitch_svg_version\\nExporting only object with id="__inkstitch_stitch_plan__"; all other objects hidden.\\n\\nEmergency save activated!\\nEmergency save completed. Inkscape will close now.\\nIf you can reproduce this crash, please file a bug at https://inkscape.org/report\\nwith a detailed description of the steps leading to the crash, so we can fix it.\\n** Message: 15:30:39.002: Error: Inkscape ist auf einen internen Fehler gesto\\xc3\\x9fen und wird nun geschlossen.\\n\\n\'\nb\'171.931\\n-15.1493\\n563.243\\n596.525\\n\'\nargs: (\'inkscape\', -11, b\'Gtk-Message: 15:30:35.382: Failed to load module "canberra-gtk-module"\\nGtk-Message: 15:30:35.407: Failed to load module "canberra-gtk-module"\\nGtk-Message: 15:30:35.407: Failed to load module "canberra-gtk-module"\\nWARNING: unknown type: inkstitch:min_stitch_len_mm\\nWARNING: unknown type: inkstitch:collapse_len_mm\\nWARNING: unknown type: inkstitch:inkstitch_svg_version\\nExporting only object with id="__inkstitch_stitch_plan__"; all other objects hidden.\\n\\nEmergency save activated!\\nEmergency save completed. Inkscape will close now.\\nIf you can reproduce this crash, please file a bug at https://inkscape.org/report\\nwith a detailed description of the steps leading to the crash, so we can fix it.\\n** Message: 15:30:39.002: Error: Inkscape ist auf einen internen Fehler gesto\\xc3\\x9fen und wird nun geschlossen.\\n\\n\', b\'171.931\\n-15.1493\\n563.243\\n596.525\\n\', [\'/usr/bin/inkscape\', \'--actions=select-by-id: __inkstitch_stitch_plan__; query-x; query-y; query-width; query-height; export-id: __inkstitch_stitch_plan__; export-id-only; export-type: png; export-dpi: 300; export-png-color-mode: RGBA_16; export-filename: /tmp/tmpwvr4fw3t/temp.png; export-do\', \'/tmp/tmpwvr4fw3t/temp.svg\'])',)

**Comment by Tina-Chris** [comment]
> I tested the beta. I found that the text window does not getbreak I'm on linux gnome. inkscape 1.2. Might need to run a newer inkscape.

running the latest inkscape AppImage did not change the super wide text box

**Comment by Tina-Chris** [comment]
> > I tested the beta. I found that the text window does not getbreak I'm on linux gnome. inkscape 1.2. Might need to run a newer inkscape.
> 
> running the latest inkscape AppImage did not change the super wide text box

I found that I can unlock the box to resize it and relock the box. but I fear this will give us several support requests.
