### ISSUE TITLE
3.1.0beta: Simulator and Troubleshoot broken

### ISSUE THREAD

**Issue by Qwertie-** [inkstitch/inkstitch#3099]
I just tested out the beta using a file that was working fine in the previous stable version. I found that the simulator did not open, and the "Troubleshoot Objects" option crashed.

Troubleshoot output:
```
ProductName:		macOS
ProductVersion:		14.5
BuildVersion:		23F79

Ink/Stitch Version: v3.1.0beta (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 158, in <module>
  File "inkex/base.py", line 252, in run
  File "lib/extensions/troubleshoot.py", line 34, in effect
  File "lib/elements/satin_column.py", line 762, in validation_errors
  File "lib/elements/satin_column.py", line 1599, in to_stitch_groups
  File "lib/elements/satin_column.py", line 1266, in do_satin
  File "lib/debug/debug.py", line 166, in decorated
  File "lib/elements/satin_column.py", line 1051, in plot_points_on_rails
  File "lib/elements/satin_column.py", line 703, in flattened_sections
  File "shapely/geometry/base.py", line 599, in intersection
  File "shapely/decorators.py", line 77, in wrapped
  File "shapely/set_operations.py", line 131, in intersection
FloatingPointError: invalid value encountered in intersection
```

File causing issues:
![broken file example](https://github.com/user-attachments/assets/3634e6e7-cc28-4be3-901d-34262a748f22)

**Comment by Marif91** [comment]
Je viens de tester sur mac M2 avec la version ARM64 et Rosetta installé.

**Comment by kaalleen** [comment]
Thank you for testing the beta version. We actually just released beta2 and are searching for testers.
It would be great if you could try that one out and see if everything runs fine for you: https://inkstitch.org/en/2024-07-21-3.1.0beta2

**Comment by Qwertie-** [comment]
@kaalleen Just tested with the new beta and I can confirm it's resolved the issue 👍

**Comment by kaalleen** [comment]
Great, thank you for the feedback!
