### ISSUE TITLE
Error saving a copy of embroidery

### ISSUE THREAD

**Issue by dkhater-redhat** [inkstitch/inkstitch#3111]
Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 250, in run
  File "lib/extensions/output.py", line 65, in effect
  File "lib/output.py", line 109, in write_embroidery_file
  File "pyembroidery/EmbPattern.py", line 1727, in static_write
  File "pyembroidery/EmbPattern.py", line 1644, in write_embroidery
  File "pyembroidery/PecWriter.py", line 32, in write
  File "pyembroidery/PecWriter.py", line 40, in write_pec
  File "pyembroidery/PecWriter.py", line 64, in write_pec_header
AssertionError: too many color changes, (574) out of bounds (0, 255)

When i try to troubleshoot, I get
```
All selected shapes are valid! If you are still having trouble with a shape not being embroidered, check if it is in a layer with an ignore command.
```

**Comment by tyrosinase** [comment]
You will definitely want to upgrade to the newest version (if not the beta), which will give you a cleaner error message.

But what's happening there is literally what the last line says: there are 574 color changes, and PES/PEC format is limited to 255. You probably don't want even 255 color changes, so you'll need to color-sort your file.

**Comment by dkhater-redhat** [comment]
gotcha! thanks so much for this. also love that this is an open source community. once i get time, i definitely want to check the code out :-D
