### ISSUE TITLE
AutoFill: path_to_stitches TypeError

### ISSUE THREAD

**Issue by Cortheny** [inkstitch/inkstitch#3119]
Incluez la description de l'erreur et (si possible) le fichier svg.

Windows 10 version: 10.0.22631

Ink/Stitch Version: v3.1.0 (windows) 2024-07-27 09:04

Traceback (most recent call last):
  File "lib\elements\element.py", line 641, in handle_unexpected_exceptions
  File "lib\elements\element.py", line 605, in embroider
  File "lib\elements\fill_stitch.py", line 961, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 1044, in do_auto_fill
  File "lib\debug\debug.py", line 166, in decorated
  File "lib\stitches\auto_fill.py", line 116, in auto_fill
  File "lib\debug\debug.py", line 166, in decorated
  File "lib\stitches\auto_fill.py", line 929, in path_to_stitches
TypeError: 'NoneType' object is not iterable
![290724 bug envoye inkstitch](https://github.com/user-attachments/assets/77ba9d04-6571-4af7-87d2-981ff7c93929)

**Comment by tyrosinase** [comment]
I'm getting a slightly different behavior on beta2:

```
Ink/Stitch Version: v3.1.0beta2 (linux) 2024-07-21 09:58

Traceback (most recent call last):
  File "lib/elements/element.py", line 641, in handle_unexpected_exceptions
  File "lib/elements/element.py", line 605, in embroider
  File "lib/elements/fill_stitch.py", line 961, in to_stitch_groups
  File "lib/elements/fill_stitch.py", line 1044, in do_auto_fill
  File "lib/debug/debug.py", line 166, in decorated
  File "lib/stitches/auto_fill.py", line 116, in auto_fill
  File "lib/debug/debug.py", line 166, in decorated
  File "lib/stitches/auto_fill.py", line 922, in path_to_stitches
  File "lib/stitches/auto_fill.py", line 872, in travel
  File "networkx/utils/backends.py", line 412, in __call__
  File "networkx/algorithms/shortest_paths/generic.py", line 175, in shortest_path
  File "networkx/utils/backends.py", line 412, in __call__
  File "networkx/algorithms/shortest_paths/weighted.py", line 2431, in bidirectional_dijkstra
networkx.exception.NetworkXNoPath: No path between (384.706910125443, 440.74436420844137) and (378.16993990253866, 423.30708661417316).
```

while trying to render the red ring (with all the letters cut out of it, so a very complicated path).

I'm getting the same silent failure on the simulator as in #3083; the above is happening when the Params window tries to render the ring.

**Comment by Cortheny** [comment]
Je devrai peut être ne pas exclure les lettres et les broder par dessus si ma densité n'est pas trop importante
________________________________
De : Tyrosinase ***@***.***>
Envoyé : lundi 29 juillet 2024 19:48
À : inkstitch/inkstitch ***@***.***>
Cc : Cortheny ***@***.***>; Author ***@***.***>
Objet : Re: [inkstitch/inkstitch] INKSCAPE INKSTITCH (Issue #3119)


I'm getting a slightly different behavior on beta2:

Ink/Stitch Version: v3.1.0beta2 (linux) 2024-07-21 09:58

Traceback (most recent call last):
  File "lib/elements/element.py", line 641, in handle_unexpected_exceptions
  File "lib/elements/element.py", line 605, in embroider
  File "lib/elements/fill_stitch.py", line 961, in to_stitch_groups
  File "lib/elements/fill_stitch.py", line 1044, in do_auto_fill
  File "lib/debug/debug.py", line 166, in decorated
  File "lib/stitches/auto_fill.py", line 116, in auto_fill
  File "lib/debug/debug.py", line 166, in decorated
  File "lib/stitches/auto_fill.py", line 922, in path_to_stitches
  File "lib/stitches/auto_fill.py", line 872, in travel
  File "networkx/utils/backends.py", line 412, in __call__
  File "networkx/algorithms/shortest_paths/generic.py", line 175, in shortest_path
  File "networkx/utils/backends.py", line 412, in __call__
  File "networkx/algorithms/shortest_paths/weighted.py", line 2431, in bidirectional_dijkstra
networkx.exception.NetworkXNoPath: No path between (384.706910125443, 440.74436420844137) and (378.16993990253866, 423.30708661417316).


while trying to render the red ring (with all the letters cut out of it, so a very complicated path).

I'm getting the same silent failure on the simulator as in #3083<https://github.com/inkstitch/inkstitch/issues/3083>; the above is happening when the Params window tries to render the ring.

**Comment by tyrosinase** [comment]
Yup, it shouldn't be giving that raw error but the underlying problem is that the fill is just going to be a mess as far as trying to path it. If I was doing that design I might either drop the cutouts, or else break it into the inner and outer circles and all the in-between pieces, and use circular fill on all of them (all with a center target point): 

![image](https://github.com/user-attachments/assets/7bb7ce47-2384-476d-9ada-40a06434f39f)

Piece pulled out to show what I mean:

![image](https://github.com/user-attachments/assets/aac27a99-747d-4eca-beb9-e9e6a4df9bb1)

(Depending on how stable the ground is, anyway - of course if it's not stable enough for the fills to all join up, it's not stable enough for the letters to align with their cutouts either.)

**Comment by Cortheny** [comment]
Je comprends le principe mais je ne sais pas faire
________________________________
De : Tyrosinase ***@***.***>
Envoyé : lundi 29 juillet 2024 21:18
À : inkstitch/inkstitch ***@***.***>
Cc : Cortheny ***@***.***>; Author ***@***.***>
Objet : Re: [inkstitch/inkstitch] INKSCAPE INKSTITCH (Issue #3119)


Yup, it shouldn't be giving that raw error but the underlying problem is that the fill is just going to be a mess as far as trying to path it. If I was doing that design I might either drop the cutouts, or else break it into the inner and outer circles and all the in-between pieces, and use circular fill on all of them (all with a center target point):

image.png (view on web)<https://github.com/user-attachments/assets/7bb7ce47-2384-476d-9ada-40a06434f39f>

Piece pulled out to show what I mean:

image.png (view on web)<https://github.com/user-attachments/assets/aac27a99-747d-4eca-beb9-e9e6a4df9bb1>

(Depending on how stable the ground is, anyway - of course if it's not stable enough for the fills to all join up, it's not stable enough for the letters to align with their cutouts either.)

**Comment by tyrosinase** [comment]
I made two circles, one aligned with the top edge of the letters, one aligned with the bottom edge, then used `Path > Division` (Ctrl+/) to cut up the piece.

Then I used `Extensions > Ink/Stitch > Commands > Attach Command to Objects` (one of the Francophones can probably give the exact translation) to attach a Target command to each new object, and dragged all the target icons to center so all the circle fills would align.

And then I used `Extensions > Ink/Stitch > Params` to change all the object fills to Circular.

You'll have to test it to make sure all the fills blend smoothly, and there will end up being jump stitches. I would try stitching the lettering over a solid fill (maybe Circular) first. If it works, that will save a lot of work.

**Comment by claudinepeyrat06** [comment]
@Cortheny  utilise simplement Outils Remplissage>Briser  des  objets de  remplissage sur  ta zone rouge et le problème  devrait disparaitre.
Si tu veux du  remplissage centrale  avec le  même centre pour chaque partie,il  faut que tu les selectionnes   tous,  puis commande > ajouter des commandes à des objets  sélectionnés et tu coches position  de la cible.
Ensuite tu déplaces toutes les cibles pour  les superposées
Mais  plus  simplement avec un remplissage  pas trop  dense je  ne ferai pas de trou dans le  remplissage  et broderai le lettrage en surépaisseur.

**Comment by Cortheny** [comment]
Bonsoir

Merci beaucoup !

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________
