### ISSUE TITLE
Inkstitch unexpected error

### ISSUE THREAD

**Issue by babygirl1213** [inkstitch/inkstitch#3125]
I received an error when i am trying to save a design as a PES file

Ink/Stitch Version: v3.0.1 (windows)

Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\troubleshoot.py", line 33, in effect
  File "lib\elements\satin_column.py", line 652, in validation_errors
  File "lib\elements\satin_column.py", line 1262, in to_stitch_groups
  File "lib\elements\satin_column.py", line 1090, in do_satin
  File "lib\debug.py", line 231, in decorated
  File "lib\elements\satin_column.py", line 898, in plot_points_on_rails
  File "lib\elements\satin_column.py", line 629, in flattened_sections
  File "lib\elements\satin_column.py", line 629, in <listcomp>
IndexError: tuple index out of range

**Comment by tyrosinase** [comment]
Somewhere in your file, you have a single line marked as a satin stitch. Troubleshooting should find it for you (if it doesn't on that version, the beta version should).

I'm going to close the issue, but if that doesn't solve your problem, or if you need help finding it or installing the beta, feel free to continue the comment thread.
