### ISSUE TITLE
been trying to get a useable embroidery format for hours keep getting random errors heres one of them 

### ISSUE THREAD

**Issue by fantascey** [inkstitch/inkstitch#3128]
Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 564, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 632, in do_contour_fill
  File "lib\stitches\contour_fill.py", line 137, in offset_polygon
  File "lib\stitches\contour_fill.py", line 186, in _match_polygons_and_holes
  File "shapely\geometry\base.py", line 685, in difference
  File "shapely\topology.py", line 72, in __call__
  File "shapely\topology.py", line 37, in _check_topology
shapely.errors.TopologicalError: The operation 'GEOSDifference_r' could not be performed. Likely cause is invalidity of the geometry <shapely.geometry.multipolygon.MultiPolygon object at 0x1C580670>

shapely.geos - ERROR - TopologyException: Input geom 1 is invalid: Self-intersection at 572.83985570345192 604.54059962657766
shapely.geos - INFO - Self-intersection at or near point 572.83985570345192 604.54059962657766

**Comment by tyrosinase** [comment]
That error is fixed in the current Ink/Stitch version.
