### ISSUE TITLE
GradientFill: KeyError: 'stop-color' in _get_gradient_cache_key_data

### ISSUE THREAD

**Issue by MohamedZakariaa** [inkstitch/inkstitch#3132]
Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues/new

Include the error description and also (if possible) the svg file.

Windows 10 version: 10.0.22631

Ink/Stitch Version: v3.1.0 (windows) 2024-07-27 09:04

Traceback (most recent call last):
  File "lib\elements\element.py", line 641, in handle_unexpected_exceptions
  File "lib\elements\element.py", line 600, in embroider
  File "lib\debug\debug.py", line 166, in decorated
  File "lib\elements\element.py", line 510, in _load_cached_stitch_groups
  File "lib\elements\element.py", line 579, in get_cache_key
  File "lib\elements\element.py", line 564, in _get_gradient_cache_key_data
  File "lib\elements\element.py", line 564, in <listcomp>
  File "inkex\styles.py", line 331, in __getitem__
KeyError: 'stop-color'

**Comment by kaalleen** [comment]
Do you have the svg file? It would be nice if we could have a look at it. You can also only save the part of it which is not working. Supposedly a gradient fill.

**Comment by capellancitizen** [comment]
Offhand: It's legal to have a `stop` with no `stop-color`, in which case it defaults to `black`. Additionally `stop-color` can be a property of the element itself instead of a style parameter (though Inkscape at least has the style key override the property). Same for `stop-opacity` (defaults to `1`). It seems like Inkscape 1.3.2 will always write the `style` attribute of any given `stop` with both `stop-opacity` and `stop-color`, but if this user's file originates from somewhere else, maybe it had a gradient with `stop-color` missing or included as a parameter?

**Comment by kaalleen** [comment]
Closing in favor of #3195 which provides an svg file.
