### ISSUE TITLE
problem with fill?

### ISSUE THREAD

**Issue by sarawas** [inkstitch/inkstitch#3138]
Trying to change fill to auto , this message came up
![kitten file 2](https://github.com/user-attachments/assets/c3d55a83-096f-482a-8d31-8ef6831de558)

Windows 10 version: 10.0.19045

Ink/Stitch Version: v3.1.0 (windows) 2024-07-27 09:04

Traceback (most recent call last):
  File "lib\elements\element.py", line 641, in handle_unexpected_exceptions
  File "lib\elements\element.py", line 605, in embroider
  File "lib\elements\fill_stitch.py", line 961, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 1044, in do_auto_fill
  File "lib\debug\debug.py", line 166, in decorated
  File "lib\stitches\auto_fill.py", line 92, in auto_fill
  File "lib\debug\debug.py", line 166, in decorated
  File "lib\stitches\auto_fill.py", line 143, in adjust_shape_for_pull_compensation
AttributeError: 'MultiPolygon' object has no attribute 'exterior'

**Comment by sarawas** [comment]
SOLVED! wayward node! Thanks 😀

**Comment by kaalleen** [comment]
I'm going to reopen this. It still is considered a bug. Thanks for the error report!
