### ISSUE TITLE
Problem with manual windows 11 build

### ISSUE THREAD

**Issue by jooshkins** [inkstitch/inkstitch#3140]
Trying to get a manual build working, but I am running into this error message, whenever trying to run Params or Lettering.

Windows 11, 64 bit build

I couldn't find any issue that mentions this error. Has anyone else seen this?

`Traceback (most recent call last):
  File "C:\Users\foo\AppData\Roaming\inkscape\extensions\inkstitch\inkstitch.py", line 113, in <module>
    from lib.debug.debug import debug  # noqa: E402  # import global variable debug - don't import whole module
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\foo\AppData\Roaming\inkscape\extensions\inkstitch\lib\debug\debug.py", line 17, in <module>
    from ..svg import line_strings_to_path
  File "C:\Users\foo\AppData\Roaming\inkscape\extensions\inkstitch\lib\svg\__init__.py", line 6, in <module>
    from .guides import get_guides
  File "C:\Users\foo\AppData\Roaming\inkscape\extensions\inkstitch\lib\svg\guides.py", line 8, in <module>
    from ..utils import Point, cache, string_to_floats
  File "C:\Users\foo\AppData\Roaming\inkscape\extensions\inkstitch\lib\utils\__init__.py", line 6, in <module>
    from .cache import cache
  File "C:\Users\foo\AppData\Roaming\inkscape\extensions\inkstitch\lib\utils\cache.py", line 12, in <module>
    import diskcache
ModuleNotFoundError: No module named 'diskcache'
`

**Comment by jooshkins** [comment]
Also from running `pip install -r inkstitch/requirements.txt`

It shows that the module is installed:
`Processing c:\users\foo\appdata\roaming\inkscape\extensions\pyembroidery
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting inkex@ git+https://gitlab.com/inkscape/extensions.git@618fe5e1e431d4b28a078660bf17afc65335fe39 (from -r inkstitch/requirements.txt (line 7))
  Using cached inkex-1.2.0-py3-none-any.whl
Collecting colormath@ git+https://github.com/gtaylor/python-colormath.git@4a076831fd5136f685aa7143db81eba27b2cd19a (from -r inkstitch/requirements.txt (line 29))
  Using cached colormath-3.0.0-py3-none-any.whl
Requirement already satisfied: wxPython>=4.1.1 in c:\users\foo\appdata\local\programs\python\python39\lib\site-packages (from -r inkstitch/requirements.txt (line 12)) (4.2.1)
Requirement already satisfied: backports.functools_lru_cache in c:\users\foo\appdata\local\programs\python\python39\lib\site-packages (from -r inkstitch/requirements.txt (line 14)) (2.0.0)
Requirement already satisfied: networkx in c:\users\foo\appdata\local\programs\python\python39\lib\site-packages (from -r inkstitch/requirements.txt (line 15)) (3.2.1)
Requirement already satisfied: shapely>=2.0.0 in c:\users\foo\appdata\local\programs\python\python39\lib\site-packages (from -r inkstitch/requirements.txt (line 16)) (2.0.5)
Requirement already satisfied: lxml in c:\users\foo\appdata\local\programs\python\python39\lib\site-packages (from -r inkstitch/requirements.txt (line 17)) (5.3.0)
Requirement already satisfied: appdirs in c:\users\foo\appdata\local\programs\python\python39\lib\site-packages (from -r inkstitch/requirements.txt (line 18)) (1.4.4)
Requirement already satisfied: numpy in c:\users\foo\appdata\local\programs\python\python39\lib\site-packages (from -r inkstitch/requirements.txt (line 19)) (1.26.4)
Requirement already satisfied: jinja2>2.9 in c:\users\foo\appdata\local\programs\python\python39\lib\site-packages (from -r inkstitch/requirements.txt (line 20)) (3.1.4)
Requirement already satisfied: requests in c:\users\foo\appdata\local\programs\python\python39\lib\site-packages (from -r inkstitch/requirements.txt (line 21)) (2.32.3)
Requirement already satisfied: tomli in c:\users\foo\appdata\local\programs\python\python39\lib\site-packages (from -r inkstitch/requirements.txt (line 25)) (2.0.1)
Requirement already satisfied: flask>=2.2.0 in c:\users\foo\appdata\local\programs\python\python39\lib\site-packages (from -r inkstitch/requirements.txt (line 31)) (3.0.3)
Requirement already satisfied: fonttools in c:\users\foo\appdata\local\programs\python\python39\lib\site-packages (from -r inkstitch/requirements.txt (line 32)) (4.53.1)
Requirement already satisfied: trimesh>=3.15.2 in c:\users\foo\appdata\local\programs\python\python39\lib\site-packages (from -r inkstitch/requirements.txt (line 33)) (4.4.4)
Requirement already satisfied: scipy in c:\users\foo\appdata\local\programs\python\python39\lib\site-packages (from -r inkstitch/requirements.txt (line 34)) (1.13.1)
Requirement already satisfied: diskcache in c:\users\foo\appdata\local\programs\python\python39\lib\site-packages (from -r inkstitch/requirements.txt (line 35)) (5.6.3)
Requirement already satisfied: flask-cors in c:\users\foo\appdata\local\programs\python\python39\lib\site-packages (from -r inkstitch/requirements.txt (line 36)) (4.0.1)
Requirement already satisfied: pywinutils in c:\users\foo\appdata\local\programs\python\python39\lib\site-packages (from -r inkstitch/requirements.txt (line 37)) (0.2)
Requirement already satisfied: pywin32 in c:\users\foo\appdata\local\programs\python\python39\lib\site-packages (from -r inkstitch/requirements.txt (line 38)) (306)
Requirement already satisfied: Pillow>=7.0.0 in c:\users\foo\appdata\local\programs\python\python39\lib\site-packages (from inkex@ git+https://gitlab.com/inkscape/extensions.git@618fe5e1e431d4b28a078660bf17afc65335fe39->-r inkstitch/requirements.txt (line 7)) (10.4.0)
Requirement already satisfied: cssselect<2.0.0,>=1.2.0 in c:\users\foo\appdata\local\programs\python\python39\lib\site-packages (from inkex@ git+https://gitlab.com/inkscape/extensions.git@618fe5e1e431d4b28a078660bf17afc65335fe39->-r inkstitch/requirements.txt (line 7)) (1.2.0)
Requirement already satisfied: packaging>=20.3 in c:\users\foo\appdata\local\programs\python\python39\lib\site-packages (from inkex@ git+https://gitlab.com/inkscape/extensions.git@618fe5e1e431d4b28a078660bf17afc65335fe39->-r inkstitch/requirements.txt (line 7)) (24.1)
Requirement already satisfied: pySerial<4.0,>=3.4 in c:\users\foo\appdata\local\programs\python\python39\lib\site-packages (from inkex@ git+https://gitlab.com/inkscape/extensions.git@618fe5e1e431d4b28a078660bf17afc65335fe39->-r inkstitch/requirements.txt (line 7)) (3.5)
Requirement already satisfied: pyparsing>=3.0.9 in c:\users\foo\appdata\local\programs\python\python39\lib\site-packages (from inkex@ git+https://gitlab.com/inkscape/extensions.git@618fe5e1e431d4b28a078660bf17afc65335fe39->-r inkstitch/requirements.txt (line 7)) (3.1.2)
Requirement already satisfied: scour<0.38,>=0.37 in c:\users\foo\appdata\local\programs\python\python39\lib\site-packages (from inkex@ git+https://gitlab.com/inkscape/extensions.git@618fe5e1e431d4b28a078660bf17afc65335fe39->-r inkstitch/requirements.txt (line 7)) (0.37)
Requirement already satisfied: tinycss2<2.0.0,>=1.0.1 in c:\users\foo\appdata\local\programs\python\python39\lib\site-packages (from inkex@ git+https://gitlab.com/inkscape/extensions.git@618fe5e1e431d4b28a078660bf17afc65335fe39->-r inkstitch/requirements.txt (line 7)) (1.3.0)
Requirement already satisfied: six in c:\users\foo\appdata\local\programs\python\python39\lib\site-packages (from wxPython>=4.1.1->-r inkstitch/requirements.txt (line 12)) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\foo\appdata\local\programs\python\python39\lib\site-packages (from jinja2>2.9->-r inkstitch/requirements.txt (line 20)) (2.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\foo\appdata\local\programs\python\python39\lib\site-packages (from requests->-r inkstitch/requirements.txt (line 21)) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\foo\appdata\local\programs\python\python39\lib\site-packages (from requests->-r inkstitch/requirements.txt (line 21)) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\foo\appdata\local\programs\python\python39\lib\site-packages (from requests->-r inkstitch/requirements.txt (line 21)) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\foo\appdata\local\programs\python\python39\lib\site-packages (from requests->-r inkstitch/requirements.txt (line 21)) (2024.7.4)
Requirement already satisfied: Werkzeug>=3.0.0 in c:\users\foo\appdata\local\programs\python\python39\lib\site-packages (from flask>=2.2.0->-r inkstitch/requirements.txt (line 31)) (3.0.3)
Requirement already satisfied: itsdangerous>=2.1.2 in c:\users\foo\appdata\local\programs\python\python39\lib\site-packages (from flask>=2.2.0->-r inkstitch/requirements.txt (line 31)) (2.2.0)
Requirement already satisfied: click>=8.1.3 in c:\users\foo\appdata\local\programs\python\python39\lib\site-packages (from flask>=2.2.0->-r inkstitch/requirements.txt (line 31)) (8.1.7)
Requirement already satisfied: blinker>=1.6.2 in c:\users\foo\appdata\local\programs\python\python39\lib\site-packages (from flask>=2.2.0->-r inkstitch/requirements.txt (line 31)) (1.8.2)
Requirement already satisfied: importlib-metadata>=3.6.0 in c:\users\foo\appdata\local\programs\python\python39\lib\site-packages (from flask>=2.2.0->-r inkstitch/requirements.txt (line 31)) (8.2.0)
Requirement already satisfied: colorama in c:\users\foo\appdata\local\programs\python\python39\lib\site-packages (from click>=8.1.3->flask>=2.2.0->-r inkstitch/requirements.txt (line 31)) (0.4.6)
Requirement already satisfied: zipp>=0.5 in c:\users\foo\appdata\local\programs\python\python39\lib\site-packages (from importlib-metadata>=3.6.0->flask>=2.2.0->-r inkstitch/requirements.txt (line 31)) (3.20.0)
Requirement already satisfied: webencodings>=0.4 in c:\users\foo\appdata\local\programs\python\python39\lib\site-packages (from tinycss2<2.0.0,>=1.0.1->inkex@ git+https://gitlab.com/inkscape/extensions.git@618fe5e1e431d4b28a078660bf17afc65335fe39->-r inkstitch/requirements.txt (line 7)) (0.5.1)
Building wheels for collected packages: pyembroidery
  Building wheel for pyembroidery (setup.py): started
  Building wheel for pyembroidery (setup.py): finished with status 'done'
  Created wheel for pyembroidery: filename=pyembroidery-1.4.36-py3-none-any.whl size=134520 sha256=219ad9e1e3416ca871f968aa33d92020d874760a06cd9b1c862a9a88044865fa
  Stored in directory: C:\Users\foo\AppData\Local\Temp\pip-ephem-wheel-cache-la7wsypq\wheels\ab\6b\65\2951de890cb010bea41bbc8bc887ef388b2273e8b5bcd038ed
Successfully built pyembroidery
Installing collected packages: pyembroidery
  Attempting uninstall: pyembroidery
    Found existing installation: pyembroidery 1.4.36
    Uninstalling pyembroidery-1.4.36:
      Successfully uninstalled pyembroidery-1.4.36
Successfully installed pyembroidery-1.4.36`

**Comment by kaalleen** [comment]
I just assume that you are talking about manual install and not a manual build for windows. In that case you probably need to tell inkscape to use your python version. Go to `Edit > Preferences > System > User preferences` and click on `Open`. You'll the the preferences.xml file in that folder. Close Inkscape and open the file with a text editor. Search for `<group id="extensions"`. Add this attribute `python-interpreter="C:\Program Files\Python39\python.exe"`. Substitute the path with yours. You can look it up in cmd with the `where python` command.

**Comment by jooshkins** [comment]
Yes I meant manual install. And that fixed it, thanks!
Do you mind if I add a troubleshooting note about this error to the [Manual install page](https://inkstitch.org/developers/inkstitch/windows-manual-build/)?

**Comment by kaalleen** [comment]
That would be nice. Thanks for offering your help!

**Comment by kaalleen** [comment]
Resolved by #3158
