### ISSUE TITLE
File wont save as jef but will save as svg using inkstitch extension

### ISSUE THREAD

**Issue by Mbeedleco** [inkstitch/inkstitch#3155]
Using inkstitch this message is popping up when i go to save file as a jef file,
Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\output.py", line 56, in effect
  File "lib\extensions\base.py", line 200, in elements_to_stitch_groups
  File "lib\elements\element.py", line 329, in embroider
  File "lib\elements\element.py", line 387, in validate
  File "lib\elements\fill_stitch.py", line 321, in validation_errors
  File "lib\elements\fill_stitch.py", line 274, in shape
AttributeError: 'LineString' object has no attribute 'geoms'

it is all looking good when i go into embroidery preview but it just wont save
![girls will be girls](https://github.com/user-attachments/assets/1660ee10-aa4a-45c8-8968-b5b244b7e2c3)

**Comment by tyrosinase** [comment]
You should upgrade to the current version of Ink/Stitch; this is a known bug in older versions.

Once you do that, it will export without error but Troubleshoot will point out some things that may need fixed. One problem it won't point out is: you have your text doubled, and should probably ungroup and delete one copy.

![image](https://github.com/user-attachments/assets/1fe38a9a-09c0-4349-b770-e499426fddd1)
