### ISSUE TITLE
Error while changing pull compensation percentage

### ISSUE THREAD

**Issue by cpjet64** [inkstitch/inkstitch#3159]
Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues/new

Include the error description and also (if possible) the svg file.

Windows 10 version: 10.0.22631

Ink/Stitch Version: v3.1.0 (windows) 2024-07-27 09:04

Traceback (most recent call last):
  File "lib\elements\element.py", line 641, in handle_unexpected_exceptions
  File "lib\elements\element.py", line 600, in embroider
  File "lib\debug\debug.py", line 166, in decorated
  File "lib\elements\element.py", line 510, in _load_cached_stitch_groups
  File "lib\elements\element.py", line 578, in get_cache_key
  File "lib\elements\element.py", line 170, in _get_specified_style
  File "inkex\elements\_base.py", line 650, in specified_style
  File "inkex\styles.py", line 518, in specified_style
  File "inkex\styles.py", line 497, in cascaded_style
  File "inkex\styles.py", line 233, in update
  File "inkex\styles.py", line 140, in _add
  File "inkex\utils.py", line 306, in notify
  File "inkex\utils.py", line 368, in _callback
SystemError: unknown opcode

**Comment by kaalleen** [comment]
Interesting! Do you have the file which caused the issue? It would be a great help in order to solve the problem.

**Comment by cpjet64** [comment]
I actually have a reddit post because I was having a host of issues. I ended up creating a brand new file from scratch and it resolved my problems. The original problematic file and the full description and what we tried is on my reddit post. Please see https://www.reddit.com/r/Inkstitch/comments/1ew7ohu/issues_with_stitching/. If you have any questions please let me know I would love to help however I can.

**Comment by cpjet64** [comment]
I regularly get the Inkstitch sub-GUIs crashing out on me but this was the first time I ever had the error report message.

**Comment by kaalleen** [comment]
I ran the linked file from reddit and couldn't reproduce the error. Is this the file were the error was coming from?
If so, how exactly did you trigger it?

**Comment by cpjet64** [comment]
I haven't used the software in a bit so sorry this wont be the prettiest but A. yes that file also had the sub-GUIs crashing out. B. The sub-GUI crash could be reproduced regularly and pretty easily by changing stitch settings and then previewing multiple times.

**Comment by kaalleen** [comment]
I tried again reproducing the problem and couldn't. Maybe this is an outdated issue and has vanished with inkex and/or Ink/Stitch updates. I'll close the issue now. If it is still an issue, let's hope we get a reproducible report. Thanks for taking the extra step and for your report on this though.
