### ISSUE TITLE
Pull compensation edge case

### ISSUE THREAD

**Issue by sarawas** [inkstitch/inkstitch#3164]
I was having problems with the image (kept crashing) so I copied and pasted part into a new doc, This error came up

![bird crash](https://github.com/user-attachments/assets/27a2e664-a79a-4084-9b9a-d1883209b523)
Include the error description and also (if possible) the svg file.

Windows 10 version: 10.0.19045

Ink/Stitch Version: v3.1.0 (windows) 2024-07-27 09:04

Traceback (most recent call last):
  File "lib\elements\element.py", line 641, in handle_unexpected_exceptions
  File "lib\elements\element.py", line 605, in embroider
  File "lib\elements\fill_stitch.py", line 961, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 1044, in do_auto_fill
  File "lib\debug\debug.py", line 166, in decorated
  File "lib\stitches\auto_fill.py", line 92, in auto_fill
  File "lib\debug\debug.py", line 166, in decorated
  File "lib\stitches\auto_fill.py", line 143, in adjust_shape_for_pull_compensation
AttributeError: 'MultiPolygon' object has no attribute 'exterior'

**Comment by tyrosinase** [comment]
Looks like it's running into a weird edge case in the shape adjustment: there's some interior structure to the fill right where the wing runs into the body:

![image](https://github.com/user-attachments/assets/2bd663ad-528b-4c45-8631-fb732c406099)

As a workaround, remove those interior points and, if you were trying to do a stitch pattern there, use this technique instead: https://inkstitch.org/docs/stitches/patterns/

**Comment by sarawas** [comment]
Many Thanks, I did try troubleshoot and it didn't offer any errors. I will
go back and rejig
Cheers
Sara

**Comment by kaalleen** [comment]
Closing. Fixed in #3143

You can still comment here if you have further questions!
