### ISSUE TITLE
When running "params" - IllegalArgumentException: point array must contain 0 or >1 elements

### ISSUE THREAD

**Issue by ominika** [inkstitch/inkstitch#3180]
You can reproduce this error running "params" on "dress-black" layer and number "2" object.
If I change a place of any node of this object - error no longer occurs.

![silksong-gitgud-ver2](https://github.com/user-attachments/assets/afa59f0c-1a86-4e95-bd9e-8f22b67af448)

Windows 10 version: 10.0.19045

Ink/Stitch Version: v3.1.0 (windows) 2024-07-27 09:04

Traceback (most recent call last):
  File "lib\elements\element.py", line 641, in handle_unexpected_exceptions
  File "lib\elements\element.py", line 603, in embroider
  File "lib\elements\element.py", line 680, in validate
  File "lib\elements\satin_column.py", line 757, in validation_errors
  File "lib\elements\satin_column.py", line 559, in csp
  File "lib\elements\satin_column.py", line 559, in <listcomp>
  File "shapely\geometry\linestring.py", line 73, in __new__
  File "shapely\decorators.py", line 77, in wrapped
  File "shapely\creation.py", line 119, in linestrings
shapely.errors.GEOSException: IllegalArgumentException: point array must contain 0 or >1 elements

**Comment by kaalleen** [comment]
Thank you for the error report. This is really helpful. The path somehow has become invalid an contains a subpath with only one node. Inkscape will correct the path as soon as any other node is touched (as you noticed). But Ink/Stitch of course shouldn't fail on it.
