### ISSUE TITLE
Satin Column: flattened_sections: IndexError (on older Ink/Stitch version)

### ISSUE THREAD

**Issue by gjulien105** [inkstitch/inkstitch#3182]
I was attempting to change the color of the font when the F developed the extra line that could not be removed. I did a troubleshoot and the code below was what I got. Please Help!
Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\troubleshoot.py", line 33, in effect
  File "lib\elements\satin_column.py", line 652, in validation_errors
  File "lib\elements\satin_column.py", line 1257, in to_stitch_groups
  File "lib\elements\satin_column.py", line 1052, in do_zigzag_underlay
  File "lib\debug.py", line 231, in decorated
  File "lib\elements\satin_column.py", line 898, in plot_points_on_rails
  File "lib\elements\satin_column.py", line 629, in flattened_sections
  File "lib\elements\satin_column.py", line 629, in <listcomp>
IndexError: tuple index out of range

![Fly Hawks Fly](https://github.com/user-attachments/assets/8ec7d0e8-a73d-42ef-a918-1afb26ad674f)

**Comment by kaalleen** [comment]
Beside of what tyrosinase said ...
Can you update to the newest Ink/Stitch version and see if you can still produce the error message?
