### ISSUE TITLE
Clone of an image: 'NoneType' object has no attribute 'path'

### ISSUE THREAD

**Issue by no3l1a** [inkstitch/inkstitch#3184]
Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues/new

Include the error description and also (if possible) the svg file.

Windows 10 version: 10.0.22631

Ink/Stitch Version: v3.1.0 (windows) 2024-07-27 09:04

Traceback (most recent call last):
  File "lib\elements\element.py", line 641, in handle_unexpected_exceptions
  File "lib\elements\element.py", line 600, in embroider
  File "lib\debug\debug.py", line 166, in decorated
  File "lib\elements\element.py", line 510, in _load_cached_stitch_groups
  File "lib\elements\element.py", line 577, in get_cache_key
  File "lib\elements\element.py", line 426, in parse_path
  File "lib\elements\element.py", line 418, in path
  File "inkex\elements\_use.py", line 53, in get_path
AttributeError: 'NoneType' object has no attribute 'path'

![kolbe logo](https://github.com/user-attachments/assets/bd742fc3-264c-45b9-b9c0-01342162f157)

**Comment by tyrosinase** [comment]
That's a pretty atypical, non-Inkscape SVG file (all clips and clones of bitmap objects in the `def` file).

You'll have to spend some time releasing clips and turning the clip shapes into stitchable objects, to get something Ink/Stitch can work with. Or you can just use Inkscape itself to trace the bitmap, which will give you a better start.
