### ISSUE TITLE
Error when saving as VP3

### ISSUE THREAD

**Issue by rivens623** [inkstitch/inkstitch#3185]
path1092: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.0.0 (windows)

Traceback (most recent call last):
  File "networkx\algorithms\shortest_paths\weighted.py", line 728, in multi_source_dijkstra
KeyError: (44.14240168551189, 531.4960629921261)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "lib\elements\auto_fill.py", line 223, in to_patches
  File "lib\debug.py", line 133, in decorated
  File "lib\stitches\auto_fill.py", line 73, in auto_fill
  File "lib\debug.py", line 133, in decorated
  File "lib\stitches\auto_fill.py", line 629, in path_to_stitches
  File "lib\stitches\auto_fill.py", line 594, in travel
  File "networkx\algorithms\shortest_paths\generic.py", line 162, in shortest_path
  File "networkx\algorithms\shortest_paths\weighted.py", line 157, in dijkstra_path
  File "networkx\algorithms\shortest_paths\weighted.py", line 464, in single_source_dijkstra
  File "networkx\algorithms\shortest_paths\weighted.py", line 730, in multi_source_dijkstra
networkx.exception.NetworkXNoPath: No path to (44.14240168551189, 531.4960629921261).

**Comment by tyrosinase** [comment]
This is an older version of Ink/Stitch, so I'm going to close this issue (it is fixed by #2635) - if the same file still causes issues in the current version, we can reopen it.

If you can't upgrade, you can work around the problem by either breaking the fill object into smaller pieces, or by changing it up a little - add a fill start location, change the fill angle (even just slightly will sometimes do it), etc.
