### ISSUE TITLE
clamp_path_to_polygon: TopologyException

### ISSUE THREAD

**Issue by kelforfinding** [inkstitch/inkstitch#3193]
Windows 10 version: 10.0.19045

Ink/Stitch Version: v3.1.0 (windows) 2024-07-27 09:04

Traceback (most recent call last):
  File "lib\elements\element.py", line 641, in handle_unexpected_exceptions
  File "lib\elements\element.py", line 605, in embroider
  File "lib\elements\fill_stitch.py", line 942, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 1020, in do_underlay
  File "lib\debug\debug.py", line 166, in decorated
  File "lib\stitches\auto_fill.py", line 116, in auto_fill
  File "lib\debug\debug.py", line 166, in decorated
  File "lib\stitches\auto_fill.py", line 929, in path_to_stitches
  File "lib\stitches\auto_fill.py", line 885, in travel
  File "lib\utils\clamp_path.py", line 118, in clamp_path_to_polygon
  File "shapely\geometry\base.py", line 545, in buffer
  File "shapely\decorators.py", line 77, in wrapped
  File "shapely\constructive.py", line 180, in buffer
shapely.errors.GEOSException: TopologyException: depth mismatch at  at -704860.6933804747 812.95985944280005

![LotusEmpire](https://github.com/user-attachments/assets/8f2db522-9421-4e5c-afe2-32b0c7f7a051)

**Comment by kaalleen** [comment]
Interesting. I cannot reproduce the error.
Maybe you can fix the issue when you remove all the small holes from the shape? They won't stitch out nicely anyway.

**Comment by kaalleen** [comment]
Hopefully fixed "fixed" by #4221 (which simply skips clamping when it is not working out)
