### ISSUE TITLE
Gradient style KeyError 'stop-color'

### ISSUE THREAD

**Issue by jmd82855** [inkstitch/inkstitch#3195]
Windows 10 version: 10.0.22631

Ink/Stitch Version: v3.1.0 (windows) 2024-07-27 09:04

Traceback (most recent call last):
  File "lib\elements\element.py", line 641, in handle_unexpected_exceptions
  File "lib\elements\element.py", line 600, in embroider
  File "lib\debug\debug.py", line 166, in decorated
  File "lib\elements\element.py", line 510, in _load_cached_stitch_groups
  File "lib\elements\element.py", line 579, in get_cache_key
  File "lib\elements\element.py", line 564, in _get_gradient_cache_key_data
  File "lib\elements\element.py", line 564, in <listcomp>
  File "inkex\styles.py", line 331, in __getitem__
KeyError: 'stop-color'

**Comment by kaalleen** [comment]
Can you upload the svg file which is causing the issue?

**Comment by jmd82855** [comment]
![Candy Corn](https://github.com/user-attachments/assets/e77cde4e-2b23-41eb-9765-8985acdadc82)
