### ISSUE TITLE
Letters to font error

### ISSUE THREAD

**Issue by hcox18** [inkstitch/inkstitch#3208]
Receiving this error code when trying to convert PES letter files to font: 

Ink/Stitch Version: 3.0.1 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 231, in run
  File "lib/extensions/letters_to_font.py", line 43, in effect
  File "lib/extensions/letters_to_font.py", line 73, in get_glyph_element
  File "lib/stitch_plan/generate_stitch_plan.py", line 26, in generate_stitch_plan
AttributeError: 'NoneType' object has no attribute 'get_as_colorblocks'

**Comment by hcox18** [comment]
I also tried with XXX and DST with the same error, but would prefer to import PES. I am able to open the individual letter files within inkstitch if that information is helpful.

**Comment by kaalleen** [comment]
Can you update to the newest Ink/Stitch release and see if the error is still showing up and report back?

**Comment by hcox18** [comment]
Updated to most recent, stable version of Inkscape and newest Inkstitch. Error still pops up

Include the error description and also (if possible) the svg file.

ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H2026
CPU:				x86_64

Ink/Stitch Version: 3.1.0-high-sierra-catalina (osx) 2024-07-27 00:44

Traceback (most recent call last):
  File "inkstitch.py", line 162, in <module>
  File "inkex/base.py", line 252, in run
  File "lib/extensions/letters_to_font.py", line 46, in effect
  File "lib/extensions/letters_to_font.py", line 82, in get_glyph_element
  File "lib/stitch_plan/generate_stitch_plan.py", line 27, in generate_stitch_plan
AttributeError: 'NoneType' object has no attribute 'get_as_colorblocks'

**Comment by hcox18** [comment]
I took out the symbols and it seems to be working now. Thanks for your help!

**Comment by kaalleen** [comment]
Thanks for the report. I'd still be interested to figure out the original problem (with symbols on), so other folks don't run into the same issue. Would you mind to zip your letter files and send them over to us? Please report if you did, otherwise I wouldn't notice the incoming files.

https://lexneva.name/owncloud/index.php/s/NCcJbJqnKmL7nES
