### ISSUE TITLE
Stitch Plan Preview  - Realistic View error

### ISSUE THREAD

**Issue by FarragoOdyssey** [inkstitch/inkstitch#3218]
I created this attached logo.  I am able to successfully view the Stich Plan. I would like to view the realistic preview of it before I actually stitch it though.

Here is the error I keep getting:

***
Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues/new

Include the error description and also (if possible) the svg file.

Windows 10 version: 10.0.19045

Ink/Stitch Version: v3.1.0 (windows) 2024-07-27 09:04

Traceback (most recent call last):
  File "inkstitch.py", line 162, in <module>
  File "inkex\base.py", line 252, in run
  File "lib\extensions\stitch_plan_preview.py", line 61, in effect
  File "lib\extensions\stitch_plan_preview.py", line 123, in rasterize
  File "lib\extensions\utils\inkex_command.py", line 220, in inkscape
  File "lib\extensions\utils\inkex_command.py", line 186, in call
  File "lib\extensions\utils\inkex_command.py", line 154, in _call
  File "subprocess.py", line 858, in __init__
  File "subprocess.py", line 1311, in _execute_child
PermissionError: [WinError 5] Access is denied
***

![4th Emb go](https://github.com/user-attachments/assets/5b3570ba-63f6-4929-a40e-c5967279b6c2)

**Comment by capellancitizen** [comment]
That's a strange error message. [When someone else got a similar error, they were able to resolve it by rebooting their computer. Would you mind trying that?](https://github.com/inkstitch/inkstitch/issues/642)

If that doesn't work, you can try the realistic vector rendering mode, which often has worse performance but shouldn't cause the error.

The permissions error is odd: the program being invoked here is (or should be) inkscape itself, so it's weird that you would have a permissions error now when you're already able to run inkscape. Don't know enough about Windows permissions to know offhand what might be causing it.

**Comment by rejbasket** [comment]
This issue is very odd to occur, I did try to recreate this issue in windows with no success. To my understanding access is denied because writing to temp folder for user is being blocked, how, I don’t know for sure. Perhaps an anti-virus software blocks writing to temp folder, or extra security measures on the computer is causing this issue.
If this issue continues to happen, run Inkscape as Administrator.

**Comment by capellancitizen** [comment]
I was wondering about that. Does your computer have any antivirus or security software? Is there anything special about how you installed Inkscape or Inkstitch?

**Comment by kaalleen** [comment]
Closing. No further response.
If this is still an issue, please complain and we'll reopen the issue.
