### ISSUE TITLE
Failed on  AutoSatin Running Stitch 50 (autosatinrun28) at *.dst export

### ISSUE THREAD

**Issue by RichardRapid** [inkstitch/inkstitch#3221]
the Error Message from the failed export:
>
Failed on  AutoSatin Running Stitch 50 (autosatinrun28): Satin column: Object has too few subpaths.  A satin column should have at least two subpaths (the rails).

Please run Extensions > Ink/Stitch > Troubleshoot > Troubleshoot objects. This will indicate the errorneus position.
<

The error Message from the Troubleshoot:
>
Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\troubleshoot.py", line 33, in effect
  File "lib\elements\satin_column.py", line 652, in validation_errors
  File "lib\elements\satin_column.py", line 1262, in to_stitch_groups
  File "lib\elements\satin_column.py", line 1090, in do_satin
  File "lib\debug.py", line 231, in decorated
  File "lib\elements\satin_column.py", line 898, in plot_points_on_rails
  File "lib\elements\satin_column.py", line 629, in flattened_sections
  File "lib\elements\satin_column.py", line 629, in <listcomp>
IndexError: tuple index out of range
<
![PAPA _ MAMA Leandra   Jonathan](https://github.com/user-attachments/assets/6ea0a4ef-8687-4bcc-9295-0e48dc8d3fb2)

**Comment by tyrosinase** [comment]
Something has happened in the ampersand and a running stitch is marked as a satin (which, as the message indicates, only has one "rail").

![image](https://github.com/user-attachments/assets/aea4b153-3551-4ec5-b444-0ce929ab2e23)

The current version of Ink/Stitch (3.1.0 versus your 3.0.1) will handle that more-or-less correctly, but doesn't appear to have that fix included in the font cleanup so I'm not going to close the issue. Upgrading will fix it for you, or you can just delete that particular stitch object (it doesn't really add anything to the glyph, and is mostly just an auto-route artifact).

**Comment by kaalleen** [comment]
> more-or-less correctly, but doesn't appear to have that fix included in the font cleanup

What do you mean by that? Is there anything not working as expected?

**Comment by tyrosinase** [comment]
That running stitch is mismarked as a satin in the font file. It doesn't hurt anything now since 3.1.0 just stitches it as a default running stitch anyway (I think?) but it does throw an error in pre-3.1.0 Ink/Stitch. (Not that fixing the font in the current version would help with that, of course.)

**Comment by kaalleen** [comment]
Oh, thank you for pointing it out. I should've read it more carefully. I totally missed the point :D
I will rephrase the title then.

**Comment by kaalleen** [comment]
Geneva simple is an auto-route font. It originally has no running stitches. The satin param must have been set by the user.
Therefore I'm going to close the issue now. Nothing we can fix here that isn't already fixed.
