### ISSUE TITLE
auto_fill: path_to_stitches:  TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by anitarafiq** [inkstitch/inkstitch#3223]
Windows 10 version: 10.0.22631

Ink/Stitch Version: v3.1.0 (windows) 2024-07-27 09:05

Traceback (most recent call last):
  File "lib\elements\element.py", line 641, in handle_unexpected_exceptions
  File "lib\elements\element.py", line 605, in embroider
  File "lib\elements\fill_stitch.py", line 961, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 1044, in do_auto_fill
  File "lib\debug\debug.py", line 166, in decorated
  File "lib\stitches\auto_fill.py", line 116, in auto_fill
  File "lib\debug\debug.py", line 166, in decorated
  File "lib\stitches\auto_fill.py", line 929, in path_to_stitches
TypeError: 'NoneType' object is not iterable
![head-of-a-lion-with-a-crown-logo-free-vector](https://github.com/user-attachments/assets/aa472177-78e9-4143-b32e-783d3a41b82a)

**Comment by kaalleen** [comment]
Thank you for the error report. Can you upload the svg file which was causing the issue? The uploaded file is a jpg file.

**Comment by anitarafiq** [comment]
> Thank you for the error report. Can you upload the svg file which was causing the issue? The uploaded file is a jpg file.



> Thank you for the error report. Can you upload the svg file which was causing the issue? The uploaded file is a jpg file.

![lion](https://github.com/user-attachments/assets/7bdd20d0-7634-422d-8755-9a6c9c70858b)
![lion](https://github.com/user-attachments/assets/77bcb2e1-9b35-4318-9799-2d6bf92ba520)

**Comment by kaalleen** [comment]
Interesting. Thank you.
Can you describe your last steps before the error showed up?

**Comment by anitarafiq** [comment]
Well this error is happening with the fill stitch only when I run it with stroke it runs perfectly but in fill settings it only worked with gradient fill with imperfect filling and auto fill didn't work at all

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by kaalleen** [comment]
That's a bit strange. I tried to reproduce the error, but can't. Anybody else able to reproduce?

**Comment by tyrosinase** [comment]
> That's a bit strange. I tried to reproduce the error, but can't. Anybody else able to reproduce?

I couldn't (on 3.1.0/Linux).

**Comment by kaalleen** [comment]
Thanks for testing it!

**Comment by kaalleen** [comment]
@anitarafiq Is there a chance that you had underpathing disabled when the error showed up?

**Comment by anitarafiq** [comment]
Kallen my dear what is under patching??

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by kaalleen** [comment]
I'm going to close this issue, as I think it is similar to #3258 and usually has to do with underpathing. Please post a comment, if underpating was not used when the error appeared.
