### ISSUE TITLE
when running params

### ISSUE THREAD

**Issue by shiharris** [inkstitch/inkstitch#3232]
Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues/new

Include the error description and also (if possible) the svg file.

ProductName:		macOS
ProductVersion:		13.6.7
BuildVersion:		22G720
CPU:				arm64

Ink/Stitch Version: v3.1.0 (osx) 2024-07-27 08:50

Traceback (most recent call last):
  File "lib/elements/element.py", line 641, in handle_unexpected_exceptions
  File "lib/elements/element.py", line 605, in embroider
  File "lib/elements/fill_stitch.py", line 961, in to_stitch_groups
  File "lib/elements/fill_stitch.py", line 1044, in do_auto_fill
  File "lib/debug/debug.py", line 166, in decorated
  File "lib/stitches/auto_fill.py", line 92, in auto_fill
  File "lib/debug/debug.py", line 166, in decorated
  File "lib/stitches/auto_fill.py", line 143, in adjust_shape_for_pull_compensation
AttributeError: 'MultiPolygon' object has no attribute 'exterior'
![mama](https://github.com/user-attachments/assets/3f895741-f7af-4e30-94ba-4f9eb9a7e10c)

**Comment by gusvisser** [comment]
I had a look at your file it turns out that your satin elements in est 2010 all have a fill and a stroke so this would need to get set to only a stroke

Gus Visser

**Comment by tyrosinase** [comment]
As gus says, the "est. 2010" has a fill it shouldn't have, and that's brought out a bug - fixed in #3143 but not yet in a current release. To work around it, remove the fill (and change the stroke color instead, if that's what you intended).

I'm going to close the issue since the underlying bug is fixed, but if you have more questions don't hesitate to continue the conversation here.
