### ISSUE TITLE
opening params of multiple selected paths

### ISSUE THREAD

**Issue by Arkar1an** [inkstitch/inkstitch#3237]
I selected various objects (satin surges -> cohesion -> Auto-Route -> paths 1-10) in my svg file and attempted to open params with the inkstitch extension 
![tkr_west](https://github.com/user-attachments/assets/7731625e-c0fb-428f-8ddf-eb3404106e54)
and received the following error message:

```
Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\params.py", line 786, in effect
  File "lib\extensions\params.py", line 489, in __init__
  File "lib\extensions\params.py", line 748, in create_tabs
  File "lib\extensions\params.py", line 678, in get_nodes_by_class
  File "lib\extensions\base.py", line 115, in get_nodes
  File "lib\extensions\base.py", line 99, in descendants
  File "lib\extensions\base.py", line 99, in descendants
  File "lib\extensions\base.py", line 99, in descendants
  [Previous line repeated 2 more times]
  File "lib\extensions\base.py", line 72, in descendants
  File "lib\elements\element.py", line 422, in has_command
  File "lib\elements\element.py", line 418, in get_commands
  File "lib\elements\element.py", line 414, in commands
  File "lib\commands.py", line 191, in find_commands
  File "lib\commands.py", line 119, in __init__
  File "lib\commands.py", line 129, in parse_command
IndexError: list index out of range
```

But even just trying to look at the realistic visualizer does not work either...

**Comment by tyrosinase** [comment]
This looks like it might be the same situation as #2434, though that issue is closed which should mean there's a fix (in 2023, so it shouldn't be just a dev release).

In any case, see if removing and reapplying the commands works around the problem.

**Comment by Arkar1an** [comment]
It's strange, I was working with this version for weeks and then all of a sudden, today, all kinds of functions wouldn't work and were giving me that error today including using the realistic visualizer and trying to open the params... You can see in the svg that I have applied stop commands to satin rails for the other two symbols and i was trying to finish that work today on the final symbol...

I updated to the latest version and now I am not having that problem
