### ISSUE TITLE
Inkstitch

### ISSUE THREAD

**Issue by eReneeMo** [inkstitch/inkstitch#3238]
Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues/new

Include the error description and also (if possible) the svg file.

Windows 10 version: 10.0.19045

Ink/Stitch Version: v3.1.0 (windows) 2024-07-27 09:04

Traceback (most recent call last):
  File "lib\elements\element.py", line 641, in handle_unexpected_exceptions
  File "lib\elements\element.py", line 603, in embroider
  File "lib\elements\element.py", line 680, in validate
  File "lib\elements\satin_column.py", line 757, in validation_errors
  File "lib\elements\satin_column.py", line 559, in csp
  File "lib\elements\satin_column.py", line 559, in <listcomp>
  File "shapely\geometry\linestring.py", line 73, in __new__
  File "shapely\decorators.py", line 77, in wrapped
  File "shapely\creation.py", line 119, in linestrings
shapely.errors.GEOSException: IllegalArgumentException: point array must contain 0 or >1 elements

**Comment by tyrosinase** [comment]
This looks like another instance of the same (still open) bug as #3180 - as kaalleen says there, `The path somehow has become invalid and contains a subpath with only one node. Inkscape will correct the path as soon as any other node is touched.`

I'm going to close the issue in favor of the other one, but if you have trouble locating the specific path you can still upload it to this thread (or email it to the devs if you don't want it public) and someone will try to help you out. Selecting your satins and going into Node Edit usually turns up the stray node.
