### ISSUE TITLE
code erreur

### ISSUE THREAD

**Issue by ByCarineC** [inkstitch/inkstitch#3260]
Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues/new

Include the error description and also (if possible) the svg file.

Windows 10 version: 10.0.19045

Ink/Stitch Version: v3.1.0 (windows) 2024-07-27 09:04

Traceback (most recent call last):
  File "lib\elements\element.py", line 641, in handle_unexpected_exceptions
  File "lib\elements\element.py", line 600, in embroider
  File "lib\debug\debug.py", line 166, in decorated
  File "lib\elements\element.py", line 510, in _load_cached_stitch_groups
  File "lib\elements\element.py", line 579, in get_cache_key
  File "lib\elements\element.py", line 564, in _get_gradient_cache_key_data
  File "lib\elements\element.py", line 564, in <listcomp>
  File "inkex\styles.py", line 331, in __getitem__
KeyError: 'stop-color'
![dessinbug](https://github.com/user-attachments/assets/fccaa6cd-784a-4707-812d-79f69b4db43a)

**Comment by kaalleen** [comment]
Thanks a lot for the great file (in terms of error fixing possibilities :) )

The gradient style has been fixed, clones of grouped clones have been fixed. The only thing that remains unfixed is that the size isn't recognized correctly for an svg file within the svg file. Not sure if we should take the hassle to fix it though. I think I'll close the issue since two of the main problems within the file should be gone in the next release. The size issues can be fixed manually by the user by "ungrouping" the svg element. I think that is good enough.
