### ISSUE TITLE
Simulating Path Give Python Error

### ISSUE THREAD

**Issue by atrus6** [inkstitch/inkstitch#329]
In the attached file is an svg with a single path (path895). It's a bit of a wonky path, but I wanted to see what happened if you simulated it. Simulation however, throws the python error:

```
Traceback (most recent call last):
  File "inkstitch.py", line 20, in <module>
    if script_name.endswith('.py'):
  File "inkscape-0.92.3/share/extensions/inkex.py", line 283, in affect
  File "lib/extensions/simulate.py", line 21, in effect
  File "lib/extensions/base.py", line 194, in elements_to_patches
  File "lib/elements/element.py", line 260, in embroider
  File "lib/elements/auto_fill.py", line 137, in to_patches
  File "lib/elements/auto_fill.py", line 101, in fill_shape
  File "lib/elements/auto_fill.py", line 93, in shrink_or_grow_shape
  File "site-packages/backports/functools_lru_cache.py", line 113, in wrapper
  File "lib/elements/fill.py", line 87, in shape
  File "lib/elements/fill.py", line 87, in <lambda>
  File "site-packages/shapely/geometry/polygon.py", line 240, in __init__
  File "site-packages/shapely/geometry/polygon.py", line 494, in geos_polygon_from_py
  File "shapely/speedups/_speedups.pyx", line 321, in shapely.speedups._speedups.geos_linearring_from_py
ValueError: A LinearRing must have at least 3 coordinate tuples
```

[python_error.zip](https://github.com/inkstitch/inkstitch/files/2430533/python_error.zip)
You should be able to just unzip, open the svg, hit simulate and error out.

**Comment by atrus6** [comment]
Cancel that, I was running an older version. It's all fixed in the lastest!
