### ISSUE TITLE
Error if "Underpath" => false

### ISSUE THREAD

**Issue by shtobnik** [inkstitch/inkstitch#3303]
ProductName:		macOS
ProductVersion:		14.5
BuildVersion:		23F79
CPU:				x86_64

Ink/Stitch Version: v3.1.0 (osx) 2024-07-27 08:52

Traceback (most recent call last):
  File "lib/elements/element.py", line 641, in handle_unexpected_exceptions
  File "lib/elements/element.py", line 605, in embroider
  File "lib/elements/fill_stitch.py", line 961, in to_stitch_groups
  File "lib/elements/fill_stitch.py", line 1044, in do_auto_fill
  File "lib/debug/debug.py", line 166, in decorated
  File "lib/stitches/auto_fill.py", line 116, in auto_fill
  File "lib/debug/debug.py", line 166, in decorated
  File "lib/stitches/auto_fill.py", line 929, in path_to_stitches
TypeError: 'NoneType' object is not iterable

**Comment by kaalleen** [comment]
Thank you for the error report. The issue should be fixed by now in current development releases.

**Comment by kaalleen** [comment]
I'm going to close the issue, since it is supposed to be fixed for the next Ink/Stitch version.
Just make sure, that your starting and ending points are positioned on the same outline, for example do not start at the outside of the shape and end inside of a hole.
