### ISSUE TITLE
Indkstitch Error Message

### ISSUE THREAD

**Issue by mdorval123** [inkstitch/inkstitch#3304]
Linux Mint 22

Ink/Stitch Version: v3.1.0 (linux) 2024-07-27 09:12

Traceback (most recent call last):
  File "lib/elements/element.py", line 641, in handle_unexpected_exceptions
  File "lib/elements/element.py", line 605, in embroider
  File "lib/elements/fill_stitch.py", line 956, in to_stitch_groups
  File "lib/elements/fill_stitch.py", line 1216, in do_linear_gradient_fill
  File "lib/stitches/linear_gradient_fill.py", line 28, in linear_gradient_fill
  File "lib/stitches/linear_gradient_fill.py", line 293, in _get_stitch_groups
  File "lib/stitches/circular_fill.py", line 163, in path_to_stitches
TypeError: 'NoneType' object is not iterable
![chirho](https://github.com/user-attachments/assets/81b7c975-f73c-45f6-ad6f-93cda11e20ab)

**Comment by mdorval123** [comment]
![chirho](https://github.com/user-attachments/assets/1ed61f4f-c5a7-4ff9-9456-d910033c0bbd)
