### ISSUE TITLE
unexpected error with SVG file

### ISSUE THREAD

**Issue by crdotson** [inkstitch/inkstitch#3313]
I will try simplifying this SVG and other troubleshooting, but Ink/Stitch asked me to submit an issue if I'd like to help, and I'd certainly like to help out!

With this SVG, I got the following error:

![Intapp_Logo_FullColor_Positive](https://github.com/user-attachments/assets/90524d58-ddaa-442a-ac54-0ababbb4d75b)

Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues/new

Include the error description and also (if possible) the svg file.

Windows 10 version: 10.0.22631

Ink/Stitch Version: v3.1.0 (windows) 2024-07-27 09:04

Traceback (most recent call last):
  File "lib\elements\element.py", line 641, in handle_unexpected_exceptions
  File "lib\elements\element.py", line 600, in embroider
  File "lib\debug\debug.py", line 166, in decorated
  File "lib\elements\element.py", line 510, in _load_cached_stitch_groups
  File "lib\elements\element.py", line 579, in get_cache_key
  File "lib\elements\element.py", line 564, in _get_gradient_cache_key_data
  File "lib\elements\element.py", line 564, in <listcomp>
  File "inkex\styles.py", line 331, in __getitem__
KeyError: 'stop-color'

Please let me know if you'd like any other information.  Thanks for creating Ink/Stitch!

**Comment by crdotson** [comment]
To be clear, I fixed my issue by changing all of the colors to black -- I think the initial colors were interpreted as odd stitch patterns -- but thought you might like to know about the crash anyway.

**Comment by kaalleen** [comment]
Yes, thank you for the error report and sorry for the late response.
The error has already been fixed for the next release.
But if you find more errors like this, please keep informing us on GitHub. It is really helpful.
