### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Dide300** [inkstitch/inkstitch#3314]
Ink/Stitch Version: v3.1.0 (windows) 2024-07-27 09:04

Traceback (most recent call last):
  File "lib\elements\element.py", line 641, in handle_unexpected_exceptions
  File "lib\elements\element.py", line 605, in embroider
  File "lib\elements\fill_stitch.py", line 961, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 1044, in do_auto_fill
  File "lib\debug\debug.py", line 166, in decorated
  File "lib\stitches\auto_fill.py", line 116, in auto_fill
  File "lib\debug\debug.py", line 166, in decorated
  File "lib\stitches\auto_fill.py", line 929, in path_to_stitches
TypeError: 'NoneType' object is not iterable

**Comment by kaalleen** [comment]
Is this happening when you de-activate underpathing?

**Comment by kaalleen** [comment]
Closing as duplicate of #3223
