### ISSUE TITLE
INKSTITC ERROR

### ISSUE THREAD

**Issue by DESTESS732499** [inkstitch/inkstitch#3317]
RECIEVED AN ERROR CODE AFTER PLACES A SVG IN PARAMS. I'M NEW TO THIS AND DONT KNOW IF THIS IS HOW YOU SUBMIT THE ERROR CODE CORRECTLY. HERE IS A COPY OF THE ERROR MESSAGE

Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues/new

Include the error description and also (if possible) the svg file.

ProductName:		macOS
ProductVersion:		15.1.1
BuildVersion:		24B91
CPU:				x86_64

Ink/Stitch Version: v3.1.0 (osx) 2024-07-27 08:52

Traceback (most recent call last):
  File "lib/elements/element.py", line 641, in handle_unexpected_exceptions
  File "lib/elements/element.py", line 600, in embroider
  File "lib/debug/debug.py", line 166, in decorated
  File "lib/elements/element.py", line 510, in _load_cached_stitch_groups
  File "lib/elements/element.py", line 584, in get_cache_key
  File "lib/elements/clone.py", line 71, in get_cache_key_data
  File "lib/elements/clone.py", line 71, in <listcomp>
  File "lib/elements/element.py", line 579, in get_cache_key
  File "lib/elements/element.py", line 564, in _get_gradient_cache_key_data
  File "lib/elements/element.py", line 564, in <listcomp>
  File "inkex/styles.py", line 331, in __getitem__
KeyError: 'stop-color'

**Comment by tyrosinase** [comment]
You've done it exactly right!

This is fixed in #3200 so you could install a development release to fix it, but you can also just work around it by changing the colors in the gradient(s). There's something about some gradients created outside of Inkscape that the current version of Ink/Stitch didn't like, but editing it will make them recognizable.

I'm going to close the issue since the code is fixed, but you can still add comments if you need help working around it (or installing a dev release).
