### ISSUE TITLE
Export issue 

### ISSUE THREAD

**Issue by bmckendall** [inkstitch/inkstitch#3333]
![wet bandts v3](https://github.com/user-attachments/assets/7c77c892-c94e-4990-ab40-0bd9c3adca06)

Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues/new

Include the error description and also (if possible) the svg file.

Windows 10 version: 10.0.19045

Ink/Stitch Version: v3.1.0 (windows) 2024-07-27 09:04

Traceback (most recent call last):
  File "lib\elements\element.py", line 641, in handle_unexpected_exceptions
  File "lib\elements\element.py", line 605, in embroider
  File "lib\elements\fill_stitch.py", line 961, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 1044, in do_auto_fill
  File "lib\debug\debug.py", line 166, in decorated
  File "lib\stitches\auto_fill.py", line 92, in auto_fill
  File "lib\debug\debug.py", line 166, in decorated
  File "lib\stitches\auto_fill.py", line 143, in adjust_shape_for_pull_compensation
AttributeError: 'MultiPolygon' object has no attribute 'exterior'

**Comment by Marif91** [comment]
Il y a plusieurs erreurs dans ce motif.

**Comment by Marif91** [comment]
Consulter cette page pour corriger les erreurs qui sont dans ce motif https://inkstitch.org/docs/troubleshoot/

**Comment by tyrosinase** [comment]
The underlying bug has been fixed in #3143 , so if it persists after the design has been cleaned up you can try a pre-release version.
