### ISSUE TITLE
Mutter timeout settings

### ISSUE THREAD

**Issue by thhead** [inkstitch/inkstitch#3337]
This is one error:

Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues/new

Include the error description and also (if possible) the svg file.

Ubuntu 24.04.1 LTS

Ink/Stitch Version: v3.1.0 (linux) 2024-07-27 09:12

Traceback (most recent call last):
  File "inkstitch.py", line 162, in <module>
  File "inkex/base.py", line 252, in run
  File "lib/extensions/stitch_plan_preview.py", line 61, in effect
  File "lib/extensions/stitch_plan_preview.py", line 123, in rasterize
  File "lib/extensions/utils/inkex_command.py", line 220, in inkscape
  File "lib/extensions/utils/inkex_command.py", line 186, in call
  File "lib/extensions/utils/inkex_command.py", line 152, in _call
inkex.command.ProgramRunError: Return Code: -5: b"\n(inkscape:59159): GLib-GIO-ERROR **: 09:51:40.357: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'\n"
b''
args: ('Return Code: -5: b"\\n(inkscape:59159): GLib-GIO-ERROR **: 09:51:40.357: Settings schema \'org.gnome.settings-daemon.plugins.xsettings\' does not contain a key named \'antialiasing\'\\n"\nb\'\'\nargs: (\'inkscape\', -5, b"\\n(inkscape:59159): GLib-GIO-ERROR **: 09:51:40.357: Settings schema \'org.gnome.settings-daemon.plugins.xsettings\' does not contain a key named \'antialiasing\'\\n", b\'\', [\'/usr/bin/inkscape\', \'--actions=select-by-id: __inkstitch_stitch_plan__; query-x; query-y; query-width; query-height; export-id: __inkstitch_stitch_plan__; export-id-only; export-type: png; export-dpi: 300; export-png-color-mode: RGBA_16; export-filename: /tmp/tmpwwkig5ov/temp.png; export-do\', \'/tmp/tmpwwkig5ov/temp.svg\'])',)

File used: /usr/share/inkscape/examples/text-on-path.svg

**Comment by tyrosinase** [comment]
Wayland strikes again!

See if starting Inkscape from the command line with this works:

`export GDK_BACKEND=x11 && inkscape`

**Comment by kaalleen** [comment]
If I am not wrong, this usually happens with older Inkscape versions. Should be fixed when you update Inkscape.

**Comment by thhead** [comment]
Thanks for the input. Results: are they as expected? Still have error.

***@***.***:~/Desktop$ export GDK_BACKEND=x11 && inkscape
CMSSystem::load_profiles: /usr/share/color/icc/colord/x11-colors.icc is not
an ICC file!
CMSSystem::load_profiles: /usr/share/color/icc/colord/Crayons.icc is not an
ICC file!
CMSSystem::load_profiles: ICC profile with duplicate name: Artifex Software
sRGB ICC Profile:
   /usr/share/color/icc/ghostscript/srgb.icc
   /usr/share/color/icc/ghostscript/default_rgb.icc
CMSSystem::load_profiles: ICC profile with duplicate name: Artifex PS CMYK
Profile:
   /usr/share/color/icc/ghostscript/ps_cmyk.icc
   /usr/share/color/icc/ghostscript/gray_to_k.icc
CMSSystem::load_profiles: ICC profile with duplicate name: Artifex Software
sGray ICC Profile:
   /usr/share/color/icc/ghostscript/sgray.icc
   /usr/share/color/icc/ghostscript/default_gray.icc

(org.inkscape.Inkscape:8462): Gtk-CRITICAL **: 12:02:35.690: invalid
accelerator string ''

(org.inkscape.Inkscape:8462): Gtk-CRITICAL **: 12:02:35.690:
gtk_application_accels_get_actions_for_accel: assertion 'accel_key.key !=
0' failed

(org.inkscape.Inkscape:8462): Gtk-WARNING **: 12:02:35.691: Unable to parse
accelerator '': ignored request to install 1 accelerators

**Comment by kaalleen** [comment]
We can access the inkscape version somehow, but only through an Inkscape call ... which I actually wouldn't necessarily like to do.

The stitch plan extension isn't wxpython based, so no wayland work around can help with this issue (just if params, simulator, lettering and alike don't work).

**Comment by kaalleen** [comment]
Looking at the last error message you've posted I'm really confused with the Inkscape version though. Which version do you use?

**Comment by thhead** [comment]
[image: image.png]

**Comment by thhead** [comment]
Not sure image went out.
Latest release: 27.07.2024 Ink/Stitch v3.1.0

**Comment by thhead** [comment]
Ok, params, simulator, lettering and alike don't work. Same "has stopped/,
wait,force quit" I'm lost, is this a linux issue or Ink.

**Comment by thhead** [comment]
Looks like the missing, key, named 'antialiasing'\n", b'' is the culprit and common to all my errorrs.

Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'\n", b''

**Comment by kaalleen** [comment]
Which Inkscape version do you use?

**Comment by kaalleen** [comment]
You can also try to pick one of these linux-new files in here as they are build on ubuntu 24.04

https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-update-workflow

**Comment by thhead** [comment]
Inkscape 1.4 (1:1.4+202410161351+e7c3feb100)

**Comment by thhead** [comment]
Thanks, I installed the amd 64, and appears it is playing nice now I have
to get functional. Thanks again for your work ethic.
Terry

**Comment by thhead** [comment]
Forgot to mention I changed the mutter setting from 5000 to 15000. It seems
to help. All is well now Thanks again.

In versions of mutter ≥ 3.35.92, you can set the timeout used to check if a
window is still alive. This is also useful for X-forwarding over ssh with
high latency. For example, you can set the timeout to 60 s (60000 ms) using:

gsettings set org.gnome.mutter check-alive-timeout 60000

**Comment by kaalleen** [comment]
Thanks for the info. I guess we should document this when we officially release for ubuntu 24.04.
