### ISSUE TITLE
Ink/Stitch Bug

### ISSUE THREAD

**Issue by divey-tx** [inkstitch/inkstitch#3338]
Hi, I ran into an error and I'm following the instructions provided. Here is the error description and the svg file.

ProductName:		macOS
ProductVersion:		15.1.1
BuildVersion:		24B91
CPU:				x86_64

Ink/Stitch Version: v3.1.0 (osx) 2024-07-27 08:52

Traceback (most recent call last):
  File "lib/elements/element.py", line 641, in handle_unexpected_exceptions
  File "lib/elements/element.py", line 605, in embroider
  File "lib/elements/fill_stitch.py", line 961, in to_stitch_groups
  File "lib/elements/fill_stitch.py", line 1044, in do_auto_fill
  File "lib/debug/debug.py", line 166, in decorated
  File "lib/stitches/auto_fill.py", line 92, in auto_fill
  File "lib/debug/debug.py", line 166, in decorated
  File "lib/stitches/auto_fill.py", line 143, in adjust_shape_for_pull_compensation
AttributeError: 'MultiPolygon' object has no attribute 'exterior'
![tyrant](https://github.com/user-attachments/assets/2d1f34e4-56e8-4538-85c2-297415830761)

Thans,
Daniel

**Comment by Marif91** [comment]
Tout sera bien meiux quand tu enlèvera le fond de tous tes chemins, il ne faut garder que le contour !

**Comment by tyrosinase** [comment]
That bug is fixed for future releases (or dev release, per #3143) but the real problem there is: to change the color of satins, you need to change the Stroke color rather than adding a Fill.

**Comment by kaalleen** [comment]
I'm going to close the issue as it should be fixed. You can still answer on the thread if you have remaining questions.
