### ISSUE TITLE
NoneType

### ISSUE THREAD

**Issue by gursimarsaggu4** [inkstitch/inkstitch#3341]
![paidro-1](https://github.com/user-attachments/assets/fddc661b-24eb-44a6-ae92-0f8e19c17bb0)
Windows 10 version: 10.0.22631

Ink/Stitch Version: v3.1.0 (windows) 2024-07-27 09:04

Traceback (most recent call last):
  File "lib\elements\element.py", line 641, in handle_unexpected_exceptions
  File "lib\elements\element.py", line 605, in embroider
  File "lib\elements\fill_stitch.py", line 961, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 1044, in do_auto_fill
  File "lib\debug\debug.py", line 166, in decorated
  File "lib\stitches\auto_fill.py", line 116, in auto_fill
  File "lib\debug\debug.py", line 166, in decorated
  File "lib\stitches\auto_fill.py", line 929, in path_to_stitches
TypeError: 'NoneType' object is not iterable

**Comment by tyrosinase** [comment]
That bug has been fixed via #3141 in development and future releases.

However, it's likely to go away by the time you're done making an actually-stitchable design. You've got a lot going on right now:

* It's all one path. You'll need to break it up so Ink/Stitch has a better idea what order to stitch things in.
* The stroke and fill should be separate objects.
* It relies on a thick stroke, much thicker than the thread will be. Ink/Stitch can attempt to stitch it out as a zigzag if you tell it to, but you will really need to do a proper satin conversion to get good corners/curves.

I'm going to close the issue since the bug is already handled, but you can continue the conversation if you have more questions.
