### ISSUE TITLE
wont use ink stitch feature on proggram

### ISSUE THREAD

**Issue by Tregreen96** [inkstitch/inkstitch#3342]
Windows 10 version: 10.0.26100

Ink/Stitch Version: v3.1.0 (windows) 2024-07-27 09:04

Traceback (most recent call last):
  File "inkstitch.py", line 162, in <module>
  File "inkex\base.py", line 252, in run
  File "lib\extensions\convert_to_satin.py", line 54, in effect
  File "lib\elements\stroke.py", line 426, in paths
  File "lib\elements\element.py", line 426, in parse_path
  File "lib\elements\element.py", line 422, in path
  File "inkex\paths\path.py", line 611, in to_superpath
  File "inkex\paths\path.py", line 647, in __init__
  File "inkex\paths\path.py", line 700, in append_path_command
  File "inkex\paths\arc.py", line 272, in to_curves
  File "inkex\paths\arc.py", line 603, in arc_to_path
ZeroDivisionError: float division by zero

**Comment by kaalleen** [comment]
Can you send the svg file which was causing the error and give a few hints how to reproduce it?

Please note that an upload via mail is not possible. You will need to login into GitHub.
