### ISSUE TITLE
Inkstitch error message "Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch"

### ISSUE THREAD

**Issue by Lysdance** [inkstitch/inkstitch#3359]
The instructions said to create an issue on here and post the error message, so here it is:

Windows 10 version: 10.0.26100

Ink/Stitch Version: v3.1.0 (windows) 2024-07-27 09:04

Traceback (most recent call last):
  File "lib\extensions\convert_to_satin.py", line 75, in convert_path_to_satins
  File "lib\extensions\convert_to_satin.py", line 142, in path_to_satin
lib.extensions.convert_to_satin.SelfIntersectionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib\extensions\convert_to_satin.py", line 75, in convert_path_to_satins
  File "lib\extensions\convert_to_satin.py", line 142, in path_to_satin
lib.extensions.convert_to_satin.SelfIntersectionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "inkstitch.py", line 162, in <module>
  File "inkex\base.py", line 252, in run
  File "lib\extensions\convert_to_satin.py", line 61, in effect
  File "lib\extensions\convert_to_satin.py", line 89, in convert_path_to_satins
  File "lib\extensions\convert_to_satin.py", line 89, in convert_path_to_satins
  File "lib\extensions\convert_to_satin.py", line 75, in convert_path_to_satins
  File "lib\extensions\convert_to_satin.py", line 162, in path_to_satin
  File "lib\extensions\convert_to_satin.py", line 263, in generate_rungs
  File "lib\extensions\convert_to_satin.py", line 194, in get_scores
  File "lib\utils\geometry.py", line 294, in unit
ZeroDivisionError: float division by zero

![xmas](https://github.com/user-attachments/assets/984023cc-a3f6-4261-81b0-2cfd63260d02)

**Comment by tyrosinase** [comment]
It probably shouldn't throw that error, but aside from that, "convert to satin" isn't going to do what you may be expecting here. That's probably beyond the scope of the four-digit embroidery software like Embrilliance, and definitely far beyond Ink/Stitch. If you look at tutorial like https://silverseams.com/tutorials/satin-joins-and-corners.html it will give you a lot better idea about how converting raw SVG to stitchable files goes.

I'm going to close the issue since PR #3268 fixes the raw error message for future releases. But that doesn't prevent future conversation in this thread if you have more questions about how to go about making that a stitchable file.
