### ISSUE TITLE
Ink/Stitch.Troubleshoot Objects returns a bug report

### ISSUE THREAD

**Issue by Brodli4** [inkstitch/inkstitch#3369]
Ink/Stitch Version: v3.0.1 (windows)
![essai1](https://github.com/user-attachments/assets/a6a636f1-b7d0-4dfb-9e16-c5badf025d6d)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\troubleshoot.py", line 33, in effect
  File "lib\elements\satin_column.py", line 652, in validation_errors
  File "lib\elements\satin_column.py", line 1262, in to_stitch_groups
  File "lib\elements\satin_column.py", line 1090, in do_satin
  File "lib\debug.py", line 231, in decorated
  File "lib\elements\satin_column.py", line 898, in plot_points_on_rails
  File "lib\elements\satin_column.py", line 629, in flattened_sections
  File "lib\elements\satin_column.py", line 629, in <listcomp>
IndexError: tuple index out of range

**Comment by kaalleen** [comment]
The left dotted line has a satin column setting. Satin columns can't really work with only one line.
But the setting shouldn't pose an issue with the latest release and Ink/Stitch should render it as a running stitch. Which version of Ink/Stitch do you use?

**Comment by Brodli4** [comment]
V3.0.1 Windows

**Comment by kaalleen** [comment]
Current version is 3.1.0
