### ISSUE TITLE
Unable to save embroidery file with more than one Lettering objects

### ISSUE THREAD

**Issue by sabr1993** [inkstitch/inkstitch#3374]
I'm trying to get two or more different Lettering items in my embroidery file but since I add more than one lettering object, I get an error when I'm trying to save the file.

Windows 10 version: 10.0.22631

Ink/Stitch Version: v3.1.0 (windows) 2024-07-27 09:04

Traceback (most recent call last):
  File "lib\elements\element.py", line 641, in handle_unexpected_exceptions
  File "lib\elements\element.py", line 605, in embroider
  File "lib\elements\fill_stitch.py", line 961, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 1044, in do_auto_fill
  File "lib\debug\debug.py", line 166, in decorated
  File "lib\stitches\auto_fill.py", line 92, in auto_fill
  File "lib\debug\debug.py", line 166, in decorated
  File "lib\stitches\auto_fill.py", line 143, in adjust_shape_for_pull_compensation
AttributeError: 'MultiPolygon' object has no attribute 'exterior'

![image](https://github.com/user-attachments/assets/d573d8dc-d488-4ba2-a693-a1454341ba0e)
![Zeichnung](https://github.com/user-attachments/assets/e69e9ace-8aa8-410a-8b4c-3e124a5a5797)

Desired embroidery-formats for brother: pes, pec

**Comment by kaalleen** [comment]
Thank you for the error report. The underlying error has been fixed for the next version.
But it won't look good to save it like that.
The satin columns have a fill color. When you remove it and adjust the stroke color instead, you'll be fine.
