### ISSUE TITLE
Debug Error Message in Apply Pallette

### ISSUE THREAD

**Issue by victoryred** [inkstitch/inkstitch#3377]
Debian GNU/Linux 12 (bookworm)

Ink/Stitch Version: v3.1.0 (linux) 2024-07-27 09:12

Traceback (most recent call last):
  File "inkstitch.py", line 162, in <module>
  File "inkex/base.py", line 252, in run
  File "lib/extensions/apply_palette.py", line 42, in effect
  File "lib/threads/color.py", line 42, in __init__
TypeError: expected string or bytes-like object

![Good Test Paths for Cross](https://github.com/user-attachments/assets/f03b58d6-8745-4335-8bea-b421053492fe)

**Comment by kaalleen** [comment]
Thank you for the error report. Do you have the thread palettes installed?

https://inkstitch.org/docs/thread-color/#install-thread-color-palettes-for-inkscape

**Comment by victoryred** [comment]
Inkstitch reports that they are.Sent from the Luminescent EtherOn Dec 28, 2024, at 1:10 AM, Kaalleen ***@***.***> wrote:﻿
Thank you for the error report. Do you have the thread palettes installed?
https://inkstitch.org/docs/thread-color/#install-thread-color-palettes-for-inkscape
