### ISSUE TITLE
Error rendering stitch plan in params

### ISSUE THREAD

**Issue by are-dot** [inkstitch/inkstitch#3387]
I'm encountering an error when trying to adjust the params of my svg. I was able to a few times previously but now I get this error message every time I open it.

Windows 10 version: 10.0.22631

Ink/Stitch Version: v3.1.0 (windows) 2024-07-27 09:04

Traceback (most recent call last):
  File "lib\elements\element.py", line 641, in handle_unexpected_exceptions
  File "lib\elements\element.py", line 600, in embroider
  File "lib\debug\debug.py", line 166, in decorated
  File "lib\elements\element.py", line 510, in _load_cached_stitch_groups
  File "lib\elements\element.py", line 579, in get_cache_key
  File "lib\elements\element.py", line 561, in _get_gradient_cache_key_data
  File "lib\elements\fill_stitch.py", line 637, in gradient
  File "inkex\elements\_base.py", line 662, in get_computed_style
  File "inkex\styles.py", line 602, in _get_style
  File "inkex\properties.py", line 286, in convert
ValueError: Paint server not found

**Comment by kaalleen** [comment]
Do you have the svg file which caused the issue?

**Comment by tyrosinase** [comment]
@

> Do you have the svg file which caused the issue?

We've got one in #3612!

**Comment by kaalleen** [comment]
I can reproduce with 3.1.0, but I can't with current development releases. So I think it is fixes. Please open a new issue if this error shows up again with the next release.
