### ISSUE TITLE
Failed to Save; Satin column: Object has too few subpaths - Object params only use fill underlay and fill, no satin stitching

### ISSUE THREAD

**Issue by nsperger** [inkstitch/inkstitch#3390]
Error is happening when trying to save the file as a .pes, the problem being the circle, 'path1'. Stitches fine in the Params, and isn't trying to do a satin stitch, only looking to do a fill underlay and fill. File saves as a .pes file just fine when I delete 'path1'.

Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\troubleshoot.py", line 33, in effect
  File "lib\elements\satin_column.py", line 652, in validation_errors
  File "lib\elements\satin_column.py", line 1262, in to_stitch_groups
  File "lib\elements\satin_column.py", line 1090, in do_satin
  File "lib\debug.py", line 231, in decorated
  File "lib\elements\satin_column.py", line 898, in plot_points_on_rails
  File "lib\elements\satin_column.py", line 629, in flattened_sections
  File "lib\elements\satin_column.py", line 629, in <listcomp>
IndexError: tuple index out of range

![PhillyEast](https://github.com/user-attachments/assets/0b92d021-282b-4ab4-a4e0-be7a51b29e86)

**Comment by kaalleen** [comment]
The pink dot has a fill and a contour color and is defined as a satin.
If you wan to render it as a satin, you'll have to remove the fill, convert object to path and break it open at two opposing spots. Then reapply the satin settings.

**Comment by kaalleen** [comment]
And by the way, thank you for taking the extra step to inform us about errors.
The error itself has been fixed or the next release.
