### ISSUE TITLE
One object refuses to autofill. Can't figure out why

### ISSUE THREAD

**Issue by ndrwclrk** [inkstitch/inkstitch#358]
Hey folks, great plug-in!  I'm loving using it.  
I'm working on a design, found in the attached (zipped) svg file.  The object called "EyeLeft" seems to be causing trouble.  If I bring up the params box, it just sits there until I select manual fill.  When I select autofill, it does nothing. If I try a simulation, I get the following error: 
Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
    if stdout:
  File "inkscape/share/extensions/inkex.py", line 283, in affect
  File "lib/extensions/simulate.py", line 17, in effect
  File "lib/extensions/base.py", line 200, in elements_to_patches
  File "lib/elements/element.py", line 268, in embroider
  File "lib/elements/auto_fill.py", line 153, in to_patches
  File "lib/stitches/auto_fill.py", line 48, in auto_fill
  File "lib/stitches/auto_fill.py", line 167, in build_graph
Exception: Unable to autofill.  This most often happens because your shape is made up of multiple sections that aren't connected.
I just can't seem to see any hidden multiple sections in the object.  It's basically almost a mirror image of the "EyeRight" object, which autofills just fine.  Any ideas what I might be doing wrong, and how to fix it?   When I make "EyeLeft" invisible, the entire design simulates just fine. 

[DogSVG.zip](https://github.com/inkstitch/inkstitch/files/2612020/DogSVG.zip)

**Comment by kaalleen** [comment]
If you make the eye itself (the hole in the object) just a tiny bit bigger you will be fine.

You could also simplify the path by pressing Ctrl + L because you have overlaying nodes in the eyeball, although this isn't causing the issue for your design here. If you do so, you have to reassign the underlay.

**Comment by ndrwclrk** [comment]
Bingo!  That totally worked.  Thanks so much for your help.
