### ISSUE TITLE
Script not executing ERROR:root:code

### ISSUE THREAD

**Issue by katherinephx** [inkstitch/inkstitch#380]
I've installed Inkscape and I've placed the inkstitch extension in the appropriate folder /Users/myusername/.config/inkscape/extensions 
I can see the extension while working inside Inkscape however every time I try to use the extension I receive the following message. See below.  Please help.  I'm working on Mac OS Sierra

ERROR MESSAGE
Inkscape has received additional data from the script executed.  The script did not return an error, but this may indicate the results will not be as expected.

ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "hashlib.py", line 147, in <module>
  File "hashlib.py", line 97, in __get_builtin_constructor
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "hashlib.py", line 147, in <module>
  File "hashlib.py", line 97, in __get_builtin_constructor
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "hashlib.py", line 147, in <module>
  File "hashlib.py", line 97, in __get_builtin_constructor
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "hashlib.py", line 147, in <module>
  File "hashlib.py", line 97, in __get_builtin_constructor
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "hashlib.py", line 147, in <module>
  File "hashlib.py", line 97, in __get_builtin_constructor
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "hashlib.py", line 147, in <module>
  File "hashlib.py", line 97, in __get_builtin_constructor
ValueError: unsupported hash type sha512
Traceback (most recent call last):
  File "inkstitch.py", line 8, in <module>
    # ink/stitch
  File "/private/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/pip-install-p00fYd/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "lib/extensions/__init__.py", line 14, in <module>
  File "/private/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/pip-install-p00fYd/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "lib/extensions/print_pdf.py", line 13, in <module>
  File "/private/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/pip-install-p00fYd/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "site-packages/jinja2/__init__.py", line 36, in <module>
  File "/private/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/pip-install-p00fYd/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "site-packages/jinja2/loaders.py", line 16, in <module>
ImportError: cannot import name sha1
[5270] Failed to execute script inkstitch

**Comment by kaalleen** [comment]
@katherinephx welcome to the project!

>  I'm working on Mac OS Sierra

I wish I could give you a better answer, but this already might be the problem you are running into. Ink/Stitch will not work with macOS versions previous to High Sierra.
