### ISSUE TITLE
Installation problems on a production Centos7 machine

### ISSUE THREAD

**Issue by rebatov** [inkstitch/inkstitch#446]
I have installed inkstitch on ubuntu 16.04 on my desktop by just following the normal installation process and it works well. But I have a production server running on Centos7 with inkscape 0.92.2 and I did the same but converting the DST files to SVG from the command line results an error.

$ inkscape -z Motherday-SP.DST -l motherday.svg
Motherday-SP.DST:1: parser error : Start tag expected, '<' not found
LA:Holiday-        
^
Motherday-SP.DST:1: parser error : Start tag expected, '<' not found
LA:Holiday-        
^

** (inkscape:4772): WARNING **: Specified document Motherday-SP.DST cannot be opened (does not exist or not a valid SVG file)

Is it because it is not installed correctly, I also tried installing from the source but that didnot work and resulted in error during pip installation.

Please help!

**Comment by lexelby** [comment]
That does sound like something went wrong with the installation on the centos server.  If Inkscape doesn't see the `inkstitch_output*.inx` files, then it won't know to use Ink/Stitch to open DST files, and it will default to trying to open them as SVG files.  I'd recommend you `rm inkstitch*` from your extensions directory and give it another try.

I have to say, I'm fascinated and really curious about your workflow!  How does converting DST files to SVG on the command line help you?

**Comment by rebatov** [comment]
I tried like you suggested and still inkscape does not seem to identify inkstitch at all and maybe it is treating like the SVG. My workflow is I have an application that can deal with multiple genre of vector files and convert it to SVG and PNG may it be with inkscape, gs, libreofffice, etc. My recent endeavor is on the embroidery vector files and I did try pyembroidery but it is not as accurate as inkstitch is regarding the SVG/PNG export. Please help me with this, if you have troubles recreating the issue, please let me know.

**Comment by lexelby** [comment]
Neat idea!

You can forget about Inkscape.  You can just call Ink/Stitch directly.  You don't even need to have Inkscape installed on your server.

Unzip the Ink/Stitch tarball somewhere (doesn't matter where).  Run it like this:

```
inkstitch/bin/inkstitch --extension=input your_file.dst > converted_file.svg
```

Ink/Stitch will read the embroidery file, figure out the format from the file extension, and print the SVG on standard output.

You can use this technique to do anything that Ink/Stitch can do, including saving to a different embroidery format.  Let me know if that's something you want more information about.

I hope that helps, and let us know how it goes :)

**Comment by rebatov** [comment]
Hello I tried like you suggested but it didn't go well for me and encountered the following console error.

 `./installation/inkstitch/bin/inkstitch --extension=dst Motherday-SP.DST > m.svg
Traceback (most recent call last):
  File "inkstitch.py", line 8, in <module>
  File "/tmp/pip-build-92ATw4/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "lib/extensions/__init__.py", line 1, in <module>
  File "/tmp/pip-build-92ATw4/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "lib/extensions/auto_satin.py", line 5, in <module>
  File "/tmp/pip-build-92ATw4/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "lib/elements/__init__.py", line 1, in <module>
  File "/tmp/pip-build-92ATw4/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "lib/elements/auto_fill.py", line 5, in <module>
  File "/tmp/pip-build-92ATw4/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "site-packages/shapely/geometry/__init__.py", line 4, in <module>
  File "/tmp/pip-build-92ATw4/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "site-packages/shapely/geometry/base.py", line 17, in <module>
  File "/tmp/pip-build-92ATw4/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "site-packages/shapely/coords.py", line 8, in <module>
  File "/tmp/pip-build-92ATw4/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "site-packages/shapely/geos.py", line 75, in <module>
  File "site-packages/shapely/geos.py", line 56, in load_dll
OSError: Could not find lib geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so', '/workspace/dst_test/installation/inkstitch/bin/lib/libgeos_c.so'].
`
But `libgeos_c.so.1` is installed on the machine, it's strange.

**Comment by rebatov** [comment]
I also tried on a fresh centos:7.4.1708 docker image and did like you suggested and the same issue persists.
![dst](https://user-images.githubusercontent.com/17427334/57755393-94bb5d80-7710-11e9-966a-f6b1bb89b18e.png)

**Comment by lexelby** [comment]
Huh, that's really weird!  It should be able to find libgeos_c.so.1 in the `./installation/inkstitch/bin/inkstitch` directory automatically.

Does it work if you do this?

```bash
LD_LIBRARY_PATH=installation/inksttich/bin ./installation/inkstitch/bin/inkstitch --extension=dst Motherday-SP.DST > m.svg
```

**Comment by rebatov** [comment]
I did try like you suggested but it could not find goes_c or any of its variants. :(

**Comment by lexelby** [comment]
Hmm, I wonder if something went wrong during the installation.  It's possible you may have grabbed the source .tar.gz rather than the installation archive.  Could you try starting fresh with this? 

https://github.com/inkstitch/inkstitch/releases/download/v1.25.0/inkstitch-v1.25.0-linux-x86_64-en_US.tar.gz
