### ISSUE TITLE
corrupted presets file causes crash

### ISSUE THREAD

**Issue by curiouskira** [inkstitch/inkstitch#447]
I feel like I'm probably missing something silly but I'm having issues getting Params to run. I've never had any issues in the past and have even tried reinstalling the extension. I've been combing through tutorials trying to figure out what I may be doing wrong but I'm at a loss. Thanks in advance!

Traceback (most recent call last):

  File "inkstitch.py", line 54, in <module>

    stderr = stderr.strip()

  File "inkscape\share\extensions\inkex.py", line 283, in affect

  File "lib\extensions\params.py", line 583, in effect

  File "lib\extensions\params.py", line 325, in __init__

  File "lib\gui\presets.py", line 50, in __init__

  File "lib\gui\presets.py", line 108, in update_preset_list

  File "lib\gui\presets.py", line 98, in _load_presets

  File "json\__init__.py", line 291, in load

  File "json\__init__.py", line 339, in loads

  File "json\decoder.py", line 364, in decode

  File "json\decoder.py", line 382, in raw_decode

ValueError: No JSON object could be decoded

**Comment by lexelby** [comment]
Awesome!  You've found a bug in Ink/Stitch.  I really appreciate your reporting it.  Welcome to the project :)

Somehow the file that Ink/Stitch stores Params presets in has become corrupted.  Ink/Stitch should handle this situation better rather than simply crashing.

For now, you can delete that file to make Ink/Stitch start working again.  Unfortunately, that will erase any presets you might have saved before for which I'm sorry. :(  Here's where the file is:

* On Linux: `~/.config/inkstitch/presets.json`
* On Windows: `C:\Users\<your username>\AppData\Local\inkstitch`
* On Mac OS: `<your home directory>/Library/Application Support/inkstitch`

Please let me know if you can't find it, or if that doesn't fix the problem.  Sorry for the annoyance!

**Comment by curiouskira** [comment]
Worked perfectly! Thank you so much! I'm excited to get back to work. ❤️
