### ISSUE TITLE
Problem with autofill

### ISSUE THREAD

**Issue by pneumaticdeath** [inkstitch/inkstitch#468]
path81: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "lib/elements/auto_fill.py", line 210, in to_patches
  File "lib/debug.py", line 125, in decorated
  File "lib/stitches/auto_fill.py", line 64, in auto_fill
  File "lib/debug.py", line 125, in decorated
  File "lib/stitches/auto_fill.py", line 231, in build_travel_graph
  File "lib/stitches/auto_fill.py", line 274, in process_travel_edges
TypeError: 'LineString' object is not iterable

**Comment by lexelby** [comment]
This looks like the same thing or very similar to #471.  I'm going to close this ticket in favor of #471, but if you think they're two different problems, please don't hesitate to reopen this issue.
