### ISSUE TITLE
Ink  stitch will not start

### ISSUE THREAD

**Issue by cwaters1** [inkstitch/inkstitch#472]
Tried to launch: inkstitch\bin\inkstitch
Arguments: ['inkstitch\\bin\\inkstitch', '--collapse_len_mm=3', '--hide_layers=true', '--output_format=pes', '--extension=embroider', 'C:\\Users\\Clay\\AppData\\Local\\Temp\\ink_ext_XXXXXX.svgK8PP2Z']
Debugging information:

Traceback (most recent call last):
  File "inkstitch.py", line 35, in <module>
    extension = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Program Files\Inkscape\lib\python2.7/subprocess.py", line 325, in __init__
    errread, errwrite)
  File "C:\Program Files\Inkscape\lib\python2.7/subprocess.py", line 575, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

**Comment by cwaters1** [comment]
Turned out I loaded the wrong operating system.  I loaded 0X-486 instead of win 32.
