### ISSUE TITLE
error message convert to embroidering

### ISSUE THREAD

**Issue by tonilatenz** [inkstitch/inkstitch#484]
Hello,
I love to work with inkstitch since any days, but at the moment, theres any problem to convert to embroidering…
I have tried to convert the cans, thats impossible - it follows the error:
Traceback (most recent call last):

  File "inkstitch.py", line 44, in <module>

    print >> sys.stderr, traceback.format_exc()

  File "inkscape\share\extensions\inkex.py", line 283, in affect

  File "lib\extensions\embroider.py", line 82, in effect

  File "lib\output.py", line 101, in write_embroidery_file

  File "site-packages\pyembroidery\PyEmbroidery.py", line 607, in write

  File "site-packages\pyembroidery\PyEmbroidery.py", line 558, in write_embroidery

  File "site-packages\pyembroidery\JefWriter.py", line 29, in write

  File "site-packages\pyembroidery\WriteHelper.py", line 60, in write_int_32le

AttributeError: 'unicode' object has no attribute 'write'

 I have drawn a new can - without success - a part of the bumper as well successless.

Could anybody help me please?

Thank you all so much for your great work.

[Hochzeitskäfer.zip](https://github.com/inkstitch/inkstitch/files/3325362/Hochzeitskafer.zip)

**Comment by kaalleen** [comment]
Does it work if you rename your file? Avoid special characters such as äöüß.

**Comment by tonilatenz** [comment]
Wow!!! It works now :O)
Thank you so much for quick help.

Rgds
Tan, Toni's wife

**Comment by kaalleen** [comment]
Gern geschehen ;)

With one of the next releases you should be able to save (and open) files with umlauts as well.

**Comment by lexelby** [comment]
Yay, I'm glad we were able to get you unstuck.  This looks like the same as #478, so I'm going to close this one now.
