### ISSUE TITLE
Inkstitch installation problem 

### ISSUE THREAD

**Issue by tomflendrig** [inkstitch/inkstitch#520]
I installed inkscape 0.92.2 for macos (Sierra 10.12.6) with XQuarts following the instructions on the Inkscape website.

Also placed the inkstitch files in the extentions directory.

Now I'm testing if inkstitch is working following the youtube tutorial for macos installation.
I make a circle and convert it to a path. (screenshot 1)
Clicked on the params function of the inkstitch plugin. (screenshot 2)
The computer gives me this error message: (screenshot 3)

```
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "hashlib.py", line 147, in <module>
  File "hashlib.py", line 97, in __get_builtin_constructor
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "hashlib.py", line 147, in <module>
  File "hashlib.py", line 97, in __get_builtin_constructor
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "hashlib.py", line 147, in <module>
  File "hashlib.py", line 97, in __get_builtin_constructor
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "hashlib.py", line 147, in <module>
  File "hashlib.py", line 97, in __get_builtin_constructor
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "hashlib.py", line 147, in <module>
  File "hashlib.py", line 97, in __get_builtin_constructor
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "hashlib.py", line 147, in <module>
  File "hashlib.py", line 97, in __get_builtin_constructor
ValueError: unsupported hash type sha512
Traceback (most recent call last):
  File "inkstitch.py", line 8, in <module>
    
  File "/private/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/pip-install-UPA85v/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "lib/extensions/__init__.py", line 14, in <module>
  File "/private/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/pip-install-UPA85v/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "lib/extensions/print_pdf.py", line 13, in <module>
  File "/private/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/pip-install-UPA85v/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "site-packages/flask/__init__.py", line 17, in <module>
  File "/private/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/pip-install-UPA85v/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "site-packages/werkzeug/__init__.py", line 233, in <module>
  File "/private/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/pip-install-UPA85v/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "site-packages/werkzeug/exceptions.py", line 73, in <module>
  File "/private/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/pip-install-UPA85v/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "site-packages/werkzeug/wrappers/__init__.py", line 21, in <module>
  File "/private/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/pip-install-UPA85v/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "site-packages/werkzeug/wrappers/accept.py", line 1, in <module>
  File "/private/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/pip-install-UPA85v/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "site-packages/werkzeug/datastructures.py", line 2843, in <module>
  File "/private/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/pip-install-UPA85v/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "site-packages/werkzeug/http.py", line 24, in <module>
ImportError: cannot import name md5
[867] Failed to execute script inkstitch
```

Could one of you explain what went wrong?
Thanks for helping!

- Tom

![screenshot-1](https://user-images.githubusercontent.com/28000005/62823608-e7cb7200-bb92-11e9-8cc2-6827d18853c2.png)
_Screenshot 1_

![screenshot-2](https://user-images.githubusercontent.com/28000005/62823609-e7cb7200-bb92-11e9-873c-e66bc3613774.png)
_Screenshot 2_

![screenshot-3](https://user-images.githubusercontent.com/28000005/62823610-e7cb7200-bb92-11e9-9f96-54577d8b7203.png)
_Screenshot 2_

**Comment by lexelby** [comment]
Hi there!  Thanks for trying ink/stitch.  I'm really sorry you're having trouble.

We've seen a lot of folks having difficulty on MacOS.  I'm not even sure if anyone has gotten the Mac version working. :(  Unfortunately, none of our primary developers has a Mac, so we're kind of flying blind.  If you know anyone who has experience developing applications for Mac and is interested in helping out, we'd really love to talk to them.

**Comment by kaalleen** [comment]
The current official release doesn't support Sierra. If you wait for the next Ink/Stitch version to be released, you will be able to download a build for your operating system. You might have troubles with the print/realistic preview feature, but the rest should be working fine.

**Comment by skies2law** [comment]
I did the tutorial with the circle and when I get to simulate or any other command this error continues to pop up. Can anyone help.  Thanks

Unexpected error launching Ink/Stitch.
If you're having trouble, please file an issue here, including the text below:
  https://github.com/inkstitch/inkstitch/issues

Tried to launch: inkstitch\bin\inkstitch
Arguments: ['inkstitch\\bin\\inkstitch', '--extension=simulate', 



C:\\Users\\skies\\AppData\\Local\\Temp\\ink_ext_XXXXXX.svgQLNZ7Z']
Debugging information:

Traceback (most recent call last):
  File "inkstitch.py", line 35, in <module>
    extension = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Program Files\Inkscape\lib\python2.7/subprocess.py", line 325, in __init__
    errread, errwrite)
  File "C:\Program Files\Inkscape\lib\python2.7/subprocess.py", line 575, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

**Comment by kaalleen** [comment]
Closing the issue now.

For anyone reading it at a later time:
Ink/Stitch exists for Sierra only in an older version. New Ink/Stitch versions (as of Ink/Stitch 2.27.2) only support Catalina. Download and install instruction (also for Sierra) can be found on our website: https://inkstitch.org/docs/install/
