### ISSUE TITLE
Fill ValueError: A LinearRing must have at least 3 coordinate tuples

### ISSUE THREAD

**Issue by Ketaped** [inkstitch/inkstitch#569]
I had made an embroidery file and successfully saved it to my desktop as both svg and PES file.  I came back to my computer a few days later to work on another project and couldn't remember if I'd saved the file or not, so when prompted on closing, I tried to save it again, and got this error:

Traceback (most recent call last):

  File "inkstitch.py", line 44, in <module>

    print >> sys.stderr, traceback.format_exc()

  File "inkscape\share\extensions\inkex.py", line 283, in affect

  File "lib\extensions\output.py", line 48, in effect

  File "lib\extensions\base.py", line 185, in elements_to_patches

  File "lib\elements\element.py", line 268, in embroider

  File "lib\elements\element.py", line 321, in validate

  File "lib\elements\fill.py", line 148, in validation_errors

  File "site-packages\backports\functools_lru_cache.py", line 113, in wrapper

  File "lib\elements\fill.py", line 136, in shape

  File "lib\elements\fill.py", line 136, in <lambda>

  File "site-packages\shapely\geometry\polygon.py", line 240, in __init__

  File "site-packages\shapely\geometry\polygon.py", line 494, in geos_polygon_from_py

  File "speedups\_speedups.pyx", line 321, in shapely.speedups._speedups.geos_linearring_from_py

ValueError: A LinearRing must have at least 3 coordinate tuples

It seems to have saved as SVG before closing, but I'm not sure what happened here.  This might just be user error, and if so, I'm sorry for bothering you.  :)  So far I'm on the very beginning of the Ink/Stitch learning curve but really impressed with what you've managed to do so far.

**Comment by lexelby** [comment]
Ouch!  I'm sorry you're getting that messy error.  Definitely not what we want, and an error like that is definitely never your fault.

Do you get any useful information by running the Troubleshoot extension?

**Comment by BrendaH** [comment]
I got a similar issue.
I have made a design with multiple paths, some of which are satin stitch and some 'regular' fill.
All objects are ok if I use `InkStitch -> Troubleshoot objects`. Also when I select them all and do Troubleshoot.
Simulate runs a simulation.
But when I try to save as .pes or .dst or when I try to do the print/preview option I get this:

```
Traceback (most recent call last):

  File "d:\a\inkstitch\inkstitch\inkstitch.py", line 44, in <module>

  File "d:\a\inkstitch\inkstitch\inkscape\share\extensions\inkex.py", line 283, in affect

  File "d:\a\inkstitch\inkstitch\lib\extensions\print_pdf.py", line 277, in effect

  File "d:\a\inkstitch\inkstitch\lib\extensions\base.py", line 185, in elements_to_patches

  File "d:\a\inkstitch\inkstitch\lib\elements\element.py", line 268, in embroider

  File "d:\a\inkstitch\inkstitch\lib\elements\element.py", line 321, in validate

  File "d:\a\inkstitch\inkstitch\lib\elements\fill.py", line 148, in validation_errors

  File "C:\hostedtoolcache\windows\Python\2.7.17\x86\lib\site-packages\backports\functools_lru_cache.py", line 124, in wrapper

  File "d:\a\inkstitch\inkstitch\lib\elements\fill.py", line 136, in shape

  File "d:\a\inkstitch\inkstitch\lib\elements\fill.py", line 136, in <lambda>

  File "C:\hostedtoolcache\windows\Python\2.7.17\x86\lib\site-packages\shapely\geometry\polygon.py", line 240, in __init__

  File "C:\hostedtoolcache\windows\Python\2.7.17\x86\lib\site-packages\shapely\geometry\polygon.py", line 494, in geos_polygon_from_py

  File "speedups\_speedups.pyx", line 321, in shapely.speedups._speedups.geos_linearring_from_py

ValueError: A LinearRing must have at least 3 coordinate tuples
```

So, did I miss a step? This is my first tinkering with InkStitch and I have been following the manual and 'fixing' other bugs (like crossing paths that cause problems) but now I am stuck. :-s

**Comment by kaalleen** [comment]
Thanks for the file, that was helpful!

![single_point](https://user-images.githubusercontent.com/36401965/82061574-30d3c800-96c9-11ea-9291-e52b26eabc7e.png)

If you see a traceback message it is never a user error, you just shouldn't see it at all.
We tried to render a shape which was only one point for a fill and we cannot fill points.
Sorry for that. There will be a fix soon!
