### ISSUE TITLE
Error during autofill! (ZeroDivisionError: float modulo)

### ISSUE THREAD

**Issue by MichiKiefl** [inkstitch/inkstitch#602]
path3992: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "lib/elements/auto_fill.py", line 218, in to_patches
  File "lib/debug.py", line 125, in decorated
  File "lib/stitches/auto_fill.py", line 64, in auto_fill
  File "lib/debug.py", line 125, in decorated
  File "lib/stitches/auto_fill.py", line 565, in path_to_stitches
  File "lib/stitches/fill.py", line 73, in stitch_row
  File "lib/stitches/fill.py", line 34, in adjust_stagger
ZeroDivisionError: float modulo

**Comment by lexelby** [comment]
Amazing! This bug must have been here for a long time.  Thanks very much for reporting it!
