### ISSUE TITLE
subprocess.py missing

### ISSUE THREAD

**Issue by bkgoodman** [inkstitch/inkstitch#613]
New Inktich install on Inkscape 0.92.4 gives me, when running _any_ Inkstitch command:

```Tried to launch: inkstitch\bin\inkstitch
Arguments: ['inkstitch\\bin\\inkstitch', '--id=path815', '--extension=lettering', 'C:\\Users\\goodmb2\\AppData\\Local\\Temp\\ink_ext_XXXXXX.svgHXKXF0']
Debugging information:

Traceback (most recent call last):
  File "inkstitch.py", line 35, in <module>
    extension = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Program Files\Inkscape\lib\python2.7/subprocess.py", line 325, in __init__
    errread, errwrite)
  File "C:\Program Files\Inkscape\lib\python2.7/subprocess.py", line 575, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified```

**Comment by lexelby** [comment]
The most common cause of this is that your antivirus software decides that inkstitch.exe is a virus and quarantines it -- without even telling you. :(  See if you can whitelist it?  We promise it's not a virus!

**Comment by danielkschneider** [comment]
This morning Windows Defender started complaining too. That could imply that most users will have a problem since probably most people do have this enabled. At least it allows for relatively easy restoration. 
![2020-05-18 13_34_47-Windows Security](https://user-images.githubusercontent.com/2872643/82209019-dfb41600-990c-11ea-87b2-05a55224dd46.png)

**Comment by kaalleen** [comment]
Looks like we really need to do some code signing work...
