### ISSUE TITLE
"ImportError: libnsl.so.1: cannot open..." problem

### ISSUE THREAD

**Issue by pedro47140** [inkstitch/inkstitch#633]
I have installed inkstitch according to instructions, but every thing I try to do results like: 
![imagen](https://user-images.githubusercontent.com/61936769/76759832-c2d45880-678c-11ea-9bf2-8af031ee2cf2.png)
  with text like:
`Traceback (most recent call last):
  File "/home/runner/work/inkstitch/inkstitch/inkstitch.py", line 8, in <module>
  File "/home/runner/.local/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/home/runner/work/inkstitch/inkstitch/lib/extensions/__init__.py", line 10, in <module>
  File "/home/runner/.local/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/home/runner/work/inkstitch/inkstitch/lib/extensions/lettering.py", line 13, in <module>
  File "/home/runner/.local/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/home/runner/work/inkstitch/inkstitch/lib/gui/__init__.py", line 5, in <module>
  File "/home/runner/.local/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/home/runner/work/inkstitch/inkstitch/lib/gui/subtitle_combo_box.py", line 2, in <module>
  File "/home/runner/.local/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/home/runner/.local/lib/python2.7/site-packages/wx/adv.py", line 13, in <module>
  File "/home/runner/.local/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 687, in load_module
ImportError: libnsl.so.1: cannot open shared object file: No such file or directory
[28619] Failed to execute script inkstitch`

Inkscape 0.92.4
Inkstitch 1.27.2-linux-fr
Fedora 31 xfce (spanish)

This may be due to the difference in languages (Inkscape spanish, Stitch french)? or lack of some packages?
Searching about "ImportError: libnsl.so.1: cannot open..." I have seen problems with missing packages but I have checked and have all the ones mentioned in the posts I have read.

**Comment by lexelby** [comment]
This looks like a bug in our build system.  I'll take a look and see if I can figure out what's going wrong.  Sorry about that!

**Comment by lexelby** [comment]
Could you please give this one a try?  I think it might fix that ImportError: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-lexelby-fix-build

**Comment by pedro47140** [comment]
Thank you for your quick reaction.
After installing the fix I have all the options in the menu Extensions-> Ink/Stitch but I get an error:
![inkstitch](https://user-images.githubusercontent.com/61936769/77049556-94db5800-69c8-11ea-9788-e541b191be9f.png)
`The fantastic lxml wrapper for libxml2 is required by inkex.py and therefore this extension.Please download and install the latest version from http://cheeseshop.python.org/pypi/lxml/, or install it through your package manager by a command like: sudo apt-get install python-lxml

Technical details:
/home/peter/.config/inkscape/extensions/inkstitch/bin/librt.so.1: undefined symbol: __clock_nanosleep, version GLIBC_PRIVATE`

I have checked and have Python2-lxml and Python3-lxml packages installed. I visited the website **http://cheeseshop.python.org/pypi/lxml/**, I downloaded **lxml-4.5.0-cp37-cp37m-manylinux1_x86_64.whl**. But installing it is impossible for me (https://packaging.python.org/tutorials/installing-packages/) ...this is for a programmer, not an average user.

**Comment by lexelby** [comment]
No, you definitely shouldn't have to download and install anything.  Everything needed by Ink/Stitch should be packaged along with it.

I've created a new version at the same URL ([here](https://github.com/inkstitch/inkstitch/releases/tag/dev-build-lexelby-fix-build)), would you mind giving that one a try too?  I think we might be close :)

**Comment by pedro47140** [comment]
Thank you very much! Now this works flawlessly. I'm very impressed by your involvement. My friend also thanks you very much, now she will be able to launch her project.

----- Mail d'origine -----De: Lex Neva <notifications@github.com>&Agrave;: inkstitch/inkstitch <inkstitch@noreply.github.com>Cc: pedro47140 <elpotro@laposte.net>, Author <author@noreply.github.com>Envoy&eacute;: Fri, 20 Mar 2020 03:53:39 +0100 (CET)Objet: Re: [inkstitch/inkstitch] "ImportError: libnsl.so.1: cannot open..." problem (#633)


No, you definitely shouldn't have to download and install anything. Everything needed by Ink/Stitch should be packaged along with it.
I've created a new version at the same URL (here), would you mind giving that one a try too? I think we might be close :)
&mdash;You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
