### ISSUE TITLE
WindowsError:[Error 5] Access is denied

### ISSUE THREAD

**Issue by 0725thebub** [inkstitch/inkstitch#642]
Traceback (most recent call last):
  File "inkstitch.py", line 34, in <module>
    extension = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Program Files\Inkscape\lib\python2.7/subprocess.py", line 325, in __init__
    errread, errwrite)
  File "C:\Program Files\Inkscape\lib\python2.7/subprocess.py", line 575, in _execute_child
    startupinfo)
WindowsError: [Error 5] Access is denied

**Comment by 0725thebub** [comment]
My bad. Restarting the PC after installation fixed the problem. Should have done that before reporting,

**Comment by lexelby** [comment]
Whew, thank goodness -- I had no idea what might cause that error! :)
