### ISSUE TITLE
KeyError: u'\u2192'

### ISSUE THREAD

**Issue by pstorch** [inkstitch/inkstitch#662]
I'm new to Inkstitch and tried Version 1.27.2 with Inkscape 0.92.3 on Linux.

When doing Lettering, nothing happens on "Apply and quit", but when I cancel I get this error message in a popup:

```
Traceback (most recent call last):
  File "/home/runner/work/inkstitch/inkstitch/lib/extensions/lettering.py", line 241, in apply
  File "/home/runner/work/inkstitch/inkstitch/lib/extensions/lettering.py", line 195, in update_lettering
  File "/home/runner/work/inkstitch/inkstitch/lib/lettering/font.py", line 128, in render_text
  File "/home/runner/work/inkstitch/inkstitch/lib/lettering/font.py", line 151, in get_variant
KeyError: u'\u2192'

```

How can I solve this?

**Comment by kaalleen** [comment]
Oh, that's an unzipping problem - been there myself. Try to unzip like this `unzip inkstitch-refs-tags-v1.27.2-linux-de_DE.zip` (assuming you are using the german version, adapt the file name if not).
Hope this helps?!

**Comment by pstorch** [comment]
Great, thanks. It works now :+1:

**Comment by asartori86** [comment]
@kaalleen sorry but where do I find that file?
