### ISSUE TITLE
Black is an invalid color?

### ISSUE THREAD

**Issue by Wakko019** [inkstitch/inkstitch#684]
So I just updated to Inkscape version 0.92.5
then updated to Inkstitch version 1.27.2 and I am getting the following.

I did change one thing, in the inkscape settings, something about using color names versus color numbers, because of a project I did where the colors were just not correct as an svg, not an embroidery file.  I am thinking this is a user error, so any help to fix this would be great.

Exception in thread Thread-1:

Traceback (most recent call last):

  File "C:\hostedtoolcache\windows\Python\2.7.17\x86\lib\threading.py", line 801, in __bootstrap_inner

  File "d:\a\inkstitch\inkstitch\lib\gui\simulator.py", line 787, in run

  File "d:\a\inkstitch\inkstitch\lib\gui\simulator.py", line 800, in update_patches

  File "d:\a\inkstitch\inkstitch\lib\stitch_plan\stitch_plan.py", line 17, in patches_to_stitch_plan

  File "d:\a\inkstitch\inkstitch\lib\stitch_plan\stitch_plan.py", line 69, in new_color_block

  File "d:\a\inkstitch\inkstitch\lib\stitch_plan\stitch_plan.py", line 160, in __init__

  File "d:\a\inkstitch\inkstitch\lib\stitch_plan\stitch_plan.py", line 192, in color

  File "d:\a\inkstitch\inkstitch\lib\threads\color.py", line 24, in __init__

ValueError: Invalid color: 'black'

**Comment by kaalleen** [comment]
Thanks for reporting. Definitely not a user error, you just found a bug here. Ink/Stitch should never give you an ugly feedback like this one.

A workaround for you at the moment could be to open the xml dialogue window (Shift + Control +X) and change `black` to `#000000` in the style settings of your object. This isn't very convenient. An other solution would be to change your color settings back and re-apply the black color onto your object. We will work on a better solution for this. Sorry for your trouble.

**Comment by Wakko019** [comment]
Everyone on the project does an excellent job, as far as issues go, this was not so bad.  It was due to me not realizing that I did change a setting in the inkscape preferences.  I think I should mention that changing the color to pink or green before I reported this here, did work-around the problem, so I don't know if that helps or confuse the situation further, as I still had the Use named colors box checked in the SVG output area.

**Comment by kaalleen** [comment]
Thanks for reporting back. This makes totally sense. Inkscape doesn't set names for every possible color, just for a very few - even with the name setting on. I did run some testing and noticed that too ;)

The issue should be solved very soon - thanks again for reporting this bug. This is very helpful.
