### ISSUE TITLE
input: Error opening machine file with accent.

### ISSUE THREAD

**Issue by LaureFR38** [inkstitch/inkstitch#691]
It does not matter but some people do not understand why their file does not open ...

![image](https://user-images.githubusercontent.com/63351363/81401356-70317000-912f-11ea-95e6-b2b0089dc2da.png)

Traceback (most recent call last):
  File "d:\a\inkstitch\inkstitch\inkstitch.py", line 44, in <module>
  File "d:\a\inkstitch\inkstitch\lib\extensions\input.py", line 50, in affect
  File "C:\hostedtoolcache\windows\Python\2.7.17\x86\lib\encodings\utf_8.py", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 30: invalid continuation byte

**Comment by kaalleen** [comment]
Ah damn, an other (d)encoding issue!
