### ISSUE TITLE
fill: NetworkXNoPath: No path to (x, y)

### ISSUE THREAD

**Issue by melrosefranco** [inkstitch/inkstitch#693]
I've been struggling with his all night... shapes that cross them selves....but after taking closer look they don't appear to cross anywhere....will simulate fine, but then wont allow to save due to empty "d" attribute or invalid shape...now this.  advice would be welcome as well.... 

path4502: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):

  File "d:\a\inkstitch\inkstitch\lib\elements\auto_fill.py", line 218, in to_patches

  File "d:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated

  File "d:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 64, in auto_fill

  File "d:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated

  File "d:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 568, in path_to_stitches

  File "d:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 533, in travel

  File "C:\hostedtoolcache\windows\Python\2.7.17\x86\lib\site-packages\networkx\algorithms\shortest_paths\generic.py", line 172, in shortest_path

  File "C:\hostedtoolcache\windows\Python\2.7.17\x86\lib\site-packages\networkx\algorithms\shortest_paths\weighted.py", line 163, in dijkstra_path

  File "C:\hostedtoolcache\windows\Python\2.7.17\x86\lib\site-packages\networkx\algorithms\shortest_paths\weighted.py", line 472, in single_source_dijkstra

  File "C:\hostedtoolcache\windows\Python\2.7.17\x86\lib\site-packages\networkx\algorithms\shortest_paths\weighted.py", line 738, in multi_source_dijkstra

NetworkXNoPath: No path to (352.7739028029894, 743.3120123443508).

**Comment by kaalleen** [comment]
Yes, you are running into common issues here. The NetworkX error you were discovering is (hopefully) solved by now. I hope you saved the file, so you can test it on a later version of Ink/Stitch.

If it's not too much of a trouble for you, I'd be nice if you could give us feedback on this issue with the latest developement build: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-break-apart-v2

For the crossing path issue we just recently developed a new extension "Break apart fill objects" which can be found in the troubleshoot section in the Ink/Stitch menu. It's strange though, that it would simulate and then not save...

If you are having troubles with it again, it'd be great if you could send us the svg file.
We love to inspect broken files ;)

**Comment by melrosefranco** [comment]
I just did a system reset on my computer so I do believe I have the most recent version, as I had to redownload eeevvverryything.. I absolutely saved the file...ultimately I ended up saving the linework as one file, and the fill as another and aligned them on my machine....it changed all my colors but I obviously just put the right colors in as I went.  LOVE the break apart extension though gonna check that out.  



yeah, I hadn't experienced that before...usually if it simulates it saves, but I would simulate, and then directly after go to save, and...no luck... I also tried the "embroider" option... it would make the embroidery and then still...not save...but if I broke it into sections...all parts would save.  I also tried saving as a different type of file, with no luck. 

...this may sound really dumb to you....but I cant seem to figure out how to upload an svg to here... it says it wont support the file...should I email it to you? id defiantly like to know if I've missed something or did something wrong

**Comment by kaalleen** [comment]
I am sorry to not have mentioned it. It's not a dumb question, it's just not possible. You could wrap you svg into a zip-file container or append '.log' or '.txt' to the file name.

Some embroidery file formats are not able to save colors. This means colors will be randomly chosen, when you reopen the file. When you save as embroidery files it is good habbit to use the 'save copy ...' function instead of the 'save as...' this way you won't forget to also save the svg file itself in the end and you be able to change your design afterwards.

**Comment by kaalleen** [comment]
Same issue as #735
