### ISSUE TITLE
UnicodeEncodeError in stroke.py

### ISSUE THREAD

**Issue by tschutscha** [inkstitch/inkstitch#714]
Hello there,

I'm new on GitHub and hope you can help my. I use Inkscape in my research career. I am very satisfied, but after updating Inkscape to 1.0 and renewing to the current Inkstitch version ( Ink/Stitch v1.28.0 (16.05.2020), german), I can no longer save the files in .dst. I get the following error message:

Traceback (most recent call last):
  File "/home/runner/work/inkstitch/inkstitch/inkstitch.py", line 44, in <module>
  File "/home/runner/work/inkstitch/inkstitch/inkscape/share/extensions/inkex.py", line 283, in affect
  File "/home/runner/work/inkstitch/inkstitch/lib/extensions/output.py", line 48, in effect
  File "/home/runner/work/inkstitch/inkstitch/lib/extensions/base.py", line 185, in elements_to_patches
  File "/home/runner/work/inkstitch/inkstitch/lib/elements/element.py", line 309, in embroider
  File "/home/runner/work/inkstitch/inkstitch/lib/elements/stroke.py", line 192, in to_patches
  File "/home/runner/work/inkstitch/inkstitch/lib/elements/stroke.py", line 134, in is_running_stitch
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 67: ordinal not in range(128)

I use manjaro.

What I'm doing to solve the problem:
reinstall with pamac > not solved
reinstall with snap > not solved
renewing to the current Inkstitch version ( Ink/Stitch v1.28.0 (16.05.2020), englisch) > not solved

In advance I thank you for your help and have a nice day.

tschutscha

**Comment by kaalleen** [comment]
Welcome to the project and thanks for reporting your issue. This is an encoding error you experienced right there. Does it also happen, if you use a dashed stroke instead?

**Comment by tschutscha** [comment]
> Welcome to the project and thanks for reporting your issue. This is an encoding error you experienced right there. Does it also happen, if you use a dashed stroke instead?

Hi kaalleen, thank you for your answer. 
I can save a dashed line in .dst format.

**Comment by kaalleen** [comment]
Ok, great. This is the message you've missed:

> Legacy running stitch setting detected!
> 
> It looks like you're using a stroke smaller than 0.5 units to indicate a running stitch, which is deprecated.  Instead, please set your stroke to be dashed to indicate running stitch.  Any kind of dash will work.

**Comment by tschutscha** [comment]
Thank you. This information passed me.
