### ISSUE TITLE
ValueError: min() arg is an empty sequence in auto_satin.py

### ISSUE THREAD

**Issue by Bbrained** [inkstitch/inkstitch#723]
Came across this error as I was trying to create an auto-rotate satin columns

Traceback (most recent call last):
  File "d:\a\inkstitch\inkstitch\inkstitch.py", line 44, in <module>
  File "d:\a\inkstitch\inkstitch\inkscape\share\extensions\inkex.py", line 283, in affect
  File "d:\a\inkstitch\inkstitch\lib\extensions\auto_satin.py", line 54, in effect
  File "d:\a\inkstitch\inkstitch\lib\stitches\auto_satin.py", line 316, in auto_satin
  File "d:\a\inkstitch\inkstitch\lib\stitches\auto_satin.py", line 448, in add_jumps
ValueError: min() arg is an empty sequence

**Comment by lexelby** [comment]
Looks like a bug to me! Thanks for reporting it, we really appreciate it.

**Comment by Bbrained** [comment]
Thank for responding and looking into it so quickly. I really like and appreciate this project.  Everything else is working really well so far.

**Comment by lexelby** [comment]
Hi again!  I'm having a hard time understanding what might have caused this problem.  Would it be possible for you to share the SVG file you were working on when you saw this error?

**Comment by kaalleen** [comment]
Problem solved and will be fixed in the next version of Ink/Stitch.

**Comment by kaalleen** [comment]
Closing the issue due to it's age. In the meantime add_jumps has been rewritten I suppose. We just hope that we'll receive an other error report with an svg file if this is still an issue.
