### ISSUE TITLE
No such file or directory: symbols\inkstitch.svg

### ISSUE THREAD

**Issue by MandyShulerPhillips** [inkstitch/inkstitch#730]
Traceback (most recent call last):
  File "d:\a\inkstitch\inkstitch\inkstitch.py", line 44, in <module>
  File "d:\a\inkstitch\inkstitch\lib\extensions\input.py", line 46, in affect
  File "d:\a\inkstitch\inkstitch\lib\svg\rendering.py", line 247, in render_stitch_plan
  File "d:\a\inkstitch\inkstitch\lib\svg\rendering.py", line 199, in color_block_to_paths
  File "d:\a\inkstitch\inkstitch\lib\commands.py", line 377, in add_commands
  File "d:\a\inkstitch\inkstitch\lib\commands.py", line 275, in ensure_symbol
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\backports\functools_lru_cache.py", line 124, in wrapper
  File "d:\a\inkstitch\inkstitch\lib\commands.py", line 256, in symbol_defs
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\backports\functools_lru_cache.py", line 124, in wrapper
  File "d:\a\inkstitch\inkstitch\lib\commands.py", line 250, in symbols_svg
IOError: [Errno 2] No such file or directory: 'C:\\PROGRA~1\\Inkscape\\share\\inkscape\\EXTENS~1\\INKSTI~1\\symbols\\inkstitch.svg'

**Comment by kaalleen** [comment]
Looks like Ink/Stitch couldn't find the symbols necessary to use the commands.
They can be installed through Extensions > Ink/Stitch > Install Add-Ons for Inkscape.

**Comment by kaalleen** [comment]
Symbols will not require installation anymore (in the upcoming release).
