### ISSUE TITLE
ValueError: A LinearRing must have at least 3 coordinate tuples

### ISSUE THREAD

**Issue by eklynx** [inkstitch/inkstitch#731]
I'm running the "Break apart and fill holes" and getting the following error:

```
Ink/Stitch experienced an unexpected error.
If you'd like to help, please file an issue at https://github.com/inkstitch/inkstitch/issues and include the entire error description below: 

Traceback (most recent call last):
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/inkstitch.py", line 44, in <module>
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/inkscape/share/extensions/inkex.py", line 283, in affect
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/lib/extensions/break_apart.py", line 33, in effect
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/shapely/geometry/polygon.py", line 243, in __init__
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/shapely/geometry/polygon.py", line 509, in geos_polygon_from_py
  File "shapely/speedups/_speedups.pyx", line 340, in shapely.speedups._speedups.geos_linearring_from_py
ValueError: A LinearRing must have at least 3 coordinate tuples
```

Attached is an example file.[Error.svg.zip](https://github.com/inkstitch/inkstitch/files/4708115/Error.svg.zip)

**Comment by kaalleen** [comment]
Ops, thanks for catching this bug. I tested your file with the newest version. No error showed up, so this might be fixed by now.

I am just wondering... since you are running on a mac operating system (I assume) and your shape actually isn't so small that this error message should be present ... if it is related to this issue (https://github.com/inkstitch/inkstitch/issues/704#issuecomment-629991245) in some way?

**Comment by eklynx** [comment]
Yes, I'm on MacOS Catalina.  I'll grab latest and try again to see if it goes away.  As for it being related to the speedup issue you linked, do you have a recommended way I can enable/disable it to test?

**Comment by kaalleen** [comment]
We haven't released the update of the break apart function yet. It'll be in the next release. If you want to test a newer development version you could grab this file: https://github.com/inkstitch/inkstitch/releases/download/dev-build-kaalleen-empty-d/inkstitch-kaalleen-empty-d-osx-en_US.zip

@magnustron discovered that the speedup function in shapely somehow causes issues on macOS systems and that it helps to delete the corresponding file. The file can be found here: `inkstitch/bin/shapely.speedups._speedups.so`

**Comment by eklynx** [comment]
removing speedups did not solve the issue.  updated stack trace:
```
Ink/Stitch experienced an unexpected error.
If you'd like to help, please file an issue at https://github.com/inkstitch/inkstitch/issues and include the entire error description below: 

Traceback (most recent call last):
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/inkstitch.py", line 44, in <module>
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/inkscape/share/extensions/inkex.py", line 283, in affect
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/lib/extensions/break_apart.py", line 33, in effect
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/shapely/geometry/polygon.py", line 243, in __init__
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/shapely/geometry/polygon.py", line 509, in geos_polygon_from_py
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/shapely/geometry/polygon.py", line 444, in geos_linearring_from_py
ValueError: A LinearRing must have at least 3 coordinate tuples
```

Will try the dev build branch next.

**Comment by kaalleen** [comment]
Nevermind... I just tested again and I got the same error. I will have a look into it.
In the meantime try to grab one node of your shape, move it to the side and release it with the escape button.
Your shape should be fine after that.

**Comment by eklynx** [comment]
Confirmed the temporary workaround works for me.

**Comment by kaalleen** [comment]
Great, I just wrote up a fix. It should be working in the next release. Thanks for reporting this issue.
