### ISSUE TITLE
NetworkXNoPath: No path in auto_fill.py

### ISSUE THREAD

**Issue by Thilda1010** [inkstitch/inkstitch#735]
Hello, 
I would like to submit a new issue on Inkstitch : 

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "d:\a\inkstitch\inkstitch\lib\elements\auto_fill.py", line 225, in to_patches
  File "d:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "d:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 63, in auto_fill
  File "d:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "d:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 618, in path_to_stitches
  File "d:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 583, in travel
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\networkx\algorithms\shortest_paths\generic.py", line 172, in shortest_path
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\networkx\algorithms\shortest_paths\weighted.py", line 163, in dijkstra_path
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\networkx\algorithms\shortest_paths\weighted.py", line 472, in single_source_dijkstra
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\networkx\algorithms\shortest_paths\weighted.py", line 738, in multi_source_dijkstra
NetworkXNoPath: No path to (388.3464566929134, 228.10219672511502).

Have a nice day

**Comment by kaalleen** [comment]
Thanks for reporting this issue. Could you send a svg file which is causing the error?

**Comment by kaalleen** [comment]
See https://github.com/inkstitch/inkstitch/issues/1019#issuecomment-775942332

This error should be fixed in the current version of Ink/Stitch. Therefore I will close this issue now. Please reopen if you still are running into this error.
