### ISSUE TITLE
Shapely speedups library - macOS

### ISSUE THREAD

**Issue by mmarien411** [inkstitch/inkstitch#739]
After completing all params for all elements, I could not get the Simulator to load nor could I get the file to save as PES....
"Ink/Stitch experienced an unexpected error.
If you'd like to help, please file an issue at https://github.com/inkstitch/inkstitch/issues and include the entire error description below: 

Traceback (most recent call last):
  File "d:\a\inkstitch\inkstitch\inkstitch.py", line 44, in <module>
  File "d:\a\inkstitch\inkstitch\inkscape\share\extensions\inkex.py", line 283, in affect
  File "d:\a\inkstitch\inkstitch\lib\extensions\stitch_plan_preview.py", line 18, in effect
  File "d:\a\inkstitch\inkstitch\lib\extensions\base.py", line 185, in elements_to_patches
  File "d:\a\inkstitch\inkstitch\lib\elements\element.py", line 307, in embroider
  File "d:\a\inkstitch\inkstitch\lib\elements\element.py", line 364, in validate
  File "d:\a\inkstitch\inkstitch\lib\elements\fill.py", line 147, in validation_errors
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\backports\functools_lru_cache.py", line 124, in wrapper
  File "d:\a\inkstitch\inkstitch\lib\elements\fill.py", line 135, in shape
  File "d:\a\inkstitch\inkstitch\lib\elements\fill.py", line 135, in <lambda>
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\shapely\geometry\polygon.py", line 240, in __init__
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\shapely\geometry\polygon.py", line 494, in geos_polygon_from_py
  File "speedups\_speedups.pyx", line 321, in shapely.speedups._speedups.geos_linearring_from_py
ValueError: A LinearRing must have at least 3 coordinate tuples"

**Comment by mmarien411** [comment]
After reading previous issues and solutions, I made sure the extension files/packages were all installed and restarted.  I again tried the stitch simulator and  stitch plan preview, receiving this additional message...
"[2020-06-10 03:13:36,486] ERROR in app: Exception on /stitch_plan [GET]
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\flask\app.py", line 

1982, in wsgi_app
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\flask\app.py", line 

1614, in full_dispatch_request
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\flask\app.py", line 

1517, in handle_user_exception
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\flask\app.py", line 

1612, in full_dispatch_request
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\flask\app.py", line 

1598, in dispatch_request
  File "d:\a\inkstitch\inkstitch\lib\api\stitch_plan.py", line 14, in get_stitch_plan
  File "d:\a\inkstitch\inkstitch\lib\extensions\base.py", line 185, in elements_to_patches
  File "d:\a\inkstitch\inkstitch\lib\elements\element.py", line 307, in embroider
  File "d:\a\inkstitch\inkstitch\lib\elements\element.py", line 364, in validate
  File "d:\a\inkstitch\inkstitch\lib\elements\fill.py", line 147, in validation_errors
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\backports

\functools_lru_cache.py", line 124, in wrapper
  File "d:\a\inkstitch\inkstitch\lib\elements\fill.py", line 135, in shape
  File "d:\a\inkstitch\inkstitch\lib\elements\fill.py", line 135, in <lambda>
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\shapely\geometry

\polygon.py", line 240, in __init__
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\shapely\geometry

\polygon.py", line 494, in geos_polygon_from_py
  File "speedups\_speedups.pyx", line 321, in 

shapely.speedups._speedups.geos_linearring_from_py
ValueError: A LinearRing must have at least 3 coordinate tuples

**Comment by kaalleen** [comment]
Would it be possible for you to send us your svg file so we can investigate the issue?

I believe we already fixed the issue and it should be properly working in the next release. But I'd like to give it a try.

**Comment by emilyemotes** [comment]
Not sure if it's in the works but I've been having this problem too! No idea what I'm doing wrong.

**Comment by kristiandelay** [comment]
I am experiencing this same issue with a clients design on both mac and windows. 

Traceback (most recent call last):
  File "inkstitch.py", line 44, in <module>
    print >> sys.stderr, traceback.format_exc()
  File "inkscape/share/extensions/inkex.py", line 283, in affect
  File "lib/extensions/embroider.py", line 84, in effect
  File "lib/extensions/base.py", line 185, in elements_to_patches
  File "lib/elements/element.py", line 268, in embroider
  File "lib/elements/element.py", line 321, in validate
  File "lib/elements/fill.py", line 148, in validation_errors
  File "site-packages/backports/functools_lru_cache.py", line 113, in wrapper
  File "lib/elements/fill.py", line 136, in shape
  File "lib/elements/fill.py", line 136, in <lambda>
  File "site-packages/shapely/geometry/polygon.py", line 240, in __init__
  File "site-packages/shapely/geometry/polygon.py", line 494, in geos_polygon_from_py
  File "shapely/speedups/_speedups.pyx", line 321, in shapely.speedups._speedups.geos_linearring_from_py
ValueError: A LinearRing must have at least 3 coordinate tuples

I am experiencing this same issue with a clients design on both mac and windows, i am a developer as well and i am gonna download the code to set up the environment so i can help try to debug. Any pointers where to look, while i fumble around the code base?

**Comment by kaalleen** [comment]
Sorry, I must have overseen this issue for a while. This issue still exists in the current release (2.0). macOS users often experience this error caused by the shapely speedups library. The current solution we can offer to them is to delete the speedups library. Here is a description how it is done: https://inkstitch.org/docs/install-macos/#valueerror-null-geometry-supports-no-operations

We are thinking about to remove the library from the macOS build. But this will slow down the rendering for all macOS users. I am not sure which conditions have to be met to produce this error.

@kristiandelay Sorry for the late answer on your kind offer. I am not really sure if we can do anything about it other than not using the shapely speedups library. Any ideas?

**Comment by kaalleen** [comment]
This shouldn't show up in the latest release. We use a different method to install shapely.
