### ISSUE TITLE
Receive error

### ISSUE THREAD

**Issue by michaelottofits** [inkstitch/inkstitch#740]
Message below:
Traceback (most recent call last):
  File "/home/runner/work/inkstitch/inkstitch/inkstitch.py", line 44, in <module>
  File "/home/runner/work/inkstitch/inkstitch/inkscape/share/extensions/inkex.py", line 283, in affect
  File "/home/runner/work/inkstitch/inkstitch/lib/extensions/troubleshoot.py", line 26, in effect
  File "/home/runner/work/inkstitch/inkstitch/lib/elements/fill.py", line 147, in validation_errors
  File "/home/runner/.local/lib/python2.7/site-packages/backports/functools_lru_cache.py", line 124, in wrapper
  File "/home/runner/work/inkstitch/inkstitch/lib/elements/fill.py", line 135, in shape
  File "/home/runner/work/inkstitch/inkstitch/lib/elements/fill.py", line 135, in <lambda>
  File "/home/runner/.local/lib/python2.7/site-packages/shapely/geometry/polygon.py", line 243, in __init__
  File "/home/runner/.local/lib/python2.7/site-packages/shapely/geometry/polygon.py", line 509, in geos_polygon_from_py
  File "shapely/speedups/_speedups.pyx", line 340, in shapely.speedups._speedups.geos_linearring_from_py
ValueError: A LinearRing must have at least 3 coordinate tuples

**Comment by kaalleen** [comment]
Thanks for reporting your issue. We believe to have already fixed it for the next release.
