### ISSUE TITLE
Shapely speedup causes trouble on macOS systems

### ISSUE THREAD

**Issue by dHbdHbdHBb** [inkstitch/inkstitch#747]
The preview appears for lines that i draw with the pen tool (run or satin), but not with a closed shape.   I have set the stroke to none and the fill to black as seen in the screenshots, but I still never get the preview.  I'm not sure if I've just accidentally toggled some option that would hide the preview, but it makes planning fills really difficult.

Anyways any help on this would be much appreciated -- I'm thinking about doing a reinstall of both inkscape and inkstitch.
<img width="1403" alt="Screen Shot 2020-06-18 at 7 14 55 PM" src="https://user-images.githubusercontent.com/45609124/85089881-97e90e80-b198-11ea-9c3d-33b0d7a9b9ac.png">
<img width="1229" alt="Screen Shot 2020-06-18 at 7 15 40 PM" src="https://user-images.githubusercontent.com/45609124/85089886-9ae3ff00-b198-11ea-907a-62f116590724.png">

**Comment by dHbdHbdHBb** [comment]
No I don't.  But I do when I try to create the preview via Extensions > Ink/Stitch > Print/Realistic View.  The error that is thrown is: 

Ink/Stitch experienced an unexpected error.
If you'd like to help, please file an issue at https://github.com/inkstitch/inkstitch/issues and include the entire error description below: 

Traceback (most recent call last):
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/inkstitch.py", line 44, in <module>
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/inkscape/share/extensions/inkex.py", line 283, in affect
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/lib/extensions/print_pdf.py", line 277, in effect
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/lib/extensions/base.py", line 185, in elements_to_patches
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/lib/elements/element.py", line 307, in embroider
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/lib/elements/element.py", line 364, in validate
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/lib/elements/fill.py", line 147, in validation_errors
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/backports/functools_lru_cache.py", line 124, in wrapper
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/lib/elements/fill.py", line 135, in shape
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/lib/elements/fill.py", line 135, in <lambda>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/shapely/geometry/base.py", line 438, in area
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/shapely/topology.py", line 55, in __call__
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/shapely/topology.py", line 18, in _validate
ValueError: Null geometry supports no operations

This does not happen when I try to create a preview for Satin or Run stitches.  Still have not been able to get the fill stitch functioning.

**Comment by dHbdHbdHBb** [comment]
Never sorted this:  Have run troubleshoot object function from the inkstitch extensions-> troubleshoot -> troubleshoot object menu,  and it seems like my problem is that inkstitch is saying I have a null geometry.  Not sure why I am not doing anything particularly exotic -- has anyone else had this problem?  I feel like I'm missing a step, but I don't know what.  Created a closed geometry, set stroke to null, and fill to black.  Shouldn't be more complicated than that right?

It throws a very similar error to what I got running the simulator. here is the new error I get on troubleshoot object:


_Ink/Stitch experienced an unexpected error.
If you'd like to help, please file an issue at https://github.com/inkstitch/inkstitch/issues and include the entire error description below: 

Traceback (most recent call last):
  File "/Users/runner/work/inkstitch/inkstitch/inkstitch.py", line 44, in <module>
  File "/Users/runner/work/inkstitch/inkstitch/inkscape/share/extensions/inkex.py", line 283, in affect
  File "/Users/runner/work/inkstitch/inkstitch/lib/extensions/troubleshoot.py", line 26, in effect
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/fill.py", line 150, in validation_errors
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/backports/functools_lru_cache.py", line 124, in wrapper
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/fill.py", line 138, in shape
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/fill.py", line 138, in <lambda>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/shapely/geometry/base.py", line 438, in area
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/shapely/topology.py", line 55, in __call__
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/shapely/topology.py", line 18, in _validate
ValueError: Null geometry supports no operations_

**Comment by dHbdHbdHBb** [comment]
For anyone who perhaps comes across this issue -- the solution has been posted on the inkstitch [website](https://inkstitch.org/docs/install-macos/#addtitional-steps-for-catalina--big-sur).  

I went into the extensions folder and removed the file inkstitch/bin/shapely.speedups._speedups.so

Everything works as expected now.

**Comment by kaalleen** [comment]
Thanks for you feedback. Since we will soon update our shapely version, I am very curious if this is still going to be an issue.
Would it be possible for you to test the newest development branch on this? This would be a great help.
I am thinking if we could otherwise disable the speedup library in the macOS release?!?

Link to the development branch: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-inkscape1.0
Have a look into the assets and choose your osx file with your prefered language.

**Comment by kaalleen** [comment]
Issue is still not solved with an update of shapely. Some macOS users will have to remove the speedup library from their installation. I will still close this issue, because it has been documented on our website.
