### ISSUE TITLE
Inkstich Error

### ISSUE THREAD

**Issue by bigstifi** [inkstitch/inkstitch#751]
path92_900: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/lib/elements/auto_fill.py", line 212, in to_patches
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/lib/debug.py", line 125, in decorated
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 55, in auto_fill
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/lib/debug.py", line 125, in decorated
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 149, in build_fill_stitch_graph
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 173, in insert_node
ValueError: min() arg is an empty sequence

**Comment by bigstifi** [comment]
path92_900: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/lib/elements/auto_fill.py", line 212, in to_patches
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/lib/debug.py", line 125, in decorated
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 55, in auto_fill
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/lib/debug.py", line 125, in decorated
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 149, in build_fill_stitch_graph
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 173, in insert_node
ValueError: min() arg is an empty sequence
