### ISSUE TITLE
Designing a new embroidery Air Force emblem error message

### ISSUE THREAD

**Issue by DragonLadyAnnie** [inkstitch/inkstitch#753]
Traceback (most recent call last):
  File "d:\a\inkstitch\inkstitch\lib\elements\auto_fill.py", line 225, in to_patches
  File "d:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "d:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 63, in auto_fill
  File "d:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "d:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 618, in path_to_stitches
  File "d:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 583, in travel
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\networkx\algorithms\shortest_paths\generic.py", line 172, in shortest_path
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\networkx\algorithms\shortest_paths\weighted.py", line 163, in dijkstra_path
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\networkx\algorithms\shortest_paths\weighted.py", line 472, in single_source_dijkstra
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\networkx\algorithms\shortest_paths\weighted.py", line 738, in multi_source_dijkstra
NetworkXNoPath: No path to (501.732283464567, 330.45719943797167).

#751 

![image](https://user-images.githubusercontent.com/67395865/85634314-5ba22c00-b638-11ea-9069-9cc39861bf10.png)

**Comment by LochanLoch** [comment]
Maybe a would be a nice hint for all how would show us the SVG file.
SVG is an XML Document so a rename from AirForcePatch.**svg** in AirForcePatch.**txt** give all an easy way to upload the SVG/TXT file :-) 
Hope I can help soon better. I am still a newbie.

**Comment by DragonLadyAnnie** [comment]
Thanks Lochan! I figured it out, (At least got it to work) by increasing the size of my text object.

Annie Cambron
