### ISSUE TITLE
 ValueError: need more than 0 values to unpack

### ISSUE THREAD

**Issue by FinePim** [inkstitch/inkstitch#754]
path1843: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "d:\a\inkstitch\inkstitch\lib\elements\auto_fill.py", line 212, in to_patches
  File "d:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "d:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 55, in auto_fill
  File "d:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "d:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 133, in build_fill_stitch_graph
  File "d:\a\inkstitch\inkstitch\lib\stitches\fill.py", line 91, in intersect_region_with_grating
ValueError: need more than 0 values to unpack

path1843: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "d:\a\inkstitch\inkstitch\lib\elements\auto_fill.py", line 212, in to_patches
  File "d:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "d:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 55, in auto_fill
  File "d:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "d:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 133, in build_fill_stitch_graph
  File "d:\a\inkstitch\inkstitch\lib\stitches\fill.py", line 91, in intersect_region_with_grating
ValueError: need more than 0 values to unpack

path1843: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "d:\a\inkstitch\inkstitch\lib\elements\auto_fill.py", line 212, in to_patches
  File "d:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "d:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 55, in auto_fill
  File "d:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "d:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 133, in build_fill_stitch_graph
  File "d:\a\inkstitch\inkstitch\lib\stitches\fill.py", line 91, in intersect_region_with_grating
ValueError: need more than 0 values to unpack

path1843: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "d:\a\inkstitch\inkstitch\lib\elements\auto_fill.py", line 212, in to_patches
  File "d:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "d:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 55, in auto_fill
  File "d:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "d:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 133, in build_fill_stitch_graph
  File "d:\a\inkstitch\inkstitch\lib\stitches\fill.py", line 91, in intersect_region_with_grating
ValueError: need more than 0 values to unpack

**Comment by kaalleen** [comment]
See #1110
