### ISSUE TITLE
Ink/Stitch experienced an unexpected error.

### ISSUE THREAD

**Issue by Lieckio** [inkstitch/inkstitch#767]
Fresh computer, fresh instanll of Inkscape 1.0 and Ink/Stitch. Installed everything possible to all the users, when running inkstitch embroider command, I get this:

Traceback (most recent call last):
  File "d:\a\inkstitch\inkstitch\inkstitch.py", line 44, in <module>
  File "d:\a\inkstitch\inkstitch\inkscape\share\extensions\inkex.py", line 283, in affect
  File "d:\a\inkstitch\inkstitch\lib\extensions\embroider.py", line 86, in effect
  File "d:\a\inkstitch\inkstitch\lib\extensions\embroider.py", line 49, in get_output_path
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\encodings\utf_8.py", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf6 in position 81: invalid start byte

**Comment by Lieckio** [comment]
Well, after posting this I noticed what caused the issue - the export folder had Ö-letter in the name.

I would imagine these special letters in the folder names ought to work in the year 2020.

**Comment by kaalleen** [comment]
Sorry for the trouble and thanks for your report. Python2 has it's difficulties with special chars and we didn't manage to find and remove all the encoding erros. We are in the progress to update to python3, which then will not cause errors like this anymore.
I will close this issue now, because we will be working on it soon.
Please reopen, if you are still having problems after a new release after python3 migration.
