### ISSUE TITLE
ValueError: A LinearRing must have at least 3 coordinate tuples

### ISSUE THREAD

**Issue by lenerdo** [inkstitch/inkstitch#786]
I open up text box,  write Le~Nerdo  convert to path...  Launch stitch path or simulator and get these kinds of errors

Ink/Stitch experienced an unexpected error.
If you'd like to help, please file an issue at https://github.com/inkstitch/inkstitch/issues and include the entire error description below: 

Traceback (most recent call last):
  File "d:\a\inkstitch\inkstitch\inkstitch.py", line 44, in <module>
  File "d:\a\inkstitch\inkstitch\inkscape\share\extensions\inkex.py", line 283, in affect
  File "d:\a\inkstitch\inkstitch\lib\extensions\stitch_plan_preview.py", line 18, in effect
  File "d:\a\inkstitch\inkstitch\lib\extensions\base.py", line 185, in elements_to_patches
  File "d:\a\inkstitch\inkstitch\lib\elements\element.py", line 307, in embroider
  File "d:\a\inkstitch\inkstitch\lib\elements\element.py", line 364, in validate
  File "d:\a\inkstitch\inkstitch\lib\elements\fill.py", line 147, in validation_errors
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\backports\functools_lru_cache.py", line 124, in wrapper
  File "d:\a\inkstitch\inkstitch\lib\elements\fill.py", line 135, in shape
  File "d:\a\inkstitch\inkstitch\lib\elements\fill.py", line 135, in <lambda>
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\shapely\geometry\polygon.py", line 240, in __init__
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\shapely\geometry\polygon.py", line 494, in geos_polygon_from_py
  File "speedups\_speedups.pyx", line 321, in shapely.speedups._speedups.geos_linearring_from_py
ValueError: A LinearRing must have at least 3 coordinate tuples

**Comment by lenerdo** [comment]
I've installed the latest version trying  again.

**Comment by kaalleen** [comment]
No feedback so far. Let's close this issue and link it to #959
