### ISSUE TITLE
Color Pallettes import in InkStitch

### ISSUE THREAD

**Issue by LochanLoch** [inkstitch/inkstitch#799]
Traceback (most recent call last):
  File "/home/runner/work/inkstitch/inkstitch/inkstitch.py", line 44, in <module>
  File "/home/runner/work/inkstitch/inkstitch/inkscape/share/extensions/inkex.py", line 283, in affect
  File "/home/runner/work/inkstitch/inkstitch/lib/extensions/import_threadlist.py", line 38, in effect
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 6: ordinal not in range(128)

Maybe its my own made Problem but Inkscape read my own color palette without fails.
[InkStitch MadieraLochanLoch JPG-sort-WFK140.gpl.txt](https://github.com/inkstitch/inkstitch/files/5114258/InkStitch.MadieraLochanLoch.JPG-sort-WFK140.gpl.txt)
one time it worked fine but after changing a bit in color names ... I made "**true red**" to "**true_red**"
I got the traceback on top.
If I made my palettes to old version without "_" same color palettes work but in the pdf the color name is divided
![Bildschirmfoto_2020-08-23_18-17-06](https://user-images.githubusercontent.com/66974900/90983336-9dcee780-e56d-11ea-9f71-0dd6831baa3f.png) 
- dark sapphire
- true orange
- golden rod

After change to "-" for a " " I got again a Trackback ;-)
Traceback (most recent call last):
  File "/home/runner/work/inkstitch/inkstitch/inkstitch.py", line 44, in <module>
  File "/home/runner/work/inkstitch/inkstitch/inkscape/share/extensions/inkex.py", line 283, in affect
  File "/home/runner/work/inkstitch/inkstitch/lib/extensions/print_pdf.py", line 279, in effect
  File "/home/runner/work/inkstitch/inkstitch/lib/threads/catalog.py", line 64, in match_and_apply_palette
  File "/home/runner/work/inkstitch/inkstitch/lib/threads/catalog.py", line 93, in apply_palette
  File "/home/runner/work/inkstitch/inkstitch/lib/threads/palette.py", line 79, in nearest_color
ValueError: min() arg is an empty sequence

a bit longer but for me ... too much xD

or that now ^^

[2020-08-23 18:51:01,877] ERROR in app: Exception on /palette [POST]
Traceback (most recent call last):
  File "/home/runner/.local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
  File "/home/runner/.local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
  File "/home/runner/.local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
  File "/home/runner/.local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
  File "/home/runner/.local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
  File "/home/runner/work/inkstitch/inkstitch/lib/extensions/print_pdf.py", line 117, in set_palette
  File "/home/runner/work/inkstitch/inkstitch/lib/threads/catalog.py", line 93, in apply_palette
  File "/home/runner/work/inkstitch/inkstitch/lib/threads/palette.py", line 79, in nearest_color
ValueError: min() arg is an empty sequence

That Version in ZIP work now.
[FunktioniertABER.zip](https://github.com/inkstitch/inkstitch/files/5114440/FunktioniertABER.zip)

To change **Columns: 5** in the palette made no change.

That's my own made color palette from Madeira PDF's and JPG's I found on their home page. But the Colors looks still not real to me so next Version I will do from Pictures of the Yarn Box I have ;-) (Canon50D + Magic Lantern xD)

Have fun and some happy hours :-)

**Comment by LochanLoch** [comment]
Inkscape 1.0-5
Ink Stitch 1.29.1

**Comment by kaalleen** [comment]
Whoa, interesting. Thank you for this report. That's weired.
The underscore won't work because of encoding issues. I will not aim to solve them within python 2, because they will disappear when we update to the next python generation. But the color display should not be divided like that.

**Comment by LochanLoch** [comment]
and if I made it a lonely word it fails. maybe I do to many columns for InkStitch :-)

**Comment by kaalleen** [comment]
I just had a look at your gpl file... and yes, you do have too many columns.

In [`palette.py`](https://github.com/inkstitch/inkstitch/blob/b5225e851c30515ee4eeaa5e19ac92f97ab5a2d0/lib/threads/palette.py#L26) you find an example how a color palette should look like.

**Comment by LochanLoch** [comment]
But I still like my own system to find the right color ;-) and it work ... if I made the Number of color last row ... the split of color name still made in pdf. 
[FunktioniertABER_V2.zip](https://github.com/inkstitch/inkstitch/files/5146946/FunktioniertABER_V2.zip)
If someone like mine version xD in it is my V2 and the sorting I did for the color palettes.
