### ISSUE TITLE
NotImplementedError: Multi-part geometries do not provide a coordinate sequence

### ISSUE THREAD

**Issue by nn10nn10** [inkstitch/inkstitch#804]
Keep getting an error when trying to set the fill or stitch to the selected item in the picture. Even tried simplifying still nothing.

path1331: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "d:\a\inkstitch\inkstitch\lib\elements\auto_fill.py", line 212, in to_patches
  File "d:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "d:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 60, in auto_fill
  File "d:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "d:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 286, in build_travel_graph
  File "d:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 424, in build_travel_edges
  File "d:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 375, in travel_grating
  File "d:\a\inkstitch\inkstitch\lib\stitches\fill.py", line 145, in intersect_region_with_grating
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\shapely\geometry\base.py", line 808, in coords
NotImplementedError: Multi-part geometries do not provide a coordinate sequence

![image](https://user-images.githubusercontent.com/39780837/91385637-61b2b580-e7ff-11ea-9426-dd429debe08a.png)

**Comment by nn10nn10** [comment]
Appears to be an issue when the default is set to nothing or zero for "Angle of lines of stitches" under Params.

Also updated to the newest release but was still able to replicate the same issue.

**Comment by mlcdev** [comment]
I'm new to this and I keep getting overlapping and filling errors. My workflow is as follow, I load a bitmap, autotrace it, break it apart and simplify it. Attached the file I tried to convert. Is there any more beginner friendly way without re-tracing all the images?

path84_50: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "d:\a\inkstitch\inkstitch\lib\elements\auto_fill.py", line 225, in to_patches
  File "d:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "d:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 55, in auto_fill
  File "d:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "d:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 149, in build_fill_stitch_graph
  File "d:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 173, in insert_node
ValueError: min() arg is an empty sequence


[Korone_Reference_Design.zip](https://github.com/inkstitch/inkstitch/files/5143658/Korone_Reference_Design.zip)

**Comment by mlcdev** [comment]
Here is yet another file with the issue, actually I keep getting this issue all the time (on windows 10):

path265_14_12: error: Fill: Shape is not valid.  This can happen if the border crosses over itself.

[Kirby Simplified.zip](https://github.com/inkstitch/inkstitch/files/5143700/Kirby.Simplified.zip)

**Comment by mlcdev** [comment]
Here is more errors with version 1.29.1 on above korone file:

path84_12: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\lib\elements\auto_fill.py", line 212, in to_patches
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 55, in auto_fill
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 149, in build_fill_stitch_graph
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 173, in insert_node
ValueError: min() arg is an empty sequence

Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\SocketServer.py", line 599, in process_request_thread
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\SocketServer.py", line 334, in finish_request
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\SocketServer.py", line 655, in __init__
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\werkzeug\serving.py", line 329, in handle
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\BaseHTTPServer.py", line 340, in handle
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\werkzeug\serving.py", line 364, in handle_one_request
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\werkzeug\serving.py", line 306, in run_wsgi
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\werkzeug\serving.py", line 294, in execute
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\flask\app.py", line 1997, in __call__
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\flask\app.py", line 1982, in wsgi_app
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\flask\app.py", line 1598, in dispatch_request
  File "D:\a\inkstitch\inkstitch\lib\api\stitch_plan.py", line 14, in get_stitch_plan
  File "D:\a\inkstitch\inkstitch\lib\extensions\base.py", line 194, in elements_to_patches
  File "D:\a\inkstitch\inkstitch\lib\elements\element.py", line 329, in embroider
  File "D:\a\inkstitch\inkstitch\lib\elements\auto_fill.py", line 240, in to_patches
  File "D:\a\inkstitch\inkstitch\lib\elements\element.py", line 353, in fatal
SystemExit: 1

**Comment by kaalleen** [comment]
@nn10nn10 interesting Error. Would it be possible for you to send us the SVG file as well? It would make it easier for us to look into it more closely.

**Comment by kaalleen** [comment]
Here is an other issue, decribing the error: #877 (auto-fill with object touching page border causes exception)

**Comment by kaalleen** [comment]
Closing this issue. Referenced files for different errors are working with the newest release (v2.0.0).
Original error message cannot be tested because of missing svg file.
Please reopen, if the error still exists with the newest release.
