### ISSUE TITLE
Fatal Error in Auto-Fill / Element

### ISSUE THREAD

**Issue by kaalleen** [inkstitch/inkstitch#806]
@mlcdev informed us about this error in https://github.com/inkstitch/inkstitch/issues/804#issuecomment-683085073

```
Traceback (most recent call last):
File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\SocketServer.py", line 599, in process_request_thread
File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\SocketServer.py", line 334, in finish_request
File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\SocketServer.py", line 655, in init
File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\werkzeug\serving.py", line 329, in handle
File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\BaseHTTPServer.py", line 340, in handle
File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\werkzeug\serving.py", line 364, in handle_one_request
File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\werkzeug\serving.py", line 306, in run_wsgi
File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\werkzeug\serving.py", line 294, in execute
File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\flask\app.py", line 1997, in call
File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\flask\app.py", line 1982, in wsgi_app
File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\flask\app.py", line 1598, in dispatch_request
File "D:\a\inkstitch\inkstitch\lib\api\stitch_plan.py", line 14, in get_stitch_plan
File "D:\a\inkstitch\inkstitch\lib\extensions\base.py", line 194, in elements_to_patches
File "D:\a\inkstitch\inkstitch\lib\elements\element.py", line 329, in embroider
File "D:\a\inkstitch\inkstitch\lib\elements\auto_fill.py", line 240, in to_patches
File "D:\a\inkstitch\inkstitch\lib\elements\element.py", line 353, in fatal
SystemExit: 1
```

**Comment by kaalleen** [comment]
A file for this error can be found here: https://github.com/inkstitch/inkstitch/issues/804#issuecomment-683074508
