### ISSUE TITLE
Color Blur: TypeError: NoneType is Not Iterable

### ISSUE THREAD

**Issue by ecc521** [inkstitch/inkstitch#814]
MacOS 10.15.6, Inkscape 1.0.0, Inkstitch 1.29.1

Stacktrace: 
```
[2020-09-09 14:57:28,205] ERROR in app: Exception on /stitch_plan [GET]
Traceback (most recent call last):
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
  File "/Users/runner/work/inkstitch/inkstitch/lib/api/stitch_plan.py", line 15, in get_stitch_plan
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitch_plan/stitch_plan.py", line 23, in patches_to_stitch_plan
  File "/Users/runner/work/inkstitch/inkstitch/lib/threads/color.py", line 61, in __ne__
  File "/Users/runner/work/inkstitch/inkstitch/lib/threads/color.py", line 55, in __eq__
  File "/Users/runner/work/inkstitch/inkstitch/lib/threads/color.py", line 25, in __init__
TypeError: 'NoneType' object is not iterable
```

This looks like a gradient related bug, as setting everything to a solid color prevented this issue, however from a user standpoint, this is not clear at all. 

The image that triggered the error is attached. It is actually an SVG, but I changed extension to make GitHub upload it. Passed troubleshoot with only a few small fill warnings. Again - if gradients are the issue, something should show up here. 
![TuxEdited](https://user-images.githubusercontent.com/42424091/92643831-68860180-f2b0-11ea-97e8-bc736459c489.png)

Also - probably best for a different issue, but I'd be interested in looking at some improvements for MacOS, including fixing some issues with the app not closing, silent crashes in preview tool, automatically detecting the Null geometry problem, and/or automating some of the svg fixes that Inkstitch knows how to perform (breaking complex unconnected paths, fixing overlapping paths, etc), to help make Inkstitch a bit more seamless. Right now, Inkstitch isn't good enough for a normal user to download an SVG off the internet, and turn it into a design. Handling clips/masks better, and allowing for either gradient interpolation or single color fill would also be extremely useful. 

To that end, I've been unable to get a working install ([is Inkscape 1 even supposed to work?](https://github.com/inkstitch/inkstitch/pull/742)), however would be willing to try again if somebody is willing to take a look at what's going on.

**Comment by kaalleen** [comment]
Would it be possible to send an SVG file which is causing the error?
This would really be helpful for us to investigate the error.

**Comment by ecc521** [comment]
It should be attached, though it's not showing up on mobile dark mode. Github didn't let me attach an SVG, so I renamed my svg to a png. You should be able to download the PNG, change the extension, and open it. 

(I did send a request into GitHub's black box support over SVG upload)

**Comment by kaalleen** [comment]
Oh, I see. Sorry for missing the file in the first place. It would be nice to have svg-uploads available.

A lot of your mentioned requests are already on our list. Currently we are working on a new interface to make the whole extension a bit more user friendly. But at the moment we are only two people and both of us are having a hard time to find free time to be working on Ink/Stitch. We are making some progress, but we cannot be fast. The current Ink/Stitch version is working with Inkscape 1.0, but we are working on a full transition to have access to newly introduced features and also updating to a newer python version.

We have plans to handle gradients to support color blending but until then we have a long way to go. Blur will be difficult to do - but I agree, that we should catch up the color information and process it in some better way. Thanks for bringing our attention to this issue.
