### ISSUE TITLE
Could use some help. Ink/stitch for Inkscape error on Embroider export function

### ISSUE THREAD

**Issue by shimmergrl** [inkstitch/inkstitch#819]

**Comment by shimmergrl** [comment]
path272: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\lib\elements\auto_fill.py", line 212, in to_patches
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 55, in auto_fill
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 149, in build_fill_stitch_graph
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 173, in insert_node
ValueError: min() arg is an empty sequence
![error](https://user-images.githubusercontent.com/71229697/93025875-8c01c280-f5b6-11ea-8348-c82f31cc98d3.jpg)

**Comment by ecc521** [comment]
Duplicate of #817. Can you upload your SVG?

**Comment by kaalleen** [comment]
Duplicate of #734
