### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by jeanihrnaehkaestchen** [inkstitch/inkstitch#822]
Traceback (most recent call last):
  File "d:\a\inkstitch\inkstitch\inkstitch.py", line 44, in <module>
  File "d:\a\inkstitch\inkstitch\inkscape\share\extensions\inkex.py", line 283, in affect
  File "d:\a\inkstitch\inkstitch\lib\extensions\stitch_plan_preview.py", line 18, in effect
  File "d:\a\inkstitch\inkstitch\lib\extensions\base.py", line 185, in elements_to_patches
  File "d:\a\inkstitch\inkstitch\lib\elements\element.py", line 309, in embroider
  File "d:\a\inkstitch\inkstitch\lib\elements\stroke.py", line 192, in to_patches
  File "d:\a\inkstitch\inkstitch\lib\elements\stroke.py", line 134, in is_running_stitch
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 67: ordinal not in range(128)

**Comment by kaalleen** [comment]
This is an encoding error. The original message should have been:

Legacy running stitch setting detected! It looks like you're using a stroke smaller than 0.5 units to indicate a running stitch, which is deprecated. Instead, please set your stroke to be dashed to indicate running stitch. Any kind of dash will work.

Hope this helps. Encodings errors are worked on. They hopefully completely disappear once we've moved over to python3. Thanks for reporting your issue.

**Comment by kaalleen** [comment]
Ink/Stitch v2.0.0 solves the issue. Please reopen if that is not the case.
