### ISSUE TITLE
Troubleshoot/Fill: ValueError: need more than 2 values to unpack

### ISSUE THREAD

**Issue by chris59299** [inkstitch/inkstitch#823]
Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\inkstitch.py", line 44, in <module>
  File "D:\a\inkstitch\inkstitch\inkscape\share\extensions\inkex.py", line 283, in affect
  File "D:\a\inkstitch\inkstitch\lib\extensions\troubleshoot.py", line 26, in effect
  File "D:\a\inkstitch\inkstitch\lib\elements\fill.py", line 156, in validation_errors
ValueError: need more than 2 values to unpack

**Comment by kaalleen** [comment]
See #999
