### ISSUE TITLE
Auto route satin

### ISSUE THREAD

**Issue by simonjelstrup** [inkstitch/inkstitch#845]
Traceback (most recent call last):
  File "/Users/runner/work/inkstitch/inkstitch/inkstitch.py", line 44, in <module>
  File "/Users/runner/work/inkstitch/inkstitch/inkscape/share/extensions/inkex.py", line 283, in affect
  File "/Users/runner/work/inkstitch/inkstitch/lib/extensions/auto_satin.py", line 54, in effect
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_satin.py", line 321, in auto_satin
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_satin.py", line 585, in collapse_sequential_segments
StopIteration

So im trying to auto satin route a path which is not curved at all see image.
But I get this error? how do I solve that? 
<img width="271" alt="Skærmbillede 2020-10-05 kl  22 00 23" src="https://user-images.githubusercontent.com/45452208/95126083-2c7e7900-0756-11eb-9588-fc2d217b4372.png">

**Comment by kaalleen** [comment]
Thanks for reporting your issue. We definitely will need to catch this error message and give more useful information.

The auto-route satin method was created to order satin columns nicely in order to reduce e.g. jump stitches. It is meant to be used on satin columns only.

From your picutre I see, that you haven't converted your path into a satin column previously.
In our documentation we gathered information about how you can do that: https://inkstitch.org/docs/stitches/satin-column/#auto-generated-satin-columns
