### ISSUE TITLE
Importing PES after fresh windows install yields UnicodeDecodeError

### ISSUE THREAD

**Issue by d-bischoff** [inkstitch/inkstitch#849]
System is Win64, also tried x86 but to no effect. Also tried different Incscape versions. Same result. Any ideas?

Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\inkstitch.py", line 44, in <module>
  File "D:\a\inkstitch\inkstitch\lib\extensions\input.py", line 50, in affect
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\encodings\utf_8.py", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xfc in position 11: invalid start byte

**Comment by tyrosinase** [comment]
That's been an ongoing battle. Change the filename to have only basic ASCII characters in it, as a workaround.

**Comment by d-bischoff** [comment]
Thanks for your reply. It has helped resolve the issue. One addition: the whole path needs to be ASCII, there was a "ü" in the username which caused the problem.
