### ISSUE TITLE
Ink/Stitch - Path1923 Error durante Auto-Relleno

### ISSUE THREAD

**Issue by BetoVS** [inkstitch/inkstitch#851]
Hi, 

I use InkStitch on OpenSuse Tumbleweed and I tried to use Extensions-InkStitch-Visualise and export-Embroider and I got this error:

Traceback (most recent call last):
  File "/home/runner/work/inkstitch/inkstitch/lib/elements/auto_fill.py", line 212, in to_patches
  File "/home/runner/work/inkstitch/inkstitch/lib/debug.py", line 125, in decorated
  File "/home/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 55, in auto_fill
  File "/home/runner/work/inkstitch/inkstitch/lib/debug.py", line 125, in decorated
  File "/home/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 149, in build_fill_stitch_graph
  File "/home/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 173, in insert_node
ValueError: min() arg is an empty sequence

**Comment by kaalleen** [comment]
Thanks for reporting your error.
We have seen this one before in #734
It has do do with a current wrong handling of small objects in Ink/Stitch.

You can run the Cleanup Document function which can be found in the troubleshoot-section in the Ink/Stitch menu. This will remove all objects that are too small to stitch.

I will close this error now, because it is a duplicate. We will be working on it.
