### ISSUE TITLE
fill: ValueError: Null geometry supports no operations

### ISSUE THREAD

**Issue by pedabraham** [inkstitch/inkstitch#852]
Im trying to save an dst file for the first time, unsuccessfully 

Ink/Stitch experienced an unexpected error.
If you'd like to help, please file an issue at https://github.com/inkstitch/inkstitch/issues and include the entire error description below: 

Traceback (most recent call last):
  File "/Users/runner/work/inkstitch/inkstitch/inkstitch.py", line 44, in <module>
  File "/Users/runner/work/inkstitch/inkstitch/inkscape/share/extensions/inkex.py", line 283, in affect
  File "/Users/runner/work/inkstitch/inkstitch/lib/extensions/embroider.py", line 84, in effect
  File "/Users/runner/work/inkstitch/inkstitch/lib/extensions/base.py", line 194, in elements_to_patches
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/element.py", line 327, in embroider
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/element.py", line 384, in validate
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/fill.py", line 150, in validation_errors
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/backports/functools_lru_cache.py", line 124, in wrapper
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/fill.py", line 138, in shape
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/fill.py", line 138, in <lambda>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/shapely/geometry/base.py", line 438, in area
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/shapely/topology.py", line 55, in __call__
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/shapely/topology.py", line 18, in _validate
ValueError: Null geometry supports no operations

**Comment by kaalleen** [comment]
Sorry that you are having troubles with Ink/Stitch.
Would it be possible to send us an svg file which is causing the error?

**Comment by kaalleen** [comment]
See https://inkstitch.org/docs/install-macos/#valueerror-null-geometry-supports-no-operations
