### ISSUE TITLE
polyline.py: "ValueError: could not convert string to float" during preview

### ISSUE THREAD

**Issue by tmladek** [inkstitch/inkstitch#853]
```
Ink/Stitch experienced an unexpected error.
If you'd like to help, please file an issue at https://github.com/inkstitch/inkstitch/issues and include the entire error description below: 

Traceback (most recent call last):
  File "/home/runner/work/inkstitch/inkstitch/inkstitch.py", line 44, in <module>
  File "/home/runner/work/inkstitch/inkstitch/inkscape/share/extensions/inkex.py", line 283, in affect
  File "/home/runner/work/inkstitch/inkstitch/lib/extensions/embroider.py", line 84, in effect
  File "/home/runner/work/inkstitch/inkstitch/lib/extensions/base.py", line 194, in elements_to_patches
  File "/home/runner/work/inkstitch/inkstitch/lib/elements/element.py", line 329, in embroider
  File "/home/runner/work/inkstitch/inkstitch/lib/elements/polyline.py", line 100, in to_patches
  File "/home/runner/work/inkstitch/inkstitch/lib/elements/polyline.py", line 90, in stitches
  File "/home/runner/.local/lib/python2.7/site-packages/backports/functools_lru_cache.py", line 124, in wrapper
  File "/home/runner/work/inkstitch/inkstitch/lib/elements/polyline.py", line 72, in csp
  File "/home/runner/.local/lib/python2.7/site-packages/backports/functools_lru_cache.py", line 124, in wrapper
  File "/home/runner/work/inkstitch/inkstitch/lib/elements/element.py", line 267, in parse_path
  File "/home/runner/work/inkstitch/inkstitch/lib/elements/polyline.py", line 65, in path
  File "/home/runner/work/inkstitch/inkstitch/lib/elements/polyline.py", line 48, in points
ValueError: could not convert string to float: 


```

This is the whole error, I'm using Inkstitch v1.29.1-1, Inkscape 1.0.1 and Python 3.8.5 (by default installed on my system). It prevents any previews or embroidery exports.

**Comment by kaalleen** [comment]
This should be fixed in the next Ink/Stitch release. Please reopen if that is not the case.
