### ISSUE TITLE
Error during auto fill

### ISSUE THREAD

**Issue by bdal777** [inkstitch/inkstitch#854]
Traceback (most recent call last):
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/auto_fill.py", line 212, in to_patches
  File "/Users/runner/work/inkstitch/inkstitch/lib/debug.py", line 125, in decorated
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 55, in auto_fill
  File "/Users/runner/work/inkstitch/inkstitch/lib/debug.py", line 125, in decorated
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 149, in build_fill_stitch_graph
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 173, in insert_node
ValueError: min() arg is an empty sequence

**Comment by kaalleen** [comment]
Thanks for reporting your error.
We have seen this one before in #734
It has do do with a current wrong handling of small objects in Ink/Stitch.

You can run the Cleanup Document function which can be found in the troubleshoot-section in the Ink/Stitch menu. This will remove all objects that are too small to stitch.

I will close this error now, because it is a duplicate. We will be working on it.
