### ISSUE TITLE
error when embroidering filled circles

### ISSUE THREAD

**Issue by MatimataDesign** [inkstitch/inkstitch#863]
Hello,
I`ve often the Error at files, which are runs at an older release. I`d create them on an previous release, but if I open it on the current one as .svg, it doesn't export to the embroidery file.
For example:
path853-6-4: error: Fill: Shape is not valid.  This can happen if the border crosses over itself.
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\SocketServer.py", line 599, in process_request_thread
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\SocketServer.py", line 334, in finish_request
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\SocketServer.py", line 655, in __init__
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\werkzeug\serving.py", line 329, in handle
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\BaseHTTPServer.py", line 340, in handle
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\werkzeug\serving.py", line 364, in handle_one_request
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\werkzeug\serving.py", line 306, in run_wsgi
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\werkzeug\serving.py", line 294, in execute
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\flask\app.py", line 1997, in __call__
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\flask\app.py", line 1982, in wsgi_app
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\flask\app.py", line 1598, in dispatch_request
  File "D:\a\inkstitch\inkstitch\lib\api\stitch_plan.py", line 14, in get_stitch_plan
  File "D:\a\inkstitch\inkstitch\lib\extensions\base.py", line 194, in elements_to_patches
  File "D:\a\inkstitch\inkstitch\lib\elements\element.py", line 327, in embroider
  File "D:\a\inkstitch\inkstitch\lib\elements\element.py", line 386, in validate
  File "D:\a\inkstitch\inkstitch\lib\elements\element.py", line 353, in fatal
SystemExit: 1

"Cross over itselfs" couldn't be the failure - because it was run on the older inkstich.

I hope to get help from anybody...

Thank you very much.

BR
Tanja

**Comment by ecc521** [comment]
This is a legitimate error, not a bug. You can fix it by selecting your entire design, and going to Extensions > Ink/Stitch > Fill Tools - Break Apart Fill Objects and running the tool on either simple or complex - both have always worked fine for me, not sure the difference. 

InkStitch should probably leave more details in the error message, or automatically break shapes apart, however a developer may be able to tell me why this is a bad idea.

**Comment by kaalleen** [comment]
Actually the break apart function was only introduced in a recent release. We have plans to integrate it into other functions under the hood - but we haven't come to it yet. A problem could be, that users can't control the order of the shapes (if break apart results in multiple objects). But if they want to do so, they could still use the break apart function. So this is not a real issue here.

**Comment by ecc521** [comment]
That makes sense then - it works, but hasn't been fully taken advantage of yet.
Either way, it's an absolutely crucial feature (probably wouldn't be using Inkstitch without it). I've been able to use it it take images with just a few colors - SVG, PNG, etc - rasterize them, path trace, and break apart. Takes me about 5 minutes to turn a simple color image (no matter how jumbled the actual SVG markup) into a stitch pattern - except the "Error During Autofill" bug ruins it about 50% of the time.

Works wonderfully for things such as the MIT Scratch Cat - the SVG itself is an absolute mess, but a path traced & broken apart version works perfectly.

**Comment by kaalleen** [comment]
See #859
