### ISSUE TITLE
params

### ISSUE THREAD

**Issue by llaurawang** [inkstitch/inkstitch#864]
path1076: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/auto_fill.py", line 225, in to_patches
  File "/Users/runner/work/inkstitch/inkstitch/lib/debug.py", line 125, in decorated
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 55, in auto_fill
  File "/Users/runner/work/inkstitch/inkstitch/lib/debug.py", line 125, in decorated
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 149, in build_fill_stitch_graph
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 173, in insert_node
ValueError: min() arg is an empty sequence

**Comment by kaalleen** [comment]
Thanks for reporting your error.
We have seen this one before in #734
It has do do with a current wrong handling of small objects in Ink/Stitch.

You can run the Cleanup Document function which can be found in the troubleshoot-section in the Ink/Stitch menu. This will remove all objects that are too small to stitch.

I will close this error now, because it is a duplicate. We will be working on it.
