### ISSUE TITLE
color.py: TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by Verena1709** [inkstitch/inkstitch#866]
Ich bin absoluter Neuling und arbeite mich gerade in das Programm ein... Folgende Fehlermeldung habe ich bekommen, als ich nur die Kontur eines Objektes als dst. abspeichern wollte...

Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\inkstitch.py", line 44, in <module>
  File "D:\a\inkstitch\inkstitch\inkscape\share\extensions\inkex.py", line 283, in affect
  File "D:\a\inkstitch\inkstitch\lib\extensions\output.py", line 49, in effect
  File "D:\a\inkstitch\inkstitch\lib\stitch_plan\stitch_plan.py", line 17, in patches_to_stitch_plan
  File "D:\a\inkstitch\inkstitch\lib\stitch_plan\stitch_plan.py", line 69, in new_color_block
  File "D:\a\inkstitch\inkstitch\lib\stitch_plan\stitch_plan.py", line 168, in __init__
  File "D:\a\inkstitch\inkstitch\lib\stitch_plan\stitch_plan.py", line 203, in color
  File "D:\a\inkstitch\inkstitch\lib\threads\color.py", line 25, in __init__
TypeError: 'NoneType' object is not iterable

Was muss ich anders machen bzw. ändern?

**Comment by kaalleen** [comment]
Hm, gute Frage. Da scheint es Probleme mit der Erfassung der Farbinformation zu geben.
Wäre es möglich uns die Datei zukommen zu lassen (sofern keine Copyright-Bedenken dagegen sprechen)?
Wir würden uns das gerne einmal genauer anschauen. Hast du die Datei mit Inkscape erstellt?

**Comment by kaalleen** [comment]
No feedback. Let's close this issue and link it to #922
