### ISSUE TITLE
message d'erreur

### ISSUE THREAD

**Issue by Lady-Pink** [inkstitch/inkstitch#867]
path842: erreur : Erreur pendant l'auto-remplissage. Cela veut dire que Ink/Stitch a un problème.

Si vous désirez nous aider à améliorer Ink/Stitch, veuillez SVP copier/coller ce message dans un nouveau rapport d'erreur (issue) ici: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/auto_fill.py", line 212, in to_patches
  File "/Users/runner/work/inkstitch/inkstitch/lib/debug.py", line 125, in decorated
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 55, in auto_fill
  File "/Users/runner/work/inkstitch/inkstitch/lib/debug.py", line 125, in decorated
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 149, in build_fill_stitch_graph
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 173, in insert_node
ValueError: min() arg is an empty sequence

Traceback (most recent call last):
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/SocketServer.py", line 599, in process_request_thread
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/SocketServer.py", line 334, in finish_request
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/SocketServer.py", line 655, in __init__
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/werkzeug/serving.py", line 329, in handle
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/BaseHTTPServer.py", line 340, in handle
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/werkzeug/serving.py", line 364, in handle_one_request
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/werkzeug/serving.py", line 306, in run_wsgi
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/werkzeug/serving.py", line 294, in execute
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
  File "/Users/runner/work/inkstitch/inkstitch/lib/api/stitch_plan.py", line 14, in get_stitch_plan
  File "/Users/runner/work/inkstitch/inkstitch/lib/extensions/base.py", line 194, in elements_to_patches
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/element.py", line 329, in embroider
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/auto_fill.py", line 240, in to_patches
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/element.py", line 353, in fatal
SystemExit: 1

**Comment by kaalleen** [comment]
Thanks for reporting your error.
We have seen this one before in #734
It has do do with a current wrong handling of small objects in Ink/Stitch.

You can run the Cleanup Document function which can be found in the troubleshoot-section in the Ink/Stitch menu. This will remove all objects that are too small to stitch.

**Comment by kaalleen** [comment]
I will close this issue now. Since it is a duplicate. We still will be looking into it.
