### ISSUE TITLE
Mac OS Big Sur installation

### ISSUE THREAD

**Issue by g3r4n** [inkstitch/inkstitch#873]
Whem I try to add install add-ons, I got the following error:
```
Traceback (most recent call last):
  File "/Users/runner/work/inkstitch/inkstitch/inkstitch.py", line 8, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/Users/runner/work/inkstitch/inkstitch/lib/debug.py", line 13, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/Users/runner/work/inkstitch/inkstitch/lib/svg/__init__.py", line 1, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/Users/runner/work/inkstitch/inkstitch/lib/svg/guides.py", line 3, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/Users/runner/work/inkstitch/inkstitch/lib/utils/__init__.py", line 3, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/Users/runner/work/inkstitch/inkstitch/lib/utils/geometry.py", line 3, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/shapely/geometry/__init__.py", line 4, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/shapely/geometry/base.py", line 18, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/shapely/coords.py", line 8, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/shapely/geos.py", line 138, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/shapely/geos.py", line 62, in load_dll
OSError: Could not find lib c or load any of its variants [].
[3342] Failed to execute script inkstitch
```

**Comment by WattyRev** [comment]
I'm getting the same problem. Running macOs Big Sur (11.0.1), Inkscape v1.0, and plugin v1.29.1.

When I create a circle, convert it to a path, then go to Extensions -> Ink/Stitch -> Params, the same error as @g3r4n appears.

**Comment by khurchla** [comment]
I also received the same warning. Running MacOS Big Sur (11.0.1), Inkscape v1.0, and Ink/Stitch v1.29.1.

**Comment by kaalleen** [comment]
Have a look at our website. There is a library missing in the recent release when Ink/Stitch is run on Big Sur. That's why you would need to perform an extra step in your installation.
https://inkstitch.org/docs/install-macos/#addtitional-steps-for-catalina--big-sur
