### ISSUE TITLE
Mac OS X Catalina | Installation Issue

### ISSUE THREAD

**Issue by caimahanke** [inkstitch/inkstitch#874]
Hello, When i go to click anything in the ink/stitch extension I see this error message
[1430] mod is NULL - structTraceback (most recent call last):
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/struct.py", line 1, in <module>
ImportError: No module named _struct
[1430] mod is NULL - pyimod02_archiveTraceback (most recent call last):
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod02_archive.py", line 28, in <module>
ImportError: No module named struct
[1430] mod is NULL - pyimod03_importersTraceback (most recent call last):
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 24, in <module>
ImportError: No module named pyimod02_archive
Traceback (most recent call last):
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/PyInstaller/loader/pyiboot01_bootstrap.py", line 15, in <module>
ImportError: No module named pyimod03_importers
[1430] Failed to execute script pyiboot01_bootstrap

**Comment by kaalleen** [comment]
Thanks for reporting your issue and sorry for the trouble.
Which macOS version are you using?

**Comment by caimahanke** [comment]
Mac OS Catalina 
Version 10.15.3

Thank you for getting back to me

**Comment by kaalleen** [comment]
Looks like some libraries are missing...
I do not really have a good solution to offer.
Could you try if this version here is working for you?
https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-inkscape1.0

Choose a osx file from the file list under assets and select your prefered language as well.

**Comment by kaalleen** [comment]
The posted link above is outdated. The upcoming release will contain a version especially build for catalina. Therefore I'll close this issue now. Please reopen, if this issue is still needed.
