### ISSUE TITLE
comments in SVG XML break Print PDF

### ISSUE THREAD

**Issue by MartinJSoles** [inkstitch/inkstitch#885]
I'm getting an error while trying to export my design to PDF. I can export the design to a stitch file. If I open the PES file, I can then use the export to PDF option.

The error message is as follows:
```
Ink/Stitch experienced an unexpected error.
If you'd like to help, please file an issue at https://github.com/inkstitch/inkstitch/issues and include the entire error description below: 

Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\inkstitch.py", line 44, in <module>
  File "D:\a\inkstitch\inkstitch\inkscape\share\extensions\inkex.py", line 283, in affect
  File "D:\a\inkstitch\inkstitch\lib\extensions\print_pdf.py", line 281, in effect
  File "D:\a\inkstitch\inkstitch\lib\extensions\print_pdf.py", line 204, in render_svgs
  File "D:\a\inkstitch\inkstitch\lib\extensions\print_pdf.py", line 197, in strip_namespaces
TypeError: 'cython_function_or_method' object has no attribute '__getitem__'
```

I'm attaching the SVG file as it exists.
[ErrorFile.zip](https://github.com/inkstitch/inkstitch/files/5541517/ErrorFile.zip)

**Comment by kaalleen** [comment]
Thanks for your report. This will hopefully be fixed with our next release.
Thanks for the SVG file too. It makes it a lot more easier to trace down the issue.
