### ISSUE TITLE
Troubleshoot: TypeError: expected string or buffer

### ISSUE THREAD

**Issue by githubgirl200** [inkstitch/inkstitch#890]
Ink/Stitch experienced an unexpected error.

Traceback (most recent call last):
  File "d:\a\inkstitch\inkstitch\inkstitch.py", line 44, in <module>
  File "d:\a\inkstitch\inkstitch\inkscape\share\extensions\inkex.py", line 283, in affect
  File "d:\a\inkstitch\inkstitch\lib\extensions\troubleshoot.py", line 31, in effect
  File "d:\a\inkstitch\inkstitch\lib\extensions\troubleshoot.py", line 128, in add_descriptions
  File "d:\a\inkstitch\inkstitch\inkscape\share\extensions\inkex.py", line 387, in unittouu
TypeError: expected string or buffer

**Comment by kaalleen** [comment]
Huh, this is a new one ;)

Could you post your svg file (if there are no copygright restrictions)?
It would be helpful to figure out what went wrong here.
