### ISSUE TITLE
Problems with Mac OS Big Sur 

### ISSUE THREAD

**Issue by theaudcar** [inkstitch/inkstitch#891]
I get this error anytime I use any of the inkstitch tools in inkscape..
I'm just trying to get back to making embroidery files, someone pls help!

Traceback (most recent call last):
  File "/Users/runner/work/inkstitch/inkstitch/inkstitch.py", line 8, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/Users/runner/work/inkstitch/inkstitch/lib/debug.py", line 13, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/Users/runner/work/inkstitch/inkstitch/lib/svg/__init__.py", line 1, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/Users/runner/work/inkstitch/inkstitch/lib/svg/guides.py", line 3, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/Users/runner/work/inkstitch/inkstitch/lib/utils/__init__.py", line 3, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/Users/runner/work/inkstitch/inkstitch/lib/utils/geometry.py", line 3, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/shapely/geometry/__init__.py", line 4, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/shapely/geometry/base.py", line 18, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/shapely/coords.py", line 8, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/shapely/geos.py", line 138, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/shapely/geos.py", line 62, in load_dll
OSError: Could not find lib c or load any of its variants [].
[20891] Failed to execute script inkstitch

**Comment by Richard130948** [comment]
Same problem:
 File "/Users/runner/work/inkstitch/inkstitch/inkstitch.py", line 8, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/Users/runner/work/inkstitch/inkstitch/lib/debug.py", line 13, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/Users/runner/work/inkstitch/inkstitch/lib/svg/__init__.py", line 1, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/Users/runner/work/inkstitch/inkstitch/lib/svg/guides.py", line 3, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/Users/runner/work/inkstitch/inkstitch/lib/utils/__init__.py", line 3, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/Users/runner/work/inkstitch/inkstitch/lib/utils/geometry.py", line 3, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/shapely/geometry/__init__.py", line 4, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/shapely/geometry/base.py", line 18, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/shapely/coords.py", line 8, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/shapely/geos.py", line 138, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/shapely/geos.py", line 62, in load_dll
OSError: Could not find lib c or load any of its variants [].
[1044] Failed to execute script inkstitch
---------------------------------------
Starting to think that inkstitch has dropped the ball when MacOs Big Sur came out and forgot to do the testing with the new os.

**Comment by ecc521** [comment]
I am encountering this same issue on MacOS Big Sur as well.
It appears that this is an issue in the Shapely dependency. Shapely has [fixed](https://github.com/Toblerity/Shapely/pull/891) this issue, so Shapely just needs to be updated. 

@baggy-1291: Inkstitch isn't a commercial application, and the maintainers aren't pulling in money from donations. Feel free to do some testing yourself, and/or to submit PRs when you find an issue. But jobs don't work themselves, and Inkstitch comes second.

**Comment by baggy-1291** [comment]
for ecc521:
how do you update/modify Shapely in the code you sent me??
 # manpage says, "If filename is NULL, then the returned handle is for the
    # main program". This way we can let the linker do the work to figure out
    # which libc Python is actually using.
    free = CDLL(None).free

i'm new at this...thank you

**Comment by ecc521** [comment]
Sorry about the confusion,

Inkstitch needs to update Shapely. This doesn't appear to be a problem with your computer, but rather an outdated inkstitch dependency. 

It shouldn't be too hard to update, but I don't currently have time to work on it. You'd need to clone the repository, reset to the release, and update Shapely.

**Comment by baggy-1291** [comment]
for ecc521:
i have no idea what/where shapely is or located?  is shapely part of InkStitch?  or just go and get  another copy of Inkstitch  and reinstall it?  ran into this problems when i upgraded to macOS Big Sur.thank you for all your help and assistance

**Comment by roethel** [comment]
@ecc521 , thanks for the hint and reference to the shapely bug ticket.
I'm new to inkstitch code and haven't figured out to run a clean dist build on the quick, but below is a little hack that got it to work for me, providing a dummy libc.dylib in inkstitch/bin under the extensions directory:

cd <extensions dir, e.g. cd ~/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/ >
cd inkstitch/bin
ln -s libgcc_s.1.dylib libc.dylib

I simply used libgcc but really any library should do the trick since it doesn't appear libc is actually used.
No guarantees of course and I haven't extensively tested the solution -- that would go beyond my mastery of Inkstitch :) -- but so far Inkscape/Inkstitch seems to work fine.

Thanks to all that created and contributed to this plugin!

**Comment by ecc521** [comment]
@roethel - I'll need to try that out at some point. It it's really not used, I've got plenty of buggy libraries to use as dummies.

Best solution is still to fix Shapely, so this becomes practical for "normal" users (whatever the Inkstitch norm is though, I'm not sure), but that may well work for now.

**Comment by ecc521** [comment]
Also, remember the escapes.. Some idiot used a space when naming the Application Support directory:
```
cd ~/Library/Application\ Support/org.inkscape.Inkscape/config/inkscape/extensions/
cd inkstitch/bin
ln -s libpython2.7.dylib libc.dylib
```

Looks like it works, which really isn't a surprise. It looks like they really don't use the library, even if it is there.

**Comment by roethel** [comment]
Ha... yes, thanks for correcting! I did copy / paste from my terminal. Seems like Mac convention is turning more windows-like which is a major pita.

Shapely 1.7.1 should contain the fix to geos.py but there seem to be other build issues that currently forces an earlier version #871 .

**Comment by ecc521** [comment]
Looks like a big time block then.

@kaalleen: Can the workaround be added to the installation as well? It looks like this bug is being blocked by the Electron transition, so Inkstitch will likely be broken on Big Sur for a while without it. 

> ```
> cd ~/Library/Application\ Support/org.inkscape.Inkscape/config/inkscape/extensions/
> cd inkstitch/bin
> ln -s libpython2.7.dylib libc.dylib #Any random dylib should work, libpython2.7 is just a convenient one in the directory. 
> ```

**Comment by kaalleen** [comment]
Yes sure.

I have restructured the installation pages (only the english pages for now). Maybe you could have a look and verify the installation process for macOS: https://inkstitch.org/docs/install-macos/

I also included your alternative installation (#811) as the standard routine. I believe it will be easier for people to understand (sorry for it has been taken so long). Because different descriptions of the installation process could be confusing I removed my original version completely.

**Comment by kaalleen** [comment]
> Shapely 1.7.1 should contain the fix to geos.py

I am actually working on upgrading Ink/Stitch to Inkscape 1.0(.x) and also upgrading the python version along the way. But I have rare time to spend on it and also I am a little stuck with some issues (such as sizing, etc.). These updates should also enable us to use newer versions of some dependencies. I finally got linux and macos versions to build releases, but at least linux isn't quiet satified with the outcome yet... I don't know about macOS, but I suppose it has similar issues.

**Comment by ecc521** [comment]
That looks good, although I'll still want to do a test install at some
point to confirm. I'd be absolutely astounded if there are problems though,
as xattr has served me well for quite some time, and the Big Sur workaround
worked just fine today.

I like the new structure better. Same process for all systems, then a few
extra steps for Mac.

**Comment by roethel** [comment]
I did a fresh install using the new instructions and almost all looking is good:
Apple switched to zsh as default shell for MacOS which no longer accepts command line comments using '#'. It would be best to remove the comment after 'ln -s libpython2.7.dylib libc.dylib' for the folks who cut-and-paste or they'll get a file not found.

I agree, the new instructions are nice. Also, thanks for the post on xattr, very useful when Gatekeeper acts up.

**Comment by ecc521** [comment]
I totally missed the default shell change, as my user account isn't new.
That'll need to be removed.

**Comment by kaalleen** [comment]
I removed the comment in the shell script from the website.

**Comment by kaalleen** [comment]
This extra step isn't anymore necessary for Ink/Stitch v2.0.0
