### ISSUE TITLE
fill: ValueError: need more than 0 values to unpack

### ISSUE THREAD

**Issue by heartyspaghetti** [inkstitch/inkstitch#895]
path162: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/auto_fill.py", line 212, in to_patches
  File "/Users/runner/work/inkstitch/inkstitch/lib/debug.py", line 125, in decorated
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 55, in auto_fill
  File "/Users/runner/work/inkstitch/inkstitch/lib/debug.py", line 125, in decorated
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 133, in build_fill_stitch_graph
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/fill.py", line 91, in intersect_region_with_grating
ValueError: need more than 0 values to unpack

path162: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

**Comment by kaalleen** [comment]
Have a look at this comment here: https://github.com/inkstitch/inkstitch/issues/1019#issuecomment-775942332
