### ISSUE TITLE
Autofille error

### ISSUE THREAD

**Issue by claespol** [inkstitch/inkstitch#899]
path29: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\lib\elements\auto_fill.py", line 212, in to_patches
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 55, in auto_fill
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 133, in build_fill_stitch_graph
  File "D:\a\inkstitch\inkstitch\lib\stitches\fill.py", line 91, in intersect_region_with_grating
ValueError: need more than 0 values to unpack

path29: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\lib\elements\auto_fill.py", line 212, in to_patches
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 55, in auto_fill
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 133, in build_fill_stitch_graph
  File "D:\a\inkstitch\inkstitch\lib\stitches\fill.py", line 91, in intersect_region_with_grating
ValueError: need more than 0 values to unpack

**Comment by Hacko696969** [comment]
I have the same problem

**Comment by kaalleen** [comment]
I'll close this issue. The new release (v2.0.0) should have fixed it. Please reopen, if the error still occurs.
