### ISSUE TITLE
Traceback issue when running params

### ISSUE THREAD

**Issue by saraheilis** [inkstitch/inkstitch#903]
I have been using all the steps I have used before in the past to embroider, but as soon as I run params I get the message:

Traceback (most recent call last):
  File "/Users/runner/runners/2.164.0/work/inkstitch/inkstitch/inkstitch.py", line 8, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.17/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/Users/runner/runners/2.164.0/work/inkstitch/inkstitch/lib/extensions/__init__.py", line 1, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.17/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/Users/runner/runners/2.164.0/work/inkstitch/inkstitch/lib/extensions/auto_satin.py", line 5, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.17/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/Users/runner/runners/2.164.0/work/inkstitch/inkstitch/lib/i18n.py", line 6, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.17/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/Users/runner/runners/2.164.0/work/inkstitch/inkstitch/lib/utils/__init__.py", line 3, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.17/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/Users/runner/runners/2.164.0/work/inkstitch/inkstitch/lib/utils/geometry.py", line 3, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.17/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/Users/runner/hostedtoolcache/Python/2.7.17/x64/lib/python2.7/site-packages/shapely/geometry/__init__.py", line 4, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.17/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/Users/runner/hostedtoolcache/Python/2.7.17/x64/lib/python2.7/site-packages/shapely/geometry/base.py", line 18, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.17/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/Users/runner/hostedtoolcache/Python/2.7.17/x64/lib/python2.7/site-packages/shapely/coords.py", line 8, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.17/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/Users/runner/hostedtoolcache/Python/2.7.17/x64/lib/python2.7/site-packages/shapely/geos.py", line 138, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.17/x64/lib/python2.7/site-packages/shapely/geos.py", line 62, in load_dll
OSError: Could not find lib c or load any of its variants [].
[3354] Failed to execute script inkstitch

Please let me know what I can do differently.

**Comment by kaalleen** [comment]
I am assuming you are running Ink/Stitch on macOS Big Sur?
We updated installation instructions recently.
Maybe this will be helpful for you to get Ink/Stitch running: https://inkstitch.org/docs/install-macos/

**Comment by saraheilis** [comment]
Thank you! I followed all the steps and now all my options are greyed out
and unavailable to use. :/

Sarah Kilroy

**Comment by kaalleen** [comment]
This often happens if you copied the files into a sub folder within the extensions folder.
Can you make sure, all the inkstitch .inx files are directly inside the extensions folder?

**Comment by kaalleen** [comment]
This issue has been fixed with the newest release of Ink/Stitch. Therefore I'll close this issue now.
Please reopen, if you are still running into trouble.
