### ISSUE TITLE
Windows: An invalid index was passed to wxDisplay

### ISSUE THREAD

**Issue by YAOM111NGG** [inkstitch/inkstitch#906]
Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\inkstitch.py", line 44, in <module>
  File "D:\a\inkstitch\inkstitch\inkscape\share\extensions\inkex.py", line 283, in affect
  File "D:\a\inkstitch\inkstitch\lib\extensions\params.py", line 594, in effect
wxAssertionError: C++ assertion "n < m_displays.size()" failed at ..\..\src\msw\display.cpp(577) in wxDisplayFactoryMSW::CreateDisplay(): An invalid index was passed to wxDisplay

**Comment by kaalleen** [comment]
Interesting. Thanks for reporting your error. Do you have a special display setup?
