### ISSUE TITLE
XMLSyntaxError: xmlns:ns1: &#38;#38;ns_ai

### ISSUE THREAD

**Issue by sbatudin** [inkstitch/inkstitch#911]
Hello this what rhe bug says:

Traceback (most recent call last):
  File "/home/runner/work/inkstitch/inkstitch/inkstitch.py", line 44, in <module>
  File "/home/runner/work/inkstitch/inkstitch/inkscape/share/extensions/inkex.py", line 279, in affect
  File "/home/runner/work/inkstitch/inkstitch/lib/extensions/base.py", line 219, in parse
  File "/home/runner/work/inkstitch/inkstitch/inkscape/share/extensions/inkex.py", line 202, in parse
  File "src/lxml/etree.pyx", line 3521, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1880, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1900, in lxml.etree._parseFilelikeDocument
  File "src/lxml/parser.pxi", line 1795, in lxml.etree._parseDocFromFilelike
  File "src/lxml/parser.pxi", line 1201, in lxml.etree._BaseParser._parseDocFromFilelike
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
XMLSyntaxError: xmlns:ns1: '&#38;#38;#38;ns_ai;' is not a valid URI, line 5, column 39 (line 5)

**Comment by sbatudin** [comment]
To partially solve this issue I export in eps > import again in inkscape so the svg file clean it self.

**Comment by kaalleen** [comment]
Thanks for your report. We have seen this one before. There are uncommon namespaces defined in your file (at least for our interpreter).
We should be able to handle these, sorry we are not at the moment. Looks like you've found a way to get around the issue. If you need more specific help, please let us know. The issue can be removed with the help of a text-editor if necessary.

**Comment by kaalleen** [comment]
The upcoming Ink/Stitch version will inform users about the option to import the file instead of opening it directly with Inkscape.
Therefore I'll close this issue now. I am afraid there is no better way of handling this error. Please reopen, if this issue is still needed.
