### ISSUE TITLE
Params Not working

### ISSUE THREAD

**Issue by hayvp** [inkstitch/inkstitch#916]
I recently updated my computer MacOS Big Sur Version 11.0.1 - Not sure if its related but now Params and really all other inkstitch features aren't working.

I had this error come up - 
Traceback (most recent call last):
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/inkstitch.py", line 8, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/lib/debug.py", line 13, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/lib/svg/__init__.py", line 1, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/lib/svg/guides.py", line 3, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/lib/utils/__init__.py", line 3, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/lib/utils/geometry.py", line 3, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/shapely/geometry/__init__.py", line 4, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/shapely/geometry/base.py", line 18, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/shapely/coords.py", line 8, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/shapely/geos.py", line 138, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/shapely/geos.py", line 62, in load_dll
OSError: Could not find lib c or load any of its variants [].
[89053] Failed to execute script inkstitch

I really don't know what any of that means I just want to make an embroidery design for a friend for Xmas. Would someone be able to point me in the right direction for a fix?

**Comment by tyrosinase** [comment]
I'm not a Mac user  but I've seen this issue go by and yep, it's Big Sur-related. Try the revised install instructions here: https://inkstitch.org/docs/install-macos/#addtitional-steps-for-catalina--big-sur

**Comment by hayvp** [comment]
Thanks so much! Seems to have worked!
