### ISSUE TITLE
thread color: TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by MylahBatool** [inkstitch/inkstitch#922]
Hi, I'm getting the below error message at the end of the process to digitise artwork as a Jef file. I am running Inkscape/inkstitch on Mac Catalina.

Traceback (most recent call last):
  File "/Users/runner/work/inkstitch/inkstitch/inkstitch.py", line 44, in <module>
  File "/Users/runner/work/inkstitch/inkstitch/inkscape/share/extensions/inkex.py", line 283, in affect
  File "/Users/runner/work/inkstitch/inkstitch/lib/extensions/print_pdf.py", line 278, in effect
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitch_plan/stitch_plan.py", line 17, in patches_to_stitch_plan
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitch_plan/stitch_plan.py", line 69, in new_color_block
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitch_plan/stitch_plan.py", line 168, in __init__
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitch_plan/stitch_plan.py", line 203, in color
  File "/Users/runner/work/inkstitch/inkstitch/lib/threads/color.py", line 25, in __init__
TypeError: 'NoneType' object is not iterable

**Comment by kaalleen** [comment]
Hm, interesting. Would it be possible for you to share your svg file? (If there is no copyright restrictions)

**Comment by kaalleen** [comment]
Closing in favor of #922
