### ISSUE TITLE
Fill: ValueError: need more than 2 values to unpack

### ISSUE THREAD

**Issue by HowardShank** [inkstitch/inkstitch#923]
Error dialog after failure: File <path> could not be saved.

Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\inkstitch.py", line 44, in <module>
  File "D:\a\inkstitch\inkstitch\inkscape\share\extensions\inkex.py", line 283, in affect
  File "D:\a\inkstitch\inkstitch\lib\extensions\output.py", line 48, in effect
  File "D:\a\inkstitch\inkstitch\lib\extensions\base.py", line 194, in elements_to_patches
  File "D:\a\inkstitch\inkstitch\lib\elements\element.py", line 327, in embroider
  File "D:\a\inkstitch\inkstitch\lib\elements\element.py", line 384, in validate
  File "D:\a\inkstitch\inkstitch\lib\elements\fill.py", line 156, in validation_errors
ValueError: need more than 2 values to unpack

**Comment by HowardShank** [comment]
I've removed nearly all the paths in the file and the exception occurs in the attached outline zip file (SVG included).

I used Troubleshoot->Troubleshoot Objects and received the following report that all is ok.
===============================
All selected shapes are valid! 

If you are still having trouble with a shape not being embroidered, check if it is in a layer with an ignore command.
===============================

But, it will not export in any embroidery format.

Attached test svg file.
[OutlineForExport.zip](https://github.com/inkstitch/inkstitch/files/5706155/OutlineForExport.zip)

**Comment by kaalleen** [comment]
Hey, thanks for you report and the svg file. This is very helpful.

We will need to solve the issue. But for you, here is what you can do to go on working with your file:
Select this part of the image: 
![break_apart](https://user-images.githubusercontent.com/36401965/102688853-ea63c000-41f9-11eb-8d33-4bc12a8916d0.png)
and run Extensions > Ink/Stitch > Fill Tools > Break apart fill objects

This should solve your issue for now.

**Comment by LochanLoch** [comment]
and a bit sort in the XML-Editor (jumps) and ... but ty for tipp with **Extensions > Ink/Stitch > Fill Tools > Break apart fill objects** :-)

**Comment by kaalleen** [comment]
Issue fixed
