### ISSUE TITLE
Import threadlist not working " [Errno 13] Permission denied: 'c:\\borduren\\inkstitch\\palettes"

### ISSUE THREAD

**Issue by claespol** [inkstitch/inkstitch#927]
Ink/Stitch experienced an unexpected error.
If you'd like to help, please file an issue at https://github.com/inkstitch/inkstitch/issues and include the entire error description below: 

Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\inkstitch.py", line 44, in <module>
  File "D:\a\inkstitch\inkstitch\inkscape\share\extensions\inkex.py", line 283, in affect
  File "D:\a\inkstitch\inkstitch\lib\extensions\import_threadlist.py", line 33, in effect
  File "D:\a\inkstitch\inkstitch\lib\extensions\import_threadlist.py", line 62, in parse_inkstitch_threadlist
IOError: **[Errno 13] Permission denied: 'c:\\borduren\\inkstitch\\palettes**'

**Comment by kaalleen** [comment]
Thanks for the error report.

I could be mistaken but It looks like if you were trying to import a whole dictionary and not a single file.
This function is thought to apply an existing threadlist to the design in the canvas. The colors from the threadlist will be applied to the objects in your document. This is practical if you have e.g. a dst file (which has not the ability to save colors). If you additionally have a threadlist you will be able to add the correct colors easily.

Nevertheless it should not show a traceback. Therefore it needs to be fixed. Thanks again for pointing it out to us!

**Comment by claespol** [comment]
What I do is filling out the asked file path and color palette in the pop up screen in import threadlist. No possibility to give a file name.

**Comment by claespol** [comment]
I Changed as mentioned the import_threadlist.py. The other files (sorry for that) i could not find.

**Comment by claespol** [comment]
You were right mentioning the dictionary and therefore i filled out the whole name. Directory path followed by filename. This worked. However this is not what is specified in the popup window who asks for the path.

**Comment by claespol** [comment]
You were right mentioning the dictionary and therefore i filled out the whole name. Directory path followed by filename. This worked. However this is not what is specified in the popup window who asks for the path.

**Comment by kaalleen** [comment]
Oh sorry, I didn't mean you need to update the python files. This was a commit I made to avoid the traceback for later releases.

Sorry the description in the extension isn't very clear. I can see how it can cause some confusions.
