### ISSUE TITLE
Fill: ValueError: need more than 1 value to unpack

### ISSUE THREAD

**Issue by rosered624** [inkstitch/inkstitch#932]
Ink/Stitch experienced an unexpected error.
If you'd like to help, please file an issue at https://github.com/inkstitch/inkstitch/issues and include the entire error description below: 

Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\inkstitch.py", line 44, in <module>
  File "D:\a\inkstitch\inkstitch\inkscape\share\extensions\inkex.py", line 283, in affect
  File "D:\a\inkstitch\inkstitch\lib\extensions\embroider.py", line 84, in effect
  File "D:\a\inkstitch\inkstitch\lib\extensions\base.py", line 194, in elements_to_patches
  File "D:\a\inkstitch\inkstitch\lib\elements\element.py", line 327, in embroider
  File "D:\a\inkstitch\inkstitch\lib\elements\element.py", line 384, in validate
  File "D:\a\inkstitch\inkstitch\lib\elements\fill.py", line 156, in validation_errors
ValueError: need more than 1 value to unpack

**Comment by kaalleen** [comment]
Thanks for you report. We have seen it a lot lately.

Read this [comment](https://github.com/inkstitch/inkstitch/issues/924#issuecomment-748463377) to see what you can do about it.
