### ISSUE TITLE
Auto-Route Satin on Fill Areas Traceback

### ISSUE THREAD

**Issue by Markanthos** [inkstitch/inkstitch#933]
Im trying to create a satin stitch design but keep getting this error message....

Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\inkstitch.py", line 44, in <module>
  File "D:\a\inkstitch\inkstitch\inkscape\share\extensions\inkex.py", line 283, in affect
  File "D:\a\inkstitch\inkstitch\lib\extensions\auto_satin.py", line 54, in effect
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_satin.py", line 316, in auto_satin
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_satin.py", line 456, in add_jumps
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\networkx\algorithms\connectivity\edge_augmentation.py", line 264, in k_edge_augmentation
NetworkXUnfeasible: impossible to 1 connect in graph with less than 2 nodes

![image](https://user-images.githubusercontent.com/76534098/103028456-6d985500-451d-11eb-819d-11fee3cf79a2.png)

**Comment by kaalleen** [comment]
Thanks for reporting your issue here.
Auto-Route Satin is supposed to run on satin columns only. In your picture looks like a fill stitch object. Read about satin columns on our website: https://inkstitch.org/docs/stitches/satin-column/

Still you shouldn't see a error message like. Therefore we are thankful for your report. Please don't hesitate to ask further questions if you get stuck with Ink/Stitch.
