### ISSUE TITLE
fill: ValueError: need more than 0 values to unpack

### ISSUE THREAD

**Issue by elelp** [inkstitch/inkstitch#945]
Hi, inkstitch suggested I post this here!
path29: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\lib\elements\auto_fill.py", line 212, in to_patches
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 55, in auto_fill
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 133, in build_fill_stitch_graph
  File "D:\a\inkstitch\inkstitch\lib\stitches\fill.py", line 91, in intersect_region_with_grating
ValueError: need more than 0 values to unpack

path29: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\lib\elements\auto_fill.py", line 212, in to_patches
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 55, in auto_fill
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 133, in build_fill_stitch_graph
  File "D:\a\inkstitch\inkstitch\lib\stitches\fill.py", line 91, in intersect_region_with_grating
ValueError: need more than 0 values to unpack

**Comment by kaalleen** [comment]
Thanks for reporting your issue. We have recently (hoepfully) fixed the bug and it should be fine in the next release.

For now watch out for very small objects in your document. They seem to cause the error.

**Comment by kaalleen** [comment]
See https://github.com/inkstitch/inkstitch/issues/1019#issuecomment-775942332
