### ISSUE TITLE
ValueError: min() arg is an empty sequence

### ISSUE THREAD

**Issue by EyeOfIverson** [inkstitch/inkstitch#948]
So,  I'm  new to digitizing, and I'm trying to use inkstitch to digitize my family's logo for  our  ranch.  It's  relatively simple, just lines and  letters.  But  this  error message popped up:

Traceback (most recent call last):
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/auto_fill.py", line 212, in to_patches
  File "/Users/runner/work/inkstitch/inkstitch/lib/debug.py", line 125, in decorated
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 55, in auto_fill
  File "/Users/runner/work/inkstitch/inkstitch/lib/debug.py", line 125, in decorated
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 149, in build_fill_stitch_graph
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 173, in insert_node
ValueError: min() arg is an empty sequence

Traceback (most recent call last):
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/SocketServer.py", line 599, in process_request_thread
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/SocketServer.py", line 334, in finish_request
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/SocketServer.py", line 655, in __init__
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/werkzeug/serving.py", line 329, in handle
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/BaseHTTPServer.py", line 340, in handle
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/werkzeug/serving.py", line 364, in handle_one_request
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/werkzeug/serving.py", line 306, in run_wsgi
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/werkzeug/serving.py", line 294, in execute
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
  File "/Users/runner/work/inkstitch/inkstitch/lib/api/stitch_plan.py", line 14, in get_stitch_plan
  File "/Users/runner/work/inkstitch/inkstitch/lib/extensions/base.py", line 194, in elements_to_patches
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/element.py", line 329, in embroider
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/auto_fill.py", line 240, in to_patches
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/element.py", line 353, in fatal
SystemExit: 1

**Comment by kaalleen** [comment]
Thanks for reporting this error. We have seen it a lot recently and (hopefully) have fixed it by now. Within the next release it shouldn't show up anymore. For now you should have a look for very small elements in your document. They seem to cause this error.

**Comment by kaalleen** [comment]
Duplicate of #734
