### ISSUE TITLE
auto_satin: NetworkXUnfeasible

### ISSUE THREAD

**Issue by quietcabaret** [inkstitch/inkstitch#952]
Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\inkstitch.py", line 44, in <module>
  File "D:\a\inkstitch\inkstitch\inkscape\share\extensions\inkex.py", line 283, in affect
  File "D:\a\inkstitch\inkstitch\lib\extensions\auto_satin.py", line 54, in effect
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_satin.py", line 316, in auto_satin
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_satin.py", line 456, in add_jumps
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\networkx\algorithms\connectivity\edge_augmentation.py", line 264, in k_edge_augmentation
NetworkXUnfeasible: impossible to 1 connect in graph with less than 2 nodes

**Comment by kaalleen** [comment]
This is interesting, thank you for reporting your issue.
Would it be possible for you to post the broken svg file?

**Comment by kaalleen** [comment]
See #1056
