### ISSUE TITLE
ValueError: A LinearRing must have at least 3 coordinate tuples

### ISSUE THREAD

**Issue by chanse1003** [inkstitch/inkstitch#959]
Ink/Stitch experienced an unexpected error.
If you'd like to help, please file an issue at https://github.com/inkstitch/inkstitch/issues and include the entire error description below: 

Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\inkstitch.py", line 44, in <module>
  File "D:\a\inkstitch\inkstitch\inkscape\share\extensions\inkex.py", line 283, in affect
  File "D:\a\inkstitch\inkstitch\lib\extensions\output.py", line 49, in effect
  File "D:\a\inkstitch\inkstitch\lib\stitch_plan\stitch_plan.py", line 17, in patches_to_stitch_plan
  File "D:\a\inkstitch\inkstitch\lib\stitch_plan\stitch_plan.py", line 69, in new_color_block
  File "D:\a\inkstitch\inkstitch\lib\stitch_plan\stitch_plan.py", line 168, in __init__
  File "D:\a\inkstitch\inkstitch\lib\stitch_plan\stitch_plan.py", line 203, in color
  File "D:\a\inkstitch\inkstitch\lib\threads\color.py", line 25, in __init__
TypeError: 'NoneType' object is not iterable

**Comment by kaalleen** [comment]
Hm, thank you for reporting your issue. There is a color issue in your file. Would it be possible to upload the file so we can inspect it?
We have seen this error before but it's difficult to see what is causing it without seeing the actual file.

**Comment by dragonlord66666** [comment]
not sure if this is the same issue or not but I'm saving to VP3 format.
params preview worked fine but when I go to save as VP3 I get
Ink/Stitch experienced an unexpected error.
If you'd like to help, please file an issue at https://github.com/inkstitch/inkstitch/issues and include the entire error description below: 

Traceback (most recent call last):
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/inkstitch.py", line 44, in <module>
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/inkscape/share/extensions/inkex.py", line 283, in affect
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/lib/extensions/output.py", line 48, in effect
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/lib/extensions/base.py", line 185, in elements_to_patches
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/lib/elements/element.py", line 307, in embroider
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/lib/elements/element.py", line 364, in validate
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/lib/elements/fill.py", line 147, in validation_errors
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/backports/functools_lru_cache.py", line 124, in wrapper
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/lib/elements/fill.py", line 135, in shape
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/lib/elements/fill.py", line 135, in <lambda>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/shapely/geometry/polygon.py", line 243, in __init__
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/shapely/geometry/polygon.py", line 509, in geos_polygon_from_py
  File "shapely/speedups/_speedups.pyx", line 340, in shapely.speedups._speedups.geos_linearring_from_py
ValueError: A LinearRing must have at least 3 coordinate tuples

**Comment by dragonlord66666** [comment]
seems this error is for any format, tried jef too. only way I can save this is as SVG. message I get after trying to save via file>save as is that the file could not be saved. - if I use Extensions>inkstitch>embroider it just goes back to the menu to set output format and location after I click OK on the traceback error, but does not save anything of course

**Comment by kaalleen** [comment]
@dragonlord66666 I may be a bit late on this. Do you still have the file?

**Comment by kaalleen** [comment]
I renamed this issue for the second error mentioned in this thread.
The first error also can be found here: #814 (with a file). Not sure if it already has been already solved or not.

**Comment by kaalleen** [comment]
Not sure why I haven't seen it back then, but this is the speedups error. It can be solved by deleting the speedups out of the shapely folder within the Ink/Stitch files. It has been solved for the latest release, since we use a different method to install shapely.
