### ISSUE TITLE
Convert_to_satin: ValueError: No Shapely geometry can be created from null value

### ISSUE THREAD

**Issue by kaalleen** [inkstitch/inkstitch#964]
This file:

[bayern.log](https://github.com/inkstitch/inkstitch/files/5761828/bayern.log)

produces this error:

```
shapely.geos - ERROR - TopologyException: depth mismatch at  at 355.00011952691193 527.94578807791993

Ink/Stitch experienced an unexpected error.
If you'd like to help, please file an issue at https://github.com/inkstitch/inkstitch/issues and include the entire error description below: 

Traceback (most recent call last):
  File "/lib/extensions/convert_to_satin.py", line 60, in convert_path_to_satins
    rails, rungs = self.path_to_satin(path, stroke_width, style_args)
  File "/lib/extensions/convert_to_satin.py", line 119, in path_to_satin
    raise SelfIntersectionError()
lib.extensions.convert_to_satin.SelfIntersectionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "inkstitch.py", line 44, in <module>
    extension.run(args=remaining_args)
  File "/usr/share/inkscape/extensions/inkex/base.py", line 140, in run
    self.save_raw(self.effect())
  File "/lib/extensions/convert_to_satin.py", line 52, in effect
    for satin in self.convert_path_to_satins(path, element.stroke_width, style_args, correction_transform, path_style):
  File "/lib/extensions/convert_to_satin.py", line 75, in convert_path_to_satins
    for satin in self.convert_path_to_satins(path, stroke_width, style_args, correction_transform, path_style, depth=depth + 1):
  File "/lib/extensions/convert_to_satin.py", line 60, in convert_path_to_satins
    rails, rungs = self.path_to_satin(path, stroke_width, style_args)
  File "/lib/extensions/convert_to_satin.py", line 123, in path_to_satin
    left_rail = path.parallel_offset(stroke_width / 2.0, 'left', **style_args)
  File "/python3.9/site-packages/shapely/geometry/linestring.py", line 145, in parallel_offset
    return geom_factory(self.impl['parallel_offset'](
  File "/lib/python3.9/site-packages/shapely/geometry/base.py", line 78, in geom_factory
    raise ValueError("No Shapely geometry can be created from null value")
ValueError: No Shapely geometry can be created from null value

```

when convert line to satin is run on it.

Step to solve:
Select one node and run "Break path at selected nodes"

**Comment by kaalleen** [comment]
Apparently the conversion works now.
