### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by isa18120** [inkstitch/inkstitch#973]
I'm trying to convert my svg daten in jef . I don't have problem with the paths or parameters, anythink is allwright, but impossible to register under JEF. this message appears : what can I do?
Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\inkstitch.py", line 44, in <module>
  File "D:\a\inkstitch\inkstitch\inkscape\share\extensions\inkex.py", line 283, in affect
  File "D:\a\inkstitch\inkstitch\lib\extensions\output.py", line 48, in effect
  File "D:\a\inkstitch\inkstitch\lib\extensions\base.py", line 194, in elements_to_patches
  File "D:\a\inkstitch\inkstitch\lib\elements\element.py", line 329, in embroider
  File "D:\a\inkstitch\inkstitch\lib\elements\stroke.py", line 197, in to_patches
  File "D:\a\inkstitch\inkstitch\lib\elements\stroke.py", line 139, in is_running_stitch
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 1: ordinal not in range(128)

**Comment by kaalleen** [comment]
Thanks for your report. We know this should be possible but we still have some issue with it. Could you try to save your file without any special characters, such as é. Try to use "e" instead. Sorry for your inconvenience.

**Comment by kaalleen** [comment]
Ink/Stitch v2.0.0 should be able to handle this better. Therefore I am going to close this issue. Please reopen, if you still seeing a messagee like this.
