### ISSUE TITLE
Error when I export un .exp 

### ISSUE THREAD

**Issue by johan751** [inkstitch/inkstitch#977]
Hello, 
After a lot of work!!
Impossible to me to export en .exp.

I use Inkscape 1.0 flat pack on linux mint.
I have this when I export:

Traceback (most recent call last):
  File "/home/runner/work/inkstitch/inkstitch/inkstitch.py", line 44, in <module>
  File "/home/runner/work/inkstitch/inkstitch/inkscape/share/extensions/inkex.py", line 283, in affect
  File "/home/runner/work/inkstitch/inkstitch/lib/extensions/output.py", line 56, in effect
  File "/home/runner/work/inkstitch/inkstitch/lib/output.py", line 58, in write_embroidery_file
  File "/home/runner/work/inkstitch/inkstitch/lib/output.py", line 42, in jump_to_stop_point
  File "/home/runner/.local/lib/python2.7/site-packages/backports/functools_lru_cache.py", line 124, in wrapper
  File "/home/runner/work/inkstitch/inkstitch/lib/commands.py", line 213, in global_command
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 6: ordinal not in range(128)

Thank you

**Comment by kaalleen** [comment]
Are you on a older mac version?

**Comment by johan751** [comment]
I am on Linux mint, but I think I résolved the pb. Cause I put stop and cut the same time. But now my new problem I when I do an . Exp file my machin don t stop and change for the color..   maybe add parler color from inkstitch.

**Comment by kaalleen** [comment]
Means your machine will not stop for a color change?

**Comment by johan751** [comment]
Yes. I need put a stop after one color. No automatic.
