### ISSUE TITLE
Error During Autofill Problem | Mac Big Sur

### ISSUE THREAD

**Issue by justbrinicole** [inkstitch/inkstitch#995]
Traceback (most recent call last):
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/auto_fill.py", line 225, in to_patches
  File "/Users/runner/work/inkstitch/inkstitch/lib/debug.py", line 125, in decorated
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 63, in auto_fill
  File "/Users/runner/work/inkstitch/inkstitch/lib/debug.py", line 125, in decorated
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 618, in path_to_stitches
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 583, in travel
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/networkx/algorithms/shortest_paths/generic.py", line 172, in shortest_path
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/networkx/algorithms/shortest_paths/weighted.py", line 163, in dijkstra_path
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/networkx/algorithms/shortest_paths/weighted.py", line 472, in single_source_dijkstra
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/networkx/algorithms/shortest_paths/weighted.py", line 738, in multi_source_dijkstra
NetworkXNoPath: No path to (447.8740157480315, 464.0070304887749).

**Comment by kaalleen** [comment]
Thank you for reporting your error message. Would it be possible for you to upload an svg file? It would make it easier for us to see what is going wrong.

**Comment by kaalleen** [comment]
This should be fixed in the current release (v2.0.0)
