### ISSUE TITLE
fill: ValueError: need more than 0 values to unpack

### ISSUE THREAD

**Issue by mpaukova** [inkstitch/inkstitch#997]
Hello, am trying to conquer Inkstitch and it is a wild beast:

path1331: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/auto_fill.py", line 212, in to_patches
  File "/Users/runner/work/inkstitch/inkstitch/lib/debug.py", line 125, in decorated
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 55, in auto_fill
  File "/Users/runner/work/inkstitch/inkstitch/lib/debug.py", line 125, in decorated
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 133, in build_fill_stitch_graph
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/fill.py", line 91, in intersect_region_with_grating
ValueError: need more than 0 values to unpack

**Comment by kaalleen** [comment]
Thanks for informing us about your issue. Would it be possible to upload an svg file which is causing the issue?
Alternatively I would be very curious if the file is working on our newest development branch which can be downloaded here: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-inkscape1.0 It can be installed the same way as any other normal release.

**Comment by kaalleen** [comment]
See #1071
