### ISSUE TITLE
fill: ValueError: need more than 2 values to unpack (validation_errors)

### ISSUE THREAD

**Issue by meganpecho** [inkstitch/inkstitch#999]
Hi!

I keep getting 
```
Traceback (most recent call last):
  File "/Users/runner/work/inkstitch/inkstitch/inkstitch.py", line 44, in <module>
  File "/Users/runner/work/inkstitch/inkstitch/inkscape/share/extensions/inkex.py", line 283, in affect
  File "/Users/runner/work/inkstitch/inkstitch/lib/extensions/troubleshoot.py", line 26, in effect
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/fill.py", line 156, in validation_errors
ValueError: need more than 2 values to unpack
``` 
running the troubleshoot and 

```
Traceback (most recent call last):
  File "/Users/runner/work/inkstitch/inkstitch/inkstitch.py", line 44, in <module>
  File "/Users/runner/work/inkstitch/inkstitch/inkscape/share/extensions/inkex.py", line 283, in affect
  File "/Users/runner/work/inkstitch/inkstitch/lib/extensions/stitch_plan_preview.py", line 18, in effect
  File "/Users/runner/work/inkstitch/inkstitch/lib/extensions/base.py", line 194, in elements_to_patches
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/element.py", line 327, in embroider
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/element.py", line 384, in validate
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/fill.py", line 156, in validation_errors
ValueError: need more than 2 values to unpack
``` 

running either `Embroider` or trying to do the `Stitch Plan Preview`. I also can't seem to get the Simulator to load, it just runs infinitely. 

What I can deduce is something is not valid about my shapes, but I obviously can't troubleshoot and I haven't looked at python in a hot minute to be able to actually understand why it's breaking. 

Thanks!

(on Catalina)

**Comment by kaalleen** [comment]
Thank you for informing us about your issue. Would it be possible for you to upload an svg file which is causing the error? (needs to be zipped or renamed as e.g. .log). Alternatively I would be very curious if the file is working on our newest development branch which can be downloaded here: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-inkscape1.0 It can be installed the same way as any other normal release.

**Comment by kaalleen** [comment]
This issue is pretty old. Without a file it is difficult to say if it is really fixed by now, but I think it is.
If this error shows up again with any Ink/Stitch version greater than 3.1.0, please open a new error report.
